### ISSUE TITLE
Ranking info

### ISSUE THREAD

**Issue by XavierRex** [LAION-AI/Open-Assistant#1000]
Above or below the ranking should show the stats of the person logged in, and it would also be nice to see how many prompts/responses/labels have already been made overall in this project out of a targeted 50 000.

**Comment by andreaskoepf** [comment]
Ranking: Good idea, should be a relatively easy to add.

overall progress is covered by: #996

**Comment by fozziethebeat** [comment]
To clarify @XavierRex you mean show the current logged in user's general stats somewhere near the leaderboard table in the dashboard view?  I think this is mostly UI design work and funneling the data properly.  If anyone wants to take this, please mention here and I'll assign.
