### ISSUE TITLE
Label Prompter Reply useless rating option

### ISSUE THREAD

**Issue by XavierRex** [LAION-AI/Open-Assistant#1003]
The user prompt can't be helpful unless it's for dataset utility, but that's judged by low/high quality ratings. Imo this option should be removed in this task because it can be confusing.
![image](https://user-images.githubusercontent.com/98437003/215352754-2a5ed8d7-1faf-4048-9ebd-83831bf9f955.png)

**Comment by andreaskoepf** [comment]
Was already fixed earlier today: https://github.com/LAION-AI/Open-Assistant/commit/0601d874e8e20b0a966c746bc65584c032fb7df7
