### ISSUE TITLE
Whitespace not shown properly in ranking task

### ISSUE THREAD

**Issue by mashdragon** [LAION-AI/Open-Assistant#1007]
In the ranking task, and possibly elsewhere, whitespace isn't rendered properly in the choices:

![image](https://user-images.githubusercontent.com/122402293/215361448-c6be5cfb-d3ef-4268-a07d-4340bc617141.png)

This also occurs in the modal:
![image](https://user-images.githubusercontent.com/122402293/215361526-a685f386-ee84-42fd-b3ff-9d0ac167053c.png)

See commit 51a1d9a which is a related fix.

**Comment by AzielChamba** [comment]
Can the issue be addressed properly? I don't understand what it means...

**Comment by fozziethebeat** [comment]
This should be addressed by https://github.com/LAION-AI/Open-Assistant/pull/1042

**Comment by RuRo** [comment]
This doesn't appear to be completely fixed. `pre-line` still collapses whitespace, so code blocks look broken:

````
Here is the code you asked for:

```python
def foo():
    # this line should be indented
    return 123
```
````

will render like this:

![image](https://user-images.githubusercontent.com/3747318/216843367-117815bb-b48c-48b8-bf8a-2ae2cdd70468.png)

**Comment by AzielChamba** [comment]
Great
