### ISSUE TITLE
Doesn't have a requirements.txt

### ISSUE THREAD

**Issue by izam-mohammed** [LAION-AI/Open-Assistant#101]
Can't find a requirements.txt file

**Comment by sryu1** [comment]
I swear I saw one a few hours ago...

**Comment by sryu1** [comment]
Maybe it was another repo hahaha...

**Comment by sryu1** [comment]
Hey @izam-mohammed I realised there are requirements.txt files, in the subfolders of the repo.

**Comment by fozziethebeat** [comment]
The backend code has one in `backend/` and the bot has one in `discord-bot/`

I'll be closing this as working as intended.
