### ISSUE TITLE
Setup Storybook for website

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#102]
Configure and setup [Storybook](https://storybook.js.org/) to run on any visual components we build.  This will help anyone developing components test their visual look and feel without worrying about any backend business.

Key qualities:
- The setup should include both tailwindcss and chakra-ui styles to ensure the storybook view matches what'll be in the website.
- Any storybook setup should make it easy to mock out the data needed.
- Storybook can focus just on components in `components/` rather than `pages/`
- Can be run with `npm run storybook`

It would also be helpful to add to the README how someone can setup a storybook config for a new component they write (such as pointing to an example they can copy).

**Comment by jojopirker** [comment]
I have some experience in using/setting up storyboard and could try to do this

**Comment by fozziethebeat** [comment]
Great! I've done it before with nextJS so if you run into issues please let me know.  

For setting up the component stories, an idea would be to let us write our components like in [this example](https://github.com/SurfaceData/surface-redwood-template/tree/main/web/src/components/ui/SurfaceFooter).  Then we can write the component and the story in the same directory and storybook just figures it all out.
