### ISSUE TITLE
Display user avatar in leaderboard

### ISSUE THREAD

**Issue by lainisourgod** [LAION-AI/Open-Assistant#1023]
I miss avatars next to nicknames. Avatars create a feeling that here on leaderboard are humans not just database records. It makes a process more engaging and it's more interesting to compete with real human than "anonymouses".

<img width="1156" alt="CleanShot 2023-01-31 at 00 30 41@2x" src="https://user-images.githubusercontent.com/24773652/215588262-f646d08b-382e-4758-90b7-fed5f9810df6.png">

**Comment by fozziethebeat** [comment]
I don't think we have all the user avatar information readily available when we're rendering this.  But if anyone wants to take a stab at making that work (even partially) that'd be a nice UI bonus

**Comment by andreaskoepf** [comment]
The frontend DB contains avatar urls in the "image" column of the "Users" table for all discord users. For E-Mail users a dummy avatar image could be shown.

**Comment by MrlolDev** [comment]
Working on it, for email users working with https://dicebear.com/playground
