### ISSUE TITLE
Biomedical dialogue data

### ISSUE THREAD

**Issue by uyhcire** [LAION-AI/Open-Assistant#1029]
Rephrase some existing biomedical text datasets as dialogue or QA

**Comment by ontocord** [comment]
I believe you were going to start with pubmed. 

thank you!

**Comment by ontocord** [comment]
cc @pruksmhc

**Comment by uyhcire** [comment]
Inpainted dialogs (little modified from the dialog inpainting dataset), unfiltered for biomedical relevance: https://huggingface.co/datasets/ericyu3/openassistant_inpainted_dialogs

**Comment by uyhcire** [comment]
Working on filtering to biomedical topics

**Comment by ontocord** [comment]
I believe this issue is closed by the PR
