### ISSUE TITLE
Design a nice loading screen component

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#103]
When we're fetching a task for a contributor, we have a pretty boring loading component.  It would be nice to have a visually appealing loading screen component we can re-use in all of our task pages or in general whenever some part of the UI is loading data.

This should probably use a Chakra progress loader or progress bar with some additional wrapping around it.

**Comment by jojopirker** [comment]
Somewhat like this? Text would be optional...

https://user-images.githubusercontent.com/19796430/209836633-58530458-9bed-4f17-942d-de4069c1fb43.mov

**Comment by yk** [comment]
this is a very clean solution! for really long waits, we could think of displaying little hints or something like that, but I'd guess for what we need right now, this seems very neat!

could you PR this?

**Comment by fozziethebeat** [comment]
Yup! this is a solid solution
