### ISSUE TITLE
Web Team Meeting - 2023-02-01

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#1037]
Agenda:
  * Building out the required admin features
    * Halting Trees using `/api/v1/messages/{message_id}/tree/state` with `halt=true`
    * Fetch more user messages using time based pagination with `/api/v1/users/{user_id}/messages`
  * Discuss: What do we mean by browse all message trees?

**Comment by andreaskoepf** [comment]
- for user browsing the cursor method can be used `/api/v1/users/{user_id}/messages/cursor`
- display user streak + nearby user-stats window
- display `/messages` in the web-app filtered by current language .. e.g. `/messages/de`?

**Comment by andreaskoepf** [comment]
- go over the beta-feedback 
- discuss the ranking UI
  - full text / long text needs to be displayed correctly formatted
  - e.g. can we in general show a bit more of each candidate-texts?
  - can we show the long-version of text more easily, e.g. hover for devices with mouse and correctly formatted? 
  - should we show emojis for the candidate messages?

**Comment by fozziethebeat** [comment]
# Notes

* Details:
  * Just Keith & Yannic attended
  * Broad priority:
    * Implement suite of Admin features to manage data and users
    * Improve UI as time permits
    * Block on implementing chat UI until inference component has reliable docker setup 
* Admin Features:
  * When in the messages view and inspecting a message, need a way for admin's to either delete a message or halt the tree.  Halting can be done by calling `/api/v1/messages/{message_id}/tree/state`  We already have a PR for deleting the message (PR https://github.com/LAION-AI/Open-Assistant/pull/1041).  We might want to change that once it's in to instead delete a message directly instead take the admin to a message admin view where they can delete or halt the message.
  * When inspecting data for a user (via admin user view) we need to fetch more messages submitted by the user.  This should use `/api/v1/users/{user_id}/messages` with an appropriate timestamp boundary.
* Priority Beta Feedback Issues:
  * #1047 (data consent)
  * #962 (i18n)
  * #969 (UI)
  * #977 (documentation)
  * #1039 (documentation)

# To Discuss Later
* How should we display all message trees for admin review?
