### ISSUE TITLE
Add ToS/License Agreement/Cookies popup to Web-App

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#1047]
Every user of the web application has to accept the OA ToS/license agreement before submitting data

I have added backend functionality to manage users and checks for the acceptance:
https://github.com/LAION-AI/Open-Assistant/pull/1046

Required changes in web:
1. on login or dashboard navigation check ToS acceptance status at backend (potentially create user via new POST `/api/v1/frontend_users/` endpoint.
2. check if user has accepted ToS - if not display popup dialog with legal text and checkbox or Yes / No buttons.
3. Navigate user to https://laion.ai/ if they select No (or log user out)

Legal team:
- needs to prepare document to show

**Comment by AbdBarho** [comment]
Is it possible to have the user accept the ToS the first time they try to do a task instead of when they first navigate to the dashboard? 

Otherwise, I think it would also make sense to add a checkbox to the signup screen, before even logging in.

**Comment by andreaskoepf** [comment]
> Is it possible to have the user accept the ToS the first time they try to do a task instead of when they first navigate to the dashboard?

Yes absolutely .. the backend will send a 451 Unavailable For Legal Reasons response for next-task requests when the user has not accepted the ToS (acceptance-date is still Null in the DB).

**Comment by AbdBarho** [comment]
@andreaskoepf do we have the text or a link for the terms of service? otherwise I will use a dummy place holder
