### ISSUE TITLE
Use discord credentials when interact with backend when they exist

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#105]
When a user logs into the website, we store their Discord credentials.  When they exist, we should use those instead of the websites local auth identifier so that their website and discord contributions are all associated with the same ID.

This should improve the code the following api handlers to ensure this is done properly.
* `website/src/pages/api/new_task/[task_type].ts`
* `website/src/pages/api/update_task.ts`

The fix should be pretty simple and could be done with a little library code.

**Comment by KarthikRaju391** [comment]
Hey @fozziethebeat, can I work on it?

**Comment by yk** [comment]
hey @KarthikRaju391 thanks a lot for wanting to contribute! could you write down a short plan, like a few steps on what you'd do? I can assign you after that

**Comment by KarthikRaju391** [comment]
Sure @yk, based on what I understood, we want to ensure that when a user is logged in using Discord, their Discord credentials should be used on their websites instead of the local auth identifiers. 
So, I will have to change the frontend code to use the Discord credentials that have already been saved instead of the locally generated ones which will include figuring out the API requests and making changes accordingly.
I have to say that I am not sure if I have understood it correctly, but I am willing to learn. Let me know what you think. Thanks!

**Comment by yk** [comment]
sounds like a plan :)

**Comment by KarthikRaju391** [comment]
Hey @yk, I have set up the frontend successfully. Although, I was only able to sign in using email and not discord. Is there a way to login using discord?

**Comment by fozziethebeat** [comment]
yes, this one just requires rewriting a little bit of code.

To get discord credentials, I suggest going to https://discord.com/developers/applications and then
1. Create a test app (name it whatever)
2. Go to the OAuth2 page within the app
3. Copy over the client id and client secret
4. Put those in a `.env.local` file under two environment variable names: `DISCORD_CLIENT_ID` and `DISCORD_CLIENT_SECRET` (I apparently didn't document this so my apologies for it being confusing).
5. Then you can load up the website and should be able to login.

**Comment by KarthikRaju391** [comment]
Hey @yk, I did set up discord client id and secret. I am able to see `Continue with Discord` but I am not able to login with it. 
Is there something I am missing?

**Comment by KarthikRaju391** [comment]
Update: I got the discord authentication. There was a mistake in the `signin.tsx` file. In the signin method for discord, we have to do it the following way:
```typescript
     const signinWithDiscord = () => {
     signIn("discord", { callbackUrl: "/" })
  }
```
the first argument is a string and earlier it was just using the discord object

**Comment by KarthikRaju391** [comment]
Although, now it is not redirecting to the homepage after logging in with discord.

**Comment by yk** [comment]
Hey @KarthikRaju391 nice work, sorry I missed your first request. Could you include the update to the docs that you envision in your PR?

**Comment by fozziethebeat** [comment]
+1 to adding this explanation to the docs.

Can you make a screen recording of your attempt to login via discord? It works with the credentials I created but it's possible there's another discord step needed to make this work that I forgot about already.

**Comment by KarthikRaju391** [comment]
@fozziethebeat, I don't have my laptop right now, can I send the video recording by 11pm IST?
Also, I'll add the explanation to the docs by then.
Is there any steps I need to follow to update the documentation?

**Comment by yk** [comment]
no worries :) not really, just add it to the `discord-bot/README.md` where you feel it's appropriate

**Comment by KarthikRaju391** [comment]
Thanks @yk!

**Comment by KarthikRaju391** [comment]
Hey @yk, since I am not able to login through discord, I have not yet been able to make the UI changes to show the discord credentials instead of the local credentials. 
Once, I get to know the fix for the discord login, I can go ahead. Should I still make a PR for the documentation changes?

**Comment by KarthikRaju391** [comment]
https://www.loom.com/share/0d3512ae27994e91b61fc85287403d8e
This is what is happening when I try to login using discord @fozziethebeat

**Comment by yk** [comment]
> Once, I get to know the fix for the discord login, I can go ahead. Should I still make a PR for the documentation changes?

no stress, if you want, it can all go in one PR once it's ready. but two PRs is also fine, up to you :)

**Comment by fozziethebeat** [comment]
I see what the problem was.  Can you reset your database and then try logging in via discord again?

My guess is that you logged in before with email credentails and then tried logging in via discord credentials.  NextAuth doesn't let you do that by default.  Our custom signin page doesn't present the error the same way that NextAuth's default [signin page does](https://user-images.githubusercontent.com/595695/89105117-5645b780-d416-11ea-84a5-030feeebd790.png).   I filed #224 to better handle this issue.

You can side step that for now by resetting the webdb (most easily by doing `docker compose down` and then `docker compose up frontend-dev` followed by `npx prisma db push`).

**Comment by KarthikRaju391** [comment]
Oh yes, I totally forgot about restarting docker. I will work on it now.
Thank you @fozziethebeat

**Comment by KarthikRaju391** [comment]
@yk, the website is now showing discord credentials when a user is logged in through discord. 
But as mentioned in #224, what if we a user already logged in via email and wants to add their discord account too?
I found a similar request in this [reddit form](https://www.reddit.com/r/nextjs/comments/wlyj7m/nextauth_login_to_multiple_providers_at_the_same/) but it was a bit confusing. 
Also,  I had to make changes to `next.config.js` to accept the discord user avatar as the `src` for the `Image` component.

**Comment by fozziethebeat** [comment]
We're treating that problem as a separate issue in #106.  You don't need to handle that situation in this issue.

We can also skip dealing with the discord avatar in the website for now.  That's a nice to have but the important part is that when the web api handler is talking to the backend, it's sending the user's discord ID instead of the website generated ID.

**Comment by KarthikRaju391** [comment]
@fozziethebeat, regarding the API handler, right now, discord ID is being used.

![image](https://user-images.githubusercontent.com/67912316/210168269-9ab865fe-4d04-4f5d-83d1-225b26ac485f.png)

But I am getting the following error in prisma when trying to make the API requests.
![image](https://user-images.githubusercontent.com/67912316/210168306-13a5cda3-ed34-4522-8294-a57d961d6eab.png)

**Comment by fozziethebeat** [comment]
Can you inspect the contents of your database by running `npx prisma studio` and see what's in the User table?

What is this log statement emitting? Is this the user token gotten in the handler?

**Comment by KarthikRaju391** [comment]
Yes it is the user token

**Comment by KarthikRaju391** [comment]
I checked the contents of the database and nothing is being stored in User table.

**Comment by fozziethebeat** [comment]
When you restarted the docker setup and reset the database, did you log out of the website and then log back in?

The website uses JSON Web Tokens and so the issue is that the database has been reset but your JWT doesn't know it's invalid.  You have to sign out and sign back in every time yo wipe the database clean.

**Comment by KarthikRaju391** [comment]
@fozziethebeat, I reset the database again and I am able to make API requests without any problems.
Should I make the pull request now?

**Comment by fozziethebeat** [comment]
Sure! If the rest of the changes look good, prepare the PR, make sure the pre-commit checks all pass and then I'll take a look.

**Comment by KarthikRaju391** [comment]
Hey, @fozziethebeat, I synced the fork before committing and am having merge conflicts. How should I deal with them?

**Comment by fozziethebeat** [comment]
I recommend following the guidance in [this](https://timwise.co.uk/2019/10/14/merge-vs-rebase/#should-you-rebase) guide regarding pulling in changes from the main branch.

**Comment by KarthikRaju391** [comment]
@fozziethebeat, I have pulled the changes successfully but I am getting a few errors when trying to `reply as user` and `rank user replies` in the website. 
I checked the database and I found that the data being stored in the `task` are not the same throughout.

![image](https://user-images.githubusercontent.com/67912316/210213554-6dce7799-75da-4710-b6b5-ad099c616e1b.png)

**Comment by fozziethebeat** [comment]
This is a little hard to diagnose without context.  Can you prepare the pull request and send it out? It might be easier to figure out if there's an issue by just reviewing the PR

**Comment by KarthikRaju391** [comment]
Sure, I will create a pull request then.

**Comment by KarthikRaju391** [comment]
Hey @fozziethebeat, after I pulled the changes by rebasing my feature branch with the main branch, most of the changes had already been updated with the latest ones. Now, when I am trying to commit the changes, the `pre-commit` hook is running without showing any errors but the files are not being commited

**Comment by KarthikRaju391** [comment]
@yk, all the pre-commit tests are either passing or being skipped, and even doing `git add` after running `pre-commit`, when I commit the changes, pre-commit is being run again.

**Comment by yk** [comment]
if all tests pass or skip, then pre-commit is happy and there's some other reason your files aren't being committed. are they matching something in gitignore?

**Comment by KarthikRaju391** [comment]
It's the README file

**Comment by yk** [comment]
feel free to reach out to me on discord, I can maybe help you more closely

**Comment by fozziethebeat** [comment]
I'm going to close this for now.  We can figure out how to merge accounts later.
