### ISSUE TITLE
Convert re3 dataset to instructions

### ISSUE THREAD

**Issue by JediMaster25** [LAION-AI/Open-Assistant#1053]
Something like
[Re3: Generating Longer Stories With Recursive Reprompting and Revision](https://arxiv.org/abs/2210.06774)

**Comment by IkariDevGIT** [comment]
@ontocord how can you help? i would like to help

**Comment by ontocord** [comment]
@IkariDevGIT You can see the the re3 dataset is available. You could try downloading it and converting into instrucitons, like "Write me a continuations for XYZ -> continuation text". This can apply to other story like data too.

**Comment by IkariDevGIT** [comment]
@ontocord wait, where can you download it?

**Comment by olliestanley** [comment]
> @ontocord wait, where can you download it?

@IkariDevGIT  https://github.com/yangkevin2/emnlp22-re3-story-generation, see the README

`wget https://emnlp22-re3-data.s3.amazonaws.com/emnlp22_re3_data.zip`

**Comment by andreaskoepf** [comment]
Closing old data issue.
