### ISSUE TITLE
Reply as assistant page is flickering randomly when typing in the reply box

### ISSUE THREAD

**Issue by KarthikRaju391** [LAION-AI/Open-Assistant#1054]
https://user-images.githubusercontent.com/67912316/216079046-63b58617-7bb3-4b6f-9190-890d46b5a95a.mp4

**Comment by AzielChamba** [comment]
I can help with that, assign it to me.

**Comment by andreaskoepf** [comment]
@KarthikRaju391 I have not seen these overflow effects before. Which platform / browser are you on? Could it be related to the Grammarly plugin?

**Comment by KarthikRaju391** [comment]
@andreaskoepf, I am using the brave browser. I am not sure about it being related to the Grammarly plugin. I can look into it again once. 
But, I observed that it was flickering slowly even when I wasn't typing anything.

**Comment by AbdBarho** [comment]
I will close this now, since it is a Grammarly extension problem, not in this repo.
