### ISSUE TITLE
Add minimalistic system config parameter view (readonly, just the json) to admin dashboard

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#1068]
- use backend API: GET `/api/v1/admin/backend_settings/full` and if that fails use GET `/api/v1/admin/backend_settings/public` as a fallback (only trusted api-clients can access the full settings).
- add a "Parameters" tab on the left side, if selected show simply the current config as JSON text (similar to other things in the admin interface).

**Comment by notmd** [comment]
Let me take this.
