### ISSUE TITLE
Simpler docker compose build

### ISSUE THREAD

**Issue by MohamedAliRashad** [LAION-AI/Open-Assistant#107]
The current structure of the project can be confusing to new comers, I think combining the docker compose of back-end and front-end in one file and putting it outside `scripts` so the tutorial for how to build the repo is simple and straight forward will be appreciated.

**Comment by fozziethebeat** [comment]
Can you explain the issues you had with the current documentation?  We intended each of those docker compose setups to be independent based on which part of the project you're working on.

If you're working on the webside, you just need to run the script in `scripts/frontend-development` and can ignore the others.  It turns up all the required backend services.

**Comment by MohamedAliRashad** [comment]
I understand the benefits of separation for development but for simple users with me who want to fire up the project and see how it looks and works on their machine can benefit from the docker compose of the full project (similar to the docker-compose in `endtoend-demo`) be in the front of the repo with the how to use tutorial underneath the code directly.

**Comment by fozziethebeat** [comment]
If i understand correctly, a nice entry point to see the project end to end would be to highlight the `endtoend-demo` configuration so that someone could see how everything works and then decide where to help contributing?

I can take a try to better write the initial README to document that starting point.  We probably won't move things around but describing it all could be better. 

Would that help?

**Comment by croumegous** [comment]
I think I have a good idea to improve the use of docker-compose, I will make a PR very soon. Then it's up to you to see if it looks better or not

**Comment by MohamedAliRashad** [comment]
@fozziethebeat Yes

**Comment by croumegous** [comment]
Here is my PR https://github.com/LAION-AI/Open-Assistant/pull/119 that tries to simplify docker compose usage

**Comment by yk** [comment]
Solved by #119 . Thank you @croumegous
