### ISSUE TITLE
Add trollboards admin UI

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#1073]
The backend computes trollboards similarly to leaderboards: GET `/api/v1/trollboards/{time_frame}`. Valid values for time_frame are day, week, month, total.

It would be nice to have a similar view like the leaderboards for the trollboards too (only for admins as part of the admin interface):

Note: The mean-review scores "quality", "humor", "toxicity", "violence", "helpfulness" can be `null` if no corresponding label was available.

The JSON returned looks like this:
```
{
  "time_frame": "week",
  "last_updated": "2023-02-02T15:10:10.218372+00:00",
  "trollboard": [
    {
      "rank": 1,
      "user_id": "e54d8c27-8c48-4c2c-bb3a-d64bb30f17dc",
      "highlighted": false,
      "username": "enieiaedquq000hpe01ny4yn9zk",
      "auth_method": "local",
      "display_name": "xyz",
      "last_activity_date": "2023-01-31T20:46:25.869342+00:00",
      "troll_score": 45,
      "base_date": "2023-01-26T00:00:00+00:00",
      "modified_date": "2023-02-02T15:10:10.218372+00:00",
      "red_flags": 4,
      "upvotes": 20,
      "downvotes": 5,
      "spam_prompts": 40,
      "quality": 0.6065217391304348,
      "humor": 0.14743589743589744,
      "toxicity": 0.08205128205128205,
      "violence": 0.026923076923076925,
      "helpfulness": 0.5672514619883041,
      "spam": 114,
      "lang_mismach": 4,
      "not_appropriate": 3,
      "pii": 0,
      "hate_speech": 0,
      "sexual_content": 1,
      "political_content": 0
    },
    {
      "rank": 2,
      "user_id": "12341234-b867-49be-8f75-93ec86aa2f38",
      "highlighted": false,
      "username": "999999999999999",
      "auth_method": "discord",
      "display_name": "user2",
      "last_activity_date": "2023-02-02T00:05:32.565224+00:00",
      "troll_score": 31,
      "base_date": "2023-01-26T00:00:00+00:00",
      "modified_date": "2023-02-02T15:10:10.218372+00:00",
      "red_flags": 2,
      "upvotes": 9,
      "downvotes": 28,
      "spam_prompts": 0,
      "quality": 0.5031512605042017,
      "humor": 0.193359375,
      "toxicity": 0.13671875,
      "violence": 0.037109375,
      "helpfulness": 0.5047619047619047,
      "spam": 9,
      "lang_mismach": 1,
      "not_appropriate": 4,
      "pii": 0,
      "hate_speech": 1,
      "sexual_content": 0,
      "political_content": 0
    },
...
```

**Comment by andreaskoepf** [comment]
@occupytheweb Thanks a lot for implementing this. It would be nice if you could add a link from the usernames to the users admin pages (e.g. /admin/manage_user/{user_id}).

**Comment by occupytheweb** [comment]
@andreaskoepf Ok, noted. 
Should the whole be clickable, or just the username?
Will an admin user be able to perform the same kind of navigation from the Leaderboard component as well?

My current direction is to make the leaderboard generic enough to be re-usable for the Trollboard.
To allow for navigation based on a property of the model, I'll have to modify the base DataTable component to allow consumers to specify an accessor lambda for the id of the current row.

**Comment by andreaskoepf** [comment]
Sounds good. Clickable username would be fine. Would be great if the admin-nav worked for the normal leaderboard too…

**Comment by notmd** [comment]
> @andreaskoepf Ok, noted. Should the whole be clickable, or just the username? Will an admin user be able to perform the same kind of navigation from the Leaderboard component as well?
> 
> My current direction is to make the leaderboard generic enough to be re-usable for the Trollboard. To allow for navigation based on a property of the model, I'll have to modify the base DataTable component to allow consumers to specify an accessor lambda for the id of the current row.

Maybe you can extract it to useLeaderBoard and useTrollBoard hooks. Just ask me if you need help because I code most of LeaderBoard and DataTable components
