### ISSUE TITLE
Time for a blog on the docs site?

### ISSUE THREAD

**Issue by andrewm4894** [LAION-AI/Open-Assistant#1093]
Would be easy to turn on blog functionality of docusarus on the docs site.

Could be useful for persistent announcements. 

I also see lots of people wanting to add sort of experiment writes ups and things like that. I could see a lot of this ending up maybe mixing up a bit if too much ends up living in next to the code. Can be harder to find and end up as clutter potentially. 

Perhaps being able to just have people submit a blog post could be useful to have this channel too. 

Thoughts?

I can easily set this up if we want it.

**Comment by andrewm4894** [comment]
added #1203 for this

**Comment by olliestanley** [comment]
#1203 is merged so I am closing this
