### ISSUE TITLE
Allow to create a reply for task from `Open in new tab` view 

### ISSUE THREAD

**Issue by lainisourgod** [LAION-AI/Open-Assistant#1094]
Hi! 

I've been completing "Label Inital Prompt" task and seen a message that I know how to answer as an Assistant (1).

Then I opened it in a new tab to know if it had already been answered and seen that it's not answered (2).

From this point I want to be able to do a task "Reply as Assistant" for this message. E.g. have some button in a context menu, or on the page of this message (3).

<img width="785" alt="CleanShot 2023-02-04 at 16 43 51@2x" src="https://user-images.githubusercontent.com/24773652/216768439-2f173311-3498-4054-80b8-18aae5a734b2.png">

<img width="915" alt="CleanShot 2023-02-04 at 16 44 01@2x" src="https://user-images.githubusercontent.com/24773652/216768485-08069d2e-4606-4949-821f-10a4cfed5220.png">

<img width="741" alt="CleanShot 2023-02-04 at 16 44 09@2x" src="https://user-images.githubusercontent.com/24773652/216768517-970e7e7a-9a2c-42d8-b53b-0804d96c9c0a.png">

**Comment by AbdBarho** [comment]
Thanks for the suggestion.

There were a lot of discussion about making messages reachable and answerable by ID, we are very unsure about this, since the potential for abuse of this future for targeting certain messages or conversation trees is high.

**Comment by Pawank06** [comment]
Hey can you assign me this issue I can solve this issue

**Comment by fozziethebeat** [comment]
I think if we want to support full end to end task completion, we should probably created a dedicated UI for that that allows end to end editing.  In general tho I think we want to make this use case intentionally hard.
