### ISSUE TITLE
Show examples of task completions in docs

### ISSUE THREAD

**Issue by lainisourgod** [LAION-AI/Open-Assistant#1098]
We have a [prompting guide](https://projects.laion.ai/Open-Assistant/docs/guides/prompting) as a guideline for completing the task, but it misses more real-world examples.

We may collect some good and bad examples from our already collected data and present them in docs. e.g. put some screenshots with explanation why in these particular cases should have these ratings.

<img width="1199" alt="CleanShot 2023-02-04 at 20 59 20@2x" src="https://user-images.githubusercontent.com/24773652/216779846-60bda3d9-82a3-420d-be37-7b9275ca2166.png">

**Comment by lainisourgod** [comment]
I guess [a recent video of Yannick](https://youtu.be/64Izfm24FKA)  can be an appropriate and full-fledged addition to the docs as he explains the logic behind every task he completes.

**Comment by olliestanley** [comment]
This sounds like a good idea. @lainisourgod would you be willing to put a few examples together and add them to the prompting doc?

**Comment by AbdBarho** [comment]
https://projects.laion.ai/Open-Assistant/docs/guides/examples
