### ISSUE TITLE
Mail signup did not work for me

### ISSUE THREAD

**Issue by benjamin-asdf** [LAION-AI/Open-Assistant#1100]
1. Try to sign up with email
2. first time it immediatly said the link is not valid anymore
3. second time the link then timed out (got a ngnix 503 screen). 

Maybe high traffic from tthe youtube video.

**Comment by samuel-git** [comment]
Some email providers seem to block the sign up email completely (does not appear in spam folder). In my case it is gmx but out of experience it might also be a problem with web.de and other services from [Ionos](https://en.wikipedia.org/wiki/Ionos).

I got the email with an gmail.com address but the "Sign up" button leads to https://open-assistant.io/api/auth/error?error=Verification like OP.

**Comment by BananaAcid** [comment]
Same problem here on my own server. Guessing it, it might fail on one of the following: Gray Listing, SPF, DEKIM, missing generic headers, SpamAssasin

**Comment by fozziethebeat** [comment]
I think this is due to the lack of DKIM for our email address.

**Comment by EverythingSuckz** [comment]
![image](https://user-images.githubusercontent.com/65120517/217443311-4381a1f9-40dd-4784-8661-3981092f8beb.png)
:(

**Comment by davidak** [comment]
I had the problem that i don't got an e-mail (https://github.com/LAION-AI/Open-Assistant/issues/1388). Probably related to Greylisting.
