### ISSUE TITLE
API to ease our lives

### ISSUE THREAD

**Issue by Shahin-rmz** [LAION-AI/Open-Assistant#1102]
Hi,
I was wondering, why we don't have open sourced ChatGPT.

I recently work alot with chatgpt, and can give good amount of answers from there to open Assistant.
Just need an API where easily submit the prompts and answers!.

**Comment by olliestanley** [comment]
We don't want to use ChatGPT answers as training data for Open Assistant, as it violates OpenAI's TOS

**Comment by Realiserad** [comment]
ChatGPT aside, to integrate OpenAssistant with other systems, it would be very useful with an API to submit and retrieve responses.

If I understand this issue correctly,such an API is currently not available?

There seems to be a REPL [here](https://github.com/LAION-AI/Open-Assistant/blob/main/text-frontend/auto_main.py), which submits and retrieves answers over REST.

**Comment by olliestanley** [comment]
> ChatGPT aside, to integrate OpenAssistant with other systems, it would be very useful with an API to submit and retrieve responses.
> 
> If I understand this issue correctly,such an API is currently not available?
> 
> There seems to be a REPL [here](https://github.com/LAION-AI/Open-Assistant/blob/main/text-frontend/auto_main.py), which submits and retrieves answers over REST.

Yes, there's the API that we use for the website. To use it externally you would have to deal with authentication etc, following how the website does it.
