### ISSUE TITLE
persian language maybe?

### ISSUE THREAD

**Issue by Shahin-rmz** [LAION-AI/Open-Assistant#1103]
As an Iranian who speaks persian, I suggest, there will be good idea to have persian language option in Open Assistant.

**Comment by kpoeppel** [comment]
See Issue #1123

**Comment by olliestanley** [comment]
Anyone who is willing can add a translation. See 0fc1109034807085afc0b3023b63f595c0011210 for an example of how to add one

**Comment by fozziethebeat** [comment]
yes! Please submit a PR with translations if you're able to help.  This depends heavily on a persian speaker helping contribute :)

**Comment by AbdBarho** [comment]
https://open-assistant.io/fa/dashboard
