### ISSUE TITLE
When a  Task is in the Wrong Language, Do not require Spam classificantion

### ISSUE THREAD

**Issue by ozten** [LAION-AI/Open-Assistant#1108]
I chose English. I got a Russian or other language prompt.

In order to submit the form, I must flag it Spam or Not Spam, but I don't know how to read that. It is user friction to have to translate and low quality guess as to weather it is spam or not.

Expected: "Wrong Language" removes the required requirement for other fields.

**Comment by olliestanley** [comment]
I think this isn't a problem, Wrong Language messages can just be always marked as Spam
