### ISSUE TITLE
Initial Sign-on bug with TOS

### ISSUE THREAD

**Issue by Austin-Earl-Private** [LAION-AI/Open-Assistant#1117]
If the servers are under a lot of load, the sign-on link doesn't load properly. Thus moving a user to the Dashboard where they are greeted with the TOS. A user will then attempt to agree with the TOS and it will error out. The solution is to set a username in account settings first then accept TOS.

Steps to reproduce:

1. Create new account
2. Dont set UserName
3. Attempt to agree to the TOS
4. Visually nothing happens, the User thinks they are locked out. The console reports many 500 errors.

**Comment by AbdBarho** [comment]
Fixed in https://github.com/LAION-AI/Open-Assistant/pull/1207
