### ISSUE TITLE
Set up grafana and log things

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#1121]
- postgres metrics, table sizes, etc.
- backend metrics
- load balancer metrics
- frontend metrics

**Comment by andrewm4894** [comment]
Hey for frontend telemetry I can help set up https://posthog.com/ really really easy.

Basically just snippet and then get a lot of really good stuff for free basically.

**Comment by andrewm4894** [comment]
Related issue, just cross posting.

https://github.com/LAION-AI/Open-Assistant/issues/458

**Comment by abinmn** [comment]
I'd like to take up the Grafana setup and Postgres integration part

**Comment by AbdBarho** [comment]
@abinmn it is all yours

**Comment by andrewm4894** [comment]
I'd be interested in helping too, I work at a monitoring company (https://github.com/netdata/netdata)

Pretty sure I could get us a free sponsored space for monitoring via netdata, would be fairly easy to set up. Here is a demo space with a postgres node in it. https://app.netdata.cloud/spaces/netdata-demo/rooms/postgresql/

This could of course be in addition to grafana and Prometheus. 

Anyway would be happy to help too whatever tools we decide to use.

**Comment by andrewm4894** [comment]
made a PR [here](https://github.com/LAION-AI/Open-Assistant/pull/1366) with example of adding local netdata dashboards for containers and redis, postgres, etc. 

will try have a stab at something similar for Grafana and Prometheus in a different feature branch.
