### ISSUE TITLE
No Italian?

### ISSUE THREAD

**Issue by pansk** [LAION-AI/Open-Assistant#1123]
Italian language is missing. Is there any plan to add it?

**Comment by sedthh** [comment]
You can add your own language similarly to https://github.com/LAION-AI/Open-Assistant/pull/1081

**Comment by olliestanley** [comment]
@pansk Would you be interested in contributing the translation for Italian?

**Comment by Oscar-irrational** [comment]
I've sent over the italian translations, have fun ciao

**Comment by Jac-Zac** [comment]
I'll translate it in Italian

**Comment by Oscar-irrational** [comment]
> I'll translate it in Italian

check your discord messages I sent you half the translation to save you some time

**Comment by Oscar-irrational** [comment]
@Jac-Zac 
check your discord messages I sent you half the translation to save you some time

**Comment by andreaskoepf** [comment]
completed by https://github.com/LAION-AI/Open-Assistant/pull/1244
