### ISSUE TITLE
String localization issue on web interface

### ISSUE THREAD

**Issue by lewiswatson55** [LAION-AI/Open-Assistant#1124]
Hello,

There seems to be a bug somewhere with the label prompt button from within the message detail page. 

Clicking on the "label prompt" button from the recent messages tab works fine, see below 

![image](https://user-images.githubusercontent.com/7228600/216788173-7182dd9d-ab4e-4c54-9b01-bec4e17383c3.png)

But when you open the full message and select the label prompt from the menu you can see (what looks like) the localization strings, see below.

![image](https://user-images.githubusercontent.com/7228600/216788300-39d42536-9f31-4184-bc5b-9c4fecca40de.png)

Could be a known issue, but cant see anything about it. The screenshots are from the deployed/public site not locally.

**Comment by AbdBarho** [comment]
Thanks for the report, will give it a look.
