### ISSUE TITLE
Add a way to annotate spelling and grammatical errors

### ISSUE THREAD

**Issue by CWBudde** [LAION-AI/Open-Assistant#1126]
So far, the suggested answers, prompts and so forth, might contain spelling and grammatical errors. While for the user input, this is tolerable (if not favorable in order to get a bigger range of input), it's something I would not want to see from AI answers.

Especially when the user should answer as AI, it is crucial (in my belief) to spellcheck this answer before using it for the training.

**Comment by olliestanley** [comment]
Related: #1005

**Comment by olliestanley** [comment]
Covered by #1412. This issue was opened first but that one has garnered more attention so I will close this one
