### ISSUE TITLE
Split/Search task by knowledge (similarly as we split task by language)

### ISSUE THREAD

**Issue by fcolecumberri** [LAION-AI/Open-Assistant#1127]
The same way I can tell the app that my main language is not English so I can contribute the most I can on a language I have native skills, I think we could make a better job by also telling the system to search for task with certain type of content.

Currently evaluating/generating a response where we don't have deep knowledge might, some times, be ok as long as we do a good research, however that's not always the case.

To give an example, according to Dr. Robert Miles's Interview about ChatGPT ( https://www.youtube.com/watch?v=viJt_DXTfwA min 22 ), CGPT knows what an ode and a sonnet are, but once you ask it to generate one, it just can't (It generates a more less generic poem). Robert Miles thinks it is because people training CGPT might not know how to generate/evaluate one (which is a task that requires more than just a small research).

If we let people who know about literature, generate/evaluate literature related tasks, that would give better results.

And by literature, I mean any other field. Also I don't think we need a complex modification, for example I have years of experience with robotics, so if I could search for tasks that I have not helped where any of the words `ROS`, `Robot`, `Arduino`, `OpenCV`, `UART`, etc. I can generate/evaluate responses better than a what I can do when evaluating/generating a prose.

**Comment by olliestanley** [comment]
Duplicate #1316

**Comment by olliestanley** [comment]
> > Duplicate #1316
> 
> How is **this** a duplicate of another issue that came after it? if any, #1316 is a duplicate of this, not the other way arround.

Sorry meant to tag as duplicate of #1006 - 1316 is a part required for 1006 which is the overall feature
