### ISSUE TITLE
The language selector does not have a Norwegian option.

### ISSUE THREAD

**Issue by Sebbog1** [LAION-AI/Open-Assistant#1131]
No Norwegian option in the language selector is not a bug, but it should probably be added.

**Comment by Sebbog1** [comment]
I understand why you might not have added Norwegian as an option, as it may not be used alot. But it would still be a nice feature to have.

**Comment by AbdBarho** [comment]
@Sebbog1 would you be willing to contribute Norwegian translation?

**Comment by bitplane** [comment]
Here's an example of a Turkish translation that was recently merged:

https://github.com/LAION-AI/Open-Assistant/pull/1195

Tap on the "files" tab to see what changes were made to make this happen. If you do the same sort of thing for Norwegian then it'll likely be added quickly. If you need help doing this @me here or DM me on Discord, I'll be happy to help

I'm not sure which of "no", "nn" and "nb" are the right code though. I suspect "no"?

**Comment by jfainberg** [comment]
@bitplane Apologies for barging in. Norwegian has two written languages, usually denoted by "nb" and "nn", where the former is more common. "no" is sometimes used to refer to them both collectively.

**Comment by paal85** [comment]
I am currently translating Norwegian (bokmål nb-NO). First draft available here: [https://github.com/paal85/Open-Assistant/commit/99dae2af7ad32bed671a7600452ccc8b61a23e13](https://github.com/paal85/Open-Assistant/commit/99dae2af7ad32bed671a7600452ccc8b61a23e13)
I will create a merge request when I am finished, just giving a heads up here, so we don't do the same work several times.

**Comment by Sebbog1** [comment]
> Here's an example of a Turkish translation that was recently merged:
> 
> #1195
> 
> Tap on the "files" tab to see what changes were made to make this happen. If you do the same sort of thing for Norwegian then it'll likely be added quickly. If you need help doing this @me here or DM me on Discord, I'll be happy to help
> 
> I'm not sure which of "no", "nn" and "nb" are the right code though. I suspect "no"?

just make one for nn and one for nb both are valid languages ofc i dont know nynorsk (nn) so nb (norsk bokmål) first

**Comment by Sebbog1** [comment]
> I am currently translating Norwegian (bokmål nb-NO). First draft available here: [paal85@99dae2a](https://github.com/paal85/Open-Assistant/commit/99dae2af7ad32bed671a7600452ccc8b61a23e13) I will create a merge request when I am finished, just giving a heads up here, so we don't do the same work several times.

did not even know you could do that how? iam not so good at github

**Comment by Sebbog1** [comment]
> I am currently translating Norwegian (bokmål nb-NO). First draft available here: [paal85@99dae2a](https://github.com/paal85/Open-Assistant/commit/99dae2af7ad32bed671a7600452ccc8b61a23e13) I will create a merge request when I am finished, just giving a heads up here, so we don't do the same work several times.

yeah i dont know what i can do, looks very complete

**Comment by Sebbog1** [comment]
> @Sebbog1 would you be willing to contribute Norwegian translation?

yeah

**Comment by Sebbog1** [comment]
> > > I am currently translating Norwegian (bokmål nb-NO). First draft available here: [paal85@99dae2a](https://github.com/paal85/Open-Assistant/commit/99dae2af7ad32bed671a7600452ccc8b61a23e13) I will create a merge request when I am finished, just giving a heads up here, so we don't do the same work several times.
> > 
> > 
> > yeah i dont know what i can do, looks very complete
> 
> Thanks, all strings are translated, just need to test it locally, check for spelling errors and possibly adjust translation of some words I was not sure the context of while translating. I will probably complete it by tonight. I also wanted a Norwegian translation, when I found this issue. As I am a dev, and it was not too much to translate, I decided to just doing it yesterday.

still nothing on the site need help?

**Comment by LarsEJonasson** [comment]
I started my own translation and missed this thread until I was well on my way. Since this discussion is quite inactive, I completed the translation: https://github.com/LarsEJonasson/Open-AssistantLarsFork/commit/a03596dd989a3f621ac56e26745ec89d48a7ff0f 

But it needs proofreading since I moved from Norway to Sweden as a child, so my word choices may be strange.

**Comment by bitplane** [comment]
> But it needs proofreading since I moved from Norway to Sweden as a child, so my word choices may be strange.

I know nothing about Norwegian, but if it allows people from Norway to contribute then strange word choices are better than no choice of language at all! If you open a pull request maybe others can review, or we can just get it in and fix any problems later :)
