### ISSUE TITLE
Response edit option

### ISSUE THREAD

**Issue by XavierRex** [LAION-AI/Open-Assistant#1136]
I think it would be a nice option when rating responses would be the ability to edit them and send them as a separate response if they generally have good quality but contain little mistakes or incorrect grammar. In this example response, the answer is good but given twice, so being able to hit 3 dots and edit would be useful.
![image](https://user-images.githubusercontent.com/98437003/216791898-85d2f9c8-1abd-4d41-970e-c4200433a0f3.png)

**Comment by olliestanley** [comment]
We have issue #1005 to track a similar feature request with some discussion of the best solution to this, so I'll close this as a duplicate. Feel free to add any comments there!
