### ISSUE TITLE
Star rating instead of ranking?

### ISSUE THREAD

**Issue by mangoepic** [LAION-AI/Open-Assistant#1137]
Hi, I was just wondering if you guys considered a star rating instead of ranking because it's more accurate and gives you more freedom to express your opinions on the quality of the options, for example if there are a few really good ones and just one bad one, or just one good one, or none etc.

**Comment by olliestanley** [comment]
We have labelling which includes the ability to rate messages from 1 to 5 on quality, helpfulness, and other tags. There is also the ability to thumbs up/down messages. All this information will be utilised alongside the rankings, so if the message is ranked 1st that doesn't necessarily mean it will be evaluated as a great message
