### ISSUE TITLE
Answers not submitted/ Prompts lost

### ISSUE THREAD

**Issue by jkminder** [LAION-AI/Open-Assistant#1138]
It has happened to me twice now that an answer/prompt I wrote wasn't correctly submitted (not visible under messages). This happened both times after researching the answer for ~15min (which makes it especially annoying;)). Maybe the website timed out or the connection dropped. But I could still press the Submit button. Afterwards, I was forwarded the "No more tasks for you" page.

**Comment by k-nearest-neighbor** [comment]
Thanks for posting. Is it possible to say when this happened? In the last hour?
It would be super awesome if you could estimate the time using this tool and paste the "output" if gives you that looks like `<t:NNN...>` here

**Comment by jkminder** [comment]
Hmm I would say it happened between <t:1675504800:T> and <t:1675555200:T>. My username is "resoundingcarpet" if that helps.
