### ISSUE TITLE
Docker is incompatible with older/alternative versions of windows

### ISSUE THREAD

**Issue by TheRobberPanda** [LAION-AI/Open-Assistant#1142]
![Docker_Desktop_Sw13AlCdgt](https://user-images.githubusercontent.com/44844784/216798570-eb30d77e-6c84-418d-8fb2-83094c334c20.png)
![Docker_Desktop_kBwddKczpO](https://user-images.githubusercontent.com/44844784/216798572-143e1416-80dd-47c2-82af-4852567a4d37.png)

**Comment by AbdBarho** [comment]
yeah you need an up-to-date version of windows to be able to run docker in wsl2, otherwise you are stuck with old versions.

Not sure if we can do anything about this.

**Comment by olliestanley** [comment]
I don't think this is realistically something we can change. To contribute you don't need to run Docker anyway, it's only needed for starting the local development version.
