### ISSUE TITLE
Cornell Movies Dialogs corpus 

### ISSUE THREAD

**Issue by shahules786** [LAION-AI/Open-Assistant#1163]
This corpus contains a sizeable metadata-rich collection of fictional conversations extracted from raw movie scripts. The task is to prepare this data by converting it into the `instruction->answer` format.

**Comment by ontocord** [comment]
Could you please convert it to something like:

Write me a {dialog/script/play/etc) between {characters1...N} about {whatever the subject is of the movie}"

Here's a {dialog/script/play/etc) between {characters1...N} about {whatever the subject is of the movie}:

character 1: dialog
character 2: dialog
etc.

Vary so that we can have follow ups questions.  "What would character 2 say if {...}"

Basically we are try to create a dialog for someone who might want to create a movie script :)

**Comment by ontocord** [comment]
See also: https://github.com/LAION-AI/Open-Assistant/issues/415

**Comment by shahules786** [comment]
Thanks. I'm on it.

**Comment by bennmann** [comment]
I got a Cornell website authentication error when attempting to download this dataset

**Comment by shahules786** [comment]
@bennmann  Can you try it from here? https://huggingface.co/datasets/cornell_movie_dialog

**Comment by shahules786** [comment]
@ontocord Should we consider using the `gender` & `year` attribute while forming the examples? For example,

```
Character 1: Hey, how are you?
Character N: good
User: Continue the dialogue assuming that the character N is {gender} 
```
Will this cause the model to be biased?

**Comment by bennmann** [comment]
@shahules786 I suggest we use the IMDB rating to filter for quality

in awk from the raw downloads: 
```
for i in $(awk '$7>7 {print $1}' Downloads/cornell\ movie-dialogs\ corpus/movie_titles_metadata.txt); do grep -a $i Downloads/cornell\ movie-dialogs\ corpus/movie_lines.txt; done | wc -l
300881 
```

There are still a lot of lines of dialogue (300881) for IMDB rating of 7 or higher.

**Comment by shahules786** [comment]
Makes sense.  @bennmann

**Comment by ontocord** [comment]
If you want to tie ratings to dialog, i think this would be cool.

Write a script for a "campy", "high qualty", "popular" {genre} movie

**Comment by ontocord** [comment]
@shahules786 - more diversity the better and more control in conversation. If you want to swap names that would be interesting. As for gender, I think you can play with this but it might mess with the content of the script. Unless you can find scripts that are less biased.

**Comment by shahules786** [comment]
@ontocord @bennmann can you guys take a look at the sample output [here](https://github.com/shahules786/Open-Assistant/blob/cornel-md/notebooks/data-augmentation/movie-dialogs/convert-to-instruction-format.ipynb)? Let me know what you think. Shall I proceed to upload it as HF dataset as shown in #415

**Comment by bennmann** [comment]
The sample output looks good, however perhaps it would be good to increase the number of produced lines (1-4 seems very low).

**Comment by ontocord** [comment]
Looks really good and fun.  I second the comment from @bennmann . Soda was short because we started off with short dialogs from the original dataset. But here we can really go wild :)

There's some formatting issues. I think you need a space between a sentence. 
Laslty, I saw one where it says "Assume you are X complete the dialog" but instead it acts as Y.

```PATRICK: Did you buy the horse, papa?
    RODERICK: Now, just have a little patience, my boy.  Your birthday isn't until next week.
    PATRICK: But I will have it on my birthday, won't I?
User : respond as PATRICK to complete the conversation
Assistant : Sure
    RODERICK: Well, we'll just have to wait and see, won't we?
```

I think this is gonna be very cool.

**Comment by ontocord** [comment]
Also if you have meta-data about any scenes, you can add questions like "Write a description of this scene".

You could also have a final instruciton, "Put all of the dialog and descriions together into a final script for this scene entitled 'xyz':"

Title: Xyz

Scene X

[description of scene]

dialog
dialog
dialog

**Comment by shahules786** [comment]
@ontocord  I also thought about adding that, but the dataset does not have any meta-data referring to the scene to which the conversation belongs to. 
Thanks for the review, I'll fix the issues and reupload the dataset ASAP.

**Comment by bennmann** [comment]
In the notebook linked higher up in this chain, I do not parse out where the IMDB rating is used in the dataset creation.

I would still request IMDB rating of 7 or higher for this dataset :) keep me honest if it's already there and I missed it

**Comment by shahules786** [comment]
@bennmann I think we will miss a little too much with an IMDB rating 7.0 as the threshold. How about 6?
<img width="458" alt="Screenshot 2023-02-09 at 9 51 12 AM" src="https://user-images.githubusercontent.com/25312635/217717071-5d17f75c-ce62-4709-8b0a-236031f5cbec.png">

**Comment by bennmann** [comment]
That depends on if we want Open Assistant to be trained to provide IMDB 6 quality scripts when asked to co-write after training.

Quality is better than the quantity, in my opinion, especially for co-writing. @shahules786

**Comment by shahules786** [comment]
@bennmann Agreed. I have made the changed & updated the dataset.

**Comment by shahules786** [comment]
PR Merged 🎉
