### ISSUE TITLE
Code highlighting in messages

### ISSUE THREAD

**Issue by rk1a** [LAION-AI/Open-Assistant#1164]
For better readability it would be helpful to have highlighting for code snippets appearing in messages like these:
![image](https://user-images.githubusercontent.com/96744960/216818087-93295067-d83d-460e-9da6-cb1318befd60.png)

**Comment by fozziethebeat** [comment]
The messages get rendered in `website/src/components/Messages/MessageTableEntry.tsx`  If you're able to add this without having to change the data or other parts that would be super helpful

**Comment by EpicLiem** [comment]
After considering it, I am uncertain if it's feasible to extract code from a message without proper syntax marking, such as the triple backticks (```) in Markdown. Syntax highlighting will not be effective if the message does not have the proper formatting. As a result, I believe it is necessary to either modify the data or perform post-processing to achieve this goal. 

I'm happy to continue working on it, but it would involve modifying the model or running the output through another one. I don't think it's worth attempting for slightly better readability, but I could be completely wrong with my analysis or about how important syntax highlighting is.

**Comment by mashdragon** [comment]
Implementing markdown (see #837) will include code syntax highlighting for properly formatted messages and solve this issue.

It will encourage everyone to use proper formatting for their responses, so improperly formatted responses will get downvoted since they will be easy to spot.
