### ISSUE TITLE
Answering your own prompt

### ISSUE THREAD

**Issue by jkminder** [LAION-AI/Open-Assistant#1168]
I think it might be beneficial, if one is able to also answer to your own prompt as assistant. I think often one has specific domain knowledge about a topic when coming up with a question. I would argue that when writing a prompt one already has an idea about how the question should be answered. This makes collecting answers much less effort and probably also higher quality. If I am prompted with a question about a topic that is very foreign to me the answer I give will have limited quality, especially if the question is quite specific. The prompter him/herself will probably have a much better idea of the domain if he came up with the question.

**Comment by olliestanley** [comment]
We agree this would be a good feature. There's an issue for tracking it #1030 so I'm closing this as duplicate but feel free to post any comments/views you have on that discussion!
