### ISSUE TITLE
Prompt to use your chosen language!

### ISSUE THREAD

**Issue by Fehertukor** [LAION-AI/Open-Assistant#1170]
When I choose any other language than English there need to be a prompt before every prompt to write it in your chosen language!
For example:
I am checking prompts in my own language but a ton of the prompts are in English. It is not a bug in my opinion but a user misunderstanding.
There should be "chose your language not only for the interface but which language model do you want to help! " sign on top of the dashboard.
And an other sign when you write a new prompt to "do not forget to write in your language"

**Comment by GuilleHoardings** [comment]
This is related to #997. Pull requests #1071 should help with this problem.

**Comment by olliestanley** [comment]
I think this should be solved with #1071 merged. If not feel free to comment and we can reopen the issue
