### ISSUE TITLE
Need of clear and stronger labeling instructions

### ISSUE THREAD

**Issue by flowpoint** [LAION-AI/Open-Assistant#1173]
It seems some task labelers do or intend to manually use ChatGPT outputs as answers.

We need a strong instruction, that tells task labelers to not use ChatGPT.
Those instructions should probably go into the [Prompting guide](https://projects.laion.ai/Open-Assistant/docs/guides/prompting).

But if you start by signing up, you might not have read the guide as a task labeler.
We should split the guide to the relevant tasks and show it right above the task in like a html spoiler, so task labelers are reminded to adhere to good prompting standards.

This would likely, hugely improve label quality.
There are multiple papers that show how the instruction for labelers are crucial to get a similar labeling style and therefore a high quality dataset.

Comments are ofcourse welcome.

**Comment by aayojezuzchrezt** [comment]
I think that it should have a quick tutorial and tests like https://eyewire.org/ (many of the users don't really have an idea of what this thing should do, how restrictions would work and other things, good tutorial and some test should make it clearer)

**Comment by flowpoint** [comment]
closing since the open-assistant project is completed
