### ISSUE TITLE
Expose thumbs up/down buttons without opening the extras menu

### ISSUE THREAD

**Issue by olliestanley** [LAION-AI/Open-Assistant#1176]
Not showing the thumbs up/down buttons by default, and instead only showing them when they have already been selected by at least one other user, induces a bias towards clicking on the button which is "easier" to click as somebody else has done already.

**Comment by mehdi-zibout** [comment]
Hello, I am interested!

**Comment by mehdi-zibout** [comment]
So the buttons aren't there by default, because the initial value of the emotes object is the empty object, I initialized the value of thumbs up / button to 0. And this fixes it.
