### ISSUE TITLE
Language identifier showing up instead of language strings [BUG]

### ISSUE THREAD

**Issue by chronikum** [LAION-AI/Open-Assistant#1180]
Hello,

during labelling I found a bug in the frontend interface. I do not know if it is fixed after a version currently deployed and could not find any issue on it yet.

Here is how to replicate it:

- Click on messages.
- Click on a message
- Press the three dots
- Click on label

![image](https://user-images.githubusercontent.com/34622984/216827377-c8ead284-de85-4891-b6a6-2800f7512f46.png)

Then, you can see none of the language strings gets actually loaded, instead, there are the language identifiers being shown.

I am running on safari Webbrowser and it works fine for me everywhere else in the web app.
I hope I could help improving the project a bit. Love the idea!

Let me know if you have more questions.

**Comment by notmd** [comment]
fixed in #1132
