### ISSUE TITLE
Tagging the code in replies

### ISSUE THREAD

**Issue by XavierRex** [LAION-AI/Open-Assistant#1182]
Does anyone know how we should mark the code in assistant responses? Some people use
![image](https://user-images.githubusercontent.com/98437003/216831458-d568807d-917d-4609-9d8f-06656d6ccfd8.png)
 at the beginning and end of the code like on discord sometimes adding what programming language was used e.g. ```python or no marking at all.

**Comment by olliestanley** [comment]
Markdown format is good, which is the three backticks (and optionally language name) you mentioned
