### ISSUE TITLE
Scroll bar turning on and off between every 1 second

### ISSUE THREAD

**Issue by jjmachan** [LAION-AI/Open-Assistant#1183]
labels: Website
checked existing issue but didn't find any duplicates (do correct me if I'm wrong). When you load the web app at first this works as expected (scroll bar is off) but if you select any text prompt it comes back (I was currently doing the "Reply as Assistant" task)

I recorded a video of the issue here:
https://user-images.githubusercontent.com/5261489/216832512-93a261ed-2b9b-4fed-b50a-05e8b02158e6.mp4

Browser: Google Chrome (Version 109.0.5414.74 (Official Build) (64-bit))

**Comment by MalikMAlna** [comment]
I ran into this issue as well on the Create Initial Prompts tasks input box. 

I was on Chrome as well and it seems to only occur at certain screen resolution widths. I notice that the issue did not persist when expanded my browser window.

Here's a video of what I experienced for context: 

https://user-images.githubusercontent.com/24833545/216872972-0645b997-ec62-43a1-bff2-c09debf8c51d.mp4

**Comment by AbdBarho** [comment]
I will close this issue now since a LOT has changed in the UI and the input fields since being reported.

If the issue persist, feel free to re-open.
