### ISSUE TITLE
Intransparent Leaderboard points

### ISSUE THREAD

**Issue by HUisHU-Christian** [LAION-AI/Open-Assistant#1189]
So far it is quite unclear, why some persons get more points for less suggestions, answers or labels. This seems unfair. It would be nice to see a legend or a link to the legend to see how the points are calculated.

**Comment by andreaskoepf** [comment]
The magic formula can be found [here](https://github.com/LAION-AI/Open-Assistant/blob/dcb9dfe952fb0fa6fc11c719c6fc2881de19b29b/backend/oasst_backend/models/user_stats.py#L54-L69):

```
    def compute_leader_score(self) -> int:
        return (
            self.prompts
            + self.replies_assistant * 4
            + self.replies_prompter
            + self.labels_simple
            + self.labels_full * 2
            + self.rankings_total
            + self.rankings_good
            + self.accepted_prompts
            + self.accepted_replies_assistant * 4
            + self.accepted_replies_prompter
            + self.reply_ranked_1 * 9
            + self.reply_ranked_2 * 3
            + self.reply_ranked_3
        )
```

The web team decided for simplicity not to show all rows. Future version might also include query results which are currently only calculated for the troll-boards. Maybe link to the score-function can be added to the FAQ or documentation.

**Comment by fozziethebeat** [comment]
This is a good invitation for someone to figure out how to display all those de-aggregated statistics in a way that resolves this issue

**Comment by AbdBarho** [comment]
Refs #996
