### ISSUE TITLE
Refactor reward model trainer to execute testing run locally without wandb and big-enough GPU

### ISSUE THREAD

**Issue by piotrek-grl** [LAION-AI/Open-Assistant#1192]
I found that currently I'm not able to execute testing run for reward model trainer (model/reward/instructor/trainer.py) locally due to following dependencies:
- wandb
- big-enough GPU

I'm planning to make code refactoring, to separate core trainer functionality without those dependencies, so it will be possible to run it locally on any machine.

This refactoring will enable to write unit tests for a trainer, like for model evaluation (https://github.com/LAION-AI/Open-Assistant/issues/397), loss decrease check and other ML-related unit tests.

**Comment by theblackcat102** [comment]
How big are you expecting to run? Can deepspeed solve the problem?

**Comment by piotrek-grl** [comment]
Actually my local GPU is too small, when running:
```bash
python trainer.py configs/electra-base-dis-webgpt.yml
```
I'm receiving this error:

![image](https://user-images.githubusercontent.com/44177888/217255675-01f6867d-29dc-483a-b999-f4fa5fc54054.png)

So the idea is to make code possible to run in development/testing mode on any machine.

**Comment by theblackcat102** [comment]
Have you tried using deepspeed flag?

```bash
deepspeed trainer configs/electra-base-dis-webgpt.yml --deepspeed
```

You might need to install deepspeed and accelerate package. By default it uses stage 2 for speed-mem trade off, if model size matters more you can change to stage 3 for even lower memory footprint

**Comment by piotrek-grl** [comment]
Thank you @theblackcat102 , I played a bit with deepspeed and stage 3, however I'm still facing those issues. I think it might be related with my local GPU setup, therefore it's not relevant for others and we can close it for now.
