### ISSUE TITLE
Can I grab a task using a language not included in the website short list?

### ISSUE THREAD

**Issue by solyarisoftware** [LAION-AI/Open-Assistant#1198]
Hi,

As an Italian speaker, I understand that my language is not included in the list of languages available in the https://open-assistant.io/dashboard menu (which includes English and Deutsch, among others).

Is it possible for me to submit prompts and reply as an Assistant in Italian language?

Thank you.
giorgio

**Comment by bitplane** [comment]
You'd need to submit an Italian translation.

Here's an example of a Turkish translation that recently got merged:

https://github.com/LAION-AI/Open-Assistant/pull/1195

If you do the same sort of pull request for Italian then the site will support Italian for everyone when it's next released :)

**Comment by GuilleHoardings** [comment]
You can find here a [guide about how to submit a translation](https://github.com/LAION-AI/Open-Assistant/blob/main/website/docs/add_edit_translations.md).

**Comment by Jac-Zac** [comment]
I'll translate it in Italian #1123

**Comment by solyarisoftware** [comment]
Thanks all, i'll asap try to instantiate the Italian version

**Comment by andreaskoepf** [comment]
Completed by https://github.com/LAION-AI/Open-Assistant/pull/1244
