### ISSUE TITLE
Ranking task: scrolling while viewing response changes rank order

### ISSUE THREAD

**Issue by bitplane** [LAION-AI/Open-Assistant#1202]
On mobile (Android, Brave)

* Select ranking task
* Click view more button to open overlay
* Use sausage finger to scroll up and down while reading the task

When you run out of scroll at the top or bottom, the event leaks down to to the task list and they might switch order:

https://user-images.githubusercontent.com/273059/216841313-bbfebe48-fc29-40f8-b119-2da4cff87f85.mp4

**Comment by AbdBarho** [comment]
It seems the problem has been fixed, I could not reproduce it.

Will close for now, feel free to re-open.
