### ISSUE TITLE
500 when accepting TOS

### ISSUE THREAD

**Issue by ehartford** [LAION-AI/Open-Assistant#1204]
500 when Accepting TOS.

I'm logged in with Discord account.

![image](https://user-images.githubusercontent.com/1117701/216842314-6b1b1883-baa7-4b90-b602-45940dc3c336.png)

**Comment by Koloss0** [comment]
Possible duplicate of #1117

**Comment by andreaskoepf** [comment]
Should be fixed now, thanks to @AbdBarho for quick fix. 
Please try again and let us know if it works now. :-)

**Comment by ehartford** [comment]
Works now, thank you
