### ISSUE TITLE
Css Responsive error

### ISSUE THREAD

**Issue by LeonelHGTeam** [LAION-AI/Open-Assistant#1205]
Hi my name is Leonel, i´v been training the AI when suddenly i got a rank assistan replies. i try to press on the "..." to see more about the data and "..." button goes left and right not leting me to press it.  Specifically the "Can you write a story that includes the following three elements: a quest, a magical creature, and a prophecy?" task

**Comment by yk** [comment]
Any relation to #1208 or #1210 ?

**Comment by andreaskoepf** [comment]
Should be fixed by https://github.com/LAION-AI/Open-Assistant/pull/1386
