### ISSUE TITLE
rank assistan bug

### ISSUE THREAD

**Issue by LeonelHGTeam** [LAION-AI/Open-Assistant#1206]
Hi im leonel again, im reporting again a bug over the task "rank assistan" task, the button gets bugged and moves left and right without letting me to press it, its a responsive bug i think

**Comment by yk** [comment]
that sounds mean :D

**Comment by andreaskoepf** [comment]
Should be fixed by Should be fixed by https://github.com/LAION-AI/Open-Assistant/pull/1386
