### ISSUE TITLE
Training Data Format

### ISSUE THREAD

**Issue by nivibilla** [LAION-AI/Open-Assistant#1209]
Hi,

This is not an issue but a couple questions. I really like the data structure you have outlined in the presentation.

Could you maybe point me to where the training data is stored or the format is being stored as. I am a machine learning scientist by trade specialising in NLP research. I would be very interested to help in finetuning like ChatGPT.

Thanks!

Also for the training part, I believe CarperAI's TRLX and Self-instruct may be useful

TRLX : https://wandb.ai/carperai/summarize_RLHF/reports/Implementing-RLHF-Learning-to-Summarize-with-trlX--VmlldzozMzAwODM2

https://github.com/CarperAI/trlx

Self-instruct:
https://github.com/yizhongw/self-instruct

**Comment by yk** [comment]
There is no training data yet, as we are still collecting it. We're already looking at various libraries, including trlx, but thanks for the pointers :)
