### ISSUE TITLE
Contributing style guide

### ISSUE THREAD

**Issue by olliestanley** [LAION-AI/Open-Assistant#1216]
We are getting a huge volume of questions on how to label, what is good quality, what tone should the assistant reply in, etc. I am planning to write up a semi-comprehensive document we can link people to in future.

**Comment by andrewm4894** [comment]
cool - maybe something like a `contributing.md` in here could make sense? https://github.com/LAION-AI/Open-Assistant/tree/main/docs/docs/guides

I think we were also going to add task specific docs to each md in here: https://github.com/LAION-AI/Open-Assistant/tree/main/docs/docs/tasks

So maybe some combination of both could work. 

I think would be nice to have a comprehensive page for each task type and then ability from within the app to link to the specific task docs page you are looking at as a user.

**Comment by olliestanley** [comment]
> cool - maybe something like a `contributing.md` in here could make sense? https://github.com/LAION-AI/Open-Assistant/tree/main/docs/docs/guides
> 
> I think we were also going to add task specific docs to each md in here: https://github.com/LAION-AI/Open-Assistant/tree/main/docs/docs/tasks
> 
> So maybe some combination of both could work.
> 
> I think would be nice to have a comprehensive page for each task type and then ability from within the app to link to the specific task docs page you are looking at as a user.

I agree something more comprehensive would be nice longer term but what we need for now is something people can read in 2 minutes and have a good idea of what to do in most situations. We do have this guide but I think most people are not reading it and just post their questions in Discord instead https://github.com/LAION-AI/Open-Assistant/blob/main/docs/docs/guides/prompting.md
