### ISSUE TITLE
Translations not correctly displayed on various places (website)

### ISSUE THREAD

**Issue by Dryhb** [LAION-AI/Open-Assistant#1230]
No traduction for 1-5 ranking labels
The labels "Low Quality", "High Quality" .. "Harmless" have no translation (possible) in any language. Not present in the translation files even in english from what I saw. 
The bottom box too : "Prompt <prompt number> Outuput  Submit your answer    Skip Review" also aren't present (as well as the pop ups that appear when you click on "Skip" or "Review" when the order of the assistant answer wasn't changed.

**Comment by Dryhb** [comment]
On the main page, "Review" is not translated (for ex in french) but when you access the menu via the 3 dots and click "Label" (or its translation) the "Review" button is translated. (incoherence with the main page review button).

**Comment by Dryhb** [comment]
It seems that the translation for "Dashboard", "Messages", "Leaderboard" on the side_menu isn't displayed even tho the translation is created (from the translation files / other menus with the same name). On PC that is so when its always displayed because on phone there is no side menu execpt when put into computer mode in which we can see that the translation isn't well done.

**Comment by Dryhb** [comment]
Switch language box isn't translated too. I think the detected language and the selected one should be displayed.

**Comment by GuilleHoardings** [comment]
I'm not so sure about the language box: if the detected language it's wrong, it might be difficult for the user to find his desired language.

For instance, see [this best practices for language selectors](https://www.smartling.com/resources/101/language-selector-best-practices/):

> Always use the local format and spelling of the language. It needs to be recognizable instantly to native speakers. For example, German should be listed as Deutsch.
