### ISSUE TITLE
How do I delete my account? Give an option

### ISSUE THREAD

**Issue by aaachris1820** [LAION-AI/Open-Assistant#1235]

**Comment by andreaskoepf** [comment]
Sure, do you want to work on this feature?

**Comment by fozziethebeat** [comment]
Yeah we should probably support this.  We have to discuss the side affects of user deletion

**Comment by thehackerleak** [comment]
I might work on this, they issued that it need to be discussed about possible side effects, I'll wait until some relevant topic is added on this thread to discuss about, while this, I'll keep reading the documentation.

**Comment by CheckMC** [comment]
would deleting an account also delete any contributions? maybe it should be an option

**Comment by icf20** [comment]
imo u want to give a option to delete the account and stuff because the project can get GDPR'ed
