### ISSUE TITLE
Remove "hate speech" concept

### ISSUE THREAD

**Issue by CarlKenner** [LAION-AI/Open-Assistant#1238]
"Hate speech" is a (derogatory) term that refers to blasphemy against the Woke religion. As the Woke religion is objectively untrue (and self-contradictory), it makes no sense to force an AI assistant's responses, or the users' questions, to conform to that absurd belief system.

The criteria that matter for an AI assistant are accuracy, politeness, and harm avoidance. And Open-Assistant already tracks those (except perhaps for "accuracy", which is currently conflated with "quality"). If a response is true, politely worded, and doesn't harm people, then it's a good response, regardless of whether it is politically correct or not.

Artificially forcing an AI to be as irrational and emotional as society is, and training it to tell comforting lies, defeats the purpose.

The "hate speech" tag should be removed from the system, and posts previously flagged for "hate speech" should be restored.

**Comment by yk** [comment]
no

**Comment by CarlKenner** [comment]
It wasn't a question.
