### ISSUE TITLE
Option to write a prompt and immediately propose answer (i.e. Ask 2 Answer/A2A)

### ISSUE THREAD

**Issue by distbit0** [LAION-AI/Open-Assistant#1241]
I think there should be an option to write a prompt and also immediately propose the answer. People prompting within a specific field they're into will provide the best answer.

This is similar to what frequently occurs on forums such as stack exchange where someone asks a question solely to provide a context for them to provide a detailed answer due to being knowledgeable on the subject matter, and wanting to contribute their knowledge. 

Source: Youtube commenter
![image](https://user-images.githubusercontent.com/10890247/216970029-bb1885e3-49fe-403c-9baf-c45f2c751dc3.png)

**Comment by olliestanley** [comment]
We want to do this but would need somebody to work on it. There is issue #1030 to track it already so I'm closing this as duplicate
