### ISSUE TITLE
Website bug - Rank Assistant Replies

### ISSUE THREAD

**Issue by nadavMihov** [LAION-AI/Open-Assistant#1251]
Hello,
I encountered a bug in the website on the part where you rank assistant replies. 
One of the replies were: "The free energy principle, and its corollary active inference, constitute a bio-inspired theory that
assumes biological agents act to remain in a restricted set of preferred states of the world, i.e., they
minimize th" - and then the three dots sign you nedd to press to see the whole answer. 
However, when I hover on the three dots symbol the text of the answer apears in white, making another scrollbar appear next to the main one. This makes the answer span shrink and then I no longer hover above the sign, which make the second scrollbar disappear and the span grows big again. Then I do hover the sign and it all happens again.
I can't press the three dots to see the answer.
Thank you.

**Comment by blankster** [comment]
See also #1208 and #1221

**Comment by olliestanley** [comment]
Thanks for the report, this is covered by the bug reports mentioned above by @blankster so I'll close this one as duplicate but hopefully we will have this issue solved soon :)
