### ISSUE TITLE
Hide the number of thumbs up or down before interaction

### ISSUE THREAD

**Issue by JediMaster25** [LAION-AI/Open-Assistant#1252]
I feel if a message has many thumbs up or down I'm more likely to go along than to actually think about it.

**Comment by blankster** [comment]
I share this opinion. The fact that ratings are displayed by others creates a bias in my opinion.

**Comment by BradGaddis** [comment]
I concur with potential bias. It seems like I am influenced to vote one way or the other if I see that there are already thumbs up or down on a label. I'm concerned that this could ultimately sway the model, as well.

**Comment by notmd** [comment]
working on it

**Comment by blankster** [comment]
The minimum I would do would be to not show them right away at first glance. If you see them right away, it's practically impossible not to be biased. If an extra action is needed to show them, that would be already a big improvement and would prevent a lot of bias.

**Comment by blankster** [comment]
I love the implementation, it's exactly for what I hoped for. Thanks a lot :)
