### ISSUE TITLE
Localization: Usage of a Translation Management Tool

### ISSUE THREAD

**Issue by blankster** [LAION-AI/Open-Assistant#1253]
**User Story:** As a contributor, I want to keep all available languages synchronized so that a good translation quality is possible for the GUI.

**Further Remarks:** I would recommend using a language management tool like https://poeditor.com/ that can be used for free for open-source projects. It helps to ensure that all languages are in sync and if something changes in the "base language" it flags all other languages for review. It also helps to increase the translation quality iteratively.

Integration into GitHub workflows is absolutely possible, and the setup is relatively easy.

**Comment by fozziethebeat** [comment]
At some point we should set this up.

Before anyone starts integration, can I request we investigate two to three different open source options and describe their pros and cons?

**Comment by blankster** [comment]
I also would recommend to check multiple options. These translation management tools are normally often expensive - but most options are for Open-Source projects, free to use, so it's wise to consider well.

 Based on personal experience (I've translated with POEditor > 3K "terms"):

* There are many solutions but a lot of them are an overkill, you want something simple but effective - I would strongly recommend trying all options out before deciding
* Automatically marking other languages as "fuzzy" is super useful, and otherwise translations often out of sync
* You want GitHub CI support, that's really working well (I can deploy changes in around 15s to the server over it)
* Having a "translation memory" is king, allows also to see changes over time
* POEditor supports nearly every well-known export option, that can be handy
* It allows a 2-step process, for example to make it possible that translations are reviewed by someone else before approved
* Different vendors have different community features, but the question is whether you want a community within a TLM tool, or if simple options, there are not enough
