### ISSUE TITLE
Replies are Able to be Labeled Multiple Times with the Triple Dot Menu

### ISSUE THREAD

**Issue by IonizedPro45** [LAION-AI/Open-Assistant#1254]
If you use the triple dot menu on a prompt or reply and click label a label field will open. When you finish labeling there is no feedback that the label was successful. You can then label it multiple times using the same process. I'm unsure of whether labeling it multiple times does anything backend. Also, if your current task is labeling a prompt or reply and then you label it using the triple dot menu you can then label it using both the task and the popup.

![image](https://user-images.githubusercontent.com/64451674/217033443-d266a53d-2daa-413f-945b-1dde889885d9.png)

**Comment by andreaskoepf** [comment]
A previous response is overwritten in the DB when the same user sends a free-labeling response (e.g. without task) for the same message. https://github.com/LAION-AI/Open-Assistant/blob/3d221f8925785079d446d706bf5629e1f346a4f3/backend/oasst_backend/prompt_repository.py#L528-L532

**Comment by olliestanley** [comment]
Closing this as it isn't a problem, feel free to reopen if any further related queries
