### ISSUE TITLE
Potential Logic Bug: Rating your own content

### ISSUE THREAD

**Issue by blankster** [LAION-AI/Open-Assistant#1256]
I wanted to ask if this is really how it is intended, that you partially rate your own prompts and answers? While I can understand that it can make to answer the own prompt, I doubt that rating the own content is intended and serves the training data quality.

I can't reproduce it each time, but I've experienced this multiple times while grinding.

Please correct my assumption if this is really the intention.

**Comment by Dryhb** [comment]
I've had a slightly different setting where I was asked to rate an assistant prompt reply to my message (which was an answer to another message) so basically : 
Someone elese first question
First assistant answer
My answer (2nd question)
second assistant answer

And I had to rate that second assistant answer. Not sure if that influences what I would rate but if possible should be avoided ?

**Comment by nikitastaf1996** [comment]
I noticed it too.Russian is currently small language.So I notice it all the time.I believe i did enough damage.I believe my prompts are not bad.But it is not for me to decide.
