### ISSUE TITLE
Real-time data required prompt

### ISSUE THREAD

**Issue by 0x22almostEvil** [LAION-AI/Open-Assistant#1272]
![image](https://user-images.githubusercontent.com/122345469/217079749-2ef652cd-830c-4fcd-911f-3080d9b47b84.png)
![image](https://user-images.githubusercontent.com/122345469/217079778-a246f7b6-ca09-411d-9060-05f9aa7a3651.png)

**Comment by aayojezuzchrezt** [comment]
Now there are two clones of my account and score goes only for new one
![image](https://user-images.githubusercontent.com/122345469/217099212-483c6c6e-0535-4cbf-a98c-1eccdd201a61.png)
![image](https://user-images.githubusercontent.com/122345469/217099319-6968ed52-5ff5-462f-877b-eb1cb2553122.png)

**Comment by aayojezuzchrezt** [comment]
> We should prefer the responses saying they don't know imo. The ability to provide these responses will come from integration with other services, not from this training process

Personally I think that we need a new option that will label this prompt as something that needs internet-access and other stuff
