### ISSUE TITLE
Expand functionality of data export script

### ISSUE THREAD

**Issue by olliestanley** [LAION-AI/Open-Assistant#1275]
This refers to `export.py`

- [ ] add tree-state variable in root_object
- [ ] option to export all trees regardless of state or export trees in any specified state
- [ ] option to only export the prompts (only first message of tree)

This will include changing the function `fetch_message_trees_ready_for_export` in `PromptRepository` to take state as a parameter.

**Comment by andreaskoepf** [comment]
Ref to the existing [fetch_message_trees_ready_for_export()](https://github.com/LAION-AI/Open-Assistant/blob/cf4c8e70ce37d423acce21f0cf8f6700cf5cb9cd/backend/oasst_backend/prompt_repository.py#L659-L663) function.
