### ISSUE TITLE
Email spam potential

### ISSUE THREAD

**Issue by CactiStaccingCrane** [LAION-AI/Open-Assistant#1281]
On Open Assistant if you type your email to the login page, it would send to you an email that contains the verification link. However, a bad actor can make a small script to harrass other users by spamming their inbox with unsolicited email. There should be a rate limit for sending the link to an email inbox in one session.

**Comment by fozziethebeat** [comment]
This is true for any email magic link service right?  Is anyone actually doing this?

**Comment by blankster** [comment]
I don't think it's super urgent or dangerous atm, but it's the classical attack: If not rate limited, it could be "weaponized". Because of this, many services ensure rate limitation and similar.
