### ISSUE TITLE
Label prompt closes on periodic refresh

### ISSUE THREAD

**Issue by opfromthestart** [LAION-AI/Open-Assistant#1285]
If you select a message from the messages tab, select a message, and start to add a label, the periodic refresh of the site closes the menu and forgets the input you may have already made to adding a label.
Reproduce:
Click messages tab.
Click on any message.
Click to add a label.
Wait a minute or so for the refresh.

**Comment by chronikum** [comment]
At least in messages it should be fixed here: https://github.com/LAION-AI/Open-Assistant/pull/1353
