### ISSUE TITLE
Create cocktail recipes dataset

### ISSUE THREAD

**Issue by BrianArbuckle** [LAION-AI/Open-Assistant#1286]
This would involve taking a table scraped cocktail recipes and converting them to a dataset. 

1. I'll need some pointers on how to format the data. 
2. I'll dig for the source of each recipe (they are integers, I am looking for the table that was associated with the source).

**Comment by ontocord** [comment]
Cheers!

**Comment by ontocord** [comment]
You can format like the following:

User: I'm {hosting a party, doing an X event, throwing a Y} and I need to make some drinks. It should include {top ingredients}. Please give me some cocktail recpies.

Assistant: Cheers! Here is a cocktail recipe that includes {top ingredients}
...

Enjoy your {party, etc.}

+++

And different varations thereof

**Comment by BrianArbuckle** [comment]
Thank you, @ontocord ! I just started reading through the [submitting datasets guide](https://github.com/LAION-AI/Open-Assistant/blob/main/openassistant/datasets/README.md). Since a pull request is involved, I'll start small and get some eyes on it. Then I can add everything (AKA I need time for the messy bits!).

**Comment by ontocord** [comment]
Sounds good. Also, it would be good to have instructions for just making a mimosa :)

**Comment by BrianArbuckle** [comment]
Hi @ontocord, I have submitted my  PR. I was unsure of where to add the dataset folder. I placed it in the `Open-Assistant/openassistant/datasets/cocktail_recipes`. I was also unsure of the python loading script name so I went with `loading_script.py`

Also, I did not realize how cool you all were at Ontocord, you have a cocktail named after you; who knew? ;)
