### ISSUE TITLE
Possible language changing issues

### ISSUE THREAD

**Issue by Dryhb** [LAION-AI/Open-Assistant#1287]
When doing a initial prompt task in language A , you can switch to language B and complete the task. You will, after this task is completed, be presented with another task that seems to be of language B (not sure how I could check this) but that task would not be available if you would have passed trough the dashboard of language B (no initial prompt tasks are available). By that you are able to create an "unwanted" intitial prompt for language B.
When doing the same manipulation for classify tasks, when the first task in language A is done, then language B task marks as not available (that makes sense as there was none of these task on the dashboard of language B). I don't know about assistant replies. That could possibily explain the occasional wrong language prompts we get.

**Comment by fozziethebeat** [comment]
I should try to replicate and fix this

**Comment by fozziethebeat** [comment]
Replicated, yes this is a problem.  when a user changes their language we should fully reload the page and get a new task

**Comment by Dryhb** [comment]
When the labbel "wrong language" is selected, it should state what language it should be (the one selected) because if you switched language while on the page you can get confused ?
