### ISSUE TITLE
Choose which prompt to answer as assistant

### ISSUE THREAD

**Issue by 0xfeedbac** [LAION-AI/Open-Assistant#1299]
In some areas I'm a domain expert and, when replying as assistant, can therefore address domain questions more deeply/efficiently than other. 

However, the current approach does not allow to choose which prompt to answer, thus hindering the contribution speed and depth. 

Could it be possible to choose which prompt to answer from a pool of prompts? I.e. simple list of most recent prompts would be enough.

**Comment by khoda81** [comment]
@0xfeedbac This issue is tracked here: #1006

**Comment by olliestanley** [comment]
Closing this as duplicate as #1006
