### ISSUE TITLE
"Join Us" and "FAQ" buttons do nothing when on Sign Up page

### ISSUE THREAD

**Issue by billray0259** [LAION-AI/Open-Assistant#132]
Join Us and FAQ buttons in the navbar should navigate the user to the appropriate pages when clicked but do nothing when on the Sign Up page.

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/31375073/209886910-cf43f0ec-a2c1-4843-850c-3403076b40f4.png">

**Comment by fozziethebeat** [comment]
Correct! These buttons needs to be either removed or updated to actually do something.  Would you like to make a PR to remove them for now?

**Comment by billray0259** [comment]
Yes! I can remove the buttons.
