### ISSUE TITLE
Questions about porting to Windows and online

### ISSUE THREAD

**Issue by David263** [LAION-AI/Open-Assistant#1321]
I would like to provide feedback for Assistant under Windows 10, but I don't want to install Docker, or especially npm, because of npm's very large disk usage. Can this system be installed manually? 'No' is an acceptable answer.

As a separate question, will the system be made available online for gathering information more universally?

I'd like to provide information about Apache, PHP, CSS, JavaScript, HTML, and other parts of the basic Web infrastructure, including fringe areas like how browsers differ and how Windows differs from Linux.

I am also qualified to provide information in other areas, depending on how far afield you wish to go. I can handle much of physics and quantum mechanics, at least for beginners, and selected topics in spirituality, including the theories behind transcending and nonduality.

**Comment by olliestanley** [comment]
The system is available online - https://open-assistant.io - and the local Docker setup is only for doing local development on the app. Currently we don't have mechanisms to only see prompts in specific subject areas but this will be worked on soon

**Comment by David263** [comment]
I visited that page a number of times and still do not see any link to your online system. There is a link to Discord and a link to GitHub, but not to an operational system that I can try out or contribute to.

**Comment by Lyrialtus** [comment]
Right... The index page does not actually invite you to sign in. It probably should.

**Comment by David263** [comment]
It probably should. Until it does, this Issue can stay open to remind the developers to allow people to contribute to the project. (They do want external participation, right?)

**Comment by olliestanley** [comment]
There's a sign in button at the top right of the index page. Could make it more visible though

**Comment by David263** [comment]
Oh. I assumed that "sign in" referred to developers, rather than the general public. I would have expected to see a "register here to try out Assistant" button or some such clear invitation, in line with the "responsive design" appearance of your website.
