### ISSUE TITLE
Idea: Mirroring GitHub Changes to Discord Channel

### ISSUE THREAD

**Issue by blankster** [LAION-AI/Open-Assistant#1329]
It crossed my mind today that both GitHub and Discord are really busy. I was wondering if it might make sense to combine GitHub and Discord and, for example, send GitHub status messages to a special channel. This would hardly annoy anyone (watching the channel is up to you), but would allow you to see everything in one place and watch the interesting things right away on Github.

There are countless integrations which should actually make this a breeze, so little effort is to be expected. I don't see this as an absolute necessity, but probably as an easy "low-hanging fruit" to pick.

**Comment by olliestanley** [comment]
By "status messages" what exactly do you mean? Activity on issues, commits, etc?

**Comment by blankster** [comment]
Thanks for asking! Depending on the integration solution, you can configure this. I wouldn't recommend to start with an overkill, but for example new issues, status changes of issues could be helpful. The main question here must be: What creates real added value. What is newly created and changes in status, I find, corresponds to an added value.

**Comment by olliestanley** [comment]
I would be happy to have this as long as nobody has a problem with it. Would need someone to find an appropriate bot/method of integration though as I'm not too sure what's available.

**Comment by blankster** [comment]
I'm not a super expert in Discord, but I experienced such an integration in the past and really liked it. The key is to "log" into a **separate channel**.

If it helps, I could do some research of what options currently exist. But I don't want to interfere with what the Discords admins/mods have in their mind. 

I think the "nice-to-have" flag is appropriate.

**Comment by mm12** [comment]
We can just use a webhook, discord and github make it super easy.

**Comment by blankster** [comment]
That's also my conclusion. It would be super easy to do by webhooks, and I don't seem to be the only one who would like to have this. Unluckily, I can't implement it myself and need someone with higher level of access to Discord/GitHub (@olliestanley ?). 

For the instructions, see for example https://gist.github.com/jagrosh/5b1761213e33fc5b54ec7f6379034a22

**Comment by olliestanley** [comment]
> That's also my conclusion. It would be super easy to do by webhooks, and I don't seem to be the only one who would like to have this. Unluckily, I can't implement it myself and need someone with higher level of access to Discord/GitHub (@olliestanley ?).
> 
> For the instructions, see for example https://gist.github.com/jagrosh/5b1761213e33fc5b54ec7f6379034a22

I am only a collaborator for the GitHub repo, it would have to be a repo owner I believe. @andreaskoepf would you have time to set something like this up?

**Comment by andreaskoepf** [comment]
Done.
