### ISSUE TITLE
Insert two dummy conversations in an empty database

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#133]
Determine if posts table is empty upon backend startup. If so, insert 4 dummy posts to emulate two mini-conversations, e.g the two examples from the [Prompting Guide](https://github.com/LAION-AI/Open-Assistant/blob/main/Prompting_Guide.md). This allows a smoother operation of the `/tasks/` REST endpoint  (e.g. when a random task is requested) in the very early phase after deployment and during development.

It could be placed in [backend/main.py](https://github.com/LAION-AI/Open-Assistant/blob/main/backend/main.py) similar to the alembic update.

**Comment by kunimei** [comment]
good

**Comment by Anubhab2003** [comment]
Minimum variable prototype

**Comment by fozziethebeat** [comment]
This is great.  When we're starting up the database for development, something should seed it with some fake data.
