### ISSUE TITLE
Remove refresh of public message tree view

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#1332]
After navigating to a longer tree by id, e.g. https://open-assistant.io/messages/8d5fdbdf-3c3b-487f-88c1-ddde1ae8bcb2
and scrolling down the page refreshes after a couple of seconds. This makes it impossible to read through the messages as the refresh resets the scroll position back to the top. In general I don't think that auto-refresh is helpful on this page-type, i.e. it could simply be removed without losing any important functionality.

Relevant code ref:
https://github.com/LAION-AI/Open-Assistant/blob/66b7ed2b9beba9a504792e8b7aab33494df78ff6/website/src/pages/messages/%5Bid%5D/index.tsx#L18-L20

**Comment by jrrpm** [comment]
I want to work on this one.  If needed, we could add an anchor and disable the event when scrolling. Otherwise, just remove the refresh.

**Comment by andreaskoepf** [comment]
The https://github.com/LAION-AI/Open-Assistant/pull/1353 was merged .. but the page still reloads periodically.

**Comment by chronikum** [comment]
On it :)

**Comment by chronikum** [comment]
On it :)
