### ISSUE TITLE
Improvement: Avoiding "No Choice Situations" while Ranking

### ISSUE THREAD

**Issue by blankster** [LAION-AI/Open-Assistant#1334]
That's category "nice to have", but in theory such situations could be avoided and are pointless:

![image](https://user-images.githubusercontent.com/1443109/217388960-520b4b60-25c0-4077-89b2-b8f7025bbc01.png)

If there is no choice because all options are (nearly 100%) identical, I wouldn't recommend showing this to users. Human feedback should be used where it matters.

Minimum improvement could be avoiding showing 100% identical options.

**Comment by olliestanley** [comment]
I think at this point we will likely not implement this as there are other priorities and nobody has volunteered to take it on. The problem with filtering even exact duplicates is that you have to delete someone's contribution, and I don't think there is a real tangible benefit considering the scenario is quite uncommon

**Comment by blankster** [comment]
For me personally it's not a big deal to deal with such situations, just wanted to mention it somewhere to make sure if it's relevant for you guys, that it is in the backlog.
