### ISSUE TITLE
Application error: a client-side exception has occurred

### ISSUE THREAD

**Issue by CactiStaccingCrane** [LAION-AI/Open-Assistant#1339]
When I add entries for Vietnamese in Firefox at open-assistant.io, the website just bugs out and says: `Application error: a client-side exception has occurred (see the browser console for more information).` At the log, there are two issues that is labeled critical: `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/api/vl/auth/check. (Reason: CORS request did not succeed). Status code: (null).` and `Error: React.Children.only expected to receive a single React element child. Next JS` The issue persists even when I cleared out all of my cache and use incognito mode.

**Comment by CactiStaccingCrane** [comment]
It seems to be language dependent: I haven't encountered this error in English, though I might not have tested enough

**Comment by DigitalDwagon** [comment]
More detailed debugging and picking apart the error starts from here on Discord: https://canary.discord.com/channels/1055935572465700980/1055935573371658252/1072725330462257192

**Comment by DigitalDwagon** [comment]
Looks like the localhost call is unrelated, I've split it off into #1340

**Comment by notmd** [comment]
This has been fixed
