### ISSUE TITLE
Task pages make calls to localhost

### ISSUE THREAD

**Issue by DigitalDwagon** [LAION-AI/Open-Assistant#1340]
Task pages try to call to http://localhost:8080/api/v1/auth/check - which obviously fails every time. It looks like this bug is occurring on Line 17 of dashboard.tsx (https://github.com/LAION-AI/Open-Assistant/blob/363a3a124471217e723d57b084122ae1ca41ab2a/website/src/pages/dashboard.tsx) 

Line 17 reads: ```useSWR(`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/v1/auth/check`, get);```
The env call looks like it's causing the issue, so it should probably read: ```useSWR(`/api/v1/auth/check`, get);```

**Comment by notmd** [comment]
This have been fixed
