### ISSUE TITLE
Avatar does not scale or display correctly with Discord sign-in

### ISSUE THREAD

**Issue by ashduino101** [LAION-AI/Open-Assistant#1341]
The profile picture in the top right of the page is not scaled to fit the container. This can be fixed with the CSS `background-size: cover;` on the icon element. As well as this, perhaps the default user SVG icon should be hidden when a user is signed in. I cannot confirm if this happens with email sign-in, however, as the email verification does not seem to work at the moment.

What it looks like now:
![image](https://user-images.githubusercontent.com/67023707/217451131-5652eca5-ce4c-44be-ba10-ab89b43f59c1.png)

What it should look like:
![image](https://user-images.githubusercontent.com/67023707/217451163-c68cf2b6-0a5f-47aa-8ea4-44ea04ca9166.png)

**Comment by olliestanley** [comment]
Fixed by #1383
