### ISSUE TITLE
Main part of the task able to move horizontally on mobile website

### ISSUE THREAD

**Issue by Dryhb** [LAION-AI/Open-Assistant#1343]
While on mobile website, the block with the messages and rating / box to type / multiple assistant answers  to sort and the bottom links (policy, terms of service, discord...) can be moved to the side (left) for no apparent reason even tho the top part (main logo, language selection user icon, dark mode icon, dashboard / message / leaderboard buttons) do not move and aren't moveable. This isn't a zoom problem too. This can be linked to  https://github.com/LAION-AI/Open-Assistant/issues/974 where it mentions the randking card issue (where most of the issue comes from).

**Comment by jacovzap** [comment]
I have solved this problem! I made a pull request on the request #1501

**Comment by AbdBarho** [comment]
#1501
