### ISSUE TITLE
See 'missing database ocgpt_website' when attempting to log in

### ISSUE THREAD

**Issue by SamCoulson** [LAION-AI/Open-Assistant#136]
Seeing error 'FATAL:  database "ocgpt_website" does not exist' when clicking submit button.

Repo steps:

- Run ' docker compose up frontend-dev --build --attach-dependencies'
- In /website directory, run 'npm run dev'
- Run Debug in VSCode - access url 'localhost:3000' with webRoot set to '${workspaceFolder}/website' 
- Wait for page to load, click 'Sign In'.
- Enter 'test@test.com' in email box
- Click 'Continue with Email'.
- Observe error in output log 'FATAL:  database "ocgpt_website" does not exist'

**Comment by AbdBarho** [comment]
`npx prisma db push`?

https://github.com/LAION-AI/Open-Assistant/tree/main/website#getting-everything-up-and-running

**Comment by fozziethebeat** [comment]
marking this a closed given that the documentation describes the required steps.
