### ISSUE TITLE
Rank Assistant Replies lacks the ability to see line breaks.

### ISSUE THREAD

**Issue by phly95** [LAION-AI/Open-Assistant#1364]
![image](https://user-images.githubusercontent.com/3526540/217560521-b52bfca5-185b-434e-a3ff-7f7f66fe861f.png)
See how if the response is supposed to have line breaks, you cannot see them. This means I cannot accurately perform this task.

**Comment by Dryhb** [comment]
Also appears on things like ascii drawings which because even less visible (mostly a vertical thing) for ex : 43aac56c-fc2c-439a-848d-27422d5785b4

**Comment by rjmacarthy** [comment]
I can fix this, please assign to me.
