### ISSUE TITLE
Can Danish language please be included?

### ISSUE THREAD

**Issue by lytjedk** [LAION-AI/Open-Assistant#1369]
The title says it all. Can Danish please be an option.

**Comment by olliestanley** [comment]
Yes but it would depend on someone making a PR to add the frontend translation. If you'd like to do that you're welcome to, you can take a look at some of the other translation PRs for an example :)

**Comment by lytjedk** [comment]
Am I doing it right? And is it just files in that directory or are there other files that needs translation as well?
Is it possible to see the usage of the words in context. Most of them I'm confident about. But there are a few where I would like to see how the words are used.

Thanks.

**Comment by lytjedk** [comment]
If it is not easy to see what I have (tried) to do, I have made a new folder called da in website/public/locales. And I have translated the first of the files from the en folder.

**Comment by lytjedk** [comment]
Aah sorry. I think I am getting to understand it. This is my very first GIT contribution, so please be gentle. :)

I found this document and I am doing the best I can to do what it asks.
https://github.com/lytjedk/Open-Assistant/blob/main/website/docs/add_edit_translations.md

**Comment by olliestanley** [comment]
Yes this is a good start, thank you! To complete the translation we need to add the other files as well as `dashboard.json` and then add the language to the supported list here https://github.com/LAION-AI/Open-Assistant/blob/main/website/next-i18next.config.js

**Comment by lytjedk** [comment]
The link to the website Readme doesn't work.
I think I have found the link. Do I really need to install it locally to check translations?

**Comment by notmd** [comment]
closed by #1408
