### ISSUE TITLE
Two highlighted lines, not one

### ISSUE THREAD

**Issue by David263** [LAION-AI/Open-Assistant#1370]
Page https://open-assistant.io/label/label_assistant_reply asks questions about a "highlighted line". But two lines are **equally** highlighted, meaning they have a lighter background than the two other lines.

**Also:** why do I have to come here to GitHub and **create an issue** instead of having a way to submit my meta-comment to the developers through the Assistant website itself?

**Comment by andreaskoepf** [comment]
> Page https://open-assistant.io/label/label_assistant_reply asks questions about a "highlighted line". But two lines are equally highlighted, meaning they have a lighter background than the two other lines.

"Highlighted" means in this case the box with the blue border. It's always the last message of the shown conversation thread.

> **Also:** why do I have to come here to GitHub and **create an issue** instead of having a way to submit my meta-comment to the developers through the Assistant website itself?

We have a small team of active developers. Using existing infrastructure like github helps us to focus on the important parts.
