### ISSUE TITLE
Feature Request: Figure out if prompt that I'm going to submit already exists

### ISSUE THREAD

**Issue by JediMaster25** [LAION-AI/Open-Assistant#1373]
I'm forgetting whether or not I've submitted some prompts and doubting if I should submit it. Is there already an issue to view previous prompts? Some ideas I've had are page through or search my prompts, or the same for all user prompts or something like that to figure out if the prompt I'm going to submit already exists.

**Comment by mashdragon** [comment]
Related to #1306
