### ISSUE TITLE
Feedback on "Your statistics" page

### ISSUE THREAD

**Issue by GameOverFlowChart** [LAION-AI/Open-Assistant#1375]
I'm glad to see that the account page shows now my statistics. The site also seems to be optimized for mobile now. But the order needs to be fixed. Total, day, week, month is not in a meaningful order. Either make it total, month, week, day or day, week, month, total. Small timespan to big timespan or the other way around. Not Random.

**Comment by IllyShaieb** [comment]
I feel like the order should be a setting that each user adjusts based on their preferences.
