### ISSUE TITLE
Unable to execute "docker compose up --build"

### ISSUE THREAD

**Issue by ghost** [LAION-AI/Open-Assistant#1377]
Hello, I am unable to execute "docker compose up --build".
Please let me know If anyone has encountered a similar issue to one posted below:
ERROR [oasst-web builder 5/6] RUN npx prisma generate
> [oasst-web builder 5/6] RUN npx prisma generate:
#0 19.16 Error: request to https://binaries.prisma.sh/all_commits/d6e67a83f971b175a593ccc12e15c4a757f93ffe/debian-openssl-1.1.x/migration-engine.gz.sha256 failed, reason: unable to get local issuer certificate

**Comment by chronikum** [comment]
What device are you using, what is your local setup?

**Comment by mike-likes-math** [comment]
Mac OS Monterey 
Docker version 20.10.22, build 3a2c30b

**Comment by bitplane** [comment]
Is this still broken? Is it an Intel or M1 Mac?
