### ISSUE TITLE
In Rank Assistant Replies, switch from vertically stacked handled cards to horizontal tabs

### ISSUE THREAD

**Issue by ehartford** [LAION-AI/Open-Assistant#1378]
I wanna suggest:
In Rank Assistant Replies, instead of the 3 replies stacked vertically and truncated, 
<img src="https://user-images.githubusercontent.com/1117701/217689049-35a7b9e9-ece4-4335-8ffa-303f8df40801.png" width="50%" height="50%">
Rather use 3 tabs that can be reordered by dragging
Like this:
https://codesandbox.io/s/framer-motion-5-drag-to-reorder-tabs-zd2q7
<img src="https://user-images.githubusercontent.com/1117701/217689176-7122d3d2-e740-4eb3-9a09-77ee25e26d9f.png" width="50%" height="50%">
(maybe with a horizontally oriented handle on the left of the tab to hint it can be dragged, and a "1" "2" "3" on the tab to show its rank)

**Comment by olliestanley** [comment]
I think #3020 supersedes this
