### ISSUE TITLE
Sign Up by E-Mail does not work

### ISSUE THREAD

**Issue by davidak** [LAION-AI/Open-Assistant#1388]
I don't get the sign-up link.

## Steps to reproduce

1. Open https://open-assistant.io/auth/signin
2. Type in your e-mail address
3. Click "Continue with Email"

The page say:

>A sign-in link has been sent to your email address.

But i don't get an e-mail!

## Workaround

I think the problem is caused by [Greylisting](https://de.wikipedia.org/wiki/Greylisting).

With it, the receiving mail server denies the e-mail from an unknown sender first and put's it in a timeout. So your mailserver has to try again later. Many spammers don't bother to do that, so it's a very effective method to prevent spam! I think the problem is that your mailserver does not try again later!

I tried the signup yesterday, but don't got the e-mail.

Today i tried 2 times in 30 minutes and at the second time, i got the e-mail!

**Comment by andreaskoepf** [comment]
Maybe related: Missing SPF records for laion.ai were added only very recently (yesterday).

**Comment by AzielChamba** [comment]
Looks easy to fix assign me

**Comment by andreaskoepf** [comment]
> Looks easy to fix assign me

Could you please explain a bit how you intend to address the problem?

**Comment by bradshimmin** [comment]
Can confirm @davidak 's experience. Using gmail, yesterday, I tried once and saw no email. Today, I tried again, and again no email. But another try less than 5 minutes later, did the trick.

**Comment by bitplane** [comment]
Note to anyone implementing/testing this:

You can use `youremail+something@gmail.com` and keep varying the `something` part to get emails to test accounts to your main mailbox.
