### ISSUE TITLE
Hide summerize story & rate summary tasks in the frontend

### ISSUE THREAD

**Issue by AbdBarho** [LAION-AI/Open-Assistant#139]
Since our backend currently disabled these tasks: https://github.com/LAION-AI/Open-Assistant/commit/a4e5f566a86330a6335e51c1fd255b3ae73300e5 we should also hide them in the frontend.

Easiest way would be to just comment out the links in the index page.

https://github.com/LAION-AI/Open-Assistant/blob/main/website/src/components/TaskSelection/TaskSelection.tsx

**Comment by AAYUSH-droid** [comment]
Hey I would like to work in this issue @AbdBarho

**Comment by AbdBarho** [comment]
@AAYUSH-droid great! I will assign it to you.
