### ISSUE TITLE
Running the end2end docker setup triggers a failures in the backend.

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#140]
I ran the end2end docker setup to test the website and I'm seeing a backend error like the following when fetching a task:

```
open-assistant-backend-1  | 2022-12-29 09:18:57.754 | INFO     | oasst_backend.api.v1.tasks:generate_task:58 - Generating a UserReplyTask.
open-assistant-backend-1  | 2022-12-29 09:18:57.761 | ERROR    | main:oasst_exception_handler:19 - POST http://backend:8080/api/v1/tasks/ failed: OasstError(message="No threads found", error_code=2006, http_status_code=400)
```

We can investigate the cause, but are there recent changes that might have caused this?

**Comment by mjagkow** [comment]
Hi @fozziethebeat, the issue most likely is you need assistant's replies in the DB. This method asks for a conversation a user (or "prompter") can answer to. Thus this conversation needs to end with an assistant's post. The conversation is randomly sampled starting from the last post and this error indicates there are no assistant's post to start (or end in this case) with.
So to fill the db either add those replies manually if it is possible, or just complete 1) "initial prompt" task 2) consecutive "assistant reply" task 3) and finally you can run "user reply" task

**Comment by andreaskoepf** [comment]
@mjagkow I created #133 for this. Please comment there if more than 4 messages / 2 threads are necessary to get things going.

**Comment by fozziethebeat** [comment]
@andreaskoepf's proposal in #133 is good.  For simplifying developer experience, we should always seed an empty database with some fake data if it's required for the service to function properly.  We don't want new developers guessing at how to seed some database, it should just happen in docker-compose somehow.
