### ISSUE TITLE
he seleccionado idioma español y todas las tareas me salen en ingles

### ISSUE THREAD

**Issue by cgchaconr** [LAION-AI/Open-Assistant#1401]
esto ocurrio despues de apagar la luz

[Edited with estimated translation: I have selected Spanish but all the tasks appear in English. This happened after turning off light mode]

**Comment by jacovzap** [comment]
He intentado replicar este problema pero no lo consigo, podrias dar mas detalles acerca del error, como reproducirlo y de ser posible adjuntar alguna captura por favor.

Translation: [I have tried to replicate this problem but i couldnt get it, could you please give us more information about the error and how to replicate it, and if its possible attach an screenshot]

**Comment by cgchaconr** [comment]
entre nuevamente a la plataforma  y no hubo incoveniente

**Comment by AbdBarho** [comment]
We have fixed this problem in #1785
