### ISSUE TITLE
architecture diagram?

### ISSUE THREAD

**Issue by andrewm4894** [LAION-AI/Open-Assistant#1427]
would be nice if there was some sort of diagram of all the moving parts (nothing crazy fancy or anything) just to help potential new contributors get up to speed on all the moving parts (fastapi, nextjs, redis, etc). 

not sure if anything like that exists in docs yet anywhere?

**Comment by AbdBarho** [comment]
Not yet, I will try to create something quickly

**Comment by andrewm4894** [comment]
I saw mermaid a while back and might be easy to use perhaps and just have any diagrams and .md files: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams#creating-mermaid-diagrams

**Comment by bitplane** [comment]
> I saw mermaid a while back and might be easy to use perhaps and just have any diagrams and .md files: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams#creating-mermaid-diagrams
>

Cool I might try this approach in future myself.

I've been using PlantUML in work, picked it up from a really good architects on an MQ-heavy IoT project. They're very readable but are constrained to UML with specific classes of diagram (might be good or bad depending how you look at this)

https://plantuml.com/deployment-diagram

I made a pre-commit hook that uses the PlantUML Docker image to render them to SVG or PNG, and then commit them if they've changed. It works pretty well, but dunno if docker-in-docker devcontainers would work:

https://github.com/bitplane/plantuml-docker-pre-commit-hook

Mermaid might be better though if it renders inline. I wish puml would!
