### ISSUE TITLE
Cannot interact with the api

### ISSUE THREAD

**Issue by VictorLG98** [LAION-AI/Open-Assistant#1447]
I have tried to access these endpoints but I always get the error *405 Not Allowed*:

- **/api/v1/tasks/interaction**
- **/api/v1/tasks/**

**Comment by notmd** [comment]
Those endpoints need a post request. You may need to use curl or tool like Postman etc.

**Comment by andrewm4894** [comment]
Maybe some docs to show how to interact with API could be useful, I'll make a good first issue for it.

**Comment by andrewm4894** [comment]
Made this

https://github.com/LAION-AI/Open-Assistant/issues/1460

**Comment by VictorLG98** [comment]
> Those endpoints need a post request. You may need to use curl or tool like Postman etc.

Yes, i did it with requests python module but didnt work...

**Comment by olliestanley** [comment]
Closing in favour of #1460
