### ISSUE TITLE
On the bright theme the Radio buttons are not very visible

### ISSUE THREAD

**Issue by bugmaschine** [LAION-AI/Open-Assistant#1467]
![grafik](https://user-images.githubusercontent.com/38097264/218255963-36565099-160a-4922-9dbe-77c34a0def64.png)

**Comment by AbdBarho** [comment]
Fixed 

![image](https://user-images.githubusercontent.com/24505302/222945656-4f72c9d8-377c-4f85-911e-4326211d51fb.png)
