### ISSUE TITLE
Make inference more robust

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#1469]
Currently, the inference system lives under `/inference`. After installing the various dependencies, plus tmux, you can run it using the `full-dev-setup.sh` script (or use the docker compose inference profile).

The goal of this issue is to make the entire pipeline more robust with respect to errors, disconnects, timeouts, etc.

The inference system consists of multiple parts:
- one central inference server that connects to a postgres and a redis database.
- many external workers that perform the actual inference
  - each worker consist again of two parts, a python connector and a text-generation backend
  - the text-generation backend exposes an HTTP API
  - the python connector connects to the HTTP API and also to the central server via websocket
- optionally: the text-client. this one is mainly for testing, but can also be considered when robusifying the system

consider that each part of the system might fail or time out or get disconnected in some way, or throw some error. make sure that everything is resilient and properly attempts to re-start/re-connect, or in some other way gracefully handle these things, but without over-burdening the other parts when doing so.

**Comment by SerenityCodes** [comment]
I will get started on this issue if no one has already!

**Comment by andreaskoepf** [comment]
Can this be closed now? Inference is already running for some time now.

**Comment by yk** [comment]
closing: out of date. sorry @SerenityCodes
