### ISSUE TITLE
Introduce Users to Inference

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#1471]
Currently, the inference system lives under `/inference`. After installing the various dependencies, plus tmux, you can run it using the `full-dev-setup.sh` script (or use the docker compose inference profile).

The inference system currently does not consider any users, meaning it has a global collection of "chats", and anyone can interact with any chat by sending HTTP requests to the `/chat/...` endpoints.

Like the data-collection frontend does, we need to connect these chats to users. To solve this issue, see how the frontend currently hands off users to the backend and either replicate this, or come up with an improved version. Then, store the association of users to chats etc. in the database and modify the DB retrievals such that they consider chat ownership.

**Comment by yk** [comment]
@fozziethebeat would be nice to get your input here on what the best auth flow is

**Comment by yk** [comment]
also note: currently @AbdBarho is working on integrating inference into the website on the `website-chat` branch.

**Comment by AbdBarho** [comment]
>  see how the frontend currently hands off users to the backend

We currently send the `x-oasst-user` header in every request which is of the format `auth_method:user_id`.

**Comment by olliestanley** [comment]
If we are still planning to move to backend-generated JWTs (this still requires both frontend and backend work) I think it would be desirable to design the inference auth system to work like that off the bat. Otherwise we will simply have to overhaul it later. I will make a start and see how viable this is.

**Comment by yk** [comment]
> If we are still planning to move to backend-generated JWTs (this still requires both frontend and backend work) I think it would be desirable to design the inference auth system to work like that off the bat. Otherwise we will simply have to overhaul it later. I will make a start and see how viable this is.

Yes, I'd definitely just go with proper auth in the backend. if the frontend temporarily becomes such that users have to "log in twice" until the data-collection also switches, I think that's an acceptable small burden we can put on them.
