### ISSUE TITLE
Thumbs up/down and reporting for inference

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#1477]
Currently, the inference system lives under `/inference`. After installing the various dependencies, plus tmux, you can run it using the `full-dev-setup.sh` script (or use the docker compose inference profile).

The inference system consists of multiple parts:
- one central inference server that connects to a postgres and a redis database.
- many external workers that perform the actual inference
  - each worker consist again of two parts, a python connector and a text-generation backend
  - the text-generation backend exposes an HTTP API
  - the python connector connects to the HTTP API and also to the central server via websocket
- optionally: the text-client. this one is mainly for testing

Also @AbdBarho is working on a website-frontend in the `website-chat` branch.

We want users who interact with the inference system (i.e. they use the chatbot) to be able to give thumbs-up and thumbs-down to the generated replies, and also "report" the messages in case they contain inappropriate things. The goal of this issue is to create API endpoints to support that.

**Comment by layterz** [comment]
Created a PR for this here https://github.com/LAION-AI/Open-Assistant/pull/1848
