### ISSUE TITLE
Find some how-to-github material for newcomers and link it in the readme

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#148]
There are people coming from e.g. GitLab who could use an introduction on GitHub forks & PRs.

**Comment by kiritowu** [comment]
Github's documentation on ["Collaborating with pull requests"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests) seems like a good introduction.

Some important ones are:
- [About forks](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks)
- [Fork a repo](https://docs.github.com/en/get-started/quickstart/fork-a-repo)
- [Syncing a Fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork)
- [Creating a pull request from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by yk** [comment]
thank you! could you make a PR and put that into the readme? I know, very meta ;)
