### ISSUE TITLE
Unexpected Error in "Reply as Assistant" Tasks

### ISSUE THREAD

**Issue by jjhaggar** [LAION-AI/Open-Assistant#1485]
I am writing to report an issue that I have experienced several times (about 3 times I think) while using the Dashboard as an assistant (I was using it in Spanish language, just in case that is relevant to find the problem). 

I have noticed that sometimes after pressing "Review" and submitting my answer as assistant, then an error appears (I think it said something like "the task does not exist", I'll be more vigilant next time and I'll take a screenshot), the task appears to have been cancelled and my response is not visible between my "Messages" . 

This is causing me a lot of frustration and loss of valuable time, as some of these answers required extensive research and writing :'( 

I would greatly appreciate if you could find a solution for this issue.

**Comment by jjhaggar** [comment]
It happened again, this time while I was creating an "Initial Prompt" ^^UU

This time I was able to take a screenshot:
![image](https://user-images.githubusercontent.com/4078392/218289519-e6e89278-ee39-4341-ab5c-b74ad91966f5.png)

Maybe it's some kind of timeout problem? Or maybe somebody did the task before I was able to do it?

**Comment by jjhaggar** [comment]
Oh! But it seems this time the prompt I wrote was saved! :D
![image](https://user-images.githubusercontent.com/4078392/218289729-885bb0f1-aac9-4645-861b-e72fceb07e68.png)
Still, no idea of what that error message means and what should I do to avoid it, I'm very confused >_<

**Comment by GuilleHoardings** [comment]
I think that the problem here is that you start with a task that it's available, but while you are working on it, somebody else completes it and then it's not available anymore when you submit it.

**Comment by andreaskoepf** [comment]
In general the "no tasks were found" after you submitted a response is not necessarily an error. Depending on the current state only a limited number of tasks are available, e.g. there can only be 100 unlabeled initial prompts per language. When this limit is reached the system does not hand out more create initial prompt tasks before at least one prompt was labeled by three people.

**Comment by jjhaggar** [comment]
Well, if that error only showed when I have created an initial prompt it wouldn't be an issue for me (I could always enter that prompt in the future when there are more frees slots). 
My main problem is when I get that error after I answer as assistant after spending half an hour searching in Google and learning about the subject in order to answer in the best way possible. I think that this system behaviour only encourages people to answer faster, and probably not as well as they could.
