### ISSUE TITLE
Possible error at comand in the website README.md 

### ISSUE THREAD

**Issue by jacovzap** [LAION-AI/Open-Assistant#1494]
![image](https://user-images.githubusercontent.com/69549956/218282105-7dc212da-9230-4523-986e-36f57611083f.png)

The command "docker compose" does not work correctly. It might be "docker-compose".

**Comment by blankster** [comment]
I would directly send a PR with the change.

**Comment by opfromthestart** [comment]
It is supposed to be `docker compose` and not `docker-compose`. Look at [this site](https://projects.laion.ai/Open-Assistant/docs/faq#docker-compose-instead-of-docker-compose)

**Comment by MrBased** [comment]
@jacovzap This was already explained in issue #1215

**Comment by olliestanley** [comment]
Yes, closing this as not an issue, it just means you need a different Docker version
