### ISSUE TITLE
Minor graphical bug in messages tab if words are too long

### ISSUE THREAD

**Issue by JohannesGaessler** [LAION-AI/Open-Assistant#1517]
Consider the following screenshot:

![Screenshot_20230212_143428](https://user-images.githubusercontent.com/18492268/218314504-0075a677-e3e4-46f7-a1fb-8555fd005fec.png)

It seems that if a single word is too long for a line break the containers for individual messages increase their bounds beyond what is intended.

**Comment by johnflux** [comment]
Before:

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/1230500/218328535-819de7a5-2cf3-4c46-9d35-aed68cfaaf2b.png">

After:
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/1230500/218328564-bd4c837f-3587-4d89-8b17-125db7bf03e8.png">
