### ISSUE TITLE
[feature] Adding Hindi ("hi") locale to the website

### ISSUE THREAD

**Issue by upperwal** [LAION-AI/Open-Assistant#1519]
Steps:
1. Adding translations to `hi` directory inside [website/public/locales](https://github.com/LAION-AI/Open-Assistant/tree/main/website/public/locales)
2. Adding `hi` locale in [next-i18next.config.js](https://github.com/LAION-AI/Open-Assistant/blob/main/website/next-i18next.config.js)

**Comment by upperwal** [comment]
@olliestanley Can you assign it to me. I will work on it over the weekend. Thanks.

**Comment by olliestanley** [comment]
> @olliestanley Can you assign it to me. I will work on it over the weekend. Thanks.

Sure, thanks!
