### ISSUE TITLE
Support login with GitHub

### ISSUE THREAD

**Issue by bitplane** [LAION-AI/Open-Assistant#1535]
* It'll bring an easy flow of devs from GitHub onto the site
* Discord is blocked in China, GitHub isn't.

Background: We have reports from a Chinese user that Discord is blocked by their gov, so it's troublesome to log in using it. Supporting GitHub would make this easier.

**Comment by mqurishi** [comment]
I can add this support with comparing data to discord login model , i will create a PR with the required updates and comment on further requirments and differences to discord login

**Comment by GitB1at** [comment]
Unsubscribe

**Comment by olliestanley** [comment]
We support Google login now, inference backend also supports GitHub but this isn't in frontend yet. I think this can be closed
