### ISSUE TITLE
EN vs ES

### ISSUE THREAD

**Issue by XavierRex** [LAION-AI/Open-Assistant#1540]
I think the battle between the EN vs ES community could be great opportunity to speed up the work of creating a massive dataset. Just add a counter on the main page showing what score both languages have.

**Comment by gulliver-madrid** [comment]
In line with gamifying participation, it might not be a bad idea, but I would add different languages to the scoring table, not just English and Spanish.

**Comment by GuilleHoardings** [comment]
Related: #1528

**Comment by blankster** [comment]
This could be quite motivating, but it is important to remember that quality must not fall by the wayside. We absolutely must prevent people from starting to work with bots or using ChatGPT content for this purpose. If you want something like that, it's worth considering how to prevent such constructive competition from leading to a drop in quality and increase in unwanted behavior.
