### ISSUE TITLE
Enhancing messages section with locales

### ISSUE THREAD

**Issue by ehcalabres** [LAION-AI/Open-Assistant#1547]
I've seen that when you access to the messages page, if you recive no messages from the backend the cards remain empty with no feedback at all, so you don't know exactly what's going on.

I have a bit of code ready to create a PR to solve that issue and tell the user that there's no messages in that section. Also, I've added the locales for **_English_, _Spanish_, _Català_, _Euskera_ and _Galego_**.

I'll gladly create the PR 😄 

### Before

![image](https://user-images.githubusercontent.com/10390523/218520276-83191622-c51b-4c1c-92d8-0200d937fe01.png)

### After

![image](https://user-images.githubusercontent.com/10390523/218521797-486e209b-a138-4395-bebb-90b02b4ee605.png)

![image](https://user-images.githubusercontent.com/10390523/218521647-89317235-a5f0-46dd-a17b-426fbd597395.png)

**Comment by olliestanley** [comment]
Sounds good, I've assigned you
