### ISSUE TITLE
Not {lang} fetature does not work for some languages 

### ISSUE THREAD

**Issue by paskudnicc** [LAION-AI/Open-Assistant#1556]
Specifically, got this displayed while working with the Russian language
![image](https://user-images.githubusercontent.com/57360472/218609699-502f3910-b92a-45f0-a465-c5d28767356e.png)

**Comment by ArgiesDario** [comment]
Hi, I was looking all over for this screen in russian language ( https://open-assistant.io/ru/dashboard ) where this happens but I'm not able to find it

Could you provide me the url of it? or steps on how to get there. Thanks

**Comment by paskudnicc** [comment]
for example, https://open-assistant.io/ru/label/label_initial_prompt
But it was fixed some time ago, sorry for not closing in time :(
