### ISSUE TITLE
Links in header and footer don't always resolve to a valid page

### ISSUE THREAD

**Issue by AbdBarho** [LAION-AI/Open-Assistant#156]
This issue is a continuation of #132 

In our [index.tsx](https://github.com/LAION-AI/Open-Assistant/blob/main/website/src/pages/index.tsx) we show two different pages if the user is signed in vs not.

However, many links in the headers and footer point to the un-logged-in variant of the page, [example](https://github.com/LAION-AI/Open-Assistant/blob/65dbb9c4e1f85553189dc128f2ce2c82dd95219d/website/src/components/Header/Header.tsx#L106).

We need re-structure of our site paths, also considering other needed pages such as #46.

Suggestion:
I think it would make sense to leave `/` as non-logged user, and maybe add a `/app` that shows the available tasks & such. This will require new buttons or nav items to navigate to the app if you are logged in.

having a `/about` is never a bad idea.

Questions:
* do we need to worry about slugs / SEO? or just wing it?

**Comment by fozziethebeat** [comment]
Yeah I like this idea.  `/app` is the signed in page and is blocked by the middleware.  Then some initial stubs for the other links.  With the new footer links I'm not sure we need a `join us` or `faq` in the top bar.  Those fit better at the bottom.

When I get to the privacy policy my plan was to add
- `/privacy-policy`
- `/terms-of-service`

Then we should additionally have:
- `/about`
- `/`

as the public pages.

We should discuss if the leaderboard should be public.  That'd probably go under `/leaderboard`.

**Comment by fozziethebeat** [comment]
I've bucketed this as a post-mvp problem.

**Comment by fozziethebeat** [comment]
Next up, i'll make a new page (either `/home` or `/app`) that's scoped to signed in users.  I don't think we actually need other nav links.  The header link can always go to `/home` when a user is signed in and `/` when they're not.

**Comment by fozziethebeat** [comment]
I think PR #312 will close out the final change needed.  `/dashboard` is sufficient for signed in users.

**Comment by AbdBarho** [comment]
@fozziethebeat sounds good!

The PR was closed, not sure why....

**Comment by fozziethebeat** [comment]
I updated the PR to close this as it creates `/dashboard`.  The one outstanding thing to fix is to make sure the link in the header for a signed in user goes to `/dashboard`.  I forgot about that when marking this to close.
