### ISSUE TITLE
Adding missing locale keys in all languages

### ISSUE THREAD

**Issue by mqurishi** [LAION-AI/Open-Assistant#1560]
Hello , when using the application i noticed some keys were still not being translated , i want to add the missing labels to all the parts of the app and transolate them to thier respective language

![image](https://user-images.githubusercontent.com/120375378/218676680-2a7256b6-4b97-4752-8d5f-aa89a20a42bf.png)

**Comment by ArgiesDario** [comment]
Hi, is that Arabic, right?

The English i18n are in here: 
https://github.com/LAION-AI/Open-Assistant/blob/3f7244cf3b16ba0aae4f51b36f6e58aba0de62ee/website/public/locales/en/labelling.json

And Arabic ones over here:
https://github.com/LAION-AI/Open-Assistant/blob/3f7244cf3b16ba0aae4f51b36f6e58aba0de62ee/website/public/locales/ar/labelling.json

as you can see, arabic is missing a lot of translations, some example about those in screen are:
"high_quality": "High Quality",
"low_quality": "Low Quality"

Feel free to do the translations and send a PR, if not, just paste the translations over here and I'll do the PR for you

**Comment by mqurishi** [comment]
Oh i see, i think the translation layout got changed i will update as required and send the PR , thanks

**Comment by notmd** [comment]
close because #1813 is merged
