### ISSUE TITLE
Trollboard: Users with empty display-names can't be banned by GUI

### ISSUE THREAD

**Issue by blankster** [LAION-AI/Open-Assistant#1565]
When someone with the needed permissions tries to ban a user on the troll board and changes the role to "banned", this fails with the message: "User Role updated failed".

That means that this function is currently broken and changes need to be made in the database directly, what is suboptimal and should be fixed in the near future to enable moderators to do their job.

This seems to be connected with empty display-name- what should be prevented in general! 

A workaround could be a fallback mechanic back to the username.

**Comment by markuschue** [comment]
I'm new to this but I'd like to give this issue a try!

**Comment by andreaskoepf** [comment]
> I'm new to this but I'd like to give this issue a try!

Thanks a lot, I assigned the issue to you! :-) If you join our OA discord please ping me.
