### ISSUE TITLE
use_new_message_tree : Single messages try to build tree (website) 

### ISSUE THREAD

**Issue by mm12** [LAION-AI/Open-Assistant#1578]
SInce the using new message tree went live on the website, opening single messages in new tab will still try to build a tree, resulting in the error 'Unable to build tree'. Instead of throwing this error, it should first try to open it in single message view. 
Related: #1482

**Comment by notmd** [comment]
Can you post the link or some screenshot here?

**Comment by mm12** [comment]
> Can you post the link or some screenshot here?

[This message](https://open-assistant.io/messages/024055f6-c436-4756-a054-7bdf013e1131) was clicked form the messages tab
At the moment it is one of the ones that doesn't work, but that might change. Here is the screenshot: 
<img width="997" alt="Screen Shot " src="https://user-images.githubusercontent.com/5874051/219173181-a018b0c7-fcca-4690-8119-86ee4773fd7d.png">
and here is what it looks like otherwise 
<img width="767" alt="scrnsht" src="https://user-images.githubusercontent.com/5874051/219173418-9bd5de7f-31ff-4def-ad0a-8a468fee3f24.png">

**Comment by notmd** [comment]
> > Can you post the link or some screenshot here?
> 
> [This message](https://open-assistant.io/messages/024055f6-c436-4756-a054-7bdf013e1131) was clicked form the messages tab At the moment it is one of the ones that doesn't work, but that might change. Here is the screenshot: <img alt="Screen Shot " width="997" src="https://user-images.githubusercontent.com/5874051/219173181-a018b0c7-fcca-4690-8119-86ee4773fd7d.png"> and here is what it looks like otherwise <img alt="scrnsht" width="767" src="https://user-images.githubusercontent.com/5874051/219173418-9bd5de7f-31ff-4def-ad0a-8a468fee3f24.png">

That message seems to work now. That's weird. Do you face this bug frequently?

**Comment by mm12** [comment]
> > > Can you post the link or some screenshot here?
> > 
> > 
> > [This message](https://open-assistant.io/messages/024055f6-c436-4756-a054-7bdf013e1131) was clicked form the messages tab At the moment it is one of the ones that doesn't work, but that might change. Here is the screenshot: <img alt="Screen Shot " width="997" src="https://user-images.githubusercontent.com/5874051/219173181-a018b0c7-fcca-4690-8119-86ee4773fd7d.png"> and here is what it looks like otherwise <img alt="scrnsht" width="767" src="https://user-images.githubusercontent.com/5874051/219173418-9bd5de7f-31ff-4def-ad0a-8a468fee3f24.png">
> 
> That message seems to work now. That's weird. Do you face this bug frequently?

I was, seems to be fixed.
