### ISSUE TITLE
Show other peoples thumbs up and thumbs down only after the user voted

### ISSUE THREAD

**Issue by spirobel** [LAION-AI/Open-Assistant#1580]
What do you think about showing other peoples thumbs up and thumbs down only after the user voted up or down?

The opinions of others can influence results very strongly as research has shown.

So it might lead to better results if the users first give an opinion that cant be changed later, before seeing what others thought about an answer that open assistant gave.

So you get an unbiased answer that does not get biased as much by groupthink.

**Comment by notmd** [comment]
Hi, we are already hide the reaction count when user havent reacted yet. Did you miss something?
