### ISSUE TITLE
Any plan to re-implement the reward model training from InstructGPT?

### ISSUE THREAD

**Issue by ethanyanjiali** [LAION-AI/Open-Assistant#1584]
Looks like the reward model is RankGen at the moment? But I thought we are going to have InstructGPT like K pair-wise ranking loss instead of this prefix/suffix one. Is there a plan to follow up on that? I didn't see an existing Issue or PR so wanna ask.

**Comment by andreaskoepf** [comment]
K pair-wise loss was at least discussed in the beginning. We definitely would love to experiment and compare different reward-models. If you are (or anyone else is) interested in working on this please join the OA discord and ping @sanagno (Sortiris on discord) or me.

**Comment by ethanyanjiali** [comment]
Thanks Yes, I would be interested. Need a few more days to wrap up my current work, but I'll let you guys know when I'm ready to scope out the work and implement.

**Comment by olliestanley** [comment]
I will close this as an answered question but if you are interested in participating in ML development feel free to comment on an issue or come and discuss with us in the volunteers channel of the Discord server :)

**Comment by ethanyanjiali** [comment]
Sounds good. About to reach out this weekend.
