### ISSUE TITLE
New tasks do not appear in smaller languages

### ISSUE THREAD

**Issue by XavierRex** [LAION-AI/Open-Assistant#1586]
I created more than a dozen initial prompts, made several assistant response that were available, but after two hours of waiting, no new task about creating an assistant response appeared. I don't know if the tasks are assigned manually, but if automatically then the frequency of adding new ones in small languages should be increased.

**Comment by olliestanley** [comment]
The initial prompts need to be labelled to pass the spam review (by multiple other users - you cannot label your own prompts) before their trees progress to allowing responses

**Comment by XavierRex** [comment]
@olliestanley makes sense, but adding information about this when no assistant response/create initial prompt task is available in a smaller language might be a good idea
