### ISSUE TITLE
Web Moderation: Spam label is misleading

### ISSUE THREAD

**Issue by blankster** [LAION-AI/Open-Assistant#1590]
The spam label is currently being overused, which defeats its purpose of identifying problematic content quickly. While the label is intended to be helpful, it seems to appear in two cases, leading to an excessive amount of content being labeled as spam and reducing its effectiveness.

There are 2 conditions when it gets applied (credit to @olliestanley):

1. The message has not yet finished the review/labelling process
2. The message has failed the review/labelling process (e.g. through being labeled as a spam message by multiple users)

As often, @andreaskoepf already hinted the solution for this:

_Summarized: The field review_result should be nullable and set to null before enough labels are received._ 

That would massively help to separate between something that is just in review, and something that is actively flagged as real spam, and help the moderators to fight against such behavior and prevent people from wasting time.

**Comment by olliestanley** [comment]
Is this complete now or do we still need the frontend change to change what is displayed after the backend change in #1599?

**Comment by olliestanley** [comment]
I think this was fixed a long time ago
