### ISSUE TITLE
Language selection should provide the lang option in the current lang

### ISSUE THREAD

**Issue by ArgiesDario** [LAION-AI/Open-Assistant#1594]
When picking the language, it is only shown on its native name:

![image](https://user-images.githubusercontent.com/7121037/219058855-cd129416-d388-470f-93d3-c89231514f24.png)

But this makes it hard for the current language speaker to know which other are, cause those are not displayed in his language. Most pages solve this by adapting the lang name depending on which lang you are on

Example: Using English lang, the user should see other langs with its name in English between brackets

![image](https://user-images.githubusercontent.com/7121037/219059648-d9c625eb-cbd7-444b-9fef-5113bfdba189.png)

Example: Using Spanish lang, the user should see other langs with its name in Spanish between brackets

![image](https://user-images.githubusercontent.com/7121037/219059851-95c941e9-3cb2-4b01-9609-6a7f56c77ace.png)

**Comment by notmd** [comment]
[https://github.com/LAION-AI/Open-Assistant/issues/1230#issuecomment-1420270456](https://github.com/LAION-AI/Open-Assistant/issues/1230#issuecomment-1420270456)
