### ISSUE TITLE
Is it the ai model we can host on locally?

### ISSUE THREAD

**Issue by NitinNi3** [LAION-AI/Open-Assistant#1595]
Please clear me on this.so your telling that this is an ai model and data feeding website but tell me first you guys are providing the ai model scripts !

**Comment by blankster** [comment]
Check https://projects.laion.ai/Open-Assistant/docs/faq

**Comment by andreaskoepf** [comment]
> Please clear me on this.so your telling that this is an ai model and data feeding website but tell me first you guys are providing the ai model scripts !

You find all code of our model [here](https://github.com/LAION-AI/Open-Assistant/tree/main/model) - it is heavily under development and will change over the next weeks.

**Comment by NitinNi3** [comment]
So what is the format of the data set to train the model ?
