### ISSUE TITLE
Missing translation for stats

### ISSUE THREAD

**Issue by notmd** [LAION-AI/Open-Assistant#1596]
[https://web.dev.open-assistant.io/stats](https://web.dev.open-assistant.io/stats)
![image](https://user-images.githubusercontent.com/33456881/219077752-02c73262-5fdb-4ce0-b2a2-25ccf9846482.png)

**Comment by notmd** [comment]
For anyone want to take this, here is the file you need to edit [https://github.com/LAION-AI/Open-Assistant/blob/main/website/public/locales/en/stats.json](https://github.com/LAION-AI/Open-Assistant/blob/main/website/public/locales/en/stats.json)

**Comment by 0x22almostEvil** [comment]
`uwu owo uwu`

**Comment by notmd** [comment]
Oh wait. Look like translation has been added but somehow it's not displayed correctly

**Comment by 0x22almostEvil** [comment]
![image](https://user-images.githubusercontent.com/122345469/219198403-7f7abb3f-fe04-46bf-83c5-3c1c1f4031f3.png)
Somehow

**Comment by notmd** [comment]
fixed in #1603
