### ISSUE TITLE
finding it a little hard to see the checkboxes in light mode

### ISSUE THREAD

**Issue by andrewm4894** [LAION-AI/Open-Assistant#1598]
im finding the contrast a little hard to distinguish on the checkboxes and so finding it hard to sort of "anchor" quickly on where the middle is.

maybe just me - id imagine maybe not too hard to make a PR for if others agree - might have a go myself if can. 

![image](https://user-images.githubusercontent.com/2178292/219102943-f218ed19-3134-4d93-aa52-6b08375756e3.png)

**Comment by CactiStaccingCrane** [comment]
I will take on this
