### ISSUE TITLE
Links were not correctly updated after guideline revision.

### ISSUE THREAD

**Issue by JohannesGaessler** [LAION-AI/Open-Assistant#1602]
The PR https://github.com/LAION-AI/Open-Assistant/pull/1362 updated the guidelines.
However, the ? icon when providing data still points at https://projects.laion.ai/Open-Assistant/docs/guides/prompting when it should now be pointing at https://projects.laion.ai/Open-Assistant/docs/guides/guidelines .

(Initially I accidentally created this issue without text.)

**Comment by GuilleHoardings** [comment]
I think that the PR correctly updates the links, but the web page has not been updated with this new version proposed in the pull request, while the docs website has been changed. When a new version is released, it should be fixed.

**Comment by JohannesGaessler** [comment]
I looked at the PR again and I think you're right; I'll close the issue when the new version rolls out.
