### ISSUE TITLE
Sort/find users by username (ID) in admin interface

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#1615]
Currently it is possible to search for users by their display name and the user list is in general ordered by display name.

To assign the moderator role to a user it would be helpful to search for a user by their discord ID. The backend already supports this by specifying `sort_key=username` in the query to `/api/v1/users/cursor`. Probably all that would have to be done in the frontend is to allow switching between sort_key 'username' and 'display_name' and displaying the the search box either on the column-header of the display name or the username column depending on the selected sort_key.

(btw if someone is working on it, it would be great if the focus could be set to the input of the search box after clicking the filter button.)

**Comment by owen-duncan-snobel** [comment]
I am working on this now
