### ISSUE TITLE
[REQUEST] Could the data collection website show how much data has been collected for each task. 

### ISSUE THREAD

**Issue by coen22** [LAION-AI/Open-Assistant#1616]
Hi everyone,

Open Assistant looks like a really cool project.
It's also nice to see how much people have contributed to this already.
However, I can't find how much data has been collected (or what the goal is regarding data collection).

Could you perhaps add a tab below 'Leaderboard' with the overall statistics?
It could show the overall number of initial prompts that have been created, how many of those were accepted, etc.

Regards,
Coen

**Comment by andreaskoepf** [comment]
Yes, next deployment will show some stats, see merged PR https://github.com/LAION-AI/Open-Assistant/pull/1576.

Regarding the definition of an overall goal it is a bit more tricky.. obviously we want to collect as many high-quality messages as possible. The biggest challenge IMO is to get enough messages for all the languages that were added, currently we have a lot of English and and Spanish messages but all other languages are much sparser...

Not sure if you saw that: We had up to now regularly published stats in the OA discord server. And some community members also track time series of the collection process over time.

**Comment by coen22** [comment]
Ah nice and yeah I understand it is difficult to define what 'enough' data is, as you can always have more.
It's nice to see that Dutch has been added, I'll try to answer some prompts there too.
