### ISSUE TITLE
Rank assistant replies: View full text formating loss

### ISSUE THREAD

**Issue by mm12** [LAION-AI/Open-Assistant#1647]
I don't know if this is going to be solved by #1378 , but one of the reasons #1543 is so bad is because if you click to read full text, the formatting gets lost (particularly, newlines and spacing) 
This turns something like 

> 3 ways to do a thing:
> • way 1
> • way 2, explanation 
> • way 3, blah blah blah no punctuation at the end
> in conclusion the best way is one of them

into something like 

> 3 ways to do a thing: • way 1 • way 2, explanation • way 2, explanation • way 3, blah blah blah no punctuation at the end in conclusion the best way is one of them

As you can see, even though you can kind of tell with the bullet points, the lack of punctuation often found at the end of them messes it up. It also makes reading long messages very hard, as there are no paragraphs.

**Comment by blankster** [comment]
I'm attaching here some screenshots that demonstrate the problem:

![image](https://user-images.githubusercontent.com/1443109/219511699-7c6e4f83-0501-497e-ab1c-50208b8af615.png)

![image](https://user-images.githubusercontent.com/1443109/219511819-2da46c7b-1261-4924-9a30-239ebfa0f79a.png)

![image](https://user-images.githubusercontent.com/1443109/219511851-0f1b7b25-664a-423c-bcf1-814b58dcb2ba.png)

![image](https://user-images.githubusercontent.com/1443109/219511894-6f8b90eb-54b3-4d12-9944-c25885b6515e.png)

![image](https://user-images.githubusercontent.com/1443109/219511921-b5ed5e4d-b887-4d9b-b6bb-c678e95451af.png)

**Comment by notmd** [comment]
this has been fixed
