### ISSUE TITLE
Set up an initial framework for data collection, storage, cleaning, and accessing

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#165]
Many people are collecting data, for example scraping websites, etc. We need a framework (guidelines, how-to's, documented processes, etc.) on how that data does not get lost and gets made into something useful. Ideally, the people who collect the data provide the code to collect, clean, and process the data as a PR to the repo (can be some new subfolder like `datasets/`). I.e. they do not provide the data correctly, but the code, and along that, they provide clear instructions on how to use it. (Ideally the code comes in CLI-like scripts, can easily be built with e.g. `typer` or `click`). Then, we need a storage location (set up a LAION s3 bucket) and a method of running these scripts to actually collect, store, and process the data, such that it is available for downstream applications (ML training).

**Comment by yk** [comment]
will assign to @lewtun as soon as he accepts invite ;)

**Comment by lewtun** [comment]
A few initial thoughts on how we could standardise the data collection / data processing efforts:

#### 1. Create a dedicated [GitHub project board](https://github.com/LAION-AI/Open-Assistant/projects?query=is%3Aopen) to track which datasets to add / WIP / done

Using Discord to coordinate this work it pretty hard, so having an overview would help. We could use a similar format to the 🤗 Datasets [issues](https://github.com/huggingface/datasets/issues/5371), which log basic info needed for anyone to work on adding the dataset.

@yk I don't have permissions to create a new project board - if you agree, could you create one for this?


#### 2. Use the 🤗 Datasets library for loading / processing

* The dataset loading scripts will be standardised, i.e. easy to reproduce with a one-liner `load_dataset(...)` call
* Has [S3 support](https://huggingface.co/docs/datasets/v2.8.0/en/filesystems#cloud-storage)
* Allows people to easily push curated datasets to the Hugging Face Hub at some later date with the `push_to_hub()` method ([docs](https://huggingface.co/docs/datasets/v2.8.0/en/package_reference/main_classes#datasets.Dataset.push_to_hub))
* Has plenty of high-performance features baked in (caching, multiprocessing) and plays nice with 🤗 Tokenizers (which I assume we'll be using)

#### 3. Focus first on dataset hosting / loading

In principle, a cleaned or processed dataset in 🤗 Datasets is just another dataset, so my suggestion is to first focus on having a good workflow for adding raw datasets and then extending that for whatever downstream analysis is needed.

**Comment by lewtun** [comment]
Datasets that are suitable for hosting on the 🤗 Hub can likely go under this org: https://huggingface.co/OpenAssistant

**Comment by yk** [comment]
> Actually I think we can just use the existing project board and use tags + filters to get a good overview of the datasets.

Yes, that's possible and keeps things organized 👍  you decide whether the existing one or a new board, both are fine, but christoph would have to create the new one.

> 2. Use the 🤗 Datasets library for loading / processing

Fully support! Also, we can start with the hub for hosting. I also agree with first defining the workflow for adding datasets. Do you think the method I mentioned above (i.e. contributors submit PRs with `typer` scripts that download / clean / process the data, along with instructions, e.g. in readmes) is fine?

**Comment by yk** [comment]
@bitplane also look at #324 . I suggested having a few "data admins" that actually upload, and the rest submit their scraping/cleaning/processing/uploading code via PRs to the repo. Could you take a stab at making an example for that?

**Comment by bitplane** [comment]
Yeah this looks like a good solution actually as it keeps the datasets and the code separate. Do we have an idea for an example dataset that's smallish or not too much of a pain to work with so people can experiment with it?

I'm pretty good at scraping in general, but haven't used `datasets`. Any examples of "what a good one looks like" that I can steal as the base?

**Comment by yk** [comment]
> I'm pretty good at scraping in general, but haven't used `datasets`. Any examples of "what a good one looks like" that I can steal as the base?

I'm also not familiar with quality guidelines of datasets, but a common QA dataset is squad (I think it's v2 now). It's fairly standardized and might be a nice candidate to get into our ecosystem.

I'd first get it into the common message-tree format, maybe as jsonline.gz or avro, and then also make it into a "generation" dataset, maybe as parquet, both described in `docs/data_schemas.md`.

Just in case I'm mis-reading something and HF datasets actually has their own file formats, then by all means, use theirs :) whatever is easiest. let's stay pragmatic.

**Comment by lewtun** [comment]
`datasets` uses Apache Arrow under the hood to enable memory mapping, but natively supports loading many formats (JSON, CSV, text, Parquet). I'll add an example as part of https://github.com/LAION-AI/Open-Assistant/pull/324#issuecomment-1370265271
