### ISSUE TITLE
Github Wiki Tab 

### ISSUE THREAD

**Issue by mm12** [LAION-AI/Open-Assistant#1651]
The GitHub Wiki tab says `Open-Chat-GPT`
Also, we should put documentation for things like data-augmentation there instead of in a Google doc like it is on https://projects.laion.ai/Open-Assistant/docs/data/augmentation

**Comment by mm12** [comment]
(like this kind of thing https://github.com/LAION-AI/Open-Assistant/blob/main/openassistant/datasets/README.md )

**Comment by andreaskoepf** [comment]
I have disabled the wiki-feature of this repository for now since it obviously was never used since the inception of this project (and as @mm12 correctly pointed out even still contained a single dummy-page with the old initial "code-name" of this project).

**Comment by andrewm4894** [comment]
I will try and see about ways to pull from readmes that still need to live next to the code but that we might also want to copy over to the docs site, should be able to add the copy as part of a cicd or maybe some prehook thing for docs site, will explore.
