### ISSUE TITLE
Styling & rearranging of information on stats page

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#1655]
With the latest release of the OA website a stats page was added, see https://open-assistant.io/stats
The current page is functional and shows all the numbers but it could benefit from additional styling:

## Here are some ideas:
- show lang tags instead of or additionally to the native language names
- display data in tables (i.e. aligned numbers)
- use a different grouping for the section "Message trees states by language", e.g. by state
- (Charts would also be fantastic.)

The current code for the stats components can be found in [Stats.components.tsx](https://github.com/LAION-AI/Open-Assistant/blob/main/website/src/components/Stats/Stats.components.tsx).

Before the stats page was added we regularly published stats as "text tables" on discord:
![image](https://user-images.githubusercontent.com/9976399/219611297-ab5eb729-752d-4f6d-bd6e-e4efb0caac9c.png)

**Comment by rjmacarthy** [comment]
What do we think of using https://react-chartjs-2.js.org/? I've been messing around a little and have managed to render some pie and doughnut charts from the data, if acceptable I can make a PR for it.

![charts](https://user-images.githubusercontent.com/5537428/219617005-c442504d-75f2-48b5-8051-83a4f8d6866d.png)

**Comment by GuilleHoardings** [comment]
Your proposal looks amazing, @rjmacarthy!

However, I think that showing also numbers could be useful. I have been working in a table for "Message trees states by language". It looks like this:

![image](https://user-images.githubusercontent.com/19565386/219619406-4c94afc0-27a4-43f6-b612-f74a4c6fd009.png)

I think it makes it easier to compare different languages.

Maybe we could mix the two approaches. Do you think is worthy?

**Comment by rjmacarthy** [comment]
@GuilleHoardings yes I think your approach for the states by languages makes sense as a table.  If acceptable you could simply copy/rebase the code from my branch into yours and apply the table for the last stat. 
 Here is the code for the charts: https://github.com/rjmacarthy/Open-Assistant/tree/feature/stats-charts

**Comment by GuilleHoardings** [comment]
I won't be able to work in it until this evening. If you want to go ahead and do the pull request, I can add the table once it is merged.

**Comment by andreaskoepf** [comment]
@rjmacarthy @GuilleHoardings A combined approach of tabular data + charts would be fantastic!

**Comment by horribleCodes** [comment]
While you're at it, sort the different tags per language in a fashion that makes sense chronologically. So maybe something like this:

`Prompt Lottery Waiting > Initial Prompt Review > Growing > Ranking > Ready for Export > Total Active > Total`

The `Halted By Moderator` and `Aborted Low Grade` tags could be put before or after the total, depending on whether they should be included to the total message.

**Comment by GuilleHoardings** [comment]
Good suggestion, @horribleCodes. I'll do it.

**Comment by olliestanley** [comment]
Can this be closed now #1696 is merged?

**Comment by notmd** [comment]
close because the pr is merged
