### ISSUE TITLE
Weirdly formatted text in prompt

### ISSUE THREAD

**Issue by JohannesGaessler** [LAION-AI/Open-Assistant#1657]
Consider the following screenshot:

![Screenshot_20230217_111553](https://user-images.githubusercontent.com/18492268/219616727-4a2d75cb-7cbe-4607-9027-9cf4ccc72de3.png)

Clearly this is a bad way to format text but I don't think anyone would intentionally format it like this. Is there perhaps something going wrong with the new Markdown functionality?

Link to the prompt: https://open-assistant.io/messages/4da581c2-5ec0-424d-934b-1d5fc3c6be58

**Comment by JohannesGaessler** [comment]
Another example of malformed Markdown:

![Screenshot_20230217_120854](https://user-images.githubusercontent.com/18492268/219633717-88dcab18-860e-4675-a22d-a217018b2d27.png)

Link: https://open-assistant.io/messages/715cd006-04d4-434d-87a9-70b6b6203555

**Comment by notmd** [comment]
> Another example of malformed Markdown:
> 
> ![Screenshot_20230217_120854](https://user-images.githubusercontent.com/18492268/219633717-88dcab18-860e-4675-a22d-a217018b2d27.png)
> 
> Link: https://open-assistant.io/messages/715cd006-04d4-434d-87a9-70b6b6203555

Thanks, will be fixed by #1620
