### ISSUE TITLE
Add prominent link to Guidelines pages to web app

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#1663]
A trivial but high-impact change:
Add a prominent link to the [Guidelines](https://projects.laion.ai/Open-Assistant/docs/guides/guidelines) page in the OA web app.

- link in the tab bar on the side
- change the link of every "?"-button of the tasks to the guidelines pages (unless we have better task-specific documentation)

[This is a duplicate of #1320 with a more direct call for action.]

**Comment by CoffeeGeek101** [comment]
@andreaskoepf can you explain the issue. I would like to work it, but didn't understand the point you have listed.

**Comment by andreaskoepf** [comment]
The goal is to make the Guidelines document more accessible for every user. Currently it is "buried" somewhere in the documentation. It can only indirectly be reached.

Sketch for side menu (sorry, I am no designer):
![image](https://user-images.githubusercontent.com/9976399/219696290-013ef4c4-9563-4456-bbd6-a9876afbf19a.png)

**Comment by blankster** [comment]
@andreaskoepf I had to chuckle, yes, SO big should it be 😄 

I think in a not annoying way, it should, it automatically attracts the user's attention, as it really has a big impact and prevents uncertainty (many people do ask about it on Discord) when people find the guidelines.

**Comment by andreaskoepf** [comment]
> SO big should it be

Of course the tab should use the same font-style as the other entries and with a nice docs icon, maybe book or document or similar ..

**Comment by CoffeeGeek101** [comment]
@andreaskoepf okay I think I get the problem we are solving here, I'll set up the project locally and try run it. I'll be reaching out to you if I get any confusion along way.

**Comment by andreaskoepf** [comment]
@CoffeeGeek101 thanks a lot. BTW you can also reach us directly on the OA discord server, just ping ollie, blankster or me.

**Comment by owen-duncan-snobel** [comment]
I went ahead and made the guideline changes @andreaskoepf https://github.com/LAION-AI/Open-Assistant/pull/1757
Let me know if this was alright.
