### ISSUE TITLE
Docker compose up --build returns "no service selected" in Windows

### ISSUE THREAD

**Issue by ArgiesDario** [LAION-AI/Open-Assistant#1665]
Following the steps to get a local env, when running `docker compose up --build` at the root directory of the repository

I'm getting: 
```
time="2023-02-17T11:17:29-03:00" level=warning msg="The \"PWD\" variable is not set. Defaulting to a blank string."
no service selected
```

I'm using:
`Docker version 20.10.22, build 3a2c30b`
`Docker Compose version v2.15.1`
`Docker Desktop 4.16.3 (96739)`
OS: `Windows 11 Pro. Version 10.0.22624 Build 22621`

**Comment by ArgiesDario** [comment]
I tried the same thing using Ubuntu WSL with same result, seems that I'm missing something but couldn't find out what is it, any clue?

**Comment by andreaskoepf** [comment]
Please use: `docker compose --profile ci up --build --attach-dependencies`

**Comment by andrewm4894** [comment]
I will try update the docs to this effect next chance I get.

**Comment by ArgiesDario** [comment]
> Please use: `docker compose --profile ci up --build --attach-dependencies`

Thanks, it work like a charm, I sent a PR for it: https://github.com/LAION-AI/Open-Assistant/pull/1676, feel free to review it

The only place I found this exact line was in the main README

**Comment by IonMich** [comment]
I think the same change is needed in the documentation of `.devcontainer`.

**Comment by squirdev** [comment]
Thanks it works fine
