### ISSUE TITLE
Add FAQ Link to the Footer

### ISSUE THREAD

**Issue by blankster** [LAION-AI/Open-Assistant#1667]
We have a good collection of answers for frequently asked questions (which are getting optimized #1579 - feedback/help is welcome here). However, finding these answers can be a challenge. If a user can easily locate the FAQs, it will benefit them and help moderators avoid repeating the same answers.

Since people typically don't proactively search for information, but instead find exploratory or need-driven information, I suggest including a link to the FAQs in the footer since they are currently difficult to find, and there is sufficient space in the footer.

![image](https://user-images.githubusercontent.com/1443109/219694849-db19416c-6331-4174-9210-24f97125d62a.png)

Internally, we have discussed whether the guidelines should also be included. In my opinion, they should be, but not as a replacement for another link, rather as a supplement.

In my "perfect world", the footer would look like this: Docs, Guidelines, FAQ. At the very least, Docs and FAQ should be included to increase the likelihood that users find the FAQ.

**Comment by blankster** [comment]
Meant as extension (not replacement) to #1663

**Comment by andreaskoepf** [comment]
The href for the link should be: https://projects.laion.ai/Open-Assistant/docs/faq

**Comment by ArgiesDario** [comment]
Bear in mind that there is a different type of fotter in the landing page when there is no user logged in

In https://open-assistant.io/
![image](https://user-images.githubusercontent.com/7121037/219782494-20ef3632-6a8f-4ac5-b9ec-a4b307f31bb0.png)

Should the FAQ go in the 'About' column, below 'Docs' ?

**Comment by ArgiesDario** [comment]
Assuming the answear of previous question is yes, I sent a PR to add FAQ in both screens

![image](https://user-images.githubusercontent.com/7121037/219828642-1d7a4291-1e38-4b8c-876a-82a209e0fcb3.png)

![image](https://user-images.githubusercontent.com/7121037/219828657-6a58e6ba-4a31-4da2-8c50-e643a51974c5.png)

Feel free to review it

**Comment by blankster** [comment]
@ArgiesDario as far as I can rate it, that looks exactly how it should be :) Thanks!
