### ISSUE TITLE
Total stats lower than lasts month stats

### ISSUE THREAD

**Issue by nadavMihov** [LAION-AI/Open-Assistant#1669]
I went into my account page and the total stats were less than last's month stats.
![image](https://user-images.githubusercontent.com/82936591/219696416-b4aca415-fded-4a44-9299-619f52a5233c.png)
Maybe it happened because I got dislikes before the latest month? But the lables count is also wrong.

**Comment by andreaskoepf** [comment]
If you look in the footer of the https://open-assistant.io/de/leaderboard you see when the stats were last calculated/updated. 

Current default settings are:
```
    USER_STATS_INTERVAL_DAY: int = 5  # minutes
    USER_STATS_INTERVAL_WEEK: int = 15  # minutes
    USER_STATS_INTERVAL_MONTH: int = 60  # minutes
    USER_STATS_INTERVAL_TOTAL: int = 240  # minutes
```
