### ISSUE TITLE
Ranking assistant replies bug - a reply is too big

### ISSUE THREAD

**Issue by nadavMihov** [LAION-AI/Open-Assistant#1685]
Hello,
I was ranking some assistant reply when I came across a reply so wide it wouln't let me place it at the top if it was in the bottom before (and vice versa). 
![image](https://user-images.githubusercontent.com/82936591/219733733-0a8293d5-1999-4533-b9ff-a743fdc9304e.png)
This only happens if the reply is first or last, If it's in the middle I can move it anywhere.

**Comment by JohannesGaessler** [comment]
Workaround: I was always able to move the smaller messages instead of the larger one.

**Comment by owen-duncan-snobel** [comment]
I am taking a stab at this

**Comment by owen-duncan-snobel** [comment]
@andreaskoepf I figured out what was causing it. The Sortable items were bound to stay in the parent container when dragged/sorted. If I disable it you can see it works. Let me know if disabling it is fine the only "issue" is if someone drags it to the top of the screen it just looks slightly ugly until you let go and it snaps back.

https://user-images.githubusercontent.com/43126781/220173473-3f2fb064-0dd1-4759-91b7-e44086cabf4f.mov
