### ISSUE TITLE
Add shortcuts for basic markdown, same as in github edit page

### ISSUE THREAD

**Issue by complynx** [LAION-AI/Open-Assistant#1689]
Here, in  gh, when you send text, you have preview tab and a bunch of buttons to help you out. Not everyone can get that you can do md formatting in the text

**Comment by notmd** [comment]
for anyone who want to implement this here is a few packages I found
[https://github.com/bytedance/bytemd](https://github.com/bytedance/bytemd)
[https://github.com/uiwjs/react-md-editor](https://github.com/uiwjs/react-md-editor)
