### ISSUE TITLE
Unresponisive change of language

### ISSUE THREAD

**Issue by LeandroCaniglia** [LAION-AI/Open-Assistant#1692]
I usually work on Spanish. However, today I switched to English and then I was unable to switch back to Spanish.

**Comment by ArgiesDario** [comment]
hi @LeandroCaniglia, I was trying to reproduce your error but had no luck, switching between English and Spanish seems to be working fine for me. Do you remember in which url you were when this happened? Which browser are you using?

**Comment by LeandroCaniglia** [comment]
The misbehavior is erratic, therefore not a big deal (my initial assumption
was different). Most of the times, switching between English and Spanish
works as expected. And when it fails, switching back and forth a couple of
times solves the issue. It just failed to me a minute ago and now is
working. If I can find a reproducible pattern, I'll let you know.

I'm using Firefox 110.0 (64-bit)


---

¿Qué pasó con Santiago Maldonado?

Pista: “*Gustavo Lleral. Lo nombramos nosotros. Está bien. Serio. Ya
tuvimos contactos. Mahiques va a verlo el lunes*” - Del celular de Darío
Nieto (en comunicación con Macri)

---
leandro caniglia ph.d. | president | *FAST *| fundacion argentina de
smalltalk
http://www.fast.org.ar
