### ISSUE TITLE
Dots menu popup created inside owning element

### ISSUE THREAD

**Issue by bitplane** [LAION-AI/Open-Assistant#1698]
In today's deployment, the pop-up dots menu is kinda borked, breaks the text, isn't usable with short messages:

https://user-images.githubusercontent.com/273059/219822141-00b46f41-242d-43c9-8d6b-b99de12eca41.mp4

**Comment by notmd** [comment]
related change #1684

**Comment by mm12** [comment]
Was about to put a bug in for this, good to see it is already here.
