### ISSUE TITLE
Front bug when clicking in menu button

### ISSUE THREAD

**Issue by VictorLG98** [LAION-AI/Open-Assistant#1704]
I just found this bug, when I click on the menu button, the front end goes crazy and doesn't show the text boxes properly. It happens every time I click.

![image](https://user-images.githubusercontent.com/68274609/219856106-7e05cbd6-f0c6-411b-973b-ef671250429e.png)

I have tried clearing the cache  and restarting session but it keeps happening. I am using Google Chrome...

**Comment by VictorLG98** [comment]
It's like the box that opens when you click on the 3 dots doesn't overlap the message box.
This can be a good first issue for someone

**Comment by jentrialgo** [comment]
Duplicated #1698
