### ISSUE TITLE
Letterbox Data source

### ISSUE THREAD

**Issue by VictorLG98** [LAION-AI/Open-Assistant#1705]
I was wondering if letterbox could be a good source for creating a Q/A dataset. My idea is to scrape this https://letterboxd.com/films/popular/ like:
**Q: Can you make a brief summary about the film {film}?**
**A: In his second year of fighting crime, Batman uncovers corruption in Gotham City...**

Let me know if this is a good idea and what are the steps to be followed

**Comment by bitplane** [comment]
Looks like they use themoviedb for data, who explicitly forbid derived works:

https://www.themoviedb.org/terms-of-use

But you could get the popular film names, look them up on Wikipedia and use Wikipedia's data which is shared under an open license.
