### ISSUE TITLE
Japanese language removed by error

### ISSUE THREAD

**Issue by GuilleHoardings** [LAION-AI/Open-Assistant#1706]
If I'm not mistaken, [this commit](https://github.com/LAION-AI/Open-Assistant/commit/b1726d9312627962815b8643f94e9073c1ece697) removed the Japanese language from the language selector. I think it's an error. I'll create a pull request to fix it.

**Comment by GuilleHoardings** [comment]
I see now that it was not a mistake, because in the commit message it says "japanese localisation not available yet". However, I think that big languages are supposed to be in the language selector even when the interface is not localized. In addition, there are already many Japanese messages.

**Comment by andreaskoepf** [comment]
Probably @lejayekaye didn’t know what he/she was doing. Japanese must be re-added as soon as possible. I informed the web-team that we need to do more scrutiny in the future - the PR had not have been merged.
