### ISSUE TITLE
Comments in code are interpreted as titles when not code is not marked as markdown 

### ISSUE THREAD

**Issue by GuilleHoardings** [LAION-AI/Open-Assistant#1708]
Now that the messages interpret markdown, when there's text in a programming language like python that uses `#` for comments and the code was not marked as a code block, the line is interpreted as a title and the appearance is broken. [Example](https://open-assistant.io/es/messages/7ad5771e-965b-4a96-b774-a97b9fd7c9fa):

![image](https://user-images.githubusercontent.com/19565386/219867268-da760a1f-be41-4793-9f08-18d329c188a9.png)

I don't know what would be the solution. Maybe, adding a button to disable markdown on a specific message?

**Comment by notmd** [comment]
That's invalid syntax if you want to render code. You need to wrap it in ```
Example
```python
# comment
print("hello word")
```

**Comment by GuilleHoardings** [comment]
I think that the problem is that, as Markdown was not supported initially and there were no clear guidelines, some people didn't format the code correctly and now their messages look different to when they wrote it. I don't know if, from a data quality point of view, having code without Markdown will cause problems.

Anyway, maybe it's not worth addressing this issue.

**Comment by bitplane** [comment]
It may be worth looking through the data for `# comments` and fixing those. I don't think we lose much by doing that do we?

**Comment by GuilleHoardings** [comment]
Do you mean manually, or having an automated process? Manually seems like too much work, and automatically, seems difficult to find the start and end of the code.

**Comment by bitplane** [comment]
I guess looking through the data when it's out and writing something that will identify how big the issue is.

Another option would be to add "media-type" to the metadata and add "text/markdown" to recent ones and "text/plain" to older ones before the markdown change that have headings in them, and leave the rest ambiguous.
