### ISSUE TITLE
Options menu is hidden.

### ISSUE THREAD

**Issue by lg303** [LAION-AI/Open-Assistant#1712]
The options menu when it is displayed down is hidden, up if it works well.

I don't think it's the browser because it's the same computer and the same browser that I've been using on the page for a week or two. Maybe for an update but the rest on the computer and in the browser works fine.

Although it may only be on this computer, I wanted to let you know in case the same thing happens to other people.

Thank you for your time.

ERROR:
![imagen](https://user-images.githubusercontent.com/93588712/219872152-3f251e28-54a7-43ad-8a18-aa80429a06b5.png)

OK:
![imagen](https://user-images.githubusercontent.com/93588712/219872196-495c496e-c2be-481c-8920-82fcd9ccff07.png)

=============================================================================

Original text:
Menu de opciones se oculta.

El menu de opciones cuando se despliega hacia abajo se oculta , hacia arriba si funciona bien.

No creo que sea el navegador por que es la misma computadora y el mismo navegador que uso en la pagina desde hace una o dos semanas. Quizas por una actualizacion pero lo demas en computador y en el navegador funciona bien.

Aunque puede ser solo en este computador queria avisarles por si a otras personas les sucede lo mismo.

Gracias por su atencion.

**Comment by notmd** [comment]
Duplicate of #1698
