### ISSUE TITLE
Gamification: Score Affected by Recent Changes Backwardly?

### ISSUE THREAD

**Issue by blankster** [LAION-AI/Open-Assistant#1713]
Multiple users in the general discussion channel on discord are reporting that their existing score seems to be lowered (see https://discord.com/channels/1055935572465700980/1055935573371658252/1076505610738221118 ) and I can also confirm this to a smaller degree.

Were these changes in existing scores affected by changes like https://github.com/LAION-AI/Open-Assistant/issues/1659#issuecomment-1434505810 or has this other origins?

I'm raising this issue to prevent that recent changes affecting unintentional, the historical scoring. If it's intentional, it would be nice to have an answer for the community.

In my personal example, I have the feeling that the score was multiple hundreds more and lowering the prompt score could be the origin for this, but I'm not confident with this.

**Comment by andreaskoepf** [comment]
> I'm raising this issue to prevent that recent changes affecting unintentional, the historical scoring. If it's intentional, it would be nice to have an answer for the community.

There is no "historical" scoring, the query is evaluated each time over the whole relevant part of the database. I reduced the value of initial prompts by factor 10x as a reaction to https://github.com/LAION-AI/Open-Assistant/issues/1659. The change in scoring affects all users in the same way, old and new users ...

**Comment by blankster** [comment]
Thanks for the explanation, for me, that's convincing and absolutely ok - and it sets the right incentives.

For me, this issue can be closed, we can still reference to it.
