### ISSUE TITLE
Messages in message tab can still be too wide for some reason

### ISSUE THREAD

**Issue by JohannesGaessler** [LAION-AI/Open-Assistant#1717]
Consider the following screenshot:

![Screenshot_20230218_192444](https://user-images.githubusercontent.com/18492268/219882413-4f229bf1-c171-4de0-acfa-373008ccc133.png)

One of the messages on the left extends too far to the right.
Link: https://open-assistant.io/messages/2ac0f50b-087f-45e4-824a-ed9ce3e70c62

**Comment by JohannesGaessler** [comment]
This only occurred to me after I already made the issue, but since I reported a very similar issue just yesterday, should I have waited longer to ensure that the current codebase has already been deployed?

**Comment by notmd** [comment]
should be fixed by #1715
