### ISSUE TITLE
Feature suggestion: For a given set of assistant answers to a prompt, let the users generate a synthesized compund answer

### ISSUE THREAD

**Issue by michaelbogdan** [LAION-AI/Open-Assistant#1718]
This might be useful for two things:

1. Sometimes after answering a prompt myself, I see several other answers touching on points I missed in my own answer. Or I see a style better suited to the prompt, but factually wrong. In any case, a compound answer synthesizes the best parts of all assistant answers and might provide even better examples of good answers than any one human could provide.
2. The combination of answers before compunding and the compund answers might be used to train a model that samples the possible answers an LLM might give to a prompt and then synthesizes a compund answer to use in training either the reward model or the LLM itself.

**Comment by olliestanley** [comment]
I think this is covered by message editing issue
