### ISSUE TITLE
Show error message and retry when submitting tasks

### ISSUE THREAD

**Issue by notmd** [LAION-AI/Open-Assistant#1723]
https://github.com/LAION-AI/Open-Assistant/blob/4ab4821b05ba85a1d85bd6d94773cd0f0e5c452d/website/src/hooks/tasks/useGenericTaskAPI.tsx#L42

we should handle all kinds of errors instead of showing the NONE_AVAILABLE state. Maybe trigger a toast to let the user know or something.

**Comment by andreaskoepf** [comment]
The possibility to retry message submission in case of an error would also be very helpful to prevent loss of work when users submit assistant replies while the server is temporarily not reachable (e.g. during updates).
