### ISSUE TITLE
Website UI: Tree: Author bubble cut off 

### ISSUE THREAD

**Issue by mm12** [LAION-AI/Open-Assistant#1725]
Issue observed on message: https://open-assistant.io/messages/6c899c17-7616-47c0-89c6-f80bce031475
Screenshot of issue: 
<img width="764" alt="Screen Shot 2023-02-18 at 2 51 27PM" src="https://user-images.githubusercontent.com/5874051/219898974-48a0d11c-053b-49ae-8485-2a3b43aa1a6c.png">
Browser:  `Chrome 112.0.5602.2`

**Comment by notmd** [comment]
What do you mean "author bubble cut off"? The screenshot still seems correct to me.
