### ISSUE TITLE
Suggest edits to posts

### ISSUE THREAD

**Issue by complynx** [LAION-AI/Open-Assistant#1729]
Some posts are good content-wise, but bad either grammatically or in style. Would be great to introduce a layer of rating and filtering based on suggested design changes of the posts.

**Comment by michaelbogdan** [comment]
Related #1718. The suggested edit is valuable training data as it can teach the assistant how to synthesize bad input from the user into higher quality output while retaining content and overall structure.

**Comment by olliestanley** [comment]
Related: #1005 #1126

**Comment by olliestanley** [comment]
Going to close this as covered by #1542 which is being worked on
