### ISSUE TITLE
Add a description to the github repository

### ISSUE THREAD

**Issue by AbdBarho** [LAION-AI/Open-Assistant#173]
This should make the project easier to find through github search and such.

![Screenshot 2022-12-30 094527](https://user-images.githubusercontent.com/24505302/210051683-961f7f8e-b1be-4141-bc3e-e112d83ef2f6.jpg)

**Comment by Nil-Andreu** [comment]
What about:
"Revolutionary chat based language model for extraordinary conversations."

**Comment by yk** [comment]
> "Revolutionary chat based language model for extraordinary conversations."

very market-y ;) I'll go with the statement from the roadmap so far, but open to ideas

**Comment by yk** [comment]
done
