### ISSUE TITLE
View stats page when logged out

### ISSUE THREAD

**Issue by someone13574** [LAION-AI/Open-Assistant#1742]
Currently you are unable to view the statistics page at `https://open-assistant.io/stats.` when not logged in and it would be beneficial to be able to do so.

**Comment by bitplane** [comment]
Should this apply to other pages in general? Like we can't view individual messages without signing in.

**Comment by someone13574** [comment]
Ideally any pages that contain useful information that doesn't depend on user action should be visible. That would include the statistics, recent messages, leader board, and message tree pages with any information or actions that require the user to be logged in (reactions, user messages, user statistics) disabled.

**Comment by michaelbogdan** [comment]
On the other hand, if someone is using this to host as a private instance they might not want just about anyone to snoop around. So consider adding a global flag for this kind of stuff.

**Comment by andreaskoepf** [comment]
> Should this apply to other pages in general? Like we can't view individual messages without signing in.

For messages this requires changes since emoji-responses require a registered user, i.e. they would have to become read-only and several commands in the ".." menu need to be disabled/removed.

**Comment by blankster** [comment]
Something I would recommend considering: There is also the potential that some people abuse their username to push "problematic messages"/advertisement over a publicly available board. I saw unluckily usernames like "Heil *****" and similar.
