### ISSUE TITLE
CSS styling for docs pages

### ISSUE THREAD

**Issue by bitplane** [LAION-AI/Open-Assistant#1751]
The FAQ page where it's standard <h>eadings doesn't look so nice, it's just bold and font sizes. IMO it could do with a bit of style from someone who is good at making this sort of thing look pretty:

https://projects.laion.ai/Open-Assistant/docs/faq

![image](https://user-images.githubusercontent.com/273059/219994246-c2f15e09-1261-46d8-ac08-81010aceee0d.png)

**Comment by CaglayanCaliskan** [comment]
I would like to contribute.

**Comment by JoLalo** [comment]
I would like to contribute

**Comment by cuevantn** [comment]
I would like to contibute too. Here's my proposal:

![Animation](https://user-images.githubusercontent.com/83598208/221273550-26990c43-f117-4702-86b9-05e64dc4a2f7.gif).

**Comment by andrewm4894** [comment]
done here! thanks @cuevantn 

https://github.com/LAION-AI/Open-Assistant/pull/1850
