### ISSUE TITLE
Someone is heavily spamming German prompts

### ISSUE THREAD

**Issue by Markus40** [LAION-AI/Open-Assistant#1753]
Someone is autogenerating terrible prompts. A large proportion of the initial prompts are spam.
I keep seeing very similar initial prompts with the keywords:
- Erotik
- menschliche Bewusstheit
- Psychologie
- Emotion
- Kreativität
- Welche Auswirkungen hat
- Führungsqualität
- Spiritualität
- miteinander in Verbindung gebracht werden?

**Comment by GuilleHoardings** [comment]
Could you provide the message id of some example? You can get it by clicking in the three dots of a message.

**Comment by andreaskoepf** [comment]
Most people "spamming" prompts are not aware of two things:

1. Users cannot increase the likelihood of their own prompts by submitting many prompts, e.g. the prompt-lottery draws among distinct authors uniformly.
2. If a user is banned all of their prompts will be deactivated and nobody will ever see them.

Beside from that the question is mainly if the prompts are reasonable/useful/realistic prompts or actually spam.

**Comment by Markus40** [comment]
@GuilleHoardings 

Definitely spam:
https://open-assistant.io/de/messages/5e19e093-ddec-4e95-af3f-3b8e6c20a4ed
https://open-assistant.io/de/messages/9c318344-475c-466e-9ca5-699505942964
https://open-assistant.io/de/messages/a5a050ae-e7cd-47cf-a4a2-99cb256846b1
https://open-assistant.io/de/messages/de106b05-5d1e-4f51-a088-d001643f65ea
https://open-assistant.io/de/messages/ee339262-b393-4197-98b2-9332d6183af7

Maybe spam:
https://open-assistant.io/de/messages/99fbd0ef-dd53-48b5-a2a9-46e53050079d
https://open-assistant.io/de/messages/5878523c-a1a9-4299-93d1-8f18c7549fdb
https://open-assistant.io/de/messages/255a82e8-acd7-4be0-979b-7519c55f40f8
https://open-assistant.io/de/messages/67d6e562-601a-4cf7-983c-19b4c73a022c
https://open-assistant.io/de/messages/afa11819-9236-4308-8fc5-8e587d3ca29e
https://open-assistant.io/de/messages/11ebfd10-5063-46a3-8870-6a2660bb414f
https://open-assistant.io/de/messages/2236d460-2c8a-45c2-9f67-d8bfba8ee1d4

**Comment by Markus40** [comment]
@andreaskoepf

That may be true if the contributions are reasonably good. It's a problem when users then have to work their way through endless, similar, stupid prompts. That kills any fun this thing could have. One of the main tasks of this project is to keep users engaged.

**Comment by GuilleHoardings** [comment]
We have contacted the user and we are trying to fix the problem. Thank you for the report.

**Comment by olliestanley** [comment]
This user is currently disabled so the problem should be resolved.
