### ISSUE TITLE
UX: Remove Optional Message When Skipping

### ISSUE THREAD

**Issue by blankster** [LAION-AI/Open-Assistant#1756]
Every time the skip function is used, the option to leave a message is offered.

![image](https://user-images.githubusercontent.com/1443109/220050564-9e70b684-84a8-4d2c-bdc5-be9618ac9e98.png)

Quite often this was discussed on Discord and found to be unnecessary.

Therefore, I suggest that this message/input option is removed or at least disabled to improve the user experience. 

It has high impact and should require low efforts to implement the change.

**Comment by Mekacher-Anis** [comment]
this one annoys me too XD I can work on it

**Comment by Mekacher-Anis** [comment]
should the `reason` for the skip be removed from the backend too? or should we just send a placeholder / empty string?

**Comment by andreaskoepf** [comment]
> should the `reason` for the skip be removed from the backend too? or should we just send a placeholder / empty string?

I'll make quick change that makes the skip-reason option .. so that the frontend no longer does have to send it.

**Comment by blankster** [comment]
Thanks for this, that's such an improved UX :)
