### ISSUE TITLE
Reducing Initial Prompts: Optimization of I'm feeling lucky

### ISSUE THREAD

**Issue by blankster** [LAION-AI/Open-Assistant#1758]
Currently, we have a huge backlog of "Initial Prompts", but would need the help of the users, especially in other places instead of new Initial Prompts.

Since many users use the "I'm feeling lucky" feature, possibly, they will automatically get to the option to create a new initial prompt, which we currently don't want - especially if it is "enforced" automatically.

I therefore suggest to disable initial prompts in the "I'm feeling lucky" function. If someone wants to capture one, he can still use the function directly, but should not automatically be led in this direction as well.

**Comment by jwstolk** [comment]
The backlog contains a lot of not-very-creative prompts. (IMHO, i.e: super wide general questions without the prompter indicating what his situation is, what he is trying to do or what area he is interested in.) A wider variety of users should result in more creative prompts, so maybe reduce it, but not to zero.

**Comment by andreaskoepf** [comment]
> I therefore suggest to disable initial prompts in the "I'm feeling lucky" function.

The currently running system balances tasks according to availability and weighting and initial prompts currently have a weight of 1, see https://github.com/LAION-AI/Open-Assistant/blob/ef2d67cf99e5d3390e3a8fecb4c5587929326e17/backend/oasst_backend/tree_manager.py#L183-L196

Initial prompts are still valuable for us - even if they never enter the human feedback tree building process. We can use them as prompts for synthetic outputs and to create a topic map.
