### ISSUE TITLE
Trollboard: Option to Hide Banned Users

### ISSUE THREAD

**Issue by blankster** [LAION-AI/Open-Assistant#1759]
The moderator team as well as the "spam" volume is getting bigger and bigger. To collaborate nicely together and to prevent spam/unwanted entries and inefficient overhead in collaboration, I would appreciate it if the already banned users could (optionally) be hidden on the troll board. 

This would allow a quick overview of critical users on the trollboard, instead of a view that is polluted by already banned users, and makes early detection of problematic users more difficult because this way all moderators have to go through all users again and again to evaluate whether someone is banned or not.

Early detection is important to avoid wasting the time of constructive community members and moderators.

**Comment by ArgiesDario** [comment]
Hi, just to get a clear picture of this request, I created a "megatroll" user, which ends in the Trollboard cause negative votes on his post

![image](https://user-images.githubusercontent.com/7121037/220150791-700a1304-4502-4ccb-a326-41cea877cbe3.png)

So if this user gets its Role changed to "banned"

![image](https://user-images.githubusercontent.com/7121037/220151054-92f654da-0aba-47b4-8260-e0530c405a0a.png)

We should not longer see him in the Trollboard list

Is that correct?

**Comment by andreaskoepf** [comment]
I added the necessary backend changes here: https://github.com/LAION-AI/Open-Assistant/pull/1765 You can add  `enabled=true` to the trollboards query to only retrieve enabled users, don't include send the query param to return all users and set it to false to only return disabled users. I think in the front-end it would be best to have a checkbox to toggle the filter option.

**Comment by blankster** [comment]
@ArgiesDario I was also thinking about a checkbox or something like that. To have the option to choose this, but not being forced to never see the banned users again. Both views can have their advantages while moderation.

**Comment by ArgiesDario** [comment]
> I added the necessary backend changes here: #1765 You can add `enabled=true` to the trollboards query to only retrieve enabled users, don't include send the query param to return all users and set it to false to only return disabled users. I think in the front-end it would be best to have a checkbox to toggle the filter option.

I was trying to make your endpoint work for a while, but it seems to be ignoring the enabled query param, still getting `"enabled": false` users as response

![image](https://user-images.githubusercontent.com/7121037/220247336-84fd8f66-ba3e-484b-92ab-b89cd7f9c44a.png)

If I hardcode your line 17 in trollboards.py from `enabled: Optional[bool] = None` to `enabled: Optional[bool] = True` it works as expected, so it seems to be some related to the get query params. Am I missing something?

**Comment by andreaskoepf** [comment]
> I was trying to make your endpoint work for a while, but it seems to be ignoring the enabled query param, still getting `"enabled": false` users as response

It seems you are running requests against the frontend-webserver, but the correct backend-url is `/api/v1/trollboards/{time_frame}` e.g. if you start the local dev setup it would be something like `http://localhost:8080/api/v1/trollboards/day?max_count=100&enabled=true` ... you need to add the enabled query param here: https://github.com/LAION-AI/Open-Assistant/blob/5982b1b0411a3a261d374d3aea642966123e1f76/website/src/lib/oasst_api_client.ts#L392-L396

**Comment by ArgiesDario** [comment]
@andreaskoepf thanks!👍, I'm still learning how the project works

It is working now. I added a radio button that allows to show active/enabled users (this option is the default one), and other radio that only shows banned users.

Enabled radio is green, banned is red. Here some screenshots on how it looks:

Dummy User is an active user
![imagen](https://user-images.githubusercontent.com/7121037/220436568-419a882b-ae28-4c86-bdc0-1f2b525cdfd1.png)

Megatroll is a banned user
![imagen](https://user-images.githubusercontent.com/7121037/220437009-b5780e70-c599-4aab-8616-5c0d544fd767.png)

This is how it looks with white background and spanish translations
![imagen](https://user-images.githubusercontent.com/7121037/220437163-f737aa74-56c8-43b6-9ff9-05170d66b27e.png)

I'll be sending the PR soon

**Comment by blankster** [comment]
@ArgiesDario I can't thank you enough for this, that's super helpful :)
