### ISSUE TITLE
Ability to Delete Messages From the List View in User Detail View

### ISSUE THREAD

**Issue by blankster** [LAION-AI/Open-Assistant#1768]
Currently, it's not possible to delete a message from the list view that shows the available messages of a user:

![image](https://user-images.githubusercontent.com/1443109/220166855-d404fc73-f293-4830-afff-01fc1a586329.png)

A direct action to delete the message would be useful to optimize the moderator's UX and efficiency. It could be placed next to the view action and should need a confirmation to prevent miss-clicks/unwanted deletion of messages.

**Comment by ekp1k80** [comment]
Hello, i could do it. This would be my first issue so i would need to know the container or components path in the repo and the link to do the setup of the project in my enviroment

**Comment by GuilleHoardings** [comment]
You can follow the instructions of the [README in the website directory](https://github.com/LAION-AI/Open-Assistant/blob/main/website/README.md).

**Comment by blankster** [comment]
That's still something that would be very useful for content moderation when you have to delete stuff in bigger amounts. Whoever tackles this, best thanks in advance!

**Comment by johnflux** [comment]
I can do this

**Comment by johnflux** [comment]
https://github.com/LAION-AI/Open-Assistant/pull/1860
