### ISSUE TITLE
Incorrect url in SFT prompt_dialogue dataset

### ISSUE THREAD

**Issue by maw501** [LAION-AI/Open-Assistant#1769]
As mentioned in #1368 the [url](https://github.com/LAION-AI/Open-Assistant/blob/301ad71555064d7bbd31ab920552d1aff01a3399/model/model_training/custom_datasets/prompt_dialogue.py#L90) to the `prompt_dialogue` dataset is broken. AFAICT the new url is [here](https://github.com/Rallio67/language-model-agents) so we just need to change the link and check we can load the data using the new link(s).

**Comment by bethanyconnolly** [comment]
Hi! I am new here and would like to contribute, can I be assigned this issue?

**Comment by olliestanley** [comment]
> Hi, the links for the datasets were not only wrong but the datasets had been deleted. I have retrieved them through the commit history and I would like to upload them as datasets to the Open-Assistant organisation on HuggingFace to avoid this issue in future. Please can someone approve my request to join on HuggingFace?

I am not sure who is in charge of the HF org. Maybe one of the ML leads @sanagno @theblackcat102?

**Comment by theblackcat102** [comment]
The incorrect url datasets will be removed in the [PR#1793](https://github.com/LAION-AI/Open-Assistant/pull/1793)

**Comment by bethanyconnolly** [comment]
> The incorrect url datasets will be removed in the [PR#1793](https://github.com/LAION-AI/Open-Assistant/pull/1793)

So we don't need these datasets at all any more and we can close this issue?

**Comment by ontocord** [comment]
Rallio moved his data here: https://github.com/LAION-AI/Open-Instruction-Generalist/tree/main/small_instruction_set

Now it's an official LAION-AI dataset. We can pull from here as you wish and have his blessing as well :) @theblackcat102

**Comment by bethanyconnolly** [comment]
> The incorrect url datasets will be removed in the [PR#1793](https://github.com/LAION-AI/Open-Assistant/pull/1793)
We can close this issue because the code containing the urls is removed in the above PR.
