### ISSUE TITLE
Add additional authentication methods to generate JWT on inference server

### ISSUE THREAD

**Issue by olliestanley** [LAION-AI/Open-Assistant#1790]
As #1772 is merged and users exist in the inference server database and can be authenticated via Discord OAuth2, we need to add email authentication. We should also discuss other authentication providers (e.g. GitHub)

Individual additional providers can have their own issues made to split this up further

**Comment by yk** [comment]
I'm always a bit skeptical about email, as you also need spam protection, etc.
other providers sound good, but not urgent
I've added a debug provider that just lets you log in iwth any user

**Comment by olliestanley** [comment]
> I'm always a bit skeptical about email, as you also need spam protection, etc. other providers sound good, but not urgent I've added a debug provider that just lets you log in with any user

I figured as we allow email login for the data collection app we should allow it for inference too, but agree this is non-urgent, more of a nice-to-have to expand accessibility maybe after MVP
