### ISSUE TITLE
Backend docker starts multiple instances of backend

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#18]
When executing `docker compose up` in `scripts/frontend-development` multiple instances of the backend are started as 'workers':

The [tiangolo/uvicorn-gunicorn-fastapi](https://hub.docker.com/r/tiangolo/uvicorn-gunicorn-fastapi) says: "This image has an auto-tuning mechanism included to start a number of worker processes based on the available CPU cores. That way you can just add your code and get high performance automatically, which is useful in simple deployments." ... that's why the [old backend dockerfile](https://github.com/LAION-AI/Open-Assistant/blob/c1ae50d6935a2b4cc27309ca141e92a871f18e8f/backend/backend.dockerfile) was created without this base-image...

```
frontend-development-backend-1  | [2022-12-18 01:10:28 +0000] [1] [INFO] Starting gunicorn 20.1.0
frontend-development-backend-1  | [2022-12-18 01:10:28 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
frontend-development-backend-1  | [2022-12-18 01:10:28 +0000] [1] [INFO] Using worker: uvicorn.workers.UvicornWorker
frontend-development-backend-1  | [2022-12-18 01:10:28 +0000] [7] [INFO] Booting worker with pid: 7
frontend-development-backend-1  | [2022-12-18 01:10:29 +0000] [8] [INFO] Booting worker with pid: 8
frontend-development-backend-1  | [2022-12-18 01:10:29 +0000] [9] [INFO] Booting worker with pid: 9
frontend-development-backend-1  | [2022-12-18 01:10:29 +0000] [10] [INFO] Booting worker with pid: 10
frontend-development-backend-1  | [2022-12-18 01:10:29 +0000] [11] [INFO] Booting worker with pid: 11
frontend-development-backend-1  | [2022-12-18 01:10:29 +0000] [12] [INFO] Booting worker with pid: 12
frontend-development-backend-1  | [2022-12-18 01:10:29 +0000] [13] [INFO] Booting worker with pid: 13
frontend-development-backend-1  | [2022-12-18 01:10:29 +0000] [14] [INFO] Booting worker with pid: 14
(...)
```

**Comment by yk** [comment]
can we adjust the number of workers? otherwise we'll need 1 dockerfile for dev and 1 for prod
