### ISSUE TITLE
Have the colors of the "Message tree states" match

### ISSUE THREAD

**Issue by horribleCodes** [LAION-AI/Open-Assistant#1801]
The new pie charts for the stats look great, but as of right now, both "Message tree states" charts use the same color palette, but assign different colors to the same value. This makes things a little hard to compare - it's especially unfortunate that "Ready to Export" in English is colored gray, which makes it look like an unfavorable state. It looks like the colors are randomly assigned, but can you use the same seed or something like that for all of them?

**Comment by GuilleHoardings** [comment]
@andreaskoepf I will give a try, but I'll be a little busy until the weekend, so I don't when it will be.
