### ISSUE TITLE
Search or see all messages

### ISSUE THREAD

**Issue by JediMaster25** [LAION-AI/Open-Assistant#1809]
I'm forgetting my initial prompts, and I don't want to start repeating myself.

In the messages tab there could be a way to see all my messages, not just the recent ones.

I think it would be better to avoid the same initial prompts from other people as well but I don't really know how it works so I may be wrong. That would require search which is more complex.

So a question while I'm at it. Should I worry about repeating myself or it doesn't matter?

I could have written down my prompts to search before submitting a new one but I didn't think about it before.

**Comment by andreaskoepf** [comment]
The backend API supports browsing of the full dataset ordered by creation_date of the initial prompts. Additional search could for example be realized (independently) by leveraging the message-embeddings & https://github.com/facebookresearch/faiss
For background calculation of message embeddings via HF the [Celery PR](https://github.com/LAION-AI/Open-Assistant/pull/1754) needs to be merged.

**Comment by JediMaster25** [comment]
Sounds like a good idea. It's a bit more complex than I was looking for but it works for me. It won't be helpful to most other people though.

Closing as #1812 expresses this issue better.

**Comment by johnflux** [comment]
I'm working on a fix for this
