### ISSUE TITLE
Allow to copy raw message content

### ISSUE THREAD

**Issue by notmd** [LAION-AI/Open-Assistant#1815]
Add an item in `MessageActions` component to allow copy raw message content

**Comment by CheckMC** [comment]
I'd like to work on this one

**Comment by CheckMC** [comment]
Do I need to provide translations for each language? Or should I leave it in English for now?

**Comment by notmd** [comment]
> Do I need to provide translations for each language? Or should I leave it in English for now?

English is enough for now

**Comment by CheckMC** [comment]
@notmd, can you mark this as finished?
