### ISSUE TITLE
I'm feeling lucky, possible bug

### ISSUE THREAD

**Issue by Jeremias-Roma** [LAION-AI/Open-Assistant#1820]
Classify the assistant's response, they are different from the random task mode, and select the specific task.
----------------------------------------------------------
![image](https://user-images.githubusercontent.com/89226758/220989934-00d4b49d-1ec1-481d-a1f3-ef58e3181f28.png)
----------------------------------------------------------
----------------------------------------------------------
![image](https://user-images.githubusercontent.com/89226758/220989949-ed14eb08-31d6-446a-90f7-a525b833928f.png)

**Comment by notmd** [comment]
Probably works as intended. The first pic is a full label task and the second one is a simple label task. Those are different

**Comment by Jeremias-Roma** [comment]
I had it in mind, but, the title and description of the tasks are the same, and the difference is that the "quick classify", can only be accessed through the random system, it seems to me that they may have forgotten to standardize the version in random mode.
