### ISSUE TITLE
Add a new window symbol to the guidlines tab

### ISSUE THREAD

**Issue by nadavMihov** [LAION-AI/Open-Assistant#1821]
Currently the "Guidelines" tab is opening another web page but it is not clear because the other tabs are in the same page. Can you add ![image](https://user-images.githubusercontent.com/82936591/220997051-33667896-fd7c-47a9-8294-669541029f3a.png) symbol to it?

**Comment by ArgiesDario** [comment]
Just for the record, this is the icon: https://lucide.dev/?search=external-link
