### ISSUE TITLE
What is the official communication channel?

### ISSUE THREAD

**Issue by markcheeky** [LAION-AI/Open-Assistant#183]
Materials and readme mention multiple:
- yk discord server / open-assistant
- laion discord server / open-chat-gpt-project-coordination
- Open Assistant discord server

What is the purpose of these? Is the last one the "official" channel?

**Comment by yk** [comment]
For contributors, the OA discord is the main place.
For the public, laion is right now probably the best place, we'll have to improve that and probably have a public section in the OA discord

**Comment by yk** [comment]
Closing this, I've adjusted the readme
