### ISSUE TITLE
Load font using `next/font`

### ISSUE THREAD

**Issue by notmd** [LAION-AI/Open-Assistant#1832]
https://github.com/LAION-AI/Open-Assistant/blob/d897be935706fde223b0283ce198c501a329f29a/website/src/styles/globals.css#L11
We are loading font in CSS but using [next/font](https://nextjs.org/docs/basic-features/font-optimization) will improve a lot loading performance

**Comment by CheckMC** [comment]
I can work on this one

**Comment by notmd** [comment]
@CheckMC thanks, it's yours!

**Comment by spencerwmiles** [comment]
@notmd I'll take this if @CheckMC is no longer interested!
