### ISSUE TITLE
Unused pickle file in QA generator notebook?

### ISSUE THREAD

**Issue by horribleCodes** [LAION-AI/Open-Assistant#1834]
https://github.com/LAION-AI/Open-Assistant/blob/d897be935706fde223b0283ce198c501a329f29a/notebooks/closed-book-qa/T5_closed_book_QA_generators.py#L84

Is it me, or is the data read from the pickle file never actually used in this script? I'm currently rewriting it as a proper notebook file, and I'm wondering if the `objects`-variable was supposed to be assigned to the `paragraphs`-variable. I don't have a valid pickle file, so I can't test it.

**Comment by bitplane** [comment]
Nope, it's not used. I guess it's supposed to contain paragraphs.

side note: death to pickles! they're unsafe, can execute arbitrary code and seeing them outside of /tmp makes me unreasonably angry. :joy:

**Comment by horribleCodes** [comment]
Apparently this script is an older version and hasn't really been cleaned up for anyone to use. I'm working on a revised Notebook version.
