### ISSUE TITLE
Add tag 'potentially copyrighted'. 

### ISSUE THREAD

**Issue by kpoeppel** [LAION-AI/Open-Assistant#1841]
I found one prompt containing potentially copyrighted text (it copied a recipe from a website).
There are probably many more instances.
So there should be an additional tag 'potentially copyrighted'. (or feel free to suggest a better name)

**Comment by horribleCodes** [comment]
In the case of recipes, they usually fall outside of copyright protection. From the U.S. Register of Copyright:

> Copyright law does not protect recipes that are mere listings of ingredients[...] Copyright protection may, however, extend to substantial literary expression—a description, explanation, or illustration, for example—that accompanies a recipe or formula or to a combination of recipes, as in a cookbook.

So if a recipe only lists ingredients and steps without much embellishments, they can be freely copied. Not sure if there are actual instances of copyright infringement, though.

**Comment by kpoeppel** [comment]
In this specific case it included a whole description, how it can be used and a detailed explanation. So I would be cautious here.

**Comment by jwstolk** [comment]
I even found a prompt with a copyright notice in the prompt (it was the copyright page from a printed book). I just flagged it as "likely copyrighted". For me this has been rare enough to not need a separate tag.
