### ISSUE TITLE
Sticky Navbar in App

### ISSUE THREAD

**Issue by cuevantn** [LAION-AI/Open-Assistant#1853]
I'd like to make the navbar of the app sticky, just like in the docs:

Sticky:
![sticky-1](https://user-images.githubusercontent.com/83598208/221305109-decd6610-dc7a-4dba-9ecb-209eb25f2b01.gif)

Not sticky:
![sticky-0](https://user-images.githubusercontent.com/83598208/221305091-985afa06-95e9-40b3-b461-4ff97ef792ef.gif)

I would like to contribute with that.

**Comment by olliestanley** [comment]
This seems like a useful change, I have assigned you to this ticket

**Comment by notmd** [comment]
fixed in #1823
