### ISSUE TITLE
Allow jumping directly to hightlighted message in /messages/${id}

### ISSUE THREAD

**Issue by notmd** [LAION-AI/Open-Assistant#1870]
- Render additional id attribute. Maybe something like this is fine: `message_${id}`
- Update the URL to include the hashbang: `#message_${id}`
https://github.com/LAION-AI/Open-Assistant/blob/0a7cd410edb78773c60fd67d24edd53d8773ea76/website/src/components/Messages/MessageTableEntry.tsx#L112

**Comment by notmd** [comment]
Ah this might not work because we are fetching the data from client side

**Comment by johnflux** [comment]
I tested using location hash, but it didn't work that well.
So I implemented with a custom hook using ref and useEffect
 
https://github.com/LAION-AI/Open-Assistant/pull/1886
