### ISSUE TITLE
Show all user chats

### ISSUE THREAD

**Issue by AbdBarho** [LAION-AI/Open-Assistant#1881]
Show all the chat for the currently logged in user.

This will require the following (maybe some of it is already implemented)
* An endpoint in the inference server to get all user chats
* A page or sub page on the website to show the list of chats

Clicking on a item from the list should open the chat.

Questions:
* our chats are just Ids, what do we want to show to the user? maybe the first message?

**Comment by olliestanley** [comment]
Since we added auth to the inference server this endpoint will list all chats for the currently authenticated user:

https://github.com/LAION-AI/Open-Assistant/blob/main/inference/server/main.py#L186
