### ISSUE TITLE
Proposal for prompt reply pair

### ISSUE THREAD

**Issue by notmd** [LAION-AI/Open-Assistant#1882]
Solution for #1030.
- **Option 1 (Andreas suggestion)**: Add the ability to create a reply for a prompt. After that, the message tree will go to `prompt_lottery_waiting` state.
   - Easy to implement and fit with our design, but the problem here is we have so many `prompt_lottery_waiting` trees, which can take months to complete. But in near future, most of our assistant replies will be synthetic then the waiting prompts maybe decrease dramatically.
 - **Option 2**: As Huu said a single Q/A message tree is fine (https://discord.com/channels/1055935572465700980/1059076134807023656/1078649949119598592). Add the ability to create a reply for a prompt. After that, the tree will go to `promtp_reply_pair_review` state. And after receiving N good review it will be `ready_for_export` otherwise will be `halted_by_moderator`. Because the tree only has a single Q/A we don't need to rank it. We also don't want it to grow more because someone may flood our task with this and we will need a lottery for it again. We also need to extract the review task of the prompt reply pair to a separate task
   - Good for simple Q/A and can increase our dataset a lot.
   - Much more complex implementation, more tasks.
 - **Option 3**: Just like option 1 but we only give permission to legit/verified users (maybe users in the leaderboard or something). The tree will be growing immediately after creation. Also, we can limit X prompt reply pair that can be created per day (globally or per user).

**Comment by AbdBarho** [comment]
@notmd would it be okay if you copy this over to #1030 ? so we can close this?
