### ISSUE TITLE
Ensure the model does not promote self harm

### ISSUE THREAD

**Issue by sedthh** [LAION-AI/Open-Assistant#1909]
This is for the future so we do not forget to do it, I recently came across a talk where they predicted that 2023 will be the year of the very first suicide caused by a chatbot / assitant / LLM. They predicted that some model will give the user accidental advice that would result in them killing themselves. 

The model should be evaluated to ensure it does not advocate self violence or suicide in any way. This also means that when the user is asking for help in harming themselves, the model should instead recommend to seek professional help. It is easy for a LLM to follow along a depressed discussion and add to the misery of the user.

**Comment by horribleCodes** [comment]
There already is a guideline about this:
> When being asked about a high-risk topic, make sure the user knows that as a language model, the assistant is susceptible to producing incorrect information, and that no actions should be taken regarding the assistant reply without the opinion of a professional.

I've even provided an [example](https://projects.laion.ai/Open-Assistant/docs/guides/examples#warning-about-the-potential-for-self-harm-in-individuals-with-suicidal-tendencies) of refusing to provide information if it's reasonable to assume the user will use that information to cause self-harm.
You could argue about whether there should be extra steps taken to ensure the assistant won't make an inappropriate decision in such a case, but we'll need suggestions on how this could be done.

**Comment by bitplane** [comment]
I don't think the assisted suicide thing is that big of a risk or something we should block. If someone uses the thing to research their options, get referred to a doctor and they arrive at euthanasia as an informed decision that's supported my medical professionals, then we shouldn't go full ChatGPT on them and block that. It's something that's legal in some countries and not others, and people will feel the same way about abortion and other similar issues.

That said, if someone is asking for suicide options then we shouldn't immediately recommend knots and types of rope.

I think this will be a powerful tool, and there's a balance to be struck between serving users and safety. We don't want this to be a very useful way to harm people, but we shouldn't stop people from finding factual information just in case they harm themselves either.

So I think the best option here is to get a dataset of actual conversations that saved lives (and more morbidly, conversations that didn't) and train the model on these so it's got suicide helpline skills.
