### ISSUE TITLE
Proposal: Add the translation of the guidelines in Spanish

### ISSUE THREAD

**Issue by FabricioMoreno** [LAION-AI/Open-Assistant#1917]
Since Spanish is the second most popular language of interaction with the project, I would like to work on translating the guidelines so that users better understand what should and should not be done when contributing datasets to the website.

**Comment by horribleCodes** [comment]
We should add support for all translations of the documentation. That being said, we'd have to carefully review all proposed translations when it comes to things such as guidelines, because we have to make sure nothing gets lost in translation.

**Comment by FabricioMoreno** [comment]
I know, I'm working on it when it's ready I'll upload it

**Comment by andreaskoepf** [comment]
We don't support localization of our documentation. I would suggest to first try automatic machine translation from English .. actually creating localized documents would require tracking changes and updating all localized copies after changes were made.
