### ISSUE TITLE
Markdown syntax

### ISSUE THREAD

**Issue by XavierRex** [LAION-AI/Open-Assistant#1919]
In the UI we should add a short tutorial on how to use markdown syntax to create a table, bigger letters and bold letters etc. (or add a link to some tutorial) to make responses look better. Especially teach people how to create proper tables would be useful.

**Comment by etiennebalit** [comment]
It seems react-markdown and remarkGfm are being used to render the Markdown (GFM being for Github Flavored Markdown).

Should we start by linking to Github docs for Markdown formatting?

OpenAssistant docs currently link to: https://www.markdownguide.org/basic-syntax

**Comment by vivasvan1** [comment]
Hi

I would like to attempt to build this. and had a doubt.

Are we talking about all the text input fields or just some specific ones here ?

**Comment by ultWorld** [comment]
@Anantha-Kandrapu have you already done this? or should i do this?

**Comment by Anantha-Kandrapu** [comment]
I've just added the tool tip like he suggested
