### ISSUE TITLE
Cleanup all eslint warnings in the website

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#193]
Running `npm run build` reveals a large number of small warnings.  We should do a full pass over and clean them up.

**Comment by AbdBarho** [comment]
`npx eslint --fix` unfortunately does not solve the problem.

Maybe we could integrate some tool that does this for us automatically.

https://github.com/trivago/prettier-plugin-sort-imports

**Comment by croumegous** [comment]
I'll be happy to work on this cleanup

**Comment by AbdBarho** [comment]
@croumegous great, I will assign it to you.

**Comment by croumegous** [comment]
PR https://github.com/LAION-AI/Open-Assistant/pull/199
