### ISSUE TITLE
Docker Building Error

### ISSUE THREAD

**Issue by huangtao36** [LAION-AI/Open-Assistant#1931]
<img width="853" alt="image" src="https://user-images.githubusercontent.com/27218434/222410749-2428be46-2ce5-4ec4-8def-11445cdafeea.png">

When executing the command "docker compose --profile ci up --build --attach-dependencies", an error as shown in the picture appears, and I don't know how to solve it. Do you have any suggestions?

**Comment by notmd** [comment]
Did you try to run the command again?
