### ISSUE TITLE
Except check with pre-commit for the notebook files

### ISSUE THREAD

**Issue by wannaphong** [LAION-AI/Open-Assistant#1935]
From #1903, pre-commit  is error by jupyter notebook. I was export the notebook from Google colab then add to my pull request but pre-commit was error with the  jupyter notebook file. I try to clean all output and edit by jupyter notebook but it is still error. (You can review from my old commits.)

Why did it go wrong?

I will resubmit the pull request if this issues was fixed.

**Comment by olliestanley** [comment]
Pre-commit doesn't like the formatting of the notebook. You can install pre-commit to your local machine and run it for the notebook, then it will automatically fix the formatting following our pre-commit config.

**Comment by olliestanley** [comment]
> > Pre-commit doesn't like the formatting of the notebook. You can install pre-commit to your local machine and run it for the notebook, then it will automatically fix the formatting following our pre-commit config.
> 
> OK 👍 I will resubmit but I think the Github action should has automatically fix. If people send pull request by comptuer than can't install pre-commit (like me), It should be automatically fix.

Unfortunately I don't think it's possible for GitHub Actions to actually change the PR contents so it has to be fixed by the user

> @olliestanley I still found the same error but It's passed with my local machine.
> 
> #1936

Ok. Let me look at it, I will try to fix it for you
