### ISSUE TITLE
Allow the user in ranking tasks to indicate that all answers are factually wrong

### ISSUE THREAD

**Issue by AbdBarho** [LAION-AI/Open-Assistant#1939]
Maybe using a checkbox to indicate that all presented answers are factually wrong 

This is especially relevant for synthetic data

This requires
* Add endpoint in the backend to report this (this could also be a flag that is send along as part of the ranking data send as submission) (maybe already implemented in https://github.com/LAION-AI/Open-Assistant/commit/6244ef622b03fb62e8ad25fc75de50d7f7fa13c5 ?)
* Add checkbox (or anything else) in the UI to allow the user to indicate that all of the answers being ranked are factually wrong.

**Comment by notmd** [comment]
@AbdBarho this is covered by my PR #1937

**Comment by AbdBarho** [comment]
great!
