### ISSUE TITLE
How to prepare 2023-02-12_oasst_prod.jsonl

### ISSUE THREAD

**Issue by ghtaro** [LAION-AI/Open-Assistant#1942]
Hi, 

I am trying to run sample scripts in https://github.com/LAION-AI/Open-Assistant/tree/main/model.
I would to run RL training script, but I could not prepare oasst dataset specified in config yml.

![image](https://user-images.githubusercontent.com/24857936/222607280-214a89bc-9c98-48b5-bf90-d80d7c62965a.png)

It would be very helpful if you tell me how to do it.

**Comment by andreaskoepf** [comment]
The OA dataset has not been released. If you want to prepare training code you can look at a sample of 100 English trees here: https://github.com/Open-Assistant/oasst-model-eval/blob/main/model_eval/manual/data/en_100_tree.jsonl

If you are interested in helping us to train the RL model please join the OA discord and ping me (or other members of the dev team).

**Comment by huangtao36** [comment]
Are there any open datasets where I can try to train it

**Comment by ghtaro** [comment]
@andreaskoepf Thank you very much for your reply. I managed to run RL training with WebGPT, but will definitely try en_100_tree and visit OA discord!
