### ISSUE TITLE
Write a manual / black-box "smoke test" suite

### ISSUE THREAD

**Issue by k-nearest-neighbor** [LAION-AI/Open-Assistant#197]
Write a quick test suite of around a dozen basic "happy path" or "smoke test" cases, stored in an .md somewhere.

The idea is you can refer to these cases when you want to quickly test a branch or your own changes so you know nothing major is broken (auth, rating tasks, etc.).

This can also serve as a suite of cases to automate.

**Comment by andreaskoepf** [comment]
can this be closed?
