### ISSUE TITLE
Add llama support?

### ISSUE THREAD

**Issue by jiacheng-ye** [LAION-AI/Open-Assistant#1970]
Great work! I'm wondering whether the recent llama model will be added to the repo?

**Comment by MrlolDev** [comment]
https://twitter.com/ykilcher/status/1632370236413321219

**Comment by dany-on-demand** [comment]
Only the weights are "non-commercial academic use only". [The LLaMA example repo si GPLv3](https://github.com/facebookresearch/llama). Can't OA support LLaMA-like as a plug-in?

**Comment by olliestanley** [comment]
> Only the weights are "non-commercial academic use only". [The LLaMA example repo si GPLv3](https://github.com/facebookresearch/llama). Can't OA support LLaMA-like as a plug-in?

Yes, most likely. But the ML team is not likely to focus on supporting this when the weights can't be used anyway. If you would like to make a PR adding this support, feel free
