### ISSUE TITLE
[Simple feature] Add a tooltip to the creative and spam label

### ISSUE THREAD

**Issue by EGA-SUPREMO** [LAION-AI/Open-Assistant#1973]
When I first started to add labels, I originally thought that spam label was for someone who was promoting something related to an answer, example: 

`User: what is the best way to save money?` 

`Assisant: With NerdWallet, You can start small — having just $500 saved can help you pay for some financial emergencies without going into deb....`

Then I read the guidelines, but that time I'd marked as not spam, things that should be considered spam

With creative, for some reason I originally thought that it was meant for stories, poems and prompts related to arts in general. For the rest of prompts I'd marked them as ordinary.

By the time I realized that, I have around 200~ labels, I think other people can go longer before reading the guidelines 

It would be nice a tooltip like:

Is the message an unrelated piece of text that doesn't contribute to the previous prompt in any way? If it's an initial prompt, is it something unlikely to be used to initiate a conversation with the assistant? 

Ordinary/Creative: How unlikely is the question to be asked? Is it challenging the assistant with a problem that requires creative thinking? Does the question include lots of context? On the assistant's side, is the reply straightforward, or does it contain a unique approach to a problem?

**Comment by johnflux** [comment]
I can take this on

**Comment by johnflux** [comment]
<img width="810" alt="image" src="https://user-images.githubusercontent.com/1230500/223017472-c0eb28ac-09e3-4e67-9bbf-c83cff111828.png">

How about this?

**Comment by johnflux** [comment]
Alternative:

<img width="846" alt="image" src="https://user-images.githubusercontent.com/1230500/223018388-1e3f1483-7b36-4fb4-ae9f-b5b7e6fcdaae.png">

**Comment by johnflux** [comment]
<img width="724" alt="image" src="https://user-images.githubusercontent.com/1230500/223037335-a566e81d-3d82-47b5-a1a8-98e7cc14a923.png">
