### ISSUE TITLE
Document required permissions for discord-bot in bot's README

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#198]
e.g. which "Bot Permissions" check boxes have to be checked at https://discord.com/developers/ for [ALL_UNPRIVILEGED](https://docs.hikari-py.dev/en/latest/reference/hikari/intents/).

For example all privileged gateway intents need to be activated:

- presence intent
- server members intent
- message content intent

**Comment by CBlagden** [comment]
I can update the README.

**Comment by yk** [comment]
@CBlagden thank you, I've assigned you

**Comment by CBlagden** [comment]
It looks like the README was already updated.

**Comment by yk** [comment]
@andreaskoepf can you confirm & close the issue?

**Comment by andreaskoepf** [comment]
Closing all old discord bot issues. Discord data collection never took off. It might be more viable to develop a discord bot that communicates with the inference system.
