### ISSUE TITLE
Inference worker trying to GET a non-existing inference server uri: `/health`

### ISSUE THREAD

**Issue by nero19960329** [LAION-AI/Open-Assistant#1987]
Code context: https://github.com/LAION-AI/Open-Assistant/blob/85fbaf6843fd6d45b0e1d152edaad55499d00027/inference/worker/utils.py#L48 

which I cannot find any `/health` API in inference server, so when I `docker compose --profile inference up`, inference-worker will infinitely print logs like:

```
open-assistant-inference-worker-1  | 2023-03-06 06:37:17.652 | WARNING  | utils:wait_for_inference_server:58 - Inference server not ready. Retrying in 4.07 seconds
```

Solutions:

1. Add `/health` to inference-server
2. Use other healthy check API maybe I don't know.

You could give me some hint and I think could fix it.

**Comment by olliestanley** [comment]
I am fairly sure the answer to this question is the same as the question [here](https://github.com/LAION-AI/Open-Assistant/issues/1990#issuecomment-1456744763). On my end, this `Inference server not ready.` message prints for a while but eventually stops, as a normal part of the startup process. If it is not stopping for you at all though, let us know
