### ISSUE TITLE
Inference worker trying to POST a non-existing inference server uri: `/generate_stream`

### ISSUE THREAD

**Issue by nero19960329** [LAION-AI/Open-Assistant#1990]
Code context: https://github.com/LAION-AI/Open-Assistant/blob/85fbaf6843fd6d45b0e1d152edaad55499d00027/inference/worker/__main__.py#L57

So if the uri not exists, how could inference worker to POST it?

**Comment by olliestanley** [comment]
In this context `settings.inference_server_url` does not refer to the backend located at `inference/server` in this repo (that is referred to by `settings.backend_url`) but a server running the HuggingFace [text-generation-inference](https://github.com/huggingface/text-generation-inference) server software to which we delegate the actual inference.
