### ISSUE TITLE
Web container keep logging `Can't reach database server at webdb:5432` when starting with `docker-compose`

### ISSUE THREAD

**Issue by nero19960329** [LAION-AI/Open-Assistant#1992]
### Step

- `docker compose --profile ci up --attach-dependencies`

I downloaded oasst-backend, oasst-web containers from ghcr.io, so I don't need to build those images.

### Problem

oasst-web conatiner keep telling me that it cannot reach `webdb`, which is started in my point of view.

```
open-assistant-web-1      | Environment variables loaded from .env
open-assistant-web-1      | Prisma schema loaded from schema.prisma
open-assistant-web-1      | Datasource "db": PostgreSQL database "oasst_web", schema "public" at "webdb"
open-assistant-web-1      | 
open-assistant-web-1      | Error: P1001: Can't reach database server at `webdb`:`5432`
open-assistant-web-1      | 
open-assistant-web-1      | Please make sure your database server is running at `webdb`:`5432`.
open-assistant-web-1      | Postgres is unavailable - sleeping
```

**Comment by nero19960329** [comment]
I found out codes at `website/.env` will set `DATABASE_URL` to `localhost:5433`, will it overwrite the database settings in `docker-compose.yaml`?

https://github.com/LAION-AI/Open-Assistant/blob/85fbaf6843fd6d45b0e1d152edaad55499d00027/website/.env#L5

https://github.com/LAION-AI/Open-Assistant/blob/85fbaf6843fd6d45b0e1d152edaad55499d00027/docker-compose.yaml#L119

**Comment by nero19960329** [comment]
And I had an experiment:

- Run `npx prisma db push --skip-generate` outside `web` container
  - success: `Datasource "db": PostgreSQL database "oasst_web", schema "public" at "localhost:5433"`
- Run `npx prisma db push --skip-generate` inside `web` container
  - failed: `Datasource "db": PostgreSQL database "oasst_web", schema "public" at "webdb"`
  - `Error: P1001: Can't reach database server at `webdb`:`5432``

So the problem is that I cannot connect to `webdb` inside `web` container.

**Comment by nero19960329** [comment]
Not the repo's bug, it's my local environment problem.

**Comment by vincentlux** [comment]
> Not the repo's bug, it's my local environment problem.

@nero19960329 Hi, I met the same problem... How did you fix it?

**Comment by vincentlux** [comment]
@bitplane Yeah, I changed the port and fixed the issue. Thanks!
