### ISSUE TITLE
any gpt3-like model supported for the chinese language ? 

### ISSUE THREAD

**Issue by wy200507030** [LAION-AI/Open-Assistant#1995]
i have not found model for the chinese language in open-assistant is that true?

**Comment by theblackcat102** [comment]
@wy200507030 English is our primary focus now, if you have good multilingual model or SFT dataset it's very easy to finetune it yourself.

I have done some effort on translation instruction and results are mix : https://huggingface.co/theblackcat102/pythia-1b-deduped-sft
