### ISSUE TITLE
Instruction Dataset: Retrieval-based grounded model generated Q-A pairs

### ISSUE THREAD

**Issue by michaelthwan** [LAION-AI/Open-Assistant#2004]
It is referring to discord:
https://discord.com/channels/1055935572465700980/1058348535612985394/1081779446941487104

Idea:
- I've created [searchGPT (github)](https://github.com/michaelthwan/searchGPT)  ( [Demo](https://searchgpt-demo.herokuapp.com/) ), a grounded search engine that retrieves also website / offline file content as a reference, with a footnote referencing (like new bing). We found that using a retrieval-based model works a lot better than raw LLM even though we are using a relatively smaller model (like curie). Sometimes ungrounded model gave false results.

![image](https://user-images.githubusercontent.com/14001550/223420976-fde3b910-c847-4731-bdc5-6e02efef357e.png)

Consulted Huu Nguyen 
I might do it like the uploaded image.
- Crawl knowledge / content (Wiki etc.)
- using doc2query to obtain prompts / query
- using searchGPT to give grounded answers
- (bonus) using searchGPT to give different quality of response (best / ungrounded / rude / unhelpful etc.) for reward training.

Thanks and welcome for any comments.

**Comment by ontocord** [comment]
Looks great!

**Comment by TeYo001** [comment]
This looks like a really promissing addition to this project although I am a bit worried about it possibly interfereing with non-factual based answers, such as when writing fiction or just talking.

**Comment by michaelthwan** [comment]
@TeYo001 Thanks for your constructive comment.
Currently I think it won't if I give valid prompt and valid sources related to the prompt.
Because the retrieval-based properly will force the model to answer base on only the answers.

(Demo is here: https://searchgpt-demo.herokuapp.com/ )

For example, 
Prompt: What is Silvergate bank liquidation
Obviously it is the latest news and the model answer fairly fine because somewhat it summarize, or compress the given info into a nice article. 

Grounded.
![image](https://user-images.githubusercontent.com/14001550/224486772-be7bf552-ec0c-4df0-b05e-6025184cc04b.png)
![image](https://user-images.githubusercontent.com/14001550/224486779-81935e1e-c8ea-4680-b7de-d8700435c01f.png)

Conversely, the ungrounded version (ie similar to directly asking chatgpt/llm) will really write fiction.
![image](https://user-images.githubusercontent.com/14001550/224486902-9e9c06ea-ff26-425a-8854-65064aea39a1.png)

**Comment by michaelthwan** [comment]
Now I am doing final fine-tuning of my model, understand what format I have to output and what source that is already exists in huggingface (e.g. wikitext, openwebtext ?) to save my work , carefully reading ToS of my dependencies etc..

**Comment by michaelthwan** [comment]
Working on doc2query for [wikipedia](https://huggingface.co/datasets/wikipedia)
the wikipedia dataset have **~6.4M rows** data (wiki pages) for english.
I am generating 3 queries for each so there will be **19.2M queries** in total.
Running with in like 8 workers (several colab+private machines).

Example:

![image](https://user-images.githubusercontent.com/14001550/225618715-5482365d-6578-4ace-b7df-0de27c9e0b67.png)

**Comment by michaelthwan** [comment]
Currently I have 950k pages*3 queries=2850k rows queries
![image](https://user-images.githubusercontent.com/14001550/226177133-da256bd1-967f-4b1a-9ded-92acdb8c0818.png)

After de-duplicated, there is 2550k rows.
Distribution of queries
![image](https://user-images.githubusercontent.com/14001550/226177164-7212f173-12ef-429b-804f-4f8c7d016613.png)

I will try to generate prompt-response pairs for 100 prompts for each category as a initial trial

**Comment by michaelthwan** [comment]
Uploaded 1000rows WIKI prompt, response here for review. It is not yet OA format (have raw columns) but it can be easily translated
https://huggingface.co/datasets/michaelthwan/wiki_qa_bart_1000row/blob/main/README.md
@ontocord
