### ISSUE TITLE
dataset: CounselChat

### ISSUE THREAD

**Issue by kirawi** [LAION-AI/Open-Assistant#2027]
CounselChat is basically a service where users can anonymously post questions, and therapists (unclear if they are verified or not) can respond to them. While their terms forbid data collection, a dump was provided by them to someone on https://github.com/nbertagnolli/counsel-chat/blob/master/data/counselchat-data.csv. I'm unsure of the legality of using it.

**Comment by AbdBarho** [comment]
If their terms forbid it, then its illegal.

**Comment by kirawi** [comment]
I'll try to contact them about it.

**Comment by bitplane** [comment]
The latest commit message on that repo says "Added scraped counsel chat data", so no, we can't legally use that.

**Comment by kirawi** [comment]
The linked data is the one provided by CounselChat. The repo owner had initially scraped the website before receiving that data.
