### ISSUE TITLE
I should be able to ask the bot for work in DMs

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#203]
So far, I have to go to the channel to ask for work, but then it transfers me to the DMs. If the task times out, but I'd like another one, I have to go back to the channel. It would be more convenient, if I could just also type "/work" in the DMs

**Comment by GravermanDev** [comment]
that shouldn't be hard, I can try to do this

**Comment by GravermanDev** [comment]
@yk I'm sorry but I thought it was gonna be easier and I gotta go rn, so if it's fine I'm going to complete this task tomorrow, if it's not, just unassign me, thanks

**Comment by yk** [comment]
sure, no stress :) just let us know if it turns out you need help

**Comment by AlexanderHOtt** [comment]
> So far, I have to go to the channel to ask for work, but then it transfers me to the DMs. If the task times out, but I'd like another one, I have to go back to the channel. It would be more convenient, if I could just also type "/work" in the DMs

If a user starts a task in the bot's DM, what server should the task completion be logged in?

**Comment by yk** [comment]
> If a user starts a task in the bot's DM, what server should the task completion be logged in?

Good question. Do you have a suggestion? Do we have some kind of idea from which server the user initially started interacting with the bot?

**Comment by GravermanDev** [comment]
probably sending that to the server they started interacting with the bot is the best way. Don't know if that's possible tho as I'm still trying to get this working...

**Comment by AlexanderHOtt** [comment]
> > If a user starts a task in the bot's DM, what server should the task completion be logged in?
> 
> Good question. Do you have a suggestion? Do we have some kind of idea from which server the user initially started interacting with the bot?

@andreaskoepf and I thought of logging *every* task completion message from *every* server in the log channel, but that could get hectic if the not gets a lot of traffic. We could come up with some algorithm in the future to choose servers to send messages in, but for now I'll send it in all of them.

**Comment by AlexanderHOtt** [comment]
fixed in #267
