### ISSUE TITLE
OA RM dataset

### ISSUE THREAD

**Issue by sanagno** [LAION-AI/Open-Assistant#2047]
Adapt the dataset for the RM [here](https://github.com/LAION-AI/Open-Assistant/blob/main/model/reward/instructor/rank_datasets.py#L298) so that it returns all replies as pairs, where the reply with the highest positive rating is considered as positive and the other one as negative.

Requires:
- Access to the OA data or just knowledge of the overall structure.

A further step will be to batch all pairs corresponding to the same prompt in the same batch as well. This should reduce overfitting.

**Comment by AbdBarho** [comment]
> where the reply with the highest positive rating is considered as positive and the other one as negative.

Maybe slightly tangential to this issue, I will just throw it here:

Would it make sense to train the RM using replies from different prompts? to add more "contrast" to the data?

There are a lot of good replies to prompts, and choosing the best one is hard and sometimes subjective. But if we also include replies from other prompts as part of the ranking, the model would have clear examples of bad replies and what not to do, and in general greater learning signal.
