### ISSUE TITLE
Contract tests between API and Discord Bot

### ISSUE THREAD

**Issue by jack-michaud** [LAION-AI/Open-Assistant#205]
As per discussion in #180, the communication between the discord bot and API should be tested through a Contract test. This test should test that each call satisfies the OpenAPI schema inputs and endpoints. That way, changes to the endpoint contract will automatically be caught by these tests.

**Comment by jack-michaud** [comment]
Started using [Wiremock](https://wiremock.org/docs/docker/) to create a mocked server. My tests will run on the the `OasstApiClient`.

**Comment by AlexanderHOtt** [comment]
Do you think we should move the `APIClient` to the `oasst-shared` folder? This might allow for easier testing.

**Comment by andreaskoepf** [comment]
`oasst-shared` was originally created to share elements between front-ends and backend but until we have a separate `oasst-client` package it would make sense to place the APIClient code there.

**Comment by jack-michaud** [comment]
> `oasst-shared` was originally created to share elements between front-ends and backend but until we have a separate `oasst-client` package it would make sense to place the APIClient code there.

Sounds like we don't need it just yet -- From [Discord](https://discord.com/channels/1055935572465700980/1055940266206437486/1059113791947800667)[](https://discord.com/channels/1055935572465700980/1055940266206437486/1059113791947800667):

> yes, maybe text-frontend could use this in the future as well (but very low prio)

I won't refactor the client into a separate module for this issue. will revisit when needed
