### ISSUE TITLE
Refactoring the documentation

### ISSUE THREAD

**Issue by CactiStaccingCrane** [LAION-AI/Open-Assistant#2051]
Right now the docs at https://projects.laion.ai/Open-Assistant/docs/intro is extremely messy. I'm thinking of consolidating the general docs page to make it easier to navigate and also get rid of the FAQ because that section would soon get messy as more features are built on top of OA.

**Comment by GuilleHoardings** [comment]
In my opinion, having a FAQ is a good thing. Maybe it could be organized differently, but I find it useful to link to it when people ask common questions.
