### ISSUE TITLE
Q: Has Wikipedia been considered as a dataset?

### ISSUE THREAD

**Issue by kirawi** [LAION-AI/Open-Assistant#2061]
Wikipedia contains a lot of information that is more likely to be grounded in factual evidence compared to in social media. It can also be useful to summarize high-level concepts. Also, it would be nice if a discussions page was open for questions like this, Discord isn't very searchable IMO :)

**Comment by bitplane** [comment]
Wikpedia's data is widely available as data sets and is exactly what we need. So pretty much all of the models that we'd want to start from have already been trained on Wikipedia. RWKV for example is trained on enwiki8, others are trained on things like The Pile which includes English Wikipedia.

So our data collection efforts are largely focused on specialist text sets that don't exist in The Pile or Common Crawl, or are things that can be transformed into question/answer format to make the model better at doing instruction-based things.
