### ISSUE TITLE
Make installation beginner (average scientist) friendly, localized, and allow user to feed texts and train (macOS)

### ISSUE THREAD

**Issue by jlawgit** [LAION-AI/Open-Assistant#2062]
As title, it will be highly beneficial if average scientists can train and feed texts with specialized/technical jargon.

**Comment by Danielmatiass** [comment]
sempre dentre da cultura constante no momento que houver uma pergunta a ser respondida.

**Comment by olliestanley** [comment]
Can you provide a bit of information on what is meant here? Anyone can contribute data at https://open-assistant.io with no specialist knowledge required to set up. Currently the ML team for the project is using the data contributed to the website in order to train models
