### ISSUE TITLE
Display user stats on admin `/manage_user/[id]` page

### ISSUE THREAD

**Issue by notmd** [LAION-AI/Open-Assistant#2065]
Display a statistic section like on `/account` page.

**Comment by vivasvan1** [comment]
Hi i would like to try this. i have setup the dev container but i cant find /account page. Can you please guide me a little?

**Comment by notmd** [comment]
> Edit: I found this. But i cant seem to open manage_user/[id]. ![image](https://user-images.githubusercontent.com/21074796/225108388-f2acf7f6-f7cf-4038-9f93-41134b3f6b85.png)
> 
> Hi i would like to try this. i have setup the dev container but i cant find /account page. Can you please guide me a little?

It's `/admin/manage_user/[id]`. You need to login with admin to view that's page. On local, just choose sigin with admin role
