### ISSUE TITLE
Display message tree state for admin

### ISSUE THREAD

**Issue by notmd** [LAION-AI/Open-Assistant#2066]
Using this endpoint `/api/v1/messages/[message_id]/tree/state` and display all the information for on `/admin/messages/[id]` page

**Comment by Rulios** [comment]
Hi, I can contribute to this. 

What does the state of a tree means? Active, inactive, any sort of custom state?

Should the new info in this endpoint accompany the current MessageTree?

**Comment by Rulios** [comment]
Requesting to `/api/v1/messages/[message_id]/tree/state` throws me a 404 error

![image](https://user-images.githubusercontent.com/22872640/226057706-92c00b94-1e0d-486a-bb76-7bc412eb84fc.png)

**Comment by notmd** [comment]
> Requesting to `/api/v1/messages/[message_id]/tree/state` throws me a 404 error
> 
> ![image](https://user-images.githubusercontent.com/22872640/226057706-92c00b94-1e0d-486a-bb76-7bc412eb84fc.png)

That API is in the backend. You need to edit `oasst_api_client` file to fetch it.

**Comment by Rulios** [comment]
Thanks! Working on it!

**Comment by Rulios** [comment]
Is this a good display of the data, or just want plain json? 

![image](https://user-images.githubusercontent.com/22872640/226153745-dfb8ebb8-69e0-450b-904e-f422b4b202f8.png)

**Comment by Rulios** [comment]
Is this a good display of the tree state data? 
![image](https://user-images.githubusercontent.com/22872640/226153806-947b470a-6856-4657-99ed-d14e35fbafee.png)

**Comment by notmd** [comment]
That's fine. But if you can make it better, it would be awesome.

**Comment by Rulios** [comment]
Now displaying into a table, tbh it looks wayyy better. 

![imagen](https://user-images.githubusercontent.com/22872640/226241056-a9863974-bda5-4919-a07e-f6e9a6f2fbe0.png)
