### ISSUE TITLE
buildx platform args broke build

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#2081]
@melvinebenezer PR #1763 broke build, I had to revert.

See https://github.com/LAION-AI/Open-Assistant/actions/runs/4429860792

If you have an idea how to fix it, go ahead. If not, all good to close this issue and we'll have to leave it at that :)

**Comment by melvinebenezer** [comment]
I'll give it a shot else we can close

**Comment by bitplane** [comment]
I'm guessing `build-essential` is missing from the Dockerfile? `gcc` is missing anyway, seems to be the cause of the failed build.
