### ISSUE TITLE
Add eval sets to reward model training

### ISSUE THREAD

**Issue by dvruette** [LAION-AI/Open-Assistant#2090]
Anthropic has demonstrated that reward model training improves downstream performance on certain ranking tasks [1]. We would like to see similar gains throughout our RM training. In particular, the HellaSwag and Summarizing from Feedback seem the most interesting:

HellaSwag: https://huggingface.co/datasets/hellaswag
Summarize from Feedback: https://huggingface.co/datasets/openai/summarize_from_feedback
Stanford/SHP: https://huggingface.co/datasets/stanfordnlp/SHP (suggested by @shahules786)

[1] https://arxiv.org/pdf/2112.00861.pdf

**Comment by shahules786** [comment]
Sure, I'm on it :)
