### ISSUE TITLE
Correlation metrics during reward model training

### ISSUE THREAD

**Issue by dvruette** [LAION-AI/Open-Assistant#2122]
As suggested by [ZickZack on Discord](https://discord.com/channels/1055935572465700980/1059076134807023656/1086275001809911900), the Spearman and/or Kendall correlation would be a good metric for evaluating our reward models during training, in addition to validation accuracy and loss.

Scipy provides implementations for both of these (here, Kendall correlation):
```python
from scipy import stats
a = [1,2,3]
b = [2,1,3]
stats.kendalltau(a,b)
# returns KendalltauResult(correlation=0.33333333333333337, pvalue=1.0)
```

**Comment by shahules786** [comment]
I can take this up @dvruette .  For RM evaluation I assume that each batch contains rankings for answers to a single prompt.

**Comment by dvruette** [comment]
Thank you! One batch can actually contain multiple rankings. The batch has a key `cu_lengts` which indicates the borders between samples. You can check the `compute_loss` function or the `RMLoss` class for examples.

**Comment by shahules786** [comment]
cool. I'll do that @dvruette
