### ISSUE TITLE
Make a discord script for searching for unverified new members

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#214]
New members need to introduce themselves briefly when they join. MEE6 auto-assigns the role "unverified" to them. Once I see their short introduction (and confirm it's not spam), I assign them the "verified" role and remove "unverified". But there are so many people, sometimes I miss someone. So, if someone is good at discord, I need a way of searching through the "lobby" channel for any person who has written a message, but still has the "unverified" role.

**Comment by othrayte** [comment]
After looking for ways to do this and finding no built in way to do it in the UI and no luck finding a discord bot that could do it I asked chatGPT to do it and got a sensible enough sounding result, might be worth trying (I might see if it runs once I wake up tomorrow).

>Write a python script that uses the discord API to find messages in a channel from users with the role "unverified".

## chatGPT
To use the Discord API, you will need to install the discord.py library. You can do this by running the following command:

`pip install discord.py`

Next, you will need to create a Discord bot and get its token. You can follow the instructions [here](https://discordpy.readthedocs.io/en/latest/discord.html) to do this.

Once you have the discord.py library installed and have a bot set up, you can use the following script to find messages from users with the "unverified" role in a specific channel.

```python
import discord

# Replace YOUR_BOT_TOKEN with your bot's token
client = discord.Client(token='YOUR_BOT_TOKEN')

# Replace CHANNEL_ID with the ID of the channel you want to search
channel_id = CHANNEL_ID

# Replace UNVERIFIED_ROLE_ID with the ID of the "unverified" role
unverified_role_id = UNVERIFIED_ROLE_ID

@client.event
async def on_ready():
    # Find the channel object
    channel = client.get_channel(channel_id)

    # Get a list of all messages in the channel
    messages = await channel.fetch_messages()

    # Iterate through the messages and print the ones from users with the "unverified" role
    for message in messages:
        if unverified_role_id in [role.id for role in message.author.roles]:
            print(message.content)

client.run()
```

This script will print the content of all messages in the specified channel that were sent by users with the "unverified" role.

**Comment by oyiakoumis** [comment]
@othrayte unfortunately it doesn't work as it is. However, I've built a script that works using your code:
```python
import discord

unverified_users = set()

class MyClient(discord.Client):
    async def on_ready(self):
        # Find the channel object
        channel = self.get_channel(CHANNEL_ID)

        # Get a list of all messages in the channel
        messages = channel.history(limit=200)

        # Iterate through the messages and keep the ones from users with the "unverified" role
        async for message in messages:
            if isinstance(message.author, discord.Member) and UNVERIFIED_ROLE_ID in [
                role.id for role in message.author.roles
            ]:
                unverified_users.add(message.author.name)

        print(f"All unverified users: {unverified_users}")
        await self.close()


intents = discord.Intents.default()
intents.message_content = True

client = MyClient(intents=intents)
client.run(BOT_TOKEN)
```

**Comment by batuhanerenler** [comment]
`import discord

client = discord.Client()

@client.event
async def on_ready():
   
    lobby_channel = discord.utils.get(client.get_all_channels(), name="lobby")

    
    unverified_role = discord.utils.get(client.guild.roles, name="unverified")
    unverified_members = [member for member in client.guild.members if unverified_role in member.roles]

    for member in unverified_members:
        async for message in lobby_channel.history(limit=None):
            if message.author == member:
                
                print(f"{member.name} has sent a message in the lobby channel and has the unverified role.")

client.run("YOUR_DISCORD_BOT_TOKEN")
`

**Comment by batuhanerenler** [comment]
`
import discord

client = discord.Client()

@client.event
async def on_ready():
    l
    lobby_channel = discord.utils.get(client.get_all_channels(), name="lobby")

    
    unverified_role = discord.utils.get(client.guild.roles, name="unverified")
    unverified_members = [member for member in client.guild.members if unverified_role in member.roles]

    
    for member in unverified_members:
        async for message in lobby_channel.history(limit=None):
            if message.author == member:
                
                print(f"{member.name} has sent a message in the lobby channel and has the unverified role.")

client.run("YOUR_DISCORD_BOT_TOKEN")
`

**Comment by yk** [comment]
Thank you very much everyone, I took both suggestions and a bit of copilot made `scripts/discord/verify-lobby.py`
