### ISSUE TITLE
No module named "oasst_data" 

### ISSUE THREAD

**Issue by zhongxing-mt** [LAION-AI/Open-Assistant#2148]

**Comment by zhongxing-mt** [comment]
In model_training/custom_datasets/oasst_dataset.py, there is an import "from oasst_data import ExportMessageNode, load_trees, visit_threads_depth_first". But oasst_data module is not found

**Comment by olliestanley** [comment]
You will likely need to have installed the `oasst_data` module with pip before running this code. We probably need to update the training README to make this clear

**Comment by zhongxing-mt** [comment]
@olliestanley ERROR: Could not find a version that satisfies the requirement oasst_data (from versions: none)
ERROR: No matching distribution found for oasst_data

**Comment by olliestanley** [comment]
> @olliestanley ERROR: Could not find a version that satisfies the requirement oasst_data (from versions: none)
> ERROR: No matching distribution found for oasst_data

Yes, it isn't on pypi, it's in this repository. You will probably have to do something like (from the repository root):

```
cd oasst-data
pip install .
```

**Comment by zhongxing-mt** [comment]
pip install works. But it comes to some other problem

**Comment by andreaskoepf** [comment]
> some other problem

Could you please describe the other problem?
