### ISSUE TITLE
Update model/model_training to pytorch 2.0

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#2173]
- update pytorch & deepspeed
- test SF & RM training works with small debug model
- submit PR

**Comment by olliestanley** [comment]
Based on https://github.com/Microsoft/DeepSpeed/discussions/2765 it seems like there may not be a DeepSpeed version for PyTorch 2.0 yet

They have a branch which isn't merged yet which looks like it tries to add support for Torch 2 https://github.com/Microsoft/DeepSpeed/commits/loadams/fix-torch-2
