### ISSUE TITLE
RM filtering SFT replies

### ISSUE THREAD

**Issue by sanagno** [LAION-AI/Open-Assistant#2192]
Now that we have a good RM, we should use it to filter predictions from the SFT model.

Process:
- Get samples from the SFT model.
- Filter them based on the RM model.
- Compare the quality of the filtered vs unfiltered replies.

**Comment by shahules786** [comment]
@sanagno I'll look into this.

**Comment by sanagno** [comment]
thanks a lot! Basically what you have been doing already

**Comment by shahules786** [comment]
Should this be one pipeline? @sanagno

**Comment by sanagno** [comment]
Does not have to be, but it is up to you. Whatever works in the end and is expected to be more user-friendly in terms of use but also in terms of evaluating the results in the end.
