### ISSUE TITLE
Annonomise and remove PPI

### ISSUE THREAD

**Issue by getorca** [LAION-AI/Open-Assistant#220]
Any thoughts been given to removing PPI and anonymising the data that's collected?

**Comment by fozziethebeat** [comment]
This issue is too broad and vague.  Can you first start a discussion in discord and then make an issue with more concrete action items?

**Comment by jqueguiner** [comment]
You can use MS Presidio based on Spacy NER. Only supports English and Spanish so far here is an example of how to
Use it:
https://github.com/gladiaio/gladia/blob/main/src/apis/text/text/anonymization/ms-presidio/ms-presidio.py

**Comment by andreaskoepf** [comment]
This is a very important and complex topic with multiple layers, e.g. meta-data recorded for submissions and the text-content of demonstrations itself. What we store in our db and what is exported. For example we want to exclude users and their messages when they submit toxic, inappropriate, dangerous, spam etc. Exported datasets to the contrary should be as anonymous as possible.

@ontocord is leading our data-augmentation and safety team. He is an active contributor of [PIISA](http://piisa.org/).

**Comment by yk** [comment]
I'm closing this in favor of discussions on discord

**Comment by ontocord** [comment]
We are working with the volunteer piisa.org to implement a LAION workstream for removing PII. Please join https://discord.com/channels/823813159592001537/911668194958270514 This is the LAION wide project to deal with PII in text data if you are interested. We will apply the same rules to the dataset in OA or any other LAION project involving text data. @jqueguiner - yes, presidio is awesome. It's one of the module that can plug into piisa.org framework. We found that during working on the BigScience PII effort there are PII tools lacking specifically for (1) NLP datasets, and (2) multi-lingual PII tool. Thus we creaged piisa.org.  We welcome PRs and help to the make the NLP ecosystem stronger.
