### ISSUE TITLE
Classify assistant reply - filter based on task type (e.g.: summarization, NER, question answering)

### ISSUE THREAD

**Issue by samuelazran** [LAION-AI/Open-Assistant#2204]
Some of us are looking for specific capabilities from LLMs. Is there a demand for being able to filter the dataset based on the task type, similar to how it is classified in Huggingface datasets? 

For my use case, I need high-quality dialogue summarization and NER. If it would be possible to filter on those task types, I'd love to contribute for the evaluation of this type of content.

It is not easy for me to contribute much as I see that most of the content I came across in the "classify assistant reply" are for question-answering tasks, and many are not in my domain of expertise. 

I think that this type of classification could help in estimating the abilities of a model trained on this dataset on the variety of task types.

**Comment by olliestanley** [comment]
This can be handled by topics so duplicate #1006
