### ISSUE TITLE
Add drag handles for rankable (sortable) items

### ISSUE THREAD

**Issue by othrayte** [LAION-AI/Open-Assistant#223]
Adding drag handles to the dragable items being ranked would make it clearer that they can be dragged.

This was originally suggested by @k-nearest-neighbor in [#158 ](https://github.com/LAION-AI/Open-Assistant/issues/158#issuecomment-1368148998_)
> [...] there should be a drag handle. Something like [RxDragHandleDots2](https://react-icons.github.io/react-icons/search?q=rxdraghandledots2) or [MdDragHandle](https://react-icons.github.io/react-icons/search?q=mddraghandle). On the left or right side is debatable. (both?)

Also the rankable items currently have dot points, that can probably also be removed to avoid confusing the user.

**Comment by fozziethebeat** [comment]
I'd like to add an additional request: making ranking doable by keyboard so that it's accessible.  I couldn't figure out how to rank via keyboard only.

**Comment by othrayte** [comment]
I'm interested in doing this task, I was already working on some of it in my confusion with #158.

**Comment by othrayte** [comment]
> I'd like to add an additional request: making ranking doable by keyboard so that it's accessible. I couldn't figure out how to rank via keyboard only.

I did notice some support in dnd-kit for keyboard input, wasn't how we would want that to work but it sounds worth investigating more, could be as simple as enabling it.

**Comment by fozziethebeat** [comment]
Yeah that would be rad.  If you're able to test it out and and see if it's at least semi-functional that's better than zero keyboard support.
