### ISSUE TITLE
Website signin page needs to display the `OAuthAccountNotLinked` error correctly.

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#224]
If a user logs in first via email and then tries to login via discord, they will get a `OAuthAccountNotLinked` error.  We should present that error with sensible instructions (login with the original provider).  NextAuth's default pages present this but our custom page doesn't handle this case well.

**Comment by callum-gander** [comment]
I'll take this if that's alright

**Comment by fozziethebeat** [comment]
Great! I've assigned it to you~

**Comment by fozziethebeat** [comment]
@callum-gander have you been able to look at this?

**Comment by callum-gander** [comment]
Started and got interrupted, will finish it today

**Comment by AbdBarho** [comment]
fixed in #542
