### ISSUE TITLE
Support the ChatGPT Plugin standard for external APIs using .well-known/ai-plugin.json

### ISSUE THREAD

**Issue by stefangrotz** [LAION-AI/Open-Assistant#2255]
ChatGPT is right now starting to roll out a new Plugin system that allows it to access information from external APIs.

Here are the details:
* https://platform.openai.com/docs/plugins/introduction
* https://platform.openai.com/docs/plugins/getting-started

You basically have to create the file
`yourdomain.com/.well-known/ai-plugin.json`
Where you describe your API in human language.

I know this project is far from using plugins like this, but maybe it is worth planing using this (de-faco?) standard in Open Assistant as a long term goal. 

What would we need for that? A new category of dialogues with special training data?

**Comment by pevogam** [comment]
I would relate this issue to this pull request as a specific approach: https://github.com/LAION-AI/Open-Assistant/pull/2765
