### ISSUE TITLE
Augment Training set with model data

### ISSUE THREAD

**Issue by sanagno** [LAION-AI/Open-Assistant#2265]
Currently, the quality of our data is almost "too" good. To help with the RL training, our RM should also have seen "bad" examples. One idea would be to augment our current training set with replies that we expect to be worse than average.

Task:
- Find "bad" SFT models, preferably multiple of multiple bad quality, e.g. ~100m, 1b pythia models.
- Use them to generate replies to our data. You can see a preview here https://github.com/Open-Assistant/oasst-model-eval/blob/main/model_eval/manual/data/en_100_tree.jsonl. These replies should be labelled as having lower rank as the current data.
- Train an RM based on these data as well.

**Comment by theblackcat102** [comment]
@sanagno  I have finish sampling augment results and here's the reward scores on the first en_100.jsonl score.

```
Prompt : How can I find the best 401k plan for my needs?
Human Rank (ordered by rank):
1. There are many factors to consider when selecting a retirement savings plan, such as tax advantages, 0.95556640625
2. The first step is to determine your current financial situation and goals. You should consider how m, 0.490234375
3. The first step in finding a good retirement savings plan is to determine your current financial situ, 0.794921875
4. There are many factors to consider when choosing a qualified 401(k) plan, such as your income level, 0.72021484375
5. If you're looking to invest money in a retirement savings account, there are many factors to conside, -0.3828125
-----
chip20b synthetic answers (ordered by rank)
1. The first step is to research your options. You should look at different plans and compare them base -0.1843261
2. The first step is to determine your financial goals. Once you have a clear idea of what you are .. -0.007488250
3. The best way to find a 401k plan that meets your needs is to do research and compare different optio -0.085998
```

**Comment by andreaskoepf** [comment]
The synthetic data generated by @theblackcat102  was used in training our models. We might consider releasing the synthetic data-set.
