### ISSUE TITLE
Web Team Meeting: 2023-03-31

### ISSUE THREAD

**Issue by AbdBarho** [LAION-AI/Open-Assistant#2267]
* Current state of the project
* Inference Auth
  * Additional login providers?
* Requirements for Chat UI
  * necessary features ?
  * #2100, alternative generations, A/B rating
* Next milestone
* Availability

**Comment by AbdBarho** [comment]
TODO:

* Sort list of chats by date
* Check if the chats are separate for each user
* Handle whitespace correctly in generated chats
* Make model config UI elements more visible
   * Persist the model config between chats (not per chat)
   * Show some info about the chat config without having to open the menu
   * Maybe consider using the config of the last message as initial config for this chat.
* Add "trusted" clients to the backend, which would allow the website to easily communicate with the inference without the additional login.

**Comment by notmd** [comment]
For the chat config persistent, using the config of the last message seem reasonable. We can fall back to the previous chat config (which we can store in local storage) if the chat is empty.

**Comment by notmd** [comment]
For chat UI we can take some inspiration from these:
https://www.typingmind.com/
https://github.com/mckaywrigley/chatbot-ui
Chat UI for threading.
https://github.com/littlemoonstones/ChatGPT-conversation
