### ISSUE TITLE
Continuing in the face of the open letter to stop LLM experiments

### ISSUE THREAD

**Issue by Tophness** [LAION-AI/Open-Assistant#2272]
I think we should do the opposite to what the open letter demands and set our goals much higher than they were when this project started.
There are already several smaller open source models like Alpaca, so making a ChatGPT competitor is relatively redundant now.
Governments might be able to regulate Microsoft, Google or OpenAI from training something larger than GPT-4, but not the open source community.
Can we all agree that stifling progress is silly and we'll carry on if they don't?

**Comment by ignas-g** [comment]
>Maybe it would even make sense to crowdfund money to pay people to create a dataset if we want to move quicker.  
  
Incentivising people makes sense. It does not necessarily have to be cold hard cash it could be something like a crypto-currency token or NFT
