### ISSUE TITLE
Potential vague translation on the question "Is it a bad reply, as an answer to the prompt task?" in Chinese when label assistant reply

### ISSUE THREAD

**Issue by lone-wolf-akela** [LAION-AI/Open-Assistant#2274]
The line "Is it a bad reply, as an answer to the prompt task?" is translated as "对于该提示任务来说这不是个好的回复？" in our site, which is literally "Isn't that a good reply for the prompt quest?"

I've always thought it means I need to choose "Yes"（"是"） for a good reply, as "Yes, it is (a good reply)". Only today I decide to try out the English version, do I realize that I have choose the wrong option as the "Yes" here mean "Yes, it is a bad reply".

I suggest translating it as "作为对于该提示任务的回答，这是一个糟糕的回复吗？" which is more clear.

**Comment by AbdBarho** [comment]
Could you fix it?
https://github.com/LAION-AI/Open-Assistant/blob/main/website/public/locales/zh/labelling.json
