### ISSUE TITLE
Design an informative `/about` on the website.

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#229]
@yk has written a [comprehensive slide deck](https://docs.google.com/presentation/d/1n7IrAOVOqwdYgiYrXc8Sj0He8krn5MVZO_iLkCjTtu0/edit#slide=id.p) with a roadmap and philosophy.  We should copy parts of this and make a really nice looking `/about` page on the website.

**Comment by brentbagapuro** [comment]
Hi, I'd like to work on this issue. I can take parts from the slide deck you mentioned and copy them onto different sections of the page. I noticed the homepage currently is using a Tailwind UI template (Pocket), so I can take inspiration from there, as well as integrate other Tailwind UI components as needed.

**Comment by fozziethebeat** [comment]
Great! Assigned this to you.

**Comment by brentbagapuro** [comment]
@fozziethebeat  Shall I include the slides below the "Getting to MVP" part?

**Comment by fozziethebeat** [comment]
I think for a first draft we can skip those as they're more operational.

**Comment by brentbagapuro** [comment]
Thanks for the quick response! I'll submit a PR in a few.
