### ISSUE TITLE
Connect Open Assistant to an existing web service

### ISSUE THREAD

**Issue by Nicolas-M15** [LAION-AI/Open-Assistant#2328]
I have a chatbot web service using GPT2 and would like to connect it to Open Assistant and provide users feedback to continue training Open Assistant.

Is it possible to do it, or is it too early?

**Comment by olliestanley** [comment]
Are you asking about using your GPT-2 service to generate answers for user prompts at https://open-assistant.io? If so we do not want this, we aim to collect human-written responses only

**Comment by olliestanley** [comment]
Ok - currently there isn't an Open Assistant model ready for real use, only an initial demo which can produce poor results. We aim to release a first version around 15th April so then might be a good time to revisit this
