### ISSUE TITLE
Implement inversion samples for alpaca.

### ISSUE THREAD

**Issue by jordiclive** [LAION-AI/Open-Assistant#2335]
The idea is from this [tweet](https://twitter.com/abacaj/status/1643416835843293186). I'm not sure if they include the inversion samples in the validation set, I think we should obviously exclude them from the validation. 

But is a cool idea nevertheless. I can take a look at this later this week.

**Comment by CloseChoice** [comment]
I'd look at this this evening, let you now what my results are
