### ISSUE TITLE
Can we learn from Vicuna to train and fine-tune the model?

### ISSUE THREAD

**Issue by libai-lab** [LAION-AI/Open-Assistant#2341]
I learned that Vicuña can train a large language model with a very low configuration, but only for research purposes；
Can we learn from Vicuna to train and fine-tune the model?
It would be great if I could, I'm a novice and don't understand anything, but I'm very interested and I'm very sorry to bother

**Comment by andreaskoepf** [comment]
Many people seem to refer Vicuna .. i.e. they seem to have a good PR campaign. Could someone make a comparison between OA llama based models and theirs? It Vicuna actually better and if so in which way...?

**Comment by kostum123** [comment]
> 

Koala model performed better in other languages than Vicuna during my testing. Using more data improved the model's ability to provide more accurate answers in other languages. However, as Koala wrote in their announcement blog, the Koala all model is slightly worse against the Koala distill. Of course, this assessment was for English, and I don't think the test coverage was sufficient. It is also unclear whether they extended the training time or kept it equal when they used more data. If they kept the training time equal, the model may not have seen enough quality data to fully benefit from the increased amount of data. Some sources: 
https://www.chatorg.ai/blog/chat-language-models-tracker
https://chat.lmsys.org/
https://bair.berkeley.edu/blog/2023/04/03/koala/
https://github.com/arnav-gudibande/koala-test-set
https://github.com/lm-sys/FastChat/tree/main
https://vicuna.lmsys.org/

**Comment by jerzydziewierz** [comment]
@andreaskoepf 

> Is Vicuna actually better and if so in which way...?

It appears that at this time, Vicuna is actually better, according to user preference capture on 345 samples with a win probability of 0.77. 

  
Source:

https://lmsys.org/blog/2023-05-03-arena/

**Comment by olliestanley** [comment]
> It appears that at this time, Vicuna is actually better, according to user preference capture on 345 samples with a win probability of 0.77.
> 
> Source:
> 
> https://lmsys.org/blog/2023-05-03-arena/

That is comparing to OA Pythia, where the base model is worse than Vicuna (based on LLaMA), so it makes sense
