### ISSUE TITLE
Inference doesn't show whole text during incremental updates.

### ISSUE THREAD

**Issue by kpoeppel** [LAION-AI/Open-Assistant#2354]
In the currently deployed version on `open-assistant.io/chat`, the incremental inference updates start from some later tokens. 
1. During generation:
![Screenshot at 2023-04-06 19-23-25](https://user-images.githubusercontent.com/37810656/230452347-856d81d6-3c45-4cdc-90b7-8b34c47ad6df.png)
2. Final response:
![Screenshot at 2023-04-06 19-23-31](https://user-images.githubusercontent.com/37810656/230452357-e6a43f2d-6e66-42e6-8d29-a0c85d936968.png)

In case this isn't resolved yet, I can try to tackle this.

**Comment by notmd** [comment]
Which browser are you using?

**Comment by kpoeppel** [comment]
Firefox, version 111.0.1, Linux Mint

**Comment by andreaskoepf** [comment]
> Firefox

Can confirm this defect for Firefox (same version) on Ubuntu.

**Comment by 0x22almostEvil** [comment]
The problem is also observed in Chromium on Android and Chromium on Linux

**Comment by olliestanley** [comment]
Another user in #2374 reported that this seems to occur when there is a comma near the start - all text before the comma is not visible until the generation is complete.

**Comment by Jmshaver** [comment]
Similar problem with Chromium on Mac. All text before an apostrophe was not visible until the entire generation was complete

**Comment by planetoryd** [comment]
This problem is especially apparent when talking in Chinese



![Image](https://user-images.githubusercontent.com/68096727/230739122-97ef8692-10eb-474b-b98d-75e14212a526.png)



![Image](https://user-images.githubusercontent.com/68096727/230739136-6aa11a24-35de-4a5e-8d9e-666a01dffecd.png)

Firefox 111.0.1
