### ISSUE TITLE
PII Detector for database

### ISSUE THREAD

**Issue by Simon1V** [LAION-AI/Open-Assistant#2355]
Hey, I created this regex based tool to detect PII in strings of text. 

https://github.com/Simon1V/PII-Detector
It could be both used for: 
- Detecting PII in prompts (in or out)
- Detecting PII in databases 

My suggestion would be to integrate it into 
https://github.com/LAION-AI/Open-Assistant/tree/main/scripts 
such that it can be used if necessary

**Comment by olliestanley** [comment]
It would be cool to have this as a script in the repo - feel free to make a PR containing it if you're happy to do so
