### ISSUE TITLE
Maximum chat length setting for inference

### ISSUE THREAD

**Issue by olliestanley** [LAION-AI/Open-Assistant#2357]
It would be great if the website could have a configuration option we could use to specify a max chat length. This would avoid some of the wild nonsense outputs we have seen in early testing, which is important if we plan to use the collected data for further training.

**Comment by AbdBarho** [comment]
What would be a sensible max length?

**Comment by olliestanley** [comment]
> What would be a sensible max length?

It seems to me that the model often goes wild around hitting the context limit of ~2k tokens. Hard to translate that into a number of messages but maybe we could start by limiting to maximum 5 assistant replies. We can always tweak the setting later.

**Comment by olliestanley** [comment]
It turned out that the model going haywire after a while was a result of a truncation bug which is now fixed, so this feature is no longer needed
