### ISSUE TITLE
Create role field in website User table and be able to seed it

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#236]
We need a `role` field in the website's `User` table.  By default any new user should be given the `general` role.

We also need a seed script that lets us mark one or more users as admins in advance.  That seed script should let us configure via an environment variable the set of admins via their auth method (discord or email) and the username they use (their discord username or their email address).

When a user matching this short list signs up, they should automatically be given the `admin` role.

**Comment by fozziethebeat** [comment]
Whoever does this should probably review https://next-auth.js.org/tutorials/role-based-login-strategy

**Comment by Jason-Kim1023** [comment]
I am looking into this with the provided link!  I think the general imputing of the role field should be fairly simple, now looking into the seed script aspect of it!

**Comment by fozziethebeat** [comment]
Great, I'll assign it to you for the time being.

**Comment by Jason-Kim1023** [comment]
**For the first part of adding role, I believe this change is what the provided resource states is the simple fix, which I updated in my local code:**
model User {
  id            String    @id @default(cuid())
  name          String?
  email         String?   @unique
  emailVerified DateTime?
  image         String?
  role          String?  // New Column
  accounts      Account[]
  sessions      Session[]

  tasks         RegisteredTask[]
}

**For the auto-generalrole, this code should make the user role automatically to general. trying to figure out if this part of the code should be placed in the API Auth file**

import NextAuth from 'next-auth'
import { NextApiRequest, NextApiResponse } from 'next'

const options = {
  events: {
    async onCreate (user) {
      user.role = 'general'
    },
  },
}

export default NextAuth(options)


**this code can be used to have 2 users with admin roles, but can be expanded to more users
**Step 1 would be:** 
        -config.js file that contains something like: process.env.ADMIN_USERS
 = 'JasonKim#1234', ‘jasonjihoonkimmail@gmail.com’;

**Step 2:  This code will then in the auth file of the api folder** 

require('./config');

Same code as before….. New edits:
const authOptions: AuthOptions = {
  // Ensure we can store user data in a database.
  adapter: PrismaAdapter(prisma),
  providers,
  pages: {
    signIn: "/auth/signin",
    verifyRequest: "/auth/verify",
    // error: "/auth/error", -Will be used later
  },
  session: {
    strategy: "jwt",
  },
  callbacks: {
    // This function is called when a user signs in.
    async signIn(user, account, profile) {
      // Check if the user should be marked as an admin.
      const adminUsers = process.env.ADMIN_USERS.split(",");
      if (adminUsers && adminUsers.includes(user.)) {
        // Mark the user as an admin.
        await prisma.user.update({
          where: {
            id: user.id,
          },
          data: {
            role: "ADMIN",
          },
        });
      }
    },
  },
};
 
export default NextAuth(authOptions);

**Comment by Jason-Kim1023** [comment]
as of right now looking how to check the discord/email id instead of just the user id

**Comment by fozziethebeat** [comment]
This looks great!  Whenever you're ready prepare a PR and I'll review.

**Comment by Jason-Kim1023** [comment]
just for clarification, do you want this process to happen during the session callback so that it checks if a user is an admin depending on whether or not the account parameter in session(user, account) is discord or email and then looks inside the config file to make the judgement of admin role or general role?

Essentially, something like this?
`sync session(user, account) {
      // Check if the user should be marked as an admin.
      const adminUsers = process.env.ADMIN_USERS.split(",");
      if (account && account.providor === "discord") {
        const discordID = account.id;
        const discordUsername = account.username;
        const discordIdAndUsername = `${discordUsername}#${discordID}`;
        if (adminUsers && (adminUsers.includes(discordIdAndUsername))) {
          // Mark the user as an admin.
          await prisma.user.update({
            where: {
              id: user.id,
            },
            data: {
              role: "ADMIN",
            },
          });
        }
      }
      if (adminUsers && (adminUsers.includes(user.email))) {
        // Mark the user as an admin.
        await prisma.user.update({
          where: {
            id: user.id,
          },
          data: {
            role: "ADMIN",
          },
        });
      }
      else {
        await prisma.user.update({
          where: {
            id: user.id,
          },
          data: {
            role: "general",
          },
        });
      }
    },
  },
};

export default NextAuth(authOptions);`

**Comment by fozziethebeat** [comment]
I was thinking that upon new account creation we'd check the user's ID against the environment variable.  If that matches then we'd update their `role` value in the `User` table.  From that point on, we just have to make sure the session and token objects have that role value so other parts of the app can make their changes accordingly.  

I *think* this can be done by using one of the [Next Auth event callbacks](https://next-auth.js.org/configuration/options#events) to do the check and then updating the database table.

**Comment by fozziethebeat** [comment]
The code should be almost the same as what you draft but just in a different callback.  Session gets called *a lot* and shouldn't be making mutations.

**Comment by Jason-Kim1023** [comment]
Okay, that thank you for the clarification.  Just doing the callback on user creation should be fine then since user creation for an account is unique. I’ll get on that!

**Comment by yk** [comment]
> I was thinking that upon new account creation we'd check the user's ID against the environment variable. If that matches then we'd update their `role` value in the `User` table.

I don't have a good overview over the exact events happening, but is there something like a "login" event? If we just assign upon account creation (which I assume happens on the very first login), then we can't later easily modify the admin list, when the accounts already exist.

**Comment by Jason-Kim1023** [comment]
Yup!  I can modify the code so that it updates and checks on login instead of account creation.  That way if someone is (lets say deleted from the admin list) it can be updated when that user logs in next.

**Comment by fozziethebeat** [comment]
I like that too as the account will exist on our staging database when we dd this support in.
