### ISSUE TITLE
Sign-in email marked as spam

### ISSUE THREAD

**Issue by moenia-swe** [LAION-AI/Open-Assistant#2363]
The sign-in email was reported as spam in Gmail. When I marked it as safe and tried to open the link it warned me that the link looked suspicious and asked if I really wanted to open it.

**Comment by AbdBarho** [comment]
Related https://github.com/LAION-AI/Open-Assistant/issues/1191 https://github.com/LAION-AI/Open-Assistant/issues/1388

**Comment by taunoe** [comment]
It was in spam and the Sign In link is not active.

**Comment by AbdBarho** [comment]
We are working on other options to login #2378

**Comment by olliestanley** [comment]
Going to close this as it was likely a result of the email address typo which is now fixed
