### ISSUE TITLE
ChatPDF

### ISSUE THREAD

**Issue by zas97** [LAION-AI/Open-Assistant#2369]
Would it be possible in the future to chat with Open-Assistant with the context of a pdf like in https://www.chatpdf.com/?

**Comment by olliestanley** [comment]
The basic requirement for this is just performing OCR on the PDF to extract text and then feeding that text into the LLM context as normal. It should be possible, might be a good candidate for a plugin/integration

**Comment by zas97** [comment]
If it is a large pdf file it also needs to be chunked in and then perform a query to only input the relevant chunks into the LLM as context.

**Comment by zas97** [comment]
Could you give me some hints as to how could I create a plugin with such functionality?

**Comment by olliestanley** [comment]
> Could you give me some hints as to how could I create a plugin with such functionality?

We don't have a final specification for how plugins for OA will be developed yet, but there are people working on it

**Comment by tobiasoberrauch** [comment]
Looking forward to see the plugins and especially with pdf files

**Comment by rudolphos** [comment]
I am interested in this too.

**Comment by olliestanley** [comment]
It is now possible to use plugins for this with the same spec as OpenAI

**Comment by tobiasoberrauch** [comment]
> It is now possible to use plugins for this with the same spec as OpenAI

Is there an example where I can find in the doch?
