### ISSUE TITLE
Create admin only web page that manages registered web users

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#237]
This requires:
- [ ] A nav link somewhere (probably the user profile drop down menu list) that is only visible to users with the `admin` role and then takes them to `/admin/`.
- [ ] A new page at `/admin/` that reports the list of registered users in the `User` table.  This shouldn't expose all details, just their auth method, username, and role to start.
- [ ] An API route that fetches the data above (but only for users with the `admin` role).
- [ ] An ability to set the role status for users (either from `general` to `admin` or from `admin` to `general` and ensure this is reflected in the `User` table.

Blocked by #236

**Comment by KarthikRaju391** [comment]
@fozziethebeat, I would like to try this. 

My plan would be as follows:
1. Update the User schema to include `role` as a new field.
1. Set up the API to return the user details only if the API is requested by an Admin user
2. Create an admin page that shows all the users along with their `auth-method`, `username`, and `role`
3. Allow the role to be set as `general` or `admin`. This should also be reflected in the `User` table which means a `POST` request must be sent.

**Comment by fozziethebeat** [comment]
That sounds great.  Someone is working on step 1 but it's not clear when they will finish if.  If you're able to finish all this first I'll approve.  But you might have to merge in their PR.

**Comment by KarthikRaju391** [comment]
Yeah sure, I will try and finish this soon and I'll merge their PR when it is created.

**Comment by KarthikRaju391** [comment]
Hey @fozziethebeat, I am not familiar with the backend tech stack. It would help me a lot if you could share some resources I can use to get started

**Comment by KarthikRaju391** [comment]
should I create my own Postgres instance to set up the `DATABASE_URI` in the .env file in backend folder?

**Comment by fozziethebeat** [comment]
I'm going to start creating the skeleton pages and API routes for this feature.  Once I've got the skeleton up and properly functioning, I'll hand it over for improved styling and usability.
