### ISSUE TITLE
First few words not appearing in chat tab

### ISSUE THREAD

**Issue by Thomasnerd06** [LAION-AI/Open-Assistant#2374]
When chatting with the model, I noticed that the first few words dont appear, until the responce is complete. I am not certain, but I think its when there is a comma near the start it removes all the text before the comma until its completed everything.

Not very high priority, just thought I should mention it.

**Comment by olliestanley** [comment]
Thanks for the report! This looks like a duplicate of #2354 so I'll close this thread, but I'll add your observation re this happening after commas to the other issue :)
