### ISSUE TITLE
Extraction locales: "Sign In" on a main page

### ISSUE THREAD

**Issue by 0x22almostEvil** [LAION-AI/Open-Assistant#2382]
![image](https://user-images.githubusercontent.com/122345469/230665873-e5e6646c-6158-455b-a4af-7c789479e893.png)

Tried to do it by myself a while ago, but it seems there's some catch, and I just worry to break something

**Comment by Shaariq06** [comment]
Hi,

I'm looking to contribute for the first time and I just wanted some clarification. I'm not sure if this is the issue you are referring to, but when I sign in using email, no sign in link is sent to my email. Please can you send me an update and I can work on it.

![Screenshot_20230409_102522_Chrome.jpg](https://user-images.githubusercontent.com/120254414/230765197-4369d8a4-6aea-46ed-9261-098a6a8c7ffd.jpg)

**Comment by vivekpabari** [comment]
Hii,
I have raised [PR ](https://github.com/LAION-AI/Open-Assistant/pull/2443) for resolved this issue. Please review it.

**Comment by AbdBarho** [comment]
> I'm looking to contribute for the first time and I just wanted some clarification. I'm not sure if this is the issue you are referring to, but when I sign in using email, no sign in link is sent to my email. Please can you send me an update and I can work on it.


Please check your spam folder.

**Comment by Shaariq06** [comment]
I've got the email, thank you
