### ISSUE TITLE
Cannot delete new chats

### ISSUE THREAD

**Issue by Gapi505** [LAION-AI/Open-Assistant#2384]
https://open-assistant.io/chat When you click on the trash bin, the chat doesn't delete itself.
did some inspect elementing and it seems that the `function rv() {}` function is empty or the button is not connected to any other event because other buttons call the same function but also other functions
here's a picture https://imgur.com/ks5Z85N which shows the only thing hooked onto the event is the rv function which is empty

sorry for the poor report

**Comment by olliestanley** [comment]
Yes, this isn't implemented yet but PR #2350 will add it soon

**Comment by olliestanley** [comment]
Hiding is in and full deletion is tracked by #2582 so I will close this
