### ISSUE TITLE
Chat settings resets when reopened

### ISSUE THREAD

**Issue by sedthh** [LAION-AI/Open-Assistant#2385]
Found a minor bug on the frontend: when a preset is selected, reopening the settings tab will jump back to the first option.

Thanks!

**Comment by AbdBarho** [comment]
Maybe it would make sense to replace the preset dropdown with buttons that apply the corresponding settings, after all, the preset is not saved and not needed.

**Comment by sedthh** [comment]
yeah that makes sense
