### ISSUE TITLE
why does openassistant use a custom datacollator?

### ISSUE THREAD

**Issue by raihan0824** [LAION-AI/Open-Assistant#2387]
Hi, I want to ask something simple.

In the `train_sft.py`, why do you use a customer datacollator in `DialogueDataCollator`? Why don't you use a transformers' `DataCollatorForSeq2Seq` instead? What difference does it make?

Thank you

**Comment by theblackcat102** [comment]
The initial reason is we are using decoder based model so we had to provide a masking id to only learn the response segment of the conversation.  For example  `(human)[Hi how are you](assistant)[I am fine]`, we only want the model to learn the `I am fine` section. DataCollatorForSeq2Seq is only suitable for sequence to sequence base model such as T5, but we are using decoder based model this is not suitable.

**Comment by raihan0824** [comment]
Thank you for the response. A few other repos that I read are using `DataCollatorForSeq2Seq` for the decoder model and it still works well, how is that possible?

**Comment by raihan0824** [comment]
Thank you for the response. What about `DataCollatorForLanguageModeling` ? A lot of decoder based models used that
