### ISSUE TITLE
Issues with Open Source

### ISSUE THREAD

**Issue by nivibilla** [LAION-AI/Open-Assistant#2392]
Hi,

I saw in one of the releases, you are using the gpt4all dataset which was created using OpenAI's APIs. My question is doesn't this restrict the open source nature of the project as this model will violate OpenAI's terms of using their data to create a competing model?

This question also applies to when some people may use chatgpt to complete the replies to prompts. How are you planning on cleaning this data?

Thanks

**Comment by shreesha345** [comment]
Don't worry the have all ready done that part of cleaning the data an to in a smart way

**Comment by nivibilla** [comment]
So they will omit the chatgpt generated data?
