### ISSUE TITLE
Setup cloud deployment for website

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#24]
When done, we should be able to manually deploy the website to some cloud provider of choice.

This should use the docker image created in #23.

The most likely [options](https://nextjs.org/docs/deployment) are:
- AWS Fargate (via [copilot](https://aws.github.io/copilot-cli/))
- AWS App Runner (via [copilot](https://aws.github.io/copilot-cli/))
- Google Cloud Run
- Heroku

**Comment by yk** [comment]
what about vercel? supports all of nextjs out of the box

**Comment by fozziethebeat** [comment]
Vercel is also a good option pending someone to pay for it.  Given Andreas' request for full docker support I wanted to first make sure a pure docker deployment worked smoothly so that it could be deployed just about anywhere.

**Comment by poipiii** [comment]
if we need a free option to start out with staging/deployment I recommend [fly.io](https://fly.io/docs/about/pricing/) , it quite simple to use and uses dockerfiles , their own config file and their cli tool to deploy so it fits into our pure docker deployment strategy well they also offer a free tier with the following specs 

- Up to 3 shared-cpu-1x 256mb VMs†
- 3GB persistent volume storage (total)
- 160GB outbound data transfer

**Comment by Jabster28** [comment]
hey! i'm new to this project and i'd like to help with this issue, since i've got some experience with this kinda thing. what would you like me to do, assuming we use fly? their deployment system is pretty easy to use - minimal changes to the dockerfile, and they only require running `fly deploy` whenever you want a new version. would you want the deployment to happen in a github action or something similar?

**Comment by fozziethebeat** [comment]
Hi Jabster, thank you for the offer.  We have a setup for this in review right now to deploy on AWS. 

Right now we're auto deploying to a cloud provider LAION gifted to the project and I'll be donating some AWS credits when we need them.

**Comment by Jabster28** [comment]
oh right, sorry about that. good luck!
