### ISSUE TITLE
Discord bot is failing to see the package

### ISSUE THREAD

**Issue by onegunsamurai** [LAION-AI/Open-Assistant#240]
Testing running discrod bot inside the container now independently. 

When creating a new .venv and doing

`
source .venv/bin/activate
pip3 install -r requirements.txt
`
then
`
python3 bot/bot.py
`

I'm getting

```
Traceback (most recent call last):
  File "/app/bot/bot.py", line 7, in <module>
    from bot.api_client import OasstApiClient
  File "/app/bot/bot.py", line 7, in <module>
    from bot.api_client import OasstApiClient
ModuleNotFoundError: No module named 'bot.api_client'; 'bot' is not a package
```

When replacing
```
from bot.api_client import OasstApiClient
from bot.settings import Settings
```

with 
```
from api_client import OasstApiClient
from settings import Settings
```

hitting another one
```
Traceback (most recent call last):
  File "/home/crewmaty/Open-Assistant/discord-bot/bot/bot.py", line 7, in <module>
    from api_client import OasstApiClient
  File "/home/crewmaty/Open-Assistant/discord-bot/bot/api_client.py", line 10, in <module>
    from oasst_shared.schemas import protocol as protocol_schema
ModuleNotFoundError: No module named 'oasst_shared'
```

Because this module is not even in in the Dockerfile yet.

**Comment by andreaskoepf** [comment]
To launch the bot please use: `python -m bot` (as described in the [README.md](https://github.com/LAION-AI/Open-Assistant/blob/main/discord-bot/README.md))

**Comment by andreaskoepf** [comment]
Please execute `pip install -e .` in the `oasst-shared` directory to install the shared module first.
