### ISSUE TITLE
Score issue

### ISSUE THREAD

**Issue by Schismond** [LAION-AI/Open-Assistant#2408]
I'm facing an issue where my score count is not increasing after I do tasks

**Comment by olliestanley** [comment]
It will increase, it just takes time to update. Also if you are doing "Create Initial Prompt" tasks they give very few points

**Comment by Schismond** [comment]
Thank you for clarifying the misunderstanding. I appreciate your help in
resolving the issue.

Best regards.

Le sam. 8 avr. 2023 à 19:01, Oliver Stanley ***@***.***> a
écrit :
