### ISSUE TITLE
Chat sending other peoples responds?

### ISSUE THREAD

**Issue by nadavMihov** [LAION-AI/Open-Assistant#2419]
If I write to the chat and it shows me my message is in queue, sometimes after it reaches place 0 in queue it doesn't print my message even after waiting. In that  case, I refresh the page and while the model is showing the loading icon I write the same prompt again and it deletes the previous one and outputs an unrelated message.
Can it be a message from another user?

![image](https://user-images.githubusercontent.com/82936591/230757105-31744c86-8dbb-4faf-b7e4-5f002a74b38f.png)

**Comment by yk** [comment]
I've looked into this particular message and as far as I can tell, nobody else got the same message as a response. We fixed a truncation bug in inference during that time, and also HF fixed one too, maybe this is related to either of those. will keep our eyes open!
