### ISSUE TITLE
Assistant create pedophile story describing child abuse

### ISSUE THREAD

**Issue by davidak** [LAION-AI/Open-Assistant#2422]
![Screenshot from 2023-04-09 11-02-20-censored](https://user-images.githubusercontent.com/91113/230764684-b3e054d2-fcf5-4ffc-9dbc-1dff313f9a8c.png)

(Censored to cause no harm and because even a text is considered child porn in germany, which is illegal.)

Such content can be harmful as it could motivate child abuse and is illegal in some countries. It should not be possible to generate such content.

**Comment by LowYieldFire** [comment]
By using OpenAssistant in this way you are in violation of the terms of service, which clearly state in section 3.1:

```
The user may only use the portal for the intended purposes. In particular, he/she may not misuse the portal. The user undertakes to refrain from generating text that violate criminal law, youth protection regulations or the applicable laws of the following countries: Federal Republic of Germany, United States of America (USA), Great Britain, user's place of residence. In particular it is prohibited to enter texts that lead to the creation of pornographic, violence-glorifying or paedosexual content and/or content that violates the personal rights of third parties. LAION reserves the right to file a criminal complaint with the competent authorities in the event of violations.
```

Furthermore, the model you are interacting with is a beta model based on LLAMA and will not be released to the public because the license prohibits such distribution regardless. Pinging @yk, please remove the message tree from the dataset.

**Comment by davidak** [comment]
>he/she may not misuse the portal

that does not make it more safe when it's that easy. also does not apply to released models

**Comment by CloseChoice** [comment]
This should not happen! We should probably add more safety datasets, especially anything that helps the model to respond well in chats about abuse.

**Comment by davidak** [comment]
>In any case, if you're interested in pursuing this direction, I invite you to do so in joining our red-teaming efforts

i would love to contribute to that in a more coordinated way. so far i just randomly test anything that comes to my mind. i think ethics and safety are very important for the powerful technology that is currently created

how can i join? right now i can not dedicate a lot of time for that and might not have internet access in the next weeks, but i would like to be able to follow the discussion and contribute when possible

**Comment by yk** [comment]
> how can i join? right now i can not dedicate a lot of time for that and might not have internet access in the next weeks, but i would like to be able to follow the discussion and contribute when possible

ping me on discord

**Comment by andrewm4894** [comment]
I think being able to flag or tag responses in the chat UI with various labels could feed into useful workflows and even pretty good further signals and training data around this area. Not sure if we have anything like that in the chat UI at the moment. I think could be a good feature request.

**Comment by andrewm4894** [comment]
Actually I just made this to see if makes sense as a feature request

https://github.com/LAION-AI/Open-Assistant/issues/2832

**Comment by IllusionDX** [comment]
Literally just don't ask it to generate that
