### ISSUE TITLE
Can you combine Open-Assistant with ChatRWKV and ChatGLM-6B ?

### ISSUE THREAD

**Issue by anon62** [LAION-AI/Open-Assistant#2441]
ChatRWKV and ChatGLM-6B are free and open-source chat-bots
We can work together to develop a free alternative faster
I think we can also combine OpenChatKit, but it seems to supported by LAION

**Comment by olliestanley** [comment]
What do you mean by combine?

**Comment by anon62** [comment]
> What do you mean by combine?

Sorry, I translated the word from a foreign language, I'm not sure how to translate correctly(combine, unite, merge), I mean to turn several similar projects into one project

**Comment by olliestanley** [comment]
I think these projects serve slightly different niches. To combine the projects would not really make sense, it's good to have differing options exploring different avenues for improvement
