### ISSUE TITLE
Meta Galactica

### ISSUE THREAD

**Issue by jqueguiner** [LAION-AI/Open-Assistant#245]
Would it be interesting to add https://galactica.org/explore/ to the chat engine ?

**Comment by GravermanDev** [comment]
that would definitely be interesting. Seeing how chatGPT is based on a code model, using a science model that can also code could be cool. Not like it depends on me at all, I'm just a casual contributor sharing my opinion

**Comment by gee842** [comment]
i think the success of using code models come from its vast experience with logical reasoning

**Comment by smytjf11** [comment]
If anyone is interested, here is a Colab notebook that reads in Galactica. It can just fit on a free tier GPU notebook but it burns through credits pretty quickly. What's a good way to add this to version control?

https://colab.research.google.com/drive/1R6WSKM21G4SeN4PKQ9xJF-b9yno7mxxP?usp=sharing

**Comment by yk** [comment]
> If anyone is interested, here is a Colab notebook that reads in Galactica. It can just fit on a free tier GPU notebook but it burns through credits pretty quickly. What's a good way to add this to version control?
> 
> https://colab.research.google.com/drive/1R6WSKM21G4SeN4PKQ9xJF-b9yno7mxxP?usp=sharing

In general, notebooks go into `notebooks/` with an accompanying markdown file briefly describing the notebook. I think in this particular case, it might not be necessary to create one, since it's just loading a model from the hub, which is fairly standard (correct me if I'm wrong).

**Comment by yk** [comment]
In general, galactica could be quite promising as a base, but we'd need to sort out the license situation.

**Comment by GravermanDev** [comment]
as I said on discord, unless they change their mind or give us special treatment (which is both unlikely) I don't think it can be used as a base. Would be happy to be corrected by someone with better understanding of license stuff

**Comment by smytjf11** [comment]
No worries, we had been looking to see which ones could easily run on the free tier notebooks. Galactica was the only one that is readily available in 8-bit and will fit. 

I'll poke around for something else!

**Comment by jalajthanaki** [comment]
I can see the model on hugging face: https://huggingface.co/OpenAssistant/galactica-6.7b-finetuned

Can we have the details of how Galactica-6.7b base model has been fine-tunned? 

Demo code which is present on the model card page is not working. Is there anything that I'm missing. 

See the community issues on hugging face. Facing the similar issues.[ Issue-1](https://huggingface.co/OpenAssistant/galactica-6.7b-finetuned/discussions/1), [Issue-2](https://huggingface.co/OpenAssistant/galactica-6.7b-finetuned/discussions/2)
