### ISSUE TITLE
Progress bar dont work for Russian characters

### ISSUE THREAD

**Issue by Smoodust** [LAION-AI/Open-Assistant#2451]
I was working on an annotation in Russian (writing user responses), and I noticed when I write Russian characters, the progress bar remains empty.
![image](https://user-images.githubusercontent.com/42073101/230963077-5342ea46-92b6-44bd-91cf-86b596a3412d.png)
But if typed english word
![image](https://user-images.githubusercontent.com/42073101/230963168-524faf4c-6121-4631-a399-51e8e50b081a.png)
Or digit
![image](https://user-images.githubusercontent.com/42073101/230963235-0c0e29e6-57dc-4682-8207-eeaec967b5ad.png)
Progress bar starts to fill up.

**Comment by vivekpabari** [comment]
I did some debugging on this issue. Here are my findings.
- Progress Bar only detects the English language and does not depend on any selected language.
- Reason there is the regex for word counting like this `/\w+/g`  that only matches English characters.
- This regex was added to resolve this issue [#492](https://github.com/LAION-AI/Open-Assistant/issues/492)
I will try to resolve this issue. Please assign this issue to me.

**Comment by vivekpabari** [comment]
I have raised the PR [Link](https://github.com/LAION-AI/Open-Assistant/pull/2539). Please review it.
