### ISSUE TITLE
Not too major

### ISSUE THREAD

**Issue by rickeisner** [LAION-AI/Open-Assistant#2454]
When I tried to enroll last night, the response came to my Spam folder because it was from "open-assistent.io". I was able to use this anyway. But you should correct the spelling error.
![image](https://user-images.githubusercontent.com/687417/230997466-e923ecb5-ee1e-4fb8-9476-02243397f08e.png)

**Comment by CloseChoice** [comment]
Could you please show me where the typo is exactly? I'm somehow missing it
