### ISSUE TITLE
Aborted by worker.

### ISSUE THREAD

**Issue by nadavMihov** [LAION-AI/Open-Assistant#2457]
After I created multiple chats and wrote prompts in them I got this message: "Error: aborted_by_worker". No matter what I did(retry, log in and out, refresh, new chat) this message keeps appearing every time I write a prompt. Even in my existing chats.
![image](https://user-images.githubusercontent.com/82936591/231065722-789e83d5-cc17-4a4f-a52d-f4ae40f3dd21.png)
I can't use the chat feature anymore.

**Comment by nadavMihov** [comment]
Now I can create new chats but trying to reply to the ones that were aborted gives me: "You are trying reply to a message that is not complete yet."

**Comment by olliestanley** [comment]
This seems to have been a function of high load in the early days of inference release
