### ISSUE TITLE
Unable to delete a chat

### ISSUE THREAD

**Issue by DoctorKrolic** [LAION-AI/Open-Assistant#2459]
I am unable to delete a chat. Here is the demo:
![firefox_QHFBlXXIGc](https://user-images.githubusercontent.com/70431552/231078618-208ee397-8824-4183-833c-4dac1ef8de4b.gif)

I use firefox. The version of my browser is 111.0.1 on x64.

**Comment by davidak** [comment]
Duplicate of https://github.com/LAION-AI/Open-Assistant/issues/2384

Please check for open issues before creating new ones.

**Comment by DoctorKrolic** [comment]
Ok, closing as duplicate
