### ISSUE TITLE
Please release a version trained using GPT-4chan as a base

### ISSUE THREAD

**Issue by CarlKenner** [LAION-AI/Open-Assistant#2460]
GPT-4chan was one of the leading truthful QA GPT models. And it is free and open source, unlike Llama. As far as I know, it works better than many of the other open-source models. Using it as a base, then applying the Open Assistant training data should, in theory, preserve its knowledge while forcing it to reply in a polite friendly helpful manner as an assistant, without the toxicity of 4chan.

**Comment by olliestanley** [comment]
OA will not be releasing a version with this base model, however in a few days OA training data will be public (and the code already is) so if you have your own compute you will be able to do as you wish
