### ISSUE TITLE
Current best model is based on LLama - are you planning to switch to open source alternative?

### ISSUE THREAD

**Issue by int8** [LAION-AI/Open-Assistant#2463]
Hello, 

Do you plan to use open source model backbone at some point? I can see the best model to chat with right now is Llama - which is closed I believe

**Comment by olliestanley** [comment]
See https://projects.laion.ai/Open-Assistant/docs/faq#what-license-does-open-assistant-use

**Comment by int8** [comment]
thanks, 

`The Open Assistant Pythia based models will be released as full weights and will be licensed under the Apache 2.0 license.` 

from which I conclude the current plan is to use https://huggingface.co/EleutherAI/pythia-12b (as the biggest one) 
?

**Comment by int8** [comment]
Thanks, 

I still wonder though, How will it be open if it relies on Llama ? (if that's the choice)

**Comment by olliestanley** [comment]
> Thanks,
> 
> I still wonder though, How will it be open if it relies on Llama ? (if that's the choice)

Like it says in the FAQ, there will be both LLaMa-based models (subject to Meta's license terms) and Pythia-based models (fully open). In future we hope that better open LLMs will be released
