### ISSUE TITLE
Opening chats of others

### ISSUE THREAD

**Issue by davidak** [LAION-AI/Open-Assistant#2470]
Someone shared a link to one of their chats on discord. I can click the link and see an empty chat. I can input text, but it's loading forever. So i can not overwrite their chat in the database. But i should see something different, like an error message that i don't have permission to see that URL.

Example: https://open-assistant.io/chat/06435933-5f60-7121-8000-2ca1d8f899bf

I can also open random IDs and get this behavior, e.g. with https://open-assistant.io/chat/test

It is also an idea to make chats public optionally like with ShareGPT, so users can rate them.

**Comment by notmd** [comment]
Dup #2400
