### ISSUE TITLE
Implement the function to report messages generated in chats

### ISSUE THREAD

**Issue by dacioAlvira** [LAION-AI/Open-Assistant#2475]
It is necessary to implement a function where messages generated by the AI in the chat page can be reported, as sometimes it generates content (violent, sexual or includes incorrect information). So far, in the chat section, only liking/disliking the message generated by AI is allowed, but there should also be an option to report messages.

**Comment by CloseChoice** [comment]
I agree we should be capable to flag content.

**Comment by AbdBarho** [comment]
I am not really sure what we could do with the report. We have the functionality of upvote / downvote, please use those!

Feel free to re-open if you have other ideas.
