### ISSUE TITLE
Dataset: databricks-dolly-15k

### ISSUE THREAD

**Issue by Miserlou** [LAION-AI/Open-Assistant#2480]
[databricks-dolly-15k](https://github.com/databrickslabs/dolly/tree/master/data) contains 15,000 high-quality human-generated prompt / response pairs specifically designed for instruction tuning large language models. Under the licensing terms for databricks-dolly-15k ([Creative Commons Attribution-ShareAlike 3.0 Unported License](https://creativecommons.org/licenses/by-sa/3.0/)), anyone can use, modify, or extend this dataset for any purpose, including commercial applications.

https://github.com/databrickslabs/dolly/tree/master/data

via: https://www.databricks.com/blog/2023/04/12/dolly-first-open-commercially-viable-instruction-tuned-llm

Looks like a perfect addition.

**Comment by Miserlou** [comment]
That was fast, wow.

**Comment by olliestanley** [comment]
> That was fast, wow.

The format they released the data in is very similar to the OA instruct format so it was a nice easy conversion!
