### ISSUE TITLE
query about the git, is the chat functional?

### ISSUE THREAD

**Issue by zephirusgit** [LAION-AI/Open-Assistant#2492]
How are you, good afternoon, after collaborating, I have seen with pleasure that the chat can now be used online, and this encouraged me to want to download the git, and see if I could use it locally, install docker, install the wsl that was requested as a requirement . install using the command,
docker compose --profile ci up --build --attach -dependencies
once installed I see that it appeared in docker and enter the page,
http://localhost:3000
It loads perfectly, I choose my language (Spanish)
and I accept the conditions etc.
then I see what to log in as a user with email, or as a dev,
The mail thing I see that it doesn't go anywhere, but I thought I saw when I installed that I installed a mail server, to send that type of message? Finally, I installed it on 2 pcs but I didn't get any, I suppose it's not implemented,
Entering as a dev, I see that the chat option remains as loading... with the blue bar, which is moving...
If I see in powershell how I launched it from there, what I see is that it says the following:
-web-1 | 'Host: inference-server:8000\r\n' +
open-assistant-main-web-1 | 'Connection: close\r\n' +
open-assistant-main-web-1 | '\r\n',
open-assistant-main-web-1 | _keepAliveTimeout: 0,
open-assistant-main-web-1 | _onPendingData: [Function: nop],
open-assistant-main-web-1 | agent: [Agent],
open-assistant-main-web-1 | socketPath: undefined,
open-assistant-main-web-1 | method: 'GET',
open-assistant-main-web-1 | maxHeaderSize: undefined,
open-assistant-main-web-1 | insecureHTTPParser: undefined,
open-assistant-main-web-1 | path: '/chats',
open-assistant-main-web-1 | _ended: false,
open-assistant-main-web-1 | res: null,
open-assistant-main-web-1 | aborted: false,
open-assistant-main-web-1 | timeoutCb: null,
open-assistant-main-web-1 | upgradeOrConnect: false,
open-assistant-main-web-1 | parser: null,
open-assistant-main-web-1 | maxHeadersCount: null,
open-assistant-main-web-1 | reusedSocket: false,
open-assistant-main-web-1 | host: 'inference-server',
open-assistant-main-web-1 | protocol: 'http:',
open-assistant-main-web-1 | _redirectable: [Circle *1],
open-assistant-main-web-1 | [Symbol(kCapture)]: false,
open-assistant-main-web-1 | [Symbol(kBytesWritten)]: 0,
open-assistant-main-web-1 | [Symbol(kEndCalled)]: true,
open-assistant-main-web-1 | [Symbol(kNeedDrain)]: false,
open-assistant-main-web-1 | [Symbol(corked)]: 0,
open-assistant-main-web-1 | [Symbol(kOutHeaders)]: [Object: null prototype],
open-assistant-main-web-1 | [Symbol(kUniqueHeaders)]: null
open-assistant-main-web-1 | },
open-assistant-main-web-1 | _currentUrl: 'http://inference-server:8000/chats',
open-assistant-main-web-1 | [Symbol(kCapture)]: false
open-assistant-main-web-1 | },
open-assistant-main-web-1 | cause: Error: getaddrinfo ENOTFOUND inference-server
open-assistant-main-web-1 | at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
open-assistant-main-web-1 | error: -3008,
open-assistant-main-web-1 | code: 'ENOTFOUND',
open-assistant-main-web-1 | syscall: 'getaddrinfo',
open-assistant-main-web-1 | hostname: 'inference-server'

as if that was missing...
Am I missing a service? retry something?
is it not implemented yet?

greetings and thanks for everything you have been doing.

**Comment by olliestanley** [comment]
The docker compose command with `--profile ci` only launches the website and data collection backend. To also launch the inference server (which will then allow the "Chat" on the website to load), you need to also include `--profile inference` as well as `--profile ci`
