### ISSUE TITLE
SVG conversion of the project's logo

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#25]
We need a logo/icon for the Open-Assistant website and the profile image of our discord bot. 

Please post icon/logo proposals in the `#open-chat-gpt-project-coordination` channel on the [LAION discord server](https://discord.com/invite/mVcgxMPD7e).

In mock-ups of the project website k_nearest_neighbor used a nice brain-like logo. Unfortunately it seems to be an official Google icon, therefore we cannot use it. Just as inspiration:
![image](https://user-images.githubusercontent.com/9976399/208312049-c925cff8-2e25-43d3-9652-3f896ec1d48d.png)

**Comment by yk** [comment]
![image](https://user-images.githubusercontent.com/858040/208541382-516ab22f-7e6c-4876-b4cd-c135baaf1c37.png)

on discord, christoph said this one, but in blue. It's the LAION logo in the middle. We should probably get this as a vector graphic if available.

**Comment by rsandb** [comment]
![oa-logo-color-1](https://user-images.githubusercontent.com/45190934/208975833-c3a4fc07-29ee-47e8-b1f5-33cea1753905.jpg)

![oa-logo-color-1-svg](https://user-images.githubusercontent.com/45190934/208975868-cb09ddef-b2bf-4d38-890c-dd01d16bbe87.svg)
![oa-logo-mono-1](https://user-images.githubusercontent.com/45190934/208975869-ca0b16b9-b897-4d3c-8d96-7400d36446c8.svg)

**Comment by k-nearest-neighbor** [comment]
excellent. I can organize and commit this later today

**Comment by rsandb** [comment]
Yeah, I noticed that. I'm not sure why because it renders properly in Chrome if I open it from the file folder

**Comment by rsandb** [comment]
![Asset 7](https://user-images.githubusercontent.com/45190934/209221909-a4ad8dab-3a6f-46e7-b3d9-750eebf7a8f5.svg)

**Comment by rsandb** [comment]
This one does the same thing. Maybe it's GitHub?

**Comment by andreaskoepf** [comment]
The file contained an embedded PNG which was responsible for ~90% of the filesize. I removed that:
![Open-Assist_Logo_Blue_rsandb](https://user-images.githubusercontent.com/9976399/209406404-d6393cd9-ff5f-4100-8904-94e8f3b48858.svg) (file is now 3,9kb).

**Comment by yk** [comment]
is in the repo under `assets`
