### ISSUE TITLE
Dataset: CAMEL Math and Physics

### ISSUE THREAD

**Issue by Miserlou** [LAION-AI/Open-Assistant#2501]
50K+ Math, Physics and Code inputs and outputs, sounds tasty but hidden in a zip file.

https://github.com/lightaime/camel#data-hosted-on-hugging-face

**Comment by Miserlou** [comment]
via https://twitter.com/hammh0a/status/1646524135538065409

**Comment by CheckMC** [comment]
Looks like a really good dataset. I can probably convert to OA format.

**Comment by Miserlou** [comment]
More sciences added, looks like in a more accessible format:

https://huggingface.co/datasets/camel-ai/chemistry
https://huggingface.co/datasets/camel-ai/biology

via https://github.com/lightaime/camel#data-hosted-on-hugging-face

**Comment by CheckMC** [comment]
On another look we might have to reconsider these datasets -- The license says that they are for research use only, not commercial. And, some was generated with GPT4

**Comment by camsdixon1** [comment]
Looks like this is completed. I'm going to close it out.
