### ISSUE TITLE
Add a way to view unformatted response when using inference

### ISSUE THREAD

**Issue by ashduino101** [LAION-AI/Open-Assistant#2508]
Currently, in the frontend, the assistant response is formatted no matter what. If the assistant responds with malformed or incomplete formatting (e.g. three backticks in multiple locations that aren't meant to represent a code block), the response may render incorrectly.
It would be nice to be able to view the plaintext (unformatted) response from the assistant in cases like this.

**Comment by AbdBarho** [comment]
Agree

**Comment by CertifiedJoon** [comment]
I would love to work on this. If you are okay with that, please do assign me.

**Comment by AbdBarho** [comment]
@CertifiedJoon if you are still up for it I can assign you

**Comment by CertifiedJoon** [comment]
@AbdBarho I am struggling to get inference up in my dev environment. I will update you when I have set it up successfully.

**Comment by AbdBarho** [comment]
> @AbdBarho I am struggling to get inference up in my dev environment. I will update you when I have set it up successfully.

You can get in contact with me on discord if you are still stuck.

**Comment by CertifiedJoon** [comment]
@ashduino101 

For such message,
<img width="526" alt="image" src="https://github.com/LAION-AI/Open-Assistant/assets/61619422/000f8e66-4375-4ab5-9971-623b372e90cb">


Do you mean something like this?
<img width="211" alt="image" src="https://github.com/LAION-AI/Open-Assistant/assets/61619422/c75a19ae-0d41-4882-babf-d1ecd1e2f03d">
