### ISSUE TITLE
Please recommend ways to contribute

### ISSUE THREAD

**Issue by rghosh08** [LAION-AI/Open-Assistant#2509]
Hello,

I am new in this community. I have expertise in RL (from my PhD) and LLM (fine-tuning with my company's internal data). I believe in the vision of conversation AI should be democratized for everyone's benefits. 

Appreciate recommendations on how I can make some meaningful contributions in this open source project.  

Thanks,
Rajat

**Comment by andrewm4894** [comment]
Hello and welcome!

Have a look in here for some ideas on how to get involved

https://github.com/LAION-AI/Open-Assistant/blob/main/CONTRIBUTING.md

**Comment by andrewm4894** [comment]
Closing this just to try keep issues clean as we go.
