### ISSUE TITLE
Feature to copy raw assistant's message (chat)

### ISSUE THREAD

**Issue by 0x22almostEvil** [LAION-AI/Open-Assistant#2515]
As title says. Not sure, but might be useful.

**Comment by davidak** [comment]
You can just select the text and use Copy-Paste?

**Comment by 0x22almostEvil** [comment]
> You can just select the text and use Copy-Paste?
> 
> Not sure if the added complexity is worth it. Might decrease UX, because it looks chaotic with too many features.

Markdown doesn't copy, and on mobile it takes a long time and isn't really practical ihmo

**Comment by JAsaxon** [comment]
I could like to contribute with this!

**Comment by 0x22almostEvil** [comment]
@notmd I think I can do it:
![image](https://user-images.githubusercontent.com/122345469/235363532-ea4d85c0-0f6d-4288-bf92-77efcc48f264.png)
![image](https://user-images.githubusercontent.com/122345469/235363534-3d71985b-5b8b-4f6d-8753-00156b365cc2.png)
