### ISSUE TITLE
Focus input when edit chat title or prompter message

### ISSUE THREAD

**Issue by notmd** [LAION-AI/Open-Assistant#2519]

**Comment by dosacat** [comment]
Hi, can this be assigned to me if possible?

**Comment by notmd** [comment]
Thank yo @dosacat, please try to use autoFocus props first. If it not work then we need a focus trap or something similar

**Comment by bishowX** [comment]
Hey, I haven't any activity or PR for this issue. @dosacat  are you still working this issue? if not I would like to contribute.

**Comment by dosacat** [comment]
> Hey, I haven't any activity or PR for this issue. @dosacat are you still working this issue? if not I would like to contribute.

Hi, I'm on it.

**Comment by bishowX** [comment]
> > Hey, I haven't any activity or PR for this issue. @dosacat are you still working this issue? if not I would like to contribute.
> 
> Hi, I'm on it.

Actually I've implemented the feature. how can I create a PR @notmd

**Comment by dosacat** [comment]
> Actually I've implemented the feature. how can I create a PR @notmd

Feel free to then, it's not too complicated a task.
