### ISSUE TITLE
Can't Delete chats

### ISSUE THREAD

**Issue by AnonGitCat** [LAION-AI/Open-Assistant#2532]
When I press the delete button in the "Your Chats" tab, the chat does not delete at all. Please fix this.

**Comment by Eroc123** [comment]
I believe that is a known issue, the delete buttons are currently just placeholders, the function to delete chat is not added yet

**Comment by AbdBarho** [comment]
We added a "hide" button for now, we will add delete later

**Comment by davidak** [comment]
Duplicate of https://github.com/LAION-AI/Open-Assistant/issues/2384

Please check for open issues before creating new ones.

**Comment by olliestanley** [comment]
Closing as duplicate, but hide chats is in now and we will support full delete soon
