### ISSUE TITLE
Sign In page throws an Error if an invalid email is used, but user doesn't receive feedback

### ISSUE THREAD

**Issue by oscjac** [LAION-AI/Open-Assistant#254]
If the user types `arbitryString` without the @ character, next throws a TypeError.

If `email@` with nothing after the @ character, next throws a 501 Error: Bad recipient address syntax.

I would fix this by simply checking for a valid email before calling next's `signIn()` function and, if the email isn't valid, adding an `<Alert>`(Chakra UI component) to the DOM explaining to the user why the email is invalid.

Thoughts on this solution?

**Comment by fozziethebeat** [comment]
I like this! I dont think this is a blocking bug but would be great to fix anytime soon.  You're approach makes sense so I've assigned it to you for now :)
