### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AkiDuino** [LAION-AI/Open-Assistant#2550]
Application error: a client-side exception has occurred (see the browser console for more information).

hallo yannic, 
ich bin neu hier, andi ist mein name.
test als erstes, nach umstellung auf deutsch, - als assistent .. seite läd .. black´screen: obiger fehler erscheint auf 100% black fullscreen .. 
ublock origin aktiv, sollte aber nichts mit dem fehler zu tun haben.
chrome win10

gruß - andi

**Comment by notmd** [comment]
Hi can you post a screenshot here?

**Comment by notmd** [comment]
Closing this since there is no response
