### ISSUE TITLE
Add an autoupdate functionality in the local version, and maybe one-click local installer

### ISSUE THREAD

**Issue by marcofernandez007** [LAION-AI/Open-Assistant#2552]
As received feedback from various endusers in addition to the docker image, it could be great to have a one-click installer for the various common OS platforms, potentially with an autoupdate functionality in the GUI afterwards, similar to the new features in GPT4All 2.0 in April.

**Comment by AbdBarho** [comment]
This repo is for developing the open assistant website & services, it is not for running the model in a nice UI.

You can download the models from huggingface and use any webui you like.
