### ISSUE TITLE
Not resuming where response cut off

### ISSUE THREAD

**Issue by AmanzioV** [LAION-AI/Open-Assistant#2556]
When the AI runs out of room during the response, it stops mid word. When asked to resume, how ever that ask is worded, the AI fails to resume, but is disjointed and not seamless and coherent. It was also unable to provide directions for how best to prompt it to continue; what it provided didn't work and wasn't an answer.

This was it's response: To continue your previous response, please type "..." at the end of this message and then provide the additional information or questions as needed. This will ensure a smooth continuation of our conversation without any interruptions or confusion. Thank you for your understanding! 

Providing it with this as a prompt to continue "To continue your previous response, please type "..." at the end of this message and then provide the additional information or questions as needed." Results in a response that is just "..." for example.
![Screenshot 2023-04-15 134202](https://user-images.githubusercontent.com/129108302/232252402-eb9213a9-87dd-4b8e-b30c-a90d432f1616.png)

**Comment by Armend** [comment]
Same here. Code got cut off and after asking to continue, it explained the code instead of finishing the missing lines.

**Comment by olliestanley** [comment]
This seems to just be a limitation of the model context length, we can't really do anything to "fix it" with the current models, maybe in future there will be models supporting longer context

**Comment by jidun67** [comment]
nourishment under constrained circumstances while avoiding undue gas exchange rates possibly promoting secondary metabolite synthesis from precursor supply bottleneck scenarios causing deleterious competition for vital limiting resources as CO_2 becomes scare one must keep track of evolving values monitored frequently in real-time so adapt

Model: OpenAssistant/oasst-sft-6-llama-30b
Preset: Custom

"monitored frequently in real-time so adapt"... {please continue}


...so adapt experimental designs accordingly with maximum efficiency possible allowing comprehensive evaluation of various parameters influencing cultivation performances determining whether or not those



When I do that (take its last text part and put it in quotes and then in curly brackets I ask it to please continue as an internal aside request) it works perfectly every time for me the more I used it the better it seemed to understand), and hopefully, it works for others.

**Comment by jidun67** [comment]
![Screenshot](https://user-images.githubusercontent.com/90736276/232524717-4450f3a9-839e-463f-a263-10f27a1fc3e9.png)

I hope this is an image...
