### ISSUE TITLE
Sorry, we encountered a server error. We're not sure what went wrong.

### ISSUE THREAD

**Issue by phalexo** [LAION-AI/Open-Assistant#2561]
I get the above error. I did a "docker compose ...." per instructions. I am running Ubuntu 20.04 on a SuperMicro with 330GB RAM and
4 Maxwell Titan X GPUs. 

I am able to initially connect to to the dashboard. The error appears when I click the "chat" option.

**Comment by MSDNAndi** [comment]
What do you get in the Console? Similar to what I saw?
https://github.com/LAION-AI/Open-Assistant/issues/2557

**Comment by phalexo** [comment]
> 

open-assistant-web-1                  |       _events: [Object: null prototype],
open-assistant-web-1                  |       _eventsCount: 7,
open-assistant-web-1                  |       _maxListeners: undefined,
open-assistant-web-1                  |       outputData: [],
open-assistant-web-1                  |       outputSize: 0,
open-assistant-web-1                  |       writable: true,
open-assistant-web-1                  |       destroyed: false,
open-assistant-web-1                  |       _last: true,
open-assistant-web-1                  |       chunkedEncoding: false,
open-assistant-web-1                  |       shouldKeepAlive: false,
open-assistant-web-1                  |       maxRequestsOnConnectionReached: false,
open-assistant-web-1                  |       _defaultKeepAlive: true,
open-assistant-web-1                  |       useChunkedEncodingByDefault: false,
open-assistant-web-1                  |       sendDate: false,
open-assistant-web-1                  |       _removedConnection: false,
open-assistant-web-1                  |       _removedContLen: false,
open-assistant-web-1                  |       _removedTE: false,
open-assistant-web-1                  |       strictContentLength: false,
open-assistant-web-1                  |       _contentLength: 0,
open-assistant-web-1                  |       _hasBody: true,
open-assistant-web-1                  |       _trailer: '',
open-assistant-web-1                  |       finished: true,
open-assistant-web-1                  |       _headerSent: true,
open-assistant-web-1                  |       _closed: false,
open-assistant-web-1                  |       socket: [Socket],
open-assistant-web-1                  |       _header: 'GET /chats HTTP/1.1\r\n' +
open-assistant-web-1                  |         'Accept: application/json, text/plain, */*\r\n' +
open-assistant-web-1                  |         'Content-Type: application/json\r\n' +
open-assistant-web-1                  |         'TrustedClient: eyJhcGlfa2V5IjoiNjk2OSIsImNsaWVudCI6IndlYnNpdGUiLCJwcm92aWRlcl9hY2NvdW50X2lkIjoiYTJjODA1MjctMmZiZi00ODg3LWI2MmMtMjdjN2UxOGE3YzlmIiwidXNlcl9pZCI6ImRldiIsInVzZXJuYW1lIjoiZGV2In0=\r\n' +
open-assistant-web-1                  |         'User-Agent: axios/1.3.4\r\n' +
open-assistant-web-1                  |         'Accept-Encoding: gzip, compress, deflate, br\r\n' +
open-assistant-web-1                  |         'Host: inference-server:8000\r\n' +
open-assistant-web-1                  |         'Connection: close\r\n' +
open-assistant-web-1                  |         '\r\n',
open-assistant-web-1                  |       _keepAliveTimeout: 0,
open-assistant-web-1                  |       _onPendingData: [Function: nop],
open-assistant-web-1                  |       agent: [Agent],
open-assistant-web-1                  |       socketPath: undefined,
open-assistant-web-1                  |       method: 'GET',
open-assistant-web-1                  |       maxHeaderSize: undefined,
open-assistant-web-1                  |       insecureHTTPParser: undefined,
open-assistant-web-1                  |       path: '/chats',
open-assistant-web-1                  |       _ended: false,
open-assistant-web-1                  |       res: null,
open-assistant-web-1                  |       aborted: false,
open-assistant-web-1                  |       timeoutCb: null,
open-assistant-web-1                  |       upgradeOrConnect: false,
open-assistant-web-1                  |       parser: null,
open-assistant-web-1                  |       maxHeadersCount: null,
open-assistant-web-1                  |       reusedSocket: false,
open-assistant-web-1                  |       host: 'inference-server',
open-assistant-web-1                  |       protocol: 'http:',
open-assistant-web-1                  |       _redirectable: [Circular *1],
open-assistant-web-1                  |       [Symbol(kCapture)]: false,
open-assistant-web-1                  |       [Symbol(kBytesWritten)]: 0,
open-assistant-web-1                  |       [Symbol(kEndCalled)]: true,
open-assistant-web-1                  |       [Symbol(kNeedDrain)]: false,
open-assistant-web-1                  |       [Symbol(corked)]: 0,
open-assistant-web-1                  |       [Symbol(kOutHeaders)]: [Object: null prototype],
open-assistant-web-1                  |       [Symbol(kUniqueHeaders)]: null
open-assistant-web-1                  |     },
open-assistant-web-1                  |     _currentUrl: 'http://inference-server:8000/chats',
open-assistant-web-1                  |     [Symbol(kCapture)]: false
open-assistant-web-1                  |   },
open-assistant-web-1                  |   cause: Error: getaddrinfo ENOTFOUND inference-server
open-assistant-web-1                  |       at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
open-assistant-web-1                  |     errno: -3008,
open-assistant-web-1                  |     code: 'ENOTFOUND',
open-assistant-web-1                  |     syscall: 'getaddrinfo',
open-assistant-web-1                  |     hostname: 'inference-server'
open-assistant-web-1                  |   }
open-assistant-web-1                  | }

**Comment by phalexo** [comment]
> What do you get in the Console? Similar to what I saw? #2557

Looks like the inference-server fails to be loaded, or fails thereafter, or their config does not account properly for running things locally.

**Comment by notmd** [comment]
Which docker command did you run? This is recommended command to start the dev env
```
docker compose --profile frontend-dev --profile inference up --build --attach-dependencies
```

**Comment by phalexo** [comment]
> I get the above error. I did a "docker compose ...." per instructions. I am running Ubuntu 20.04 on a SuperMicro with 330GB RAM and 4 Maxwell Titan X GPUs.
> 
> I am able to initially connect to to the dashboard. The error appears when I click the "chat" option.

The compose config instructs to add "--profile inference" to the "docker compose ..." but it does not appear to work.

So, the inference-server is not being built apparently.

**Comment by AndrewBarfield** [comment]
I having the same problem. The original docker command line doesn't start the inference server but the suggested change above causes the UI (on port 3000) to fail.

**Comment by phalexo** [comment]
Hm. Combining "ci" with "inference" appears to get rid of the error. That said the sequence of actions was

1) docker compose --profile inference --profile frontend-dev up --build --attach-dependencies
Seemed to hang, ctlr-C, but it appeared to download and build inference.
2) I tried to reverse "frontend-dev" with "inference" but after doing something it still hung.
3) combine "ci" and "reference" and this seems to work.

**Comment by wendelltron** [comment]
```compose --profile frontend-dev --profile inference --profile ci up --build --attach-dependencies```

Worked for me but I also did a ```pip install -e .``` inside the data folder. 

It seems like the docker file inference engine is gpt2 by default as well and that will need to be changed to whatever you want to use from hugging face.

**Comment by phalexo** [comment]
Well, although I get a chat screen now, and can enter a question, it has no answers. Either it is incredibly slow or there is another issue. It tells me that I am 2 or first in queue, then that I am at 0, but no answers.

**Comment by wendelltron** [comment]
Right so start a new chat, hit the gear before you type a message and select the gpt2 option? Based on the default docker compose looks like it picks the gpt2 model. If that works then it's just configuring and downloading the model I'd guess

**Comment by phalexo** [comment]
> Right so start a new chat, hit the gear before you type a message and select the gpt2 option? Based on the default docker compose looks like it picks the gpt2 model. If that works then it's just configuring and downloading the model I'd guess
> 
> Based on the docker compose is what inference system gets up and running.

Thanks. I put it on gpt2 and it gave me a lot of nonsense when I asked about orthonormal polynomials. At least it seems to work.

**Comment by wendelltron** [comment]
I wrote a guide (unofficial) that worked for me

https://forum.level1techs.com/t/open-assistant-12-billion-parameters-ought-to-be-enough-for-anyone-quick-setup-guide/196202

**Comment by phalexo** [comment]
Should MODEL_CONFIG_NAME be "custom" not "oasst1" in the
Dockerfile.worker-full?

**Comment by wendelltron** [comment]
Yes, good catch. This seems not to matter as I was trying to make the gui
default to custom (have to click the gear and select custom from the web ui
once you get to the ⁉️ n asking part) but it seemed not to be this option
to set the default model.

**Comment by phalexo** [comment]
I am having a bit of an issue with this:
Error response from daemon: could not select device driver "nvidia" with
capabilities: [[gpu]]
I thought that I typed the stuff in pretty faithfully.

I already have the nvidia driver installed on the host.

Any suggestions?

**Comment by wendelltron** [comment]
Are you able to run Nvidia smi and see your Nvidia GPU output? We could
maybe troubleshoot this outside the big tracker given it's a bit out of
their scope I suspect

**Comment by phalexo** [comment]
Yeah, I see the GPUs. Not sure where one can discuss this outside of this
venue. It is just a single thread, and may be helpful to others as well.

**Comment by phalexo** [comment]
It appears that the worker container needs to have an nvidia driver
installed to prevent the error. I am not sure why you did not have this
issue. I am trying to mix the nvidia container with Open Assistant one, or
install nvidia stuff.
