### ISSUE TITLE
Understand error logs

### ISSUE THREAD

**Issue by AbdBarho** [LAION-AI/Open-Assistant#2569]
I see a lot of errors like this on the web container:
```
OasstError {
  message: 'User not found',
  errorCode: 4002,
  httpStatusCode: 404,
  path: '/api/v1/frontend_users/discord/1111',
  method: 'GET'
}
OasstError {
  message: 'User not found',
  errorCode: 4002
  httpStatusCode: 404,
  path: '/api/v1/leaderboards/day?max_count=5',
  method: 'GET'
}
```

we should try and understand what is causing this.

My hypothsis:
new users login to the webpage, the website will try to get their stats & leaderboards, but fails to do so because they have not contributed any data yet, and therefor still don't have any account in the backend.

**Comment by notmd** [comment]
If your hypothesis is correct. I think we should disable swr retry on error globally, since many user only use chat only, and swr will retry forever
