### ISSUE TITLE
Incorrect Chinese translation for "fails_task.question"

### ISSUE THREAD

**Issue by wg138940** [LAION-AI/Open-Assistant#2570]
Hi，今天 #2418 里的翻译修改生效了，但是从网页前端看，原来的“作为对于该提示任务的回答，这是一个糟糕的回复吗？”（`fails_task.question`）的翻译的意思貌似混淆了，原来，用户需要对糟糕的回复回答“是”，但是在现在的翻译中（“对于这个聊天对话而言，此回复是否是一个好的回复？”），意思变成了需要对好的回复回答“是”

https://github.com/LAION-AI/Open-Assistant/commit/e51e0328793c311371515ce6a3065d40f0dab7ce#diff-8dd85f45ce074f451900ac071e43ef98751ce50312887aabbcd20c0cf4e83303R2

-----

Hi, today the translation modification in #2418 took effect, but from the web front end, the original translation of "作为对于该提示任务的回答,这是一个糟糕的回复吗?" (`fails_task.question`) seems to be confused. Originally, the user needed to answer "Yes" to the bad reply, but in the current translation ("对于这个聊天对话而言,此回复是否是一个好的回复?"), the meaning has become that you need to answer "Yes" to a good reply.

https://github.com/LAION-AI/Open-Assistant/commit/e51e0328793c311371515ce6a3065d40f0dab7ce#diff-8dd85f45ce074f451900ac071e43ef98751ce50312887aabbcd20c0cf4e83303R2

**Comment by AbdBarho** [comment]
can you change this please?

**Comment by lone-wolf-akela** [comment]
Pull request #2418 simply reversed #2396 and actually made it worse, which just makes me sad...

**Comment by AbdBarho** [comment]
@lone-wolf-akela can you create a PR with a fix? we can then lock down that part of the code
