### ISSUE TITLE
typos at the worst possible moment

### ISSUE THREAD

**Issue by alexander-macleod** [LAION-AI/Open-Assistant#2575]
<img width="351" alt="Screenshot 2023-04-16 at 7 26 30 AM" src="https://user-images.githubusercontent.com/6178165/232272916-d7d1036b-a10b-4fb6-a52e-cc49a4d5dbaf.png">

- Just when you signup, google/gmail marks the verification email as "fraudulent", email goes directly to spam. 
- You give the email the benefit of the doubt but you double check the sender for signs of "Open Assistant"
- You see this [image attached]

surely an easy fix? looks soooooooooo scammy

**Comment by olliestanley** [comment]
I think fixing this is in-progress and this has been reported previously so will close as duplicate
