### ISSUE TITLE
Add instruction to reverse augmentation

### ISSUE THREAD

**Issue by CloseChoice** [LAION-AI/Open-Assistant#2577]
We currently support reverse augmentation for the alpaca datasets. This proved to be not really helpful till now. As mentioned in section 5.1.1 of the [paper](https://arxiv.org/abs/2303.18223) we should probably generate some additional instruction, e.g. "Please generate a question based on the answer:" in the question part.

**Comment by ambujpawar** [comment]
Hi, I am new to this project and would like to contribute towards it.
This seems like something I could pick up.

Can you please help with explaining how should I start working with it?

**Comment by DominiqueGarmier** [comment]
i believe you can start by adding adding a new task type here: https://github.com/LAION-AI/Open-Assistant/blob/7be14b7e9c6a2e85b8c003728d7cc1126fc9f8d7/oasst-shared/oasst_shared/schemas/protocol.py#L11

and then adding support for it on the front and backend

**Comment by CloseChoice** [comment]
@DominiqueGarmier we would just add this for the datasets that already support the `reverse_augmentation` keyword for now. Maybe if it yields good results, we can add it in the `DatasetEntry` class to support it on all datasets. So maybe we could start with the alpaca loader

**Comment by CloseChoice** [comment]
Ok, with the merge of #2870 some things changed here. We need to implement this for the [`get_formatted` method of `DatasetEntry` class](https://github.com/LAION-AI/Open-Assistant/blob/main/model/model_training/custom_datasets/formatting.py#L84). So maybe adding a test [here](https://github.com/LAION-AI/Open-Assistant/blob/main/model/model_training/tests/test_formatting.py) and checking if questions and answers are reversed would be a good start.

**Comment by andreaskoepf** [comment]
I close this for now since reverse-augmentation was causing more harm than it helped.
