### ISSUE TITLE
Create Discord and Github Button Components

### ISSUE THREAD

**Issue by k-nearest-neighbor** [LAION-AI/Open-Assistant#258]
Use the buttons in CallToAction.tsx as a base.

Create Discord and Github buttons which can take arbitrary text like "Continue with Discord" / "Sign in with Discord" / "Join Our Discord Server". They should live in `src/components/Buttons/3p.jsx`

Properties: 

- ButtonText
- onClick
- colorVariant and/or className

The sign in page can use these buttons.

**Comment by KarthikRaju391** [comment]
Hi @k-nearest-neighbor, I would like to work on this!
I think the plan for this would be similar to what you have mentioned here.

**Comment by k-nearest-neighbor** [comment]
@KarthikRaju391 go for it :)

**Comment by KarthikRaju391** [comment]
Hey @k-nearest-neighbor, I won't be able to work on this for couple of days. I think I should be unassigned as of now. Sorry!

**Comment by AbdBarho** [comment]
what the status here, can we close?
