### ISSUE TITLE
Allow an option for opting out of training data collection for each chat

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#2580]

**Comment by olliestanley** [comment]
#2820 will add the backend support for this

**Comment by olliestanley** [comment]
Backend support for data opt out is merged, we now need the website to support this

**Comment by mtosity** [comment]
I will take this one and put this as an button in the drop down (above the delete button)
![Image](https://user-images.githubusercontent.com/40803798/236990100-3e2aadba-8720-4810-9cac-14fba0ea0c72.png)


But the user might also need to know which chat already opt out
