### ISSUE TITLE
Implement chat deletion

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#2582]
for now we just have hide

**Comment by olliestanley** [comment]
The inference backend supports full deletion so we just need a frontend addition here.

**Comment by ruoniw** [comment]
Will try take a look at this one as well

**Comment by yk** [comment]
@ruoniw thank you! can this e closed?

**Comment by olliestanley** [comment]
Yes this can be closed

**Comment by titonova** [comment]
@olliestanley Sorry, how do you delete messages now, from the frontend
