### ISSUE TITLE
Pagination in chat listing

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#2584]

**Comment by mtosity** [comment]
Hey @yk is this feature open for contributor? I can take this

We need pagination for this page right?

![Image](https://user-images.githubusercontent.com/40803798/232372542-b90d972d-290b-4a85-984b-a8f6b04591f7.png)


What is the API for pagination? I saw we use `api/chat` to get all the chat threads

Will we prefer "Show more" (like chatGPT) or "page 1,2,3" type of pagination?

**Comment by notmd** [comment]
@mtosity thanks, we need  a cursor pagination. the UI has to fetch more chat when scrolling down

**Comment by notmd** [comment]
> What is the API for pagination? I saw we use `api/chat` to get all the chat threads
> 

https://github.com/LAION-AI/Open-Assistant/blob/main/inference/server/oasst_inference_server/routes/chats.py#L20

**Comment by yk** [comment]
@mtosity this is now possible. would you like to build on top of https://github.com/LAION-AI/Open-Assistant/pull/2773 ?

**Comment by mtosity** [comment]
@yk Would love to, the api from #2773 works great in my local
