### ISSUE TITLE
LaTeX support for the assistant chat

### ISSUE THREAD

**Issue by leowalkling** [LAION-AI/Open-Assistant#2588]
Currently, LaTeX snippets in the assistant chat are rendered like
![image](https://user-images.githubusercontent.com/6926277/232290128-9c33d890-3f5f-45b2-aacb-07561ff5064c.png)

If the markdown rendering engine were to be configured with add-ons to use MathJax, something like the following could be produced:
![image](https://user-images.githubusercontent.com/6926277/232290432-0f6990df-0d33-4170-a19c-54677416ab9f.png)

**Comment by DominiqueGarmier** [comment]
using [remark-math](https://github.com/remarkjs/remark-math) should do the trick?

**Comment by DominiqueGarmier** [comment]
![image](https://user-images.githubusercontent.com/42445422/232703961-8619adb2-575b-4e29-b8b2-5729c65ed7dd.png)

it works now, i think you can close this issue
