### ISSUE TITLE
Support right to left languages in the UI

### ISSUE THREAD

**Issue by RaananHadar** [LAION-AI/Open-Assistant#2589]
Currently right to left languages such as hebrew or arabic are aligned to the left. This mixes the text in the wrong direction and can very likely cause users feeding you with bad data for anything other than basic messages!

Here is an example screenshot of using Hebrew:
<img width="1018" alt="Screenshot 2023-04-16 at 13 00 05" src="https://user-images.githubusercontent.com/4788815/232292545-739449a8-7249-4089-a7ae-b0b4f7852d20.png">

Here is how it should look like:
<img width="995" alt="Screenshot 2023-04-16 at 13 06 26" src="https://user-images.githubusercontent.com/4788815/232292815-d350208d-2bc7-4fd9-8d83-f8eac36dce64.png">

**Comment by notmd** [comment]
dup #916
