### ISSUE TITLE
not generating anymore content

### ISSUE THREAD

**Issue by ApahSaroj** [LAION-AI/Open-Assistant#2590]

**Comment by olliestanley** [comment]
Please clarify what you mean by this

**Comment by ApahSaroj** [comment]
While giving prompts,

https://user-images.githubusercontent.com/84530564/232308354-5fa6361e-aedd-4936-bed9-e0720fe6d2cf.mp4

 it is not generating any content..pfa

**Comment by davidak** [comment]
Today i had the issue that the response was not loading. Some hours later, it says timeout. So the system seem overloaded.

![Screenshot from 2023-04-28 16-39-44](https://user-images.githubusercontent.com/91113/235178045-b17a33ce-cf66-43ec-9394-c14d73d68092.png)

Example Chats:

0644ba35-3d14-7002-8000-ce3d0281525e
0644b9fc-5ab6-7391-8000-a5d983946068
