### ISSUE TITLE
回复内容不连贯，出现漏掉内容；而且有时候不能用中文回复

### ISSUE THREAD

**Issue by liuhuiyi66** [LAION-AI/Open-Assistant#2591]
Google translate from title: "The content of the reply is incoherent, and there is missing content; and sometimes it is impossible to reply in Chinese"

**Comment by jackdiy** [comment]
很多时候都不能正确使用中文回复，这个多语言对话体验相当差，不知道问题出在哪里，比其他LLaMA训练的模型好像有较大区别

**Comment by 0dminnimda** [comment]
Can you use English please?

**Comment by liuhuiyi66** [comment]
> Can you use English please?

Yes, I can use English, but not proficiently; problem: even responsing in English sometimes miss content. Sometimes can't reply in Chinese
