### ISSUE TITLE
How do I run chat UI locally?

### ISSUE THREAD

**Issue by Rudd-O** [LAION-AI/Open-Assistant#2593]
I'm following the instructions of the `inference` folder to run the app locally, and so far I can chat using `docker attach` just fine.  What I'd like to do is to run the nice UI locally (bonus / stretch goal: use the Open Assistant API directly from Home Assistant to interface with the model via HA).

How do I do this?  The instructions don't mention the steps necessary to do this.

My goal is to run the whole shebang fully locally on my network, accelerated by a GPU, allowing me to select which model is to be used.

Thanks in advance.

**Comment by olliestanley** [comment]
If you have Docker composed up the `inference` profile, you will need to run the frontend website to have the UI. The README here discusses running the website locally https://github.com/LAION-AI/Open-Assistant/tree/main/website

**Comment by AbdBarho** [comment]
This entire repository is for development only, if you want to run the models, checkout huggingface. you don't need to setup this repo if you just want to try the model.

**Comment by nicolas-dufour** [comment]
Hi, but what if we want to use the data-collection / chat interface locally? Is the dev repo the only way to do this? Or is there a more user-friendly way to do this?

**Comment by Rudd-O** [comment]
I don't want to try the model on some org's webpage.

I want to run the full stack, 100% locally, using my collection of GPUs.

Thanks for the link to the instructions to deploy the Web site.

**Comment by AbdBarho** [comment]
> Hi @AbdBarho , but what if we want to use the data-collection / chat interface locally? Is the dev repo the only way to do this? Or is there a more user-friendly way to do this?

if you want to run the data collection locally, then yes, you have to go through the setup.

if you really just want the chat, there is no need to build 13 different containers with tens of gigabytes of packages. Not to mentioned that the model itself is not even part of this entire setup.



You can download and use the model from huggingface easier and faster
https://huggingface.co/OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5

and if you really need a UI, you can try this: https://github.com/oobabooga/text-generation-webui

> I don't want to try the model on some org's webpage.
I want to run the full stack, 100% locally, using my collection of GPUs.

Understandable, I am just saying this because it is a waste of time & resources for everyone.

**Comment by RobertoDonPedro** [comment]
I think that this dev repository should be  fully executable locally with Docker, including the chat. 
I also managed to run it with docker including inference, but the chat isn‘t functional.  But I would invest resources to make the chat functional if anyone could provide guidance??

**Comment by Rudd-O** [comment]
> if you really just want the chat, there is no need to build 13 different containers with tens of gigabytes of packages. Not to mention that the model itself is not even part of this entire setup.
> 
> You can download and use the model from huggingface easier and faster https://huggingface.co/OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5

Uh, which file there is the executable I run?

Basically the question is what's the absolute minimum stack I need to run in order to ask questions of the model with a nice GUI interaction.  The closest I've found is the `inference/README.md` file, which doesn't really answer that question.

**Comment by olliestanley** [comment]
> > if you really just want the chat, there is no need to build 13 different containers with tens of gigabytes of packages. Not to mention that the model itself is not even part of this entire setup.
> > You can download and use the model from huggingface easier and faster https://huggingface.co/OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5
> 
> Uh, which file there is the executable I run?
> 
> Basically the question is what's the absolute minimum stack I need to run in order to ask questions of the model with a nice GUI interaction. The closest I've found is the `inference/README.md` file, which doesn't really answer that question.

You can use that model with an existing web UI solution like [this one](https://github.com/oobabooga/text-generation-webui)

**Comment by Rudd-O** [comment]
Oooooh.  That is much nicer than I expected!  Thank you.

**Comment by Rudd-O** [comment]
Sadly for me, the 12b and the 6.9b models simply don't fit the RAM in my video card.
