### ISSUE TITLE
Only gpt2 model seems to work.

### ISSUE THREAD

**Issue by phalexo** [LAION-AI/Open-Assistant#2598]
I am not certain if it is an issue or a misconfiguration of some kind.

When I do "docker compose ...." do any of the models,/checkpoints, other than gpt2, get downloaded? If so, where are they placed? If not, then where can I get all the other models listed in the drop-down menu?

Thanks.

**Comment by olliestanley** [comment]
We cannot distribute the LLaMa-based models in full form due to Meta's license. You can use the Pythia models locally by configuring your local inference worker's "model config name" setting to the name of the Pythia model on OA HF.

**Comment by phalexo** [comment]
Are these the same FB models, in unmodified form, that were leaked or some
derivatives?

**Comment by olliestanley** [comment]
@phalexo As explained in the announcements etc, these are models fine-tuned for instruction following using OA and other data
