### ISSUE TITLE
Please add step by step instructions in the readme for simple local chat.

### ISSUE THREAD

**Issue by iplayfast** [LAION-AI/Open-Assistant#2602]
I want to run open-assistant locally using text, I've an interest in offline applications that would benefit from AI.
I don't understand docker and  how to use it. Current readme instructions seem geared towards web interface.

What I would like is c++ or python code that can run a text interface.
What is currently here feels like a city block when all I want is a mobile home.

**Comment by olliestanley** [comment]
If you just want to run the model locally you probably shouldn't be using this repo. You can get the model (Pythia currently available, LLaMa delta weights available soon) from the OA HuggingFace page, then use it like any other local model

**Comment by iplayfast** [comment]
I didn't realize the models were interchangable.
