### ISSUE TITLE
Delete chatbox text only after receiving confirmation that the request has been placed

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#2604]
it's quite annoying when we are under high load and the request 500s, but the chat box is cleared anyway, means I have to re-type everything.

**Comment by amitag2** [comment]
I'd like to work on this issue!

**Comment by bishowX** [comment]
Hey @amitag2  @yk since it has been 3 days and it's still in the todo status, i was wondering if i could work on this

**Comment by yk** [comment]
Yes please

**Comment by yk** [comment]
Sorry for being so late. Can you two decide amongst yourselves? Thank you

**Comment by bishowX** [comment]
@yk do I need to be assigned to work on this?

**Comment by yk** [comment]
no, all good. I'll assign both of you for now

**Comment by amitag2** [comment]
Sorry for the delayed response, go ahead!
