### ISSUE TITLE
Creating augmented data using few-shot prompts for explanations of jokes, logical inferences, etc.

### ISSUE THREAD

**Issue by ontocord** [LAION-AI/Open-Assistant#261]
See https://www.lesswrong.com/posts/EHbJ69JDs4suovpLw/testing-palm-prompts-on-gpt3.

Try doing 2, 3 or 4 shot inference  on something like JT or neox 20B or galactica. 

After we find a promising model and configuration, we can scrape the net for jokes and paragraphs with logical inferences to create dialog data.

Human: Tell me a joke about {extract keywords from joke}
Assistant: {joke}
Human: Explain the joke.
Assisant: {explanation}

See also https://storage.googleapis.com/pathways-language-model/PaLM-paper.pdf

**Comment by smytjf11** [comment]
Going with the movie reviews idea, could we use the Rotten Tomatoes dataset to generate prompts, maybe supplement with one of the models fine tuned on it as well?

https://huggingface.co/datasets/rotten_tomatoes

**Comment by momegas** [comment]
The idea is to create a dataset with explanations. Like for example take the movie dataset and do this:
`This is a movie review for the movie {movie}: {review}. This movie review is {classifciaiton} because ...[your created answer]`
Am I right?
I'm interested in picking this up. How large should the dataset be?

**Comment by ontocord** [comment]
@momegas yes. if it is very compute intensive, it doesn't need to be large. maybe see if you can get it to work first. And then we can discuss size. we can run it on some extra compute.

**Comment by mikegarts** [comment]
Sound like a very cool task and I would love to give it a try if it is still relevant :)

**Comment by mikegarts** [comment]
@kkie02 Sure, I'm in discord as mikegarts. Feel free to ping me.
Btw I just opened a pr with somewhat relevant instruction dataset https://github.com/LAION-AI/Open-Assistant/pull/2209 but would love to cooperate on further work.

**Comment by 0x22almostEvil** [comment]
Going to work in this field, but with more specific tasks (semantics, logic, reasoning)
https://github.com/LAION-AI/Open-Assistant/issues/3122

**Comment by andreaskoepf** [comment]
Closing old data issue.
