### ISSUE TITLE
Padding is bit different in chat UI vs full UI which makes buttons jump a bit

### ISSUE THREAD

**Issue by DoctorKrolic** [LAION-AI/Open-Assistant#2613]
Just a bit annoying for the eyes:
![firefox_a2tzaoFPe3](https://user-images.githubusercontent.com/70431552/232325981-a304bb5b-fbcd-4b28-99d4-ba15f1f29f8d.gif)

**Comment by notmd** [comment]
Thanks, the hold chat UI will be redesigned later.
