### ISSUE TITLE
can't seem to accept the terms of service

### ISSUE THREAD

**Issue by butlekvi** [LAION-AI/Open-Assistant#2615]
Initial login asks for acceptance of "Terms of Service for Open Assistant".
Clicking on "accept" appears to do nothing.
Changing languages and accepting there also does nothing

**Comment by SimonWilksAL** [comment]
Same for me. Only declining works.

**Comment by dakilasera** [comment]
Check out if you have a user name already. if it is empty as in 'no user name'. set it and try again.

**Comment by SimonWilksAL** [comment]
That fixed it for me. Thx.
