### ISSUE TITLE
https://open-assistant.io/chat not working

### ISSUE THREAD

**Issue by butlekvi** [LAION-AI/Open-Assistant#2618]
Sorry, we encountered a server error. We're not sure what went wrong.

[Go back to the dashboard](https://open-assistant.io/dashboard)

**Comment by olliestanley** [comment]
This was probably just overload. Is it working again for you now?

**Comment by andrewm4894** [comment]
Working ok for me

**Comment by butlekvi** [comment]
Thanks,
It’s working now
Best regards,
Kevin
