### ISSUE TITLE
Rename/amend "messages" page to make it clear they come from the data collection, not from users' chats

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#2630]

**Comment by alexfilothodoros** [comment]
Hi! Can I take this task?

**Comment by yk** [comment]
Sure, thank you

**Comment by yk** [comment]
hi @alexfilothodoros any updates on this? no stress, just asking

**Comment by alexfilothodoros** [comment]
Hi @yk sorry for the delay. I am on my way back from a conference. I will do it this week.

Cheers
Alex
