### ISSUE TITLE
When chats are hidden, they can not be seen again.

### ISSUE THREAD

**Issue by holy-mother-I-am-drunk** [LAION-AI/Open-Assistant#2634]
When clicking the hid chat button, it hides permanently, with no way of showing it again.
Asking the AI about it gave me this:

> If you are using Open Assistant web interface, follow these steps to view your hidden conversations:
>
>Click on the gear icon (Settings) located in the bottom right corner of the page.
>
>From the drop-down menu, navigate to "Chat Preferences".
>
>On the "Chat Preferences" page, look for the "Ignored Chats" section and expand it by clicking on the arrow button next to the title.
Here you'll find a list of all the conversations you have ignored or marked as read-only. Find the desired conversation and check the box next to it to enable it again.
>
>After enabling the conversation, you can now start typing and sending messages just like before.
>
>Note: Hidden/ignored chats will remain hidden on the main conversation list but can still be accessed through search.
>
>If you are using a different version of Open Assistant, please provide more information about which application you are referring so I can assist you better.

I don't know if this is a developer only thing that it is showing, or it's just hallucinating.

**Comment by olliestanley** [comment]
We have an issue #2583 to resolve this so will close this as duplicate. The AI chat is pure hallucination :)
