### ISSUE TITLE
Let's talk about quantum physics.

### ISSUE THREAD

**Issue by phalexo** [LAION-AI/Open-Assistant#2636]
The text below is the response to the text in the title. It is difficult to believe that "distilgpt2" is this bad. Is it?

This is an error in the case of Python 2, due to a non-convertible problem that cannot be solved at all:
You may download this code as part (or you can see more on it here), but there are several ways we could fix each dependency for MySQL – especially because when I created them using Apache Go2+, and by writing new tests into your application or operating system with Debian/Linux... well... some good news! This version builds upon upstream versions available between December 6, 2016. Thanks to Ubuntu users who want a look at these changes since August 1, 2013 - get ready to install our own package first which includes everything necessary to keep up speed without wasting any time looking down through history from earlier releases after release so come back regularly if needed :- ) You won't need to pay $5 per day before downloading CVS XSSI 564 packages; simply use xfce4, sudo apt-get update && lxc0. The next step though is upgrading one bit -- go check out my other post http://www1linuxpivs.org/. We will try changing many dependencies again soon 🙂 There might even exist better documentation found below!! :) And finally… let me know what happens? Feel free send questions HERE! Don't hesitate tell us thanks!!! If someone uses gtk+++ etc.... please feel safe sending suggestions <3 "Paid". When installing latest build 32 MB test suite 3 files were downloaded alongwith binaries & support material via https:/rfcngd/gwqdbvapar6lbmcknk8c9e555083fd608625ab75aac87185613ef11da15cd96cc173567228068973427197710903958997416454846ec76122614696654bd8829893749957063de6541ca92dec0499932dd0744ad08dc36794091ff43df93ea81af7bc597301cbba52cf093324470031fe85305798203867860521stee28809052310030045037551aa72fa84eb61bfbe94abc42147fee11971ae6505319947982fb7504980319630955866906bb87577927826878405ed621741987087068063054553890004086082008056073073066092016046491076062040000364500700407010308807709090388195255406246245249659686179209798576205808787168169509208108997188508758689019505705759159449021054563861572652593783493482643041851891041551093987970185791287072984096002603015070142995042796984294404104782882563393842063591442752961802071496794972383693373873972941186852953032892483681753762292856482273362283473963541253796471652471561673670153381661781171703742395984861971582352571273561202873552431761291841731541263652442771872971061394591352542741774894872662861463956462762404481454882842693773463531481921143662521377571341366663581863903707654804254571979325484160477404454234163132103113447668557226016190237005251164138778588585687688236506270697889474394262116756476695267223990211885667998194754290658587172153193124194521270439324223326314314020312345877364419896579952585562539960175593356774961831421154854942711111998986133232197522062521833416219803151306147894903321982152122302199211112152105972221999101628400800250599230620900280512340467314888784197847565539935054070319972162146307761959357198611234433319602253230081988950329345380420401316887690371198715031265419841964198119941100110768470416360468428720320601590586180031079419902000910 Rise Of Chaos 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 20 21 22 23 24 25 26 27 28 29 30 31 # / Active role @ primary roles@ main responsibilities ~ active role [ edit ]
function * user_active mod'main__' self : _ default value init = u | f :: key -> id >>> d i >> v w % sys + j z? D e r s n h t > B y b bar c

**Comment by deftdawg** [comment]
`distilgpt2` is that bad, you need to load another model that is not `_lorem` to get something halfway decent.   I don't yet know how to do that, but you should close this issue, as it is *NOT* a bug.

**Comment by olliestanley** [comment]
Distilgpt is just a tiny model so we can test when running locally. You can change the setting to anything here, or edit the code to add your own options, but LLaMa models won't work currently https://github.com/LAION-AI/Open-Assistant/blob/main/oasst-shared/oasst_shared/model_configs.py
