### ISSUE TITLE
I don's seem to be getting points.

### ISSUE THREAD

**Issue by drkrunk** [LAION-AI/Open-Assistant#2638]
I have done some tasks and have yet to accumulate any stars/score. I have also seen several of the same exact tasks and had multiple toast messages saying "Something went wrong.". While I don't really care about the point system, I'm starting to come to the conclusion that I'm wasting my time trying to help with such an error prone project, as I'm not even confident that it's even saving my answers or helping in any way.

**Comment by luphoria** [comment]
It's likely you have to wait for your posts to get reviewed before receiving points. I've noticed that I don't get points immediately, but I did see them later:
![image](https://user-images.githubusercontent.com/60309933/232358431-7a300c78-ec66-4e01-8c91-8ef5263ede73.png)
My guess is that it has to do with "Accepted" in your account dashboard, assuming that means "accepted into the dataset" (maybe after manual review?):
![image](https://user-images.githubusercontent.com/60309933/232358522-9b1796fb-3767-40f1-9ccc-98c0428fa465.png)

**Comment by notmd** [comment]
The statistic update every 5 minutes, so please wait a bit.

**Comment by drkrunk** [comment]
Thanks for the replies! I found the stats section and it seem that you are correct; one probably gets point if your answers a accepted. I was just worried that it wasn't counting anything I was doing.
