### ISSUE TITLE
Add a "stop generation" button to chat.

### ISSUE THREAD

**Issue by Majdoddin** [LAION-AI/Open-Assistant#2647]
I am trying the online chat, sometimes it takes too long because of queuing. Sometimes it even seems it has hanged.
That button would be very useful then.

**Comment by alexn-s** [comment]
i think this is a very important feature. sometimes i wait for 20 seconds when it generates a long text.

perhaps there could be a "settings" page or toggle to cancel the generation when new text is entered and send (as a settings name: cancel generation on new text?)

**Comment by olliestanley** [comment]
Closing as covered by #2815. Although this issue was submitted first, the other one has already been added to the project board so it makes sense to retain it and close this one
