### ISSUE TITLE
Use non-LLaMa based models in Web Chat?

### ISSUE THREAD

**Issue by Maniues** [LAION-AI/Open-Assistant#2648]
LLaMa-based models are good, but I would like to try other models (Pythia-based).
When it will be possible to select other models in Chat?

**Comment by olliestanley** [comment]
I think this will not be implemented as the Pythia models can be run elsewhere (e.g. on HF space here) and we want to have our best models on the site to collect good data

https://huggingface.co/spaces/olivierdehaene/chat-llm-streaming

**Comment by olliestanley** [comment]
> While the Pythia-based models might not be good enough, i would like to see LLaMa replaced by an open source model like RedPajama or StableLM.

Neither of these projects have released sufficiently large models to be useful yet
