### ISSUE TITLE
I can't find the chat dialog box

### ISSUE THREAD

**Issue by ws694617206** [LAION-AI/Open-Assistant#2653]
I can't find the chat dialog box

**Comment by notmd** [comment]
Hi what do you mean "can't find the chat dialog box"? Can you provide screenshot or give us more context?

**Comment by ws694617206** [comment]
It's my problem, I didn't see the bottom part. I need to agree to the content on the panel first. There are too many terms that need to be dropped down. I suggest placing the terms in a dropdown box and displaying a 'I agree' at the bottom of the webpage, rather than pulling down the bottom part to see 'I agree'
