### ISSUE TITLE
Multi-language problem, the response language is different from the prompt language.

### ISSUE THREAD

**Issue by hstk30** [LAION-AI/Open-Assistant#2655]
I submit Chinese prompt, but the response content is English. It's weird.

**Comment by notmd** [comment]
Hi can you post the message link here?

**Comment by dddvanming** [comment]
![IMG_20230417_175252](https://user-images.githubusercontent.com/86154358/232450416-f330b3b8-cb62-4992-bcc5-6f74b044c53b.jpg)
Yes,but try again about 2-3 times to give the correct language, I think it caused by chinese messages treees is much lower than English or insufficient chinese data in rlhf.🤔

**Comment by notmd** [comment]
Just down vote it, might be the current limitation of the model.

**Comment by solyarisoftware** [comment]
Well, chatting in Italian I have answers in Italian, but with low quality. See: https://github.com/LAION-AI/Open-Assistant/issues/2659

> I think it caused by chinese messages treees is much lower than English or insufficient chinese data in rlhf.

I'm not sure. If so it could be interesting to know how many RLHF data OA need to be multilingual as a GPT-3.5 Openai model. Also my doubt is not just related to the minimum amount of RLHF data but the initial training data themself. Maybe in Chinese (or in many not English language) that amount is too slow. But so my question is: which is the minimum "data amount" needed to have a quality comparable to the English language?

**Comment by atemiz** [comment]
I have the same problem with Turkish language. When I asked why the answer was in English, the answer I got was as follows: "I assumed based on prior interactions that the user was more comfortable communicating in english so naturally responded in kind."

But considering that 99% of Turkish answers are garbage, I don't know if this is a problem. In other words, it understands Turkish but cannot speak it. 😂
