### ISSUE TITLE
He detectado faltas graves de ortografía en la sección 'Chat', ¿cómo debo proceder?

### ISSUE THREAD

**Issue by Euklidiadas** [LAION-AI/Open-Assistant#2657]
En la sección Chat, en la que es posible interactuar con diferentes modelos, he detectado graves faltas de ortografía propias de niños. Pongo el ejemplo del siguiente párrafo, con algunas correcciones en negrita abajo. Son principalmente de puntuación, pero también tildes, ya no digamos estilo. ¿Cómo debo proceder? No veo ninguna forma de decir "esto contiene errores".

> La escritura del número depende del contexto y de la convención estilística que se siga. En general, los números enteros hasta diez se pueden escribir tanto en numéricos (1-9) como en ordinales (1º -10º). A partir de esa cifra suele ser más común verlos escritos en forma numérica, aunque dependiendo del idioma, su cultura e incluso su país puede variar mucho la forma habitual de representarlo escrito. Volviendo a tu pregunta concreta, tanto 5 como Cinco son válidos para referirse a ese numero y dependerá también del uso que le vaya a dar al texto donde lo intenta incluir para decidir si llevarlo escrito de una u otra manera. Otra opción podría ser quinientos, qué representa otro tipo de números a la vez que mantiene la diferencia entre ambos sistemas aritméticos. Si deseas saber más alternativas para representar alguno de estos números, estaré encantado de ayudarte. Simplemente házmelo saber en este mismo chat :)

> La escritura del número depende del contexto y de la convención estilística que se siga. En general, los números enteros hasta diez se pueden escribir tanto en numéricos (1-9) como en ordinales (1º -10º). A partir de esa cifra**,** suele ser más común verlos escritos en forma numérica, aunque dependiendo del idioma, su cultura e incluso su país puede variar mucho la forma habitual de representarlo escrito. Volviendo a tu pregunta concreta, tanto 5 como **cinco** son válidos para referirse a ese numero y dependerá también del uso que le vaya a dar al texto donde lo intenta incluir para decidir si llevarlo escrito de una u otra manera. Otra opción podría ser quinientos, **que** representa otro tipo de números a la vez que mantiene la diferencia entre ambos sistemas aritméticos. Si deseas saber más alternativas para representar alguno de estos números, estaré encantado de ayudarte. Simplemente**,** házmelo saber en este mismo chat**.** :)

**Comment by raulmarindev** [comment]
> En la sección Chat, en la que es posible interactuar con diferentes modelos, he detectado graves faltas de ortografía propias de niños. Pongo el ejemplo del siguiente párrafo, con algunas correcciones en negrita abajo. Son principalmente de puntuación, pero también tildes, ya no digamos estilo. ¿Cómo debo proceder? No veo ninguna forma de decir "esto contiene errores".

Hola, entiendo que te refieres a que las respuestas del chat tienen faltas de ortografía, ¿correcto? Por lo que veo actualmente la única forma de dar feedback es utilizar la mano con el dedo para abajo. Tal vez haya otra forma pero lo desconozco.

![image](https://user-images.githubusercontent.com/26367595/232475186-d1d939d6-1d1b-4bfc-9212-8aacd6a26661.png)

Es probable que en el futuro cercano el hacer click en la mano abra una ventana en la que poder dejar un comentario más detallado tal y como ocurre con ChatGPT. De momento está todo bastante verde.

Por otro lado, es importante tener en cuenta que las respuestas que te da el chat son generadas por un modelo LLM a partir de la información con la que fue entrenado. Esta información es la que está disponible en Internet y la que ha sido introducida/revisada por los voluntarios (rhlf). Si la información que se utilizó para entrenarlo contenía faltas de ortografía el texto que creará las respuestas del chat también las contendrá. Todo esto es mi teoría desde el desconocimiento de muchas partes del proceso de entrenamiento de estos modelos.

Aquí en este hilo se habla del tema:

https://github.com/LAION-AI/Open-Assistant/issues/1558

 Voy a dejar una traducción de tu comentario por si alguien involucrado en el proyecto supiera algo más o se necesita corregir algo de lo que yo aporto.
 
> In the Chat section, where it is possible to interact with different models, I have detected serious spelling mistakes typical of children. I give the example of the following paragraph, with some corrections in bold below. They are mainly punctuation, but also accents, not to mention style. How should I proceed? I don't see any way to say "this contains errors".

**Comment by Euklidiadas** [comment]
En efecto, @raulmarindev , es exactamente mi punto. Evidentemente, el problema de base fue dar acceso a la redacción y corrección a personas con bajos conocimientos del lenguaje. Pero no estaría de más poder evaluar estos errores dentro del panel de evalución, donde te preguntan cómo de violento o no es un mensaje, o donde se marca si es spam. Una casilla que diga "Contenido con faltas ortográficas". Porque luego todo esto será bastante difícil de corregir.
