### ISSUE TITLE
How to improve OpenAssistant chat quality in not English language?

### ISSUE THREAD

**Issue by solyarisoftware** [LAION-AI/Open-Assistant#2659]
This is not a true issue, but a general question.

The quality of first release of chat https://open-assistant.io/chat is pretty impressive in English.

But in my own language, Italian, the quality of conversation is pretty poor. There is a lot of hallucinations and frankly the version is not usable so far.

How can we improve the system for not English languages?
I'm currently an annotator and I completed many task in Italian here: https://open-assistant.io/it/dashboard

But what can we do to improve the Open Assistant Italian (or any other minor) language support?

1. Do we need more Italian language annotators?
2. Maybe we do need more Italian language dataset?
3. There is any time planning of new OA releases, related to the specific language training updates? That's not clear to me.

Thanks
giorgio

**Comment by olliestanley** [comment]
The more data the better for improving performance in different languages. The dataset will continue to be expanded for subsequent training runs. However, we are always partly limited by the base model (on the website so far, LLaMA).
