### ISSUE TITLE
Cannot accept terms of service

### ISSUE THREAD

**Issue by Pave87** [LAION-AI/Open-Assistant#2674]
Clicking "Accept" button wont do anything.
Clicking "Decline" takes me out from page.

**Comment by luphoria** [comment]
I'm not sure where you are encountering this screen, because there isn't ever a point where you have to accept or decline any terms of service. On account creation, there is a notice at the bottom which describes your implicit agreement to TOS and privacy policy, but that's it

**Comment by notmd** [comment]
Hi does it work for you now? Our server was overloaded last night. If it works please close this
