### ISSUE TITLE
Sometimes it doesn't update the score

### ISSUE THREAD

**Issue by diegoenriquesantos** [LAION-AI/Open-Assistant#2677]
In the following link: https://open-assistant.io/es/account

![openassistant-error-1](https://user-images.githubusercontent.com/10709020/232603471-b92e2693-c31c-411a-949f-bab9ea337262.JPG)

Have differences between  real value 49 and 37.

**Comment by andreaskoepf** [comment]
The score is currently not updated in real time but only periodically with different intervals for different time-frames (daily stats every 5 min, total stats every 4h).

**Comment by diegoenriquesantos** [comment]
The next day, is empty the score accumulated.

![Score accumulated 0](https://user-images.githubusercontent.com/10709020/232789919-a4eecf1d-a6c9-4768-98fc-23643c80fb40.JPG)

Please could review for my user fixup. Thanks.
