### ISSUE TITLE
Include Redis in Ansible Build

### ISSUE THREAD

**Issue by GraemeHarris** [LAION-AI/Open-Assistant#268]
Adding redis to ansible build, which is an added requirement for BE API rate limiting. Requested for https://github.com/LAION-AI/Open-Assistant/issues/175#issuecomment-1368571911 @yk

**Comment by rasdani** [comment]
I can convert the redis setup from this [docker-compose.yml](https://github.com/LAION-AI/Open-Assistant/pull/187/files#diff-3fde9d1a396e140fefc7676e1bd237d67b6864552b6f45af1ebcc27bcd0bb6e9) to an ansible build. Could you assign me please, in case no one is on it already?

**Comment by rasdani** [comment]
Created a PR #405

**Comment by GraemeHarris** [comment]
Thanks @rasdani. @yk I know you wanted to take this on if you got a chance - hopefully should be good to merge though.

**Comment by yk** [comment]
thank you all :)
