### ISSUE TITLE
Needs a "coding mode" preset with temp lowered to 0.01 and max tokens at 1024

### ISSUE THREAD

**Issue by dillfrescott** [LAION-AI/Open-Assistant#2688]
I have thoroughly tested this and the lowered temperature seems to do wonders for the logic and reasoning needed to edit and formulate code

**Comment by dillfrescott** [comment]
Every other parameter can be the same as the default, unless you think it should be adjusted more

**Comment by IonizedPro45** [comment]
Maybe it could be called "Precise" or "Deterministic"
