### ISSUE TITLE
语言问题

### ISSUE THREAD

**Issue by phfyb1** [LAION-AI/Open-Assistant#2689]
当我使用中文询问时，它不会自动使用中文回答我，每次都是使用英文回答，而且要求它使用中文解释时，会有乱码现象，且有时无法正确的使用中文回答，还是使用的英文

**Comment by VimRoot** [comment]
确实如此，我一直在引导他用中文回答我的问题，但是在下一个问题进行的时候就会转变成英文回答我了

**Comment by planetoryd** [comment]
Please write in English as it is general etiquette
