### ISSUE TITLE
Improve code & style of "try our assistant" in dashboard

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#2695]
https://github.com/LAION-AI/Open-Assistant/blob/82540c044ee57171fb66e83986b933649d25e7fb/website/src/pages/dashboard.tsx#L39-L49

**Comment by Cecileblbl** [comment]
Happy to help with this

**Comment by dosacat** [comment]
Hi, do assign it to me if still available

**Comment by yk** [comment]
thank you both, I've assigned you both, maybe you coordinate amongst each other

**Comment by dosacat** [comment]
@Cecileblbl would you like to take this forward on the discord?

**Comment by Cecileblbl** [comment]
Yes you can find me under cecileblblbl in the Open Assistant Discord

**Comment by dosacat** [comment]
> I'm bitternectar on the discord #6458

**Comment by andreaskoepf** [comment]
Was this merged? Please link PR.
