### ISSUE TITLE
Add a way to load a model into the docker compose / `distilgpt2` is hard coded

### ISSUE THREAD

**Issue by deftdawg** [LAION-AI/Open-Assistant#2696]
Currently, following the Docker instructions Open Assistant starts up with only the `distilgpt2` model...   This model produces what Mr. T would call jibba-jabba; it's not an impressive showcase for Open Assistant.

Unfortunately there doesn't appear to be anyway to override this and have a better model such as `OA_SFT_Pythia_12Bq` installed. 

https://github.com/LAION-AI/Open-Assistant/blob/5f951b0a15db049cbfe68d906635df2e4b6be0b6/docker-compose.yaml#L249

I attempted replacing the `MODEL_CONFIG_NAME` in docker-compose.yml, however it had no effect.   There should be a way to do this either as passing a parameter or creating an alternate inference worker docker-compose profile or creating a docker disk volume where an external model can be loaded from.  There should be some documentation of what approach or approaches can be taken.

**Comment by olliestanley** [comment]
Running the Docker images locally is done for testing so we want it to default to a small model. We don't really intend to provide extensive support for people running the whole setup locally, although you can if you wish. The model name can be replaced with any [here](https://github.com/LAION-AI/Open-Assistant/blob/main/oasst-shared/oasst_shared/model_configs.py) but the LLaMa ones won't work as they're private for now.
