### ISSUE TITLE
Create test cases (possibly even synthetic data for training) from ChatGPT failure examples (see repo)

### ISSUE THREAD

**Issue by giuven95** [LAION-AI/Open-Assistant#270]
This repo can be used as guidance:
https://github.com/giuven95/chaptgt-failures

**Comment by yk** [comment]
Thank you. I've put this in backlog for now until we have a testing & data pipeline setup to support something like this.

**Comment by ontocord** [comment]
Hi @giuven95 since you are interested in this issue, we are also working to collect chatgpt prompts people have created and is available on the open web. Interested in helping with this?

**Comment by Forbu** [comment]
Do you think it will be usefull to gather data of OA failures too ? (scraping discord "bad-message-ids" ?)

**Comment by andreaskoepf** [comment]
Closing old data issue.
