### ISSUE TITLE
Add an option to delete previous chats

### ISSUE THREAD

**Issue by supersonichedgehogalpha** [LAION-AI/Open-Assistant#2707]
It would be really cool if I could delete my previous chats. It just keeps everything neat when using the Assistant application

**Comment by supersonichedgehogalpha** [comment]
Also, when I "hide" a chat, it doesn't go away. When I refresh, all the chats come back for some reason. maybe it's a caching issue. But overall super cool chat assistant

**Comment by olliestanley** [comment]
> Also, when I "hide" a chat, it doesn't go away. When I refresh, all the chats come back for some reason. maybe it's a caching issue. But overall super cool chat assistant

This should be solved now, can you confirm this is no longer happening?

As for full deletion, the feature will be added soon
