### ISSUE TITLE
The next day, is empty the score accumulated.

### ISSUE THREAD

**Issue by diegoenriquesantos** [LAION-AI/Open-Assistant#2717]
The next day, is empty the score accumulated.

Previous issue: https://github.com/LAION-AI/Open-Assistant/issues/2677

![Score accumulated 0](https://user-images.githubusercontent.com/10709020/232789919-a4eecf1d-a6c9-4768-98fc-23643c80fb40.JPG)

Please could review for my user fixup. Thanks.

_Originally posted by @diegoenriquesantos in https://github.com/LAION-AI/Open-Assistant/issues/2677#issuecomment-1513138378_

**Comment by olliestanley** [comment]
This should not happen again, if it does please comment again and we can reopen
