### ISSUE TITLE
message badge position bug

### ISSUE THREAD

**Issue by notmd** [LAION-AI/Open-Assistant#2719]
The code is in the `MessageTableEntry.tsx` file
![image](https://user-images.githubusercontent.com/33456881/232795572-9f6daaf6-841e-4161-970e-0999e8089356.png)

**Comment by AdarshRawat1** [comment]
Can I work on this issue?

**Comment by Aditya-13** [comment]
@notmd , Should i make that "Deleted" badge in center or show it in the message as discussed in the #3140 ?

Please assign this task to me. 

If anything else required, please explain it here.

**Comment by notmd** [comment]
@Aditya-13 Thanks, the badge should be at top right of the message.

**Comment by Aditya-13** [comment]
@notmd , is this the desired result?

![Screenshot from 2023-05-21 13-37-36](https://github.com/LAION-AI/Open-Assistant/assets/91950158/0af6e58a-1020-42de-893a-7007c024876d)

**Comment by notmd** [comment]
Yeah, but can you put it to the top a little more? Like this, this is the old behavior.
![image](https://github.com/LAION-AI/Open-Assistant/assets/33456881/3cb07e73-0ce1-4d83-9697-027bd13d1bee)
