### ISSUE TITLE
Docker | no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by glebshkut** [LAION-AI/Open-Assistant#2721]
When I'm running `docker compose --profile frontend-dev up --build --attach-dependencies` command in the root of the project
I get the following error:
```
[+] Running 0/1
 ⠴ db Pulling                                                         1.5s 
no matching manifest for linux/arm64/v8 in the manifest list entries
```
I'm using an Apple M1 chip, I tried to specify the platform in `docker-compose.yaml` file, it started composing, but later crashed

**Comment by DominiqueGarmier** [comment]
you can add `platform: linux/x86_64` just below https://github.com/LAION-AI/Open-Assistant/blob/43a9d9c281e36f9640c26acb12be722f632c17ef/docker-compose.yaml#L11

Im unsure if this should be changed. Something might depend on it not being there. We could however create an extra docker-compose environment for M1

**Comment by glebshkut** [comment]
Yeah, it helped. Thanks!

Should I remove this added line of code every time a do commits?

**Comment by DominiqueGarmier** [comment]
I believe the pr should fix your problem. For the time being you will have to remove the line on every commit (or just `git remove docker-compose.yml`)
