### ISSUE TITLE
Does the current version of open assistant possess theory of mind capability 

### ISSUE THREAD

**Issue by zyzhang1130** [LAION-AI/Open-Assistant#2727]
I tried to search in the paper but I didn’t find any relevant information.

**Comment by andreaskoepf** [comment]
We have not done research in this direction. I just tried some of the situation-descriptions/questions from the following paper: https://aclanthology.org/D18-1261.pdf .. it worked surprisingly well .. but the paper could have been in the training set. Give it a try and let us know what you find out. ;-)
