### ISSUE TITLE
Backend (and website) accept empty replies

### ISSUE THREAD

**Issue by othrayte** [LAION-AI/Open-Assistant#273]
I'm assuming this is a bug and empty assistant/prompter replies should be filtered out, or should they, is there a valid reason to allow empty replies? The same probably applies to initial prompts but there is no way to create them on the website at the moment.

**Comment by GraemeHarris** [comment]
I'm happy to take this on to quickly fix - just need to double check how we intend to end prompt dialogues

**Comment by yk** [comment]
> I'm happy to take this on to quickly fix - just need to double check how we intend to end prompt dialogues

I think this is largely independent. There's never really an "end", as the conversation could always continue

**Comment by GraemeHarris** [comment]
Have updated the `TextReplyToMessage` protocol class with pydantic to ensure the text string is not blank, but I think while we're here I could also update the `MessageRating` and `MessageRanking` classes to constrain for a non-zero rating value and for the ranking list to not be empty?
