### ISSUE TITLE
Change sign-in method?

### ISSUE THREAD

**Issue by ChrisWriter** [LAION-AI/Open-Assistant#2732]
Hello.  I initially signed up with my email address but soon discovered I have to have a link sent to my email every time I sign in, which is not ideal.  So I tried to sign in with my Discord account instead (which is using the same email address), but I received Error: To confirm your identity, sign in with the same account you used originally.

Is there any way to switch my sign in method to Discord?

**Comment by TeYo001** [comment]
You shouldn't have to re-enter in your credentials every time with email. Are you in incognito or some other form of cookie blocker?

**Comment by ChrisWriter** [comment]
I am not in incognito or using cookie blockers.

**Comment by olliestanley** [comment]
We are working on solving this issue, tracked by #3246
