### ISSUE TITLE
本地部署的模型为什么像个SB

### ISSUE THREAD

**Issue by QiGangs** [LAION-AI/Open-Assistant#2748]
[](url)参照interfece里面的流程，一共启动了4个docker容器：
open-assistant-inference-server-1
open-assistant-inference-db-1
open-assistant-inference-worker-1
open-assistant-inference-redis-1
然后使用python执行 /interface/text-client/ 中的 main
效果像个250是为什么：
![截屏2023-04-19 19 45 12](https://user-images.githubusercontent.com/22712672/233065096-cf37e7e6-e26d-43c7-9945-995dc93c5fa4.png)

**Comment by dddvanming** [comment]
这不是正式的模型，正式模型权重还没有公布，你运行的这个模型应该是没有中文训练数据的。
模型权重还在处理中:https://huggingface.co/OpenAssistant/oasst-llama-based-models
你的素质太低了，提问说这么多脏话🙂
