### ISSUE TITLE
Open Assistant is particularily bad at extracting info from contexts -> We need more context examples <-

### ISSUE THREAD

**Issue by Logophoman** [LAION-AI/Open-Assistant#2752]
@yk I have performed quite a few Tests with The Open Assistant and while it performs extremely well on casual conversation and in a bunch of scenarios I have noted that it is particularly `bad at extracting info from contexts`. Also I noted that there are very few prompts in the Dataset where users dump in a chunk of information and let the AI extract information, which often leads to the assistant ignoring true information and instead it starts hallucinating, making something up, while the true answer is right in the prompt/context. 

Why is that important? 

I know that its incredibly important to build an open ChatGPT alternative that aims at general capabilities etc. But I think in the future the biggest Value for open Systems like Open Assistant will be that they can be used to extract true information from databases/dumps/context/tools... and truthfully answer users based on the documents. 

How could we make sure to include `more context extraction prompts` to the Open Assistant dataset?

I have labeled a bunch of messages and added assistant answers, however there are way too many prompts in the pipeline already so I cannot add these context-example prompts properly....

**Comment by yk** [comment]
What sampling settings have you found to most influence information extraction? Did it get at all better with reduced temperature?

**Comment by bfalchuk** [comment]
Please show your sampling settings, and how and where you set them - seems like some may have a relationship to your perceived quality of recall of the inference?

**Comment by maziyarpanahi** [comment]
I have notice the formatting has a crucial impact on the response when you are trying to include the context. Which token formatting are you using to construct your Prompt with Context @Logophoman?
