### ISSUE TITLE
Add categories to messages and contributors for better filtering

### ISSUE THREAD

**Issue by ElFrogster** [LAION-AI/Open-Assistant#2753]
Most of us have some things we know quite a bit about and quite a lot we know nothing about. The current task system basically seems to give a contributor random messages, which will often lead to someone who knows nothing about programming getting programming questions etc, which both makes for a frustrating experience and incentivizes giving judgement about things you know little about.

A (ideally tiered) labelling or category system cod solve this. Messages could be labeled as "Movies", "Programming" > "Python", "History" etc and users could choose to whitelist/blacklist categories so it will be more tailored to what they could give input on.

**Comment by GuilleHoardings** [comment]
Related: #1006

**Comment by ElFrogster** [comment]
Oh, sorry about that. I did do a cursory search through the issues, but didn't see that one. Can probably just close this one then.
