### ISSUE TITLE
Add warning message near chat window about model hallucinations

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#2756]
A broader audience now begins to chat with our models. I saw multiple youtube videos in which people were not sure if OpenAssistant had an internet connection (search etc.) and they simply asked OA which sometimes stated that it would have internet access and people took that as a potentially "official" reply. At the current state OA has no tool-access and doesn't use search results to formulate its responses.

IMO for a general audience we need to add a warning near the chat that creates awareness for hallucination.

In general outputs look very convincing and not all people might be aware how the system works or how convincing the model can produce factually completely wrong outputs .. potentially even in an authoritative tone. By design LLMs are great imitators (that's their training objective). People need to be skeptical about "facts" presented by tho model.

The situation will improve a bit with plugins that can retrieve relevant information (e.g. via web-search) ... but still a warning would be appropriate.

**Comment by andreaskoepf** [comment]
see also #2744

**Comment by Quarks-1** [comment]
I'd like to take this issue! Jsut confirming, this would be a warning on this page right?
![image](https://user-images.githubusercontent.com/67989420/233187145-f8274288-3946-446e-b030-36dc2bc39662.png)

**Comment by Quarks-1** [comment]
![image](https://user-images.githubusercontent.com/67989420/233477988-a43b92e0-3fd8-4fd1-8a1c-f148717767b4.png)
I was thinking of adding it like this so it doesn't get lost in the message history, what do you think?
