### ISSUE TITLE
Local Inference does not work

### ISSUE THREAD

**Issue by hu-po** [LAION-AI/Open-Assistant#2757]
Trying to get local inference to work, this is the docker compose command I am running:

```
docker compose --profile ci --profile inference up --build --attach-dependencies
```

I have also tried different permutations with the `frontend-dev` and `backend-dev` profiles. They also do not work.

It seems like the chat request gets put onto a queue, but the inference worker perhaps never pulls from it? Here is an image:

![inference_no_work](https://user-images.githubusercontent.com/8493427/233109020-ebb415c7-cd62-426f-9044-2cadb1486876.png)

**Comment by Neykuratick** [comment]
Same for me. I guess it has something to do with https://github.com/LAION-AI/Open-Assistant/issues/2750 or https://github.com/LAION-AI/Open-Assistant/issues/2754

**Comment by AbdBarho** [comment]
model should not be `_lorem`, try `distillgpt2`

**Comment by Neykuratick** [comment]
`distillgpt2` is the only model that works, but in answers gibberish

**Comment by olliestanley** [comment]
See #2595
