### ISSUE TITLE
Account page (website) says "null"

### ISSUE THREAD

**Issue by othrayte** [LAION-AI/Open-Assistant#276]
If you sign in to the website with either email or the debug login (other types not tested) and go the account page (/account, or click on the user menu top right) the first content on the page is 'null'.
![image](https://user-images.githubusercontent.com/241372/210233172-a8aa1aaf-17bf-41be-8d78-f3619786ca17.png)

If you login with debug login the location where the email address would appear is also blank so you only see 'null' \n "Edit Username". We should probably show the debug username there like we do in the account menu top right.

The page probably also needs some additional labels or something on it to make it clearer what the content is.

**Comment by Jac-Zac** [comment]
This merge doesn't complitly fix the issue for me since when I try to edit the username it never updates. And also it gives me an error. I have made some changes in my pull request to fix this
