### ISSUE TITLE
Focus on chat input box text when creating new chat

### ISSUE THREAD

**Issue by bishowX** [LAION-AI/Open-Assistant#2763]
Currently, when creating a new chat it just adds "Untitled" to the chat list and does nothing. It would be very convenient for users if chat input box was in focus after clicking "Create a new chat" 

### Observed:

https://user-images.githubusercontent.com/94373953/233173332-8f67f86a-b70e-4080-a7c0-697174f31220.mp4

### Expected:

https://user-images.githubusercontent.com/94373953/233173615-7b53631a-254e-4705-811e-8011ccbce5be.mp4

**Comment by bishowX** [comment]
@notmd  I'd like to work on this

**Comment by notmd** [comment]
Thanks for your work, but I mean focus the chat's title input (the inline one) instead the main chat input. Also please continue discussion on the previous issue

**Comment by bishowX** [comment]
Maybe we can first focus on the chat title and when user presses Escape we can focus on the chat input box.
