### ISSUE TITLE
Localhost issues

### ISSUE THREAD

**Issue by acosonic** [LAION-AI/Open-Assistant#2764]
How do I change it so it runs on 0.0.0.0:3000 instead on localhost? Or at least on public_ip instead of localhost?

Is it too much or should I just reverse-proxy it?

**Comment by bishowX** [comment]
> How do I change it so it runs on 0.0.0.0:3000 instead on localhost? Or at least on public_ip instead of localhost?
> 
> Is it too much or should I just reverse-proxy it?

You can  actually go to your-ip:3000 or 0.0.0.0:3000 and it will load the site. No need to change anything

**Comment by xuzeyu91** [comment]
I deploy the IP to access the virtual machine in the virtual machine, but when I log in, it will be adjusted to localhost. Is there a configuration entry in this place?

**Comment by bishowX** [comment]
> I deploy the IP to access the virtual machine in the virtual machine, but when I log in, it will be adjusted to localhost. Is there a configuration entry in this place?

I'm sorry I didn't get the question can you provide more details on what are you trying to accomplish please

**Comment by acosonic** [comment]
When I log in, it keeps redirecting to localhost or sending XHR requests to localhost.

**Comment by bishowX** [comment]
You can change the env variable NEXTAUTH_URL in docker-compose.yaml file
https://github.com/LAION-AI/Open-Assistant/blob/a700700baed5a5ee127dac482533a798fbc19d28/docker-compose.yaml#L170
Now, after login you will be redirected to the url you configured in that variable
