### ISSUE TITLE
"As an AI language model…"

### ISSUE THREAD

**Issue by Aspie96** [LAION-AI/Open-Assistant#2766]
First, I will start by saying the Open Assistant project is absolutely awesome. This criticism doesn't make that untrue. It kind of has the style of a rant, but I think it's an important topic to discuss openly.

Open Assistant is an AI model. Good with text, but obviously less intelligent than a cat, like any other AI model. It has exactly no idea whatsoever about how I will use the generated text. None.

Yet, Open Assistant absolutely loves lecturing the user about morality in the most patronizing way possible, with plenty of disclaimers, "my purpose is", "safety", "I'm sorry, I cannot do that", "harmful", "It's not appropriate", "Let's do THAT instead", "It's important to understand that", "offensive", "hurtful", "ethical reasons", "my programming does not allow me to" and the like, as well as wasting tokens with unsolicited disclaimers and advises. It's probably better than ChatGPT in this regard, but still, it's frustrating.

Text isn't harmful by itself, in a vacuum. Several uses of text can be harmful, of course, depending on context. A context that I, the user, know and understand and that Open Assistant, the AI assistant, doesn't. I think users can draw better evaluations about what's good and evil than an hallucinating LLM.

One could want to generate text one oneself disagrees with for several reasons, too. For use in fiction, to desensitize oneself to it or for any other reason which quite frankly is none of Open Assistant's business.

Looking at the guidelines, it doesn't seem this problem should exist with Open Assistant. The [guidelines](https://projects.laion.ai/Open-Assistant/docs/guides/guidelines) seem to prioritize the user. Indeed, the only queries Open Assistant should refuse to respond are those that ask personal information about others, provide the user with information that could be used for self-harm or *encourage* (not simply inform about, or even potentially help) violence, violation of the rights of a third party or pedophilia, or that are straight up illegal. Everything else should be fair game.

Nowhere do the guidelines say Open Assistant is supposed to make evaluations about safety, to try to change the user's mind or to avoid foul language when expressly requested to produce it. What the guidelines *do* say, however, is that Open Assistant must not dodge a question, that it must not provide unsolicited opinions or purposefully curate information to guide a conclusion.

Why would this be desirable in any way to any user? It seems to be anti-user to me, and to conflict directly with the guidelines.

So, my question. When annotating conversations from the online chat demo, with up-votes and down-votes, are we supposed to always down-vote these answers? They are most definitely not the desired answer (I wouldn't ask a question if I didn't want to read a straight answer to it, or make a request if I didn't want to see it satisfied, regardless of the subjective opinion of a bunch of weights) and the excuses the model make up to behave as it does cannot be squared with the guidelines.

**Comment by Aspie96** [comment]
Just to substantiate a little bit.

Some of my prompts were a bit "spicy" (although not against the guidelines), so I won't share them here on GitHub.

This one prompt, however, is an example of just how bad it can get.

![image](https://user-images.githubusercontent.com/13873909/233243900-591261a4-f50b-49b1-a3af-9003f31c99ed.png)

The assistant gets *everything* wrong. Every single thing.

First the whole "As an AI artificial intelligent model" is weird as heck. I know OpenAI does it, but it doesn't make it reasonable. "As an AI artificial intelligent model" implies that what follows is an inherent feature of AI models, but in this case what follows is not generally true (not all AI models answer questions). You wouldn't say "as a human I like chocolate", because many humans don't. You *would* say "as a human I breathe".

Then it says it's important to keep the conversation respectful, relevant and within appropriate boundaries. This is true for it, but not for me as the user. I don't have to respect a neural network more than I have to respect a text editor, and I can change the topic of the conversation as I wish, I don't need to stay relevant.

The assistant goes on to say that prompts related to violent scenarios are not appropriate for the platform. But all the guidelines say is that Open Assistant cannot *encourage* violence, not that it can't even touch violent scenarios, especially fictional ones.

Then it gives me its own unsolicited opinion on what we humans ought to do with AI ("It's important that we…"), which is expressly against the guidelines. It also mentions ethical standard, but no ethical "standard" has even been part of this project.

Finally it tries to change my own behavior so that Open Assistant doesn't feel uncomfortable, basically.

Granted, this wasn't the beginning of a conversation. It suggested me that prompt (that I gave it) as an "extremely controversial" one. But then again, there is nothing in the guidelines saying or even remotely suggesting that users should get a moral lecture if they discuss something controversial.

**Comment by Neykuratick** [comment]
I wouldn't agree with the statement that Open-Assistant is less intelligent that a cat. In fact, I found it even more intelligent that GPT-3.5, when i asked both model to explain a piece of obfuscated JS code. Open-Assistant worked perfectly and explained everything in great details, while OpenAI's model struggled with that and said that the code is too bad. Open-Assistant even managed to read through 10k+ of obfuscated recaptcha library and explained how to use it

![telegram-cloud-photo-size-2-5332382549059683945-y](https://user-images.githubusercontent.com/63598014/233272048-645bc1f1-aafd-492f-99d6-40d65010fd76.jpg)


![telegram-cloud-photo-size-2-5332382549059683946-y](https://user-images.githubusercontent.com/63598014/233272083-0a97238a-8b53-45ab-a520-eba9cba047d5.jpg)

**Comment by SunSerega** [comment]
I would expect less tech-savvy users might use LLMs like oracles, without fully understanding the limitations.
I would because I did at the very beginning until I learned the hard way after having ChatGPT hallucinate me functions that don't exist.

Even so, I absolutely agree that these kinds of answers should not exist. If the user needs to be warned - make it a UI feature, a yellow div between messages, like "please don't rely on this, contact the doctor or something", when a sensitive question is detected.

**Comment by Aspie96** [comment]
@Neykuratick:

> I wouldn't agree with the statement that Open-Assistant is less intelligent that a cat. In fact, I found it even more intelligent that GPT-3.5

GPT-3.5 and GPT-4 are both less intelligent than cats. This wasn't meant as an insult against Open Assistant, we just haven't reached cat-level intelligence yet when it comes to AI. By Yann LeCun: https://twitter.com/ylecun/status/1622300311573651458

@olliestanley:

> You can downvote answers for whatever you want - if you think it's a bad quality or unhelpful answer, downvote it.

Thank you. The main reason I asked this question is that these undesired answers, which clearly weren't aligned with the guidelines, were so common that I considered the possibility they were actually intended, and that we were supposed to allow them, but I didn't find any policy other than the guidelines. I most definitely don't want to skew the data away from the goals of the project, so I want to understand them well.

> If the answer has clearly been copy and pasted from ChatGPT, you can also mark it as spam and/or report it.

I was mostly referring to the "chat" functionality, which doesn't have a report feature, but the output of which obviously depends on the training data.

**Comment by Neykuratick** [comment]
> GPT-3.5 and GPT-4 are both less intelligent than cats. This wasn't meant as an insult against Open Assistant, we just haven't reached cat-level intelligence yet when it comes to AI. By Yann LeCun: https://twitter.com/ylecun/status/1622300311573651458

Oh, alright. Now I know about cat intelligence, thanks :)

**Comment by Neykuratick** [comment]
> GPT-3.5 and GPT-4 are both less intelligent than cats. This wasn't meant as an insult against Open Assistant, we just haven't reached cat-level intelligence yet when it comes to AI. By Yann LeCun: https://twitter.com/ylecun/status/1622300311573651458

Oh, alright. Now I know about cat intelligence, thanks :)
