### ISSUE TITLE
putting sentiment analysis

### ISSUE THREAD

**Issue by chandru1003** [LAION-AI/Open-Assistant#277]
sentiment analysis is good thing to add an chatbot so bot can understand what user feel better on words. this i feel

**Comment by yk** [comment]
This is a bit too vague for a feature request, it's not clear how SA should enter any workflow and why it needs to be done explicitly, and not just implicitly by the response model.

**Comment by chandru1003** [comment]
my point is, the user will understand that the bot understands him/her, so engagement got better.
by implicitly SA we already got the user, showing that to the user makes sense to me

**Comment by yk** [comment]
yes, but how would that enter the chat workflow?

**Comment by chandru1003** [comment]
I referred this website, so it may help you

https://www.revechat.com/blog/chatbot-sentiment-analysis/#:~:text=Sentiment%20analysis%20is%20a%20subfield,thoughts%2C%20opinions%2C%20or%20sentiments.

**Comment by yk** [comment]
This explicitly extracts the sentiment and chooses appropriate responses. My question is, how would that interface with a generative language model that already in itself produces (hopefully) appropriate responses?
