### ISSUE TITLE
French formulation correction on website (task eval)

### ISSUE THREAD

**Issue by cog-data** [LAION-AI/Open-Assistant#2771]
I am participating in the response assessments on the OpenAI site (https://open-assistant.io/fr/label/label_assistant_reply) and I find that the wording of the task to be performed for the assessment is wrong formulated:

"Etiqueter la réponse de l'assistant
En fonction de la discussion suivante, fournir des étiquettes pour la dernière invitation."

Which is borderline incomprehensible in French, I would rather suggest:

"Evaluer la réponse de l'assistant
En tenant compte de la discussion suivante, évaluez sa dernière réponse."

Then: "Notez le message surligné" should be formulated as "Notez le message encadré"

And also there is a typo in the bottom pages selectors:
"Humoristique" in place of "Humortistique"

**Comment by olliestanley** [comment]
Please feel free to make a pull request with any fixes by editing the relevant files here:

https://github.com/LAION-AI/Open-Assistant/tree/main/website/public/locales/fr
