### ISSUE TITLE
expert intervention  

### ISSUE THREAD

**Issue by Ric71** [LAION-AI/Open-Assistant#2775]
If someone additionally labels another reply in a dialog-tree by clicking the three dots, this might imply him having extraordinary knowledge on the regarding subject. Maybe he should get the chance to write a ‚corrected‘ reply to the according prompt or at least write a prompt following the reply he labeled?

**Comment by cicerohellmann** [comment]
That would be great, it happened with me yesterday regarding modern
software languages and I couldn't really change anything about it

**Comment by planetoryd** [comment]
It seems they want sort of randomness, the lottery, to prevent manipulation. 

I believe the lottery doesn't make much sense tho. Rather, make it a reddit but with special features. 

There isn't any barrier preventing manipulation (make lotsa accounts) and their ability to do this is much worse than Reddit. 

Their social ranking system isn't anywhere superior to Reddit and users can't correct wrong answers freely.

**Comment by olliestanley** [comment]
Covered by message editing issues
