### ISSUE TITLE
what is inference-server:8000

### ISSUE THREAD

**Issue by xuzeyu91** [LAION-AI/Open-Assistant#2776]
![cd939c9fd481f9553e7b9b8108fa0e84](https://user-images.githubusercontent.com/26290929/233345320-54f1cba5-2958-448e-b80a-3a202114b077.png)

What is the service for this conference-server 8000 port? I checked that there are no 8000 ports in the docker

**Comment by bishowX** [comment]
If you're trying to run the inference server you have to use the following commnd
```bash
sudo docker compose --profile inference up --build --attach-dependencies
```
notice "inference" after --profile thats the thing which runs the inference server

**Comment by xuzeyu91** [comment]
![image](https://user-images.githubusercontent.com/26290929/233449713-99c14bb7-dcf1-40c6-819a-744110c2d345.png)

I have already started the inference service, but why hasn't the chat responded,
