### ISSUE TITLE
The website has its lightmode/darkmode icons inverted.

### ISSUE THREAD

**Issue by 7ombie** [LAION-AI/Open-Assistant#2793]
Across the site, there is a toggle at the (very) top-right that allows the user to toggle between lightmode and darkmode.

When darkmode is selected, the icon (for selecting lightmode) is a crescent moon. Conversely, the icon to select darkmode is a shining sun. It's normally the other way around.

**Comment by andrewm4894** [comment]
Actually, I think that's expected, it shows what mode you are in, so it's more like a toggle that's in moon state (when in dark mode) or sun mode (when in light mode).

**Comment by andrewm4894** [comment]
I'll close this just to clean as we go. I think it's working as it's supposed to.

**Comment by 7ombie** [comment]
I guess you can interpret it as a mode *indicator* (that can also be clicked to toggle the mode), but I'm pretty sure everyone else implements it as a regular button, with the icon indicating what the button (currently) does.

It's not the end of the world, either way. Happy to close.
