### ISSUE TITLE
Issue in lengthy data

### ISSUE THREAD

**Issue by BNNagaraj** [LAION-AI/Open-Assistant#2802]
I asked to write a ebook on python tutorials from beginner to Master level with hands-on examples. As the data is more than the allowed as per available tokens, i think it went on a continuous and   shown this msg "Sorry, we encountered a server error. We're not sure what went wrong."

![image](https://user-images.githubusercontent.com/123287126/233548144-a77294d2-c4df-4bc0-b35c-9af36f045e69.png)

**Comment by BNNagaraj** [comment]
Also not opening new chat and when sign out and tried to sign in it is showing error.

**Comment by andreaskoepf** [comment]
Don't worry .. you cannot break the system by asking to write books. There is a max tokens output limit .. it will stop when it is reached. We had an outage due to an nginx crash.
