### ISSUE TITLE
My chat history removed suddenly

### ISSUE THREAD

**Issue by linuxtopia** [LAION-AI/Open-Assistant#2808]
Hi,

I use Arch based Linux distro and Brave browser. I was chatting with OA and suddenly my chats wiped out. How and why?

Thanks

**Comment by andrewm4894** [comment]
announcement on discord: https://discord.com/channels/1055935572465700980/1058162802273038428/1098538624649285682

>⚠️  Yay dev ops ... 
You may have noticed that your existing chats disappeared on the website. This was done to take some load off  our serves to allow continued operation and to give us time to add features to handle longer chats like pagination (probably also some limits for chat-length or branching-factors).
We hope to bring the existing chats back online later (they were temporarily moved to a backup table).

So think hoping they should be back soon.

**Comment by notmd** [comment]
They will be back after https://github.com/LAION-AI/Open-Assistant/pull/2773 landed and the frontend support pagination

**Comment by linuxtopia** [comment]
then no problem, keep it up guys. OA looks promising and has huge potentials.

Bravo
