### ISSUE TITLE
Missing chats

### ISSUE THREAD

**Issue by RhinigtasSalvex** [LAION-AI/Open-Assistant#2810]
I was working on a presentation with Open-Assistant and made a longer break, when coming back I tried to continue but the session seemed to have lost connection because no queue message was displayed just the waiting wheel turned indefinitely.  So I tried reloading but got a 500 Server error.  And now I don't see the chat listed anywhere.  Going back to the chat via the URL "https://open-assistant.io/chat/< CHAT-UUID>" does not work either.

**Comment by AbdBarho** [comment]
see  #2808
