### ISSUE TITLE
Third party API integration

### ISSUE THREAD

**Issue by wilfoderek** [LAION-AI/Open-Assistant#2817]
Hi Guys, i was wondering if exist any example to integrate open assiant with an api when answer is not found.
The idea is to have a database knowledge that return the fact more relevants to open assiant abd this can respond to user. So, i was thinking in api integraton which open assistant send the promt ask by user and this search in database.
I have the database and embeddings but i have no idea how to integrate with open assiant. Any example can save my life.

Thank you in advance.

**Comment by andrewm4894** [comment]
[This PR](https://github.com/LAION-AI/Open-Assistant/pull/2765) and "Plugins" i think would be the foundation for something like this.
