### ISSUE TITLE
Structured dataset for training from r/amitheasshole

### ISSUE THREAD

**Issue by andrewm4894** [LAION-AI/Open-Assistant#282]
A decent source could be 

https://www.reddit.com/r/amitheasshole/

Could be a way to convert this into more structured training data that actually might encode a lot of nuance. 

There is lots of rules and hurustics to that subreddit such that would could extract or convert it into a sort of soft label type dataset that maybe could be useful. 

Apologies if this is a dupe as am sure reddit data already on roadmap, more so that there could be a subset of subreddits that could be enriched or transformed in some way to make them even more useful.

**Comment by AbdBarho** [comment]
Thanks for the suggestion.

I think reddit is a good source, but also biased and probably NSFW most of the time...

**Comment by yk** [comment]
Duplicate of #53 , I'll comment over there
