### ISSUE TITLE
Implement Dataset Entry for Datasets

### ISSUE THREAD

**Issue by CloseChoice** [LAION-AI/Open-Assistant#2827]
We have a new `DatasetEntry` class which helps us to generalize over datasets and enforce a common formatting.
We need to implement this class for a couple of more datasets:
 - [ ] SODA (@hardikyagnik)
 - [ ] JokeExplanation (@sampatkalyan, needs approval from CodeOwner)
 - [ ] WebGPT (@CloseChoice, needs review)
 - [x] Alpaca (@CloseChoice
 - [x] AlpacaGpt4 (@CloseChoice)

All of these datasets are found [here](https://github.com/LAION-AI/Open-Assistant/blob/main/model/model_training/custom_datasets/qa_datasets.py). An example of how the new class is implemented is found [here](https://github.com/LAION-AI/Open-Assistant/blob/main/model/model_training/custom_datasets/qa_datasets.py).

PRs can be implementations for a SINGLE Dataset. If you implement this, then checking the dataset with our script would be nice (but optional):
```bash
python check_dataset_appearances.py -d <dataset-name> --cache_dir <cache-dir> --mode sft
```

If you take up one of the datasets, please mention the dataset name in your comment, then I'll mention you at the corresponding dataset

**Comment by hardikyagnik** [comment]
I would like to take up this task.

**Comment by CloseChoice** [comment]
@hardikyagnik nice, which dataset are you working on? I just ask, so that others can work on the other datasets simultaneously

**Comment by andreaskoepf** [comment]
> I would like to take up this task.

I assigned you .. as @CloseChoice said it would be great if you could specify which one you will work on .. potentially others could help (we need this as soon as possible).

**Comment by hardikyagnik** [comment]
Hey @CloseChoice, @andreaskoepf, I will start picking up datasets sequentially starting with `SODA`.

**Comment by sampatkalyan** [comment]
hi i would also like to work on this issue.

**Comment by CloseChoice** [comment]
@sampatkalyan, could you work on JokeExplanation?

**Comment by sampatkalyan** [comment]
@CloseChoice Yes I will begin the work on the JokeExplanation.

**Comment by CloseChoice** [comment]
@sampatkalyan , @hardikyagnik did you already look into the implementation? We would really need this asap. If there is anything I can help you with, let me know otherwise I'll take up the task if this is last blocking thing for the next sft run.

**Comment by hardikyagnik** [comment]
Hey @CloseChoice , I noticed that in the current SODA implementation, for each dialogue, the first question is updated by adding a narrative field as a suffix, and the entire dialogue is returned as a list of lists of strings. To convert this to a DatasetEntry, would it be okay to separate out the alternate entries in the dialogue into 'questions' and 'answers' fields as members of the DatasetEntry?

**Comment by CloseChoice** [comment]
@hardikyagnik, the structure for dataset entry for SODA would be 
```python
DatasetEntry(
questions=[PREFIX + Q1, Q2, Q3, ...],
answers=[A1, A2, A2, ...]
```

**Comment by Andavarapu-Sampat-Kalyan** [comment]
@CloseChoice  for JokeExplaniation the DatasetEntry(
questions=joke,
answers= explanation) correct me if i am wrong.

**Comment by sampatkalyan** [comment]
@CloseChoice for JokeExplaniation the DatasetEntry(
questions=joke,
answers= explanation) correct me if i am wrong.

**Comment by CloseChoice** [comment]
@sampatkalyan yes, that is correct, please verify that you match the types in the annotations

**Comment by sampatkalyan** [comment]
@CloseChoice In JokeExplanation there is a question and answer variable in the __init__ method which is not used or updated anywhere in the code should I remove it or am I missing something here?

**Comment by CloseChoice** [comment]
@sampatkalyan Please create the PR, I'll have a look.

**Comment by sampatkalyan** [comment]
For AlpacaGpt4  should i make the change in seperate pr or the same pr

**Comment by sampatkalyan** [comment]
@CloseChoice  made the PR please check it. and let me know if there are any changes to be made.

**Comment by sampatkalyan** [comment]
@CloseChoice  added suggested changes can you please check? Thank you.

**Comment by hardikyagnik** [comment]
Hello @CloseChoice, I've created the PR, let me know if it requires any updates.
