### ISSUE TITLE
Add animation to thumbsup/down in chat when user not voted yet

### ISSUE THREAD

**Issue by notmd** [LAION-AI/Open-Assistant#2850]
maybe something like this is ok 
https://www.vecteezy.com/video/10877395-like-loop-motion-graphics-video-transparent-background-with-alpha-channel

**Comment by andreaskoepf** [comment]
We definitely should encourage users to vote for the produced messages. Ideally we would also collect more feedback about why a message was good or bad.

**Comment by sampatkalyan** [comment]
I am a bit new to this. 
Can you please help with explaining how should I start working with it?

**Comment by davidak** [comment]
That would be pretty distracting. Don't have animations unless it is part of a user interaction as feedback.

**Comment by notmd** [comment]
To clarify what I mean
- Only show the animation of 1 message at a time, maybe the last one.
- Only show the animation in a very short time, maybe 0.2s every 5s or something
- Only show the animation of 1 thumbs-up or thumbs-down at a time.

I believe I have seen some other apps do this before. This would encourage user to react with the message.

**Comment by davidak** [comment]
There could be some animation to invite the user to provide feedback **once** after the answer is completed, so it can be seen as part of the answer showing up.

We could also just place a CTA above the chat like "Please rate the answers to help us improve them".

**Comment by notmd** [comment]
Yes, only animation is not enough, we should add more thing to encourage user to rate the message

**Comment by davidak** [comment]
I suggest to close this in favor of https://github.com/LAION-AI/Open-Assistant/issues/2845 and don't use animations.

**Comment by sampatkalyan** [comment]
Hi can anyone tell me what should i do about this issue.
