### ISSUE TITLE
Display name spill-over

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#2851]
In isolated cases users misuse their freedom to use unicode display names to set bad names which spill over to other parts of the UI. Specifically affected are the leaderboard and trollboard pages which list users.

Use css styles to clip display names at the border of the surrounding cell's box.

**Comment by anon62** [comment]
by the way it was me, it was me who put ฏ๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎๎ in the nickname

**Comment by scorbett123** [comment]
Is it alright if I work on this, or is someone already doing it?
