### ISSUE TITLE
Addition of Hindi Language on the Website and for Chat

### ISSUE THREAD

**Issue by UltraGamerine** [LAION-AI/Open-Assistant#2854]
I do not see Hindi(hi) (हिन्दी) as an option in the list of languages on the website, and for chat. 

As Bangla, another one of the Indian Languages, with many speakers in Bangladesh is already supported, addition of Hindi shall 
not be very difficult.

The Language is one of the Top Five in terms of Number of Native Speakers, so adding Hindi support will definitely leverage the MultiLingual and Multi-Cultural capabilities of Open Assistant.

**Comment by olliestanley** [comment]
We depend on users to contribute translations so we can support new languages. If you would like to translate the website, please submit a pull request making the relevant additions with locale files here: https://github.com/LAION-AI/Open-Assistant/tree/main/website/public/locales

**Comment by olliestanley** [comment]
Good point! It looks like whoever added the translations forgot to add it to the language list [here](https://github.com/LAION-AI/Open-Assistant/blob/main/website/next-i18next.config.js) and so it wasn't activated. If you'd like to submit a PR adding it to that list we can enable the language right away :)

**Comment by UltraGamerine** [comment]
So I did this -
https://github.com/LAION-AI/Open-Assistant/commit/2cd0fb69d4a2f1cb10ca2b42d49cb4b939380571

**Comment by olliestanley** [comment]
Yes, that should work, if you make a PR we can get it merged as soon as the web team have chance to confirm

**Comment by UltraGamerine** [comment]
Could you please do that : )
