### ISSUE TITLE
In the chat interface, switching to "custom" should default-set the parameters of the previously selected preset

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#2859]

**Comment by notmd** [comment]
Here is the code for anyone wants to work on this.
https://github.com/LAION-AI/Open-Assistant/blob/0ba118cc9e1c4d8fd24e350139ab16cfc8d01f71/website/src/components/Chat/ChatConfigForm.tsx#L95-L106

**Comment by simonusher** [comment]
Hi! I'd like to work on this.
