### ISSUE TITLE
On mobile I have to scroll down to see text input 

### ISSUE THREAD

**Issue by andrewm4894** [LAION-AI/Open-Assistant#2865]
On Google pixel 6 I see this in a new chat:

![Screenshot_20230423-190240](https://user-images.githubusercontent.com/2178292/233856962-a2ffe1d7-178d-400c-8ca0-047356c8029f.png)

I have to scroll down to see the input:

![Screenshot_20230423-190249](https://user-images.githubusercontent.com/2178292/233856951-b1697149-02c9-44ae-8621-3c816f1fd66f.png)

Was showing a family member chat on their phone today and this confused them.

**Comment by notmd** [comment]
I noticed this as well. But this only happen on real mobile

**Comment by vishal7738639800** [comment]
I think you have to use dvh(dynamic viewport height),maybe this will solve you issue

**Comment by vishal7738639800** [comment]
@Viddesh1 its dynamic view port height and width

**Comment by vishal7738639800** [comment]
@Viddesh1 it will look like these
![Screenshot 2023-05-02 220515](https://user-images.githubusercontent.com/77560549/235729021-f0e83c79-a44b-4c5d-a54d-f51e43f80332.png)
