### ISSUE TITLE
chat response text gets cut off on website

### ISSUE THREAD

**Issue by PlasticMemmories** [LAION-AI/Open-Assistant#2866]
There have been many times where the output of open assistant gets cut off. I've tested it on both safari and firefox on Ios (I don't know if this bug exists on desktop) and it happens on both browsers. I'm also a screen reader user although I don't know if that matters at all. I will attach a screen shot to show you what I mean
![IMG_0144](https://user-images.githubusercontent.com/130701499/233860600-1bfa6564-e8f1-40e7-b586-4409e1aadf01.png)

**Comment by olliestanley** [comment]
The model probably just hit its maximum reply length

**Comment by olliestanley** [comment]
(you can often get it to continue by just typing "continue" as your next chat

**Comment by PlasticMemmories** [comment]
oh I didn't know about that, I assumed it'd act like chatGPT and not be cut off, also sorry couldn't add a label for some reason
