### ISSUE TITLE
I can't try the chat

### ISSUE THREAD

**Issue by cesaronly87** [LAION-AI/Open-Assistant#2868]
Sorry, we encountered a server error. We're not sure what went wrong.

**Comment by andreaskoepf** [comment]
Just tried and it is working for me.

**Comment by Quarks-1** [comment]
Do you mean on the deployed website or when you build internally?

**Comment by ZenXir** [comment]
@Quarks-1 Do you known how to fix this error when login deployed website
![image](https://user-images.githubusercontent.com/57025873/233986092-43c44902-2dae-4d51-b78a-e515ace0c685.png)

**Comment by i-am-neo** [comment]
I can't even sign in.  The front-end keeps saying it sent a sign-in link to whatever email I try (gmail) and I don't get any emails.

**Comment by nikitazu** [comment]
@i-am-neo , hi

I haven't tried that myself yet, I'm trying to figure out how to run the project on windows machine, but it seems like you don't need to do the registration process on `localhost` environment.
According to the [guide](https://github.com/LAION-AI/Open-Assistant/blob/main/docs/docs/guides/developers.md) you need to use the `dev` user to sign in.

![image](https://user-images.githubusercontent.com/271185/234380966-c2c6acd9-8eaf-4a8d-8545-646b700e551f.png)
