### ISSUE TITLE
buttons on a mobile screen take up 50% of the width

### ISSUE THREAD

**Issue by wrknbuycnsmndie** [LAION-AI/Open-Assistant#2871]
# You can see on the screenshot
![20230424_090626.jpg](https://user-images.githubusercontent.com/73478400/233870958-0092079c-9fa1-4f35-abf9-dd9865f65c4d.jpg)

**Comment by olliestanley** [comment]
Is this really a problem?

**Comment by AbdBarho** [comment]
Feel free to contribute a fix!

**Comment by wrknbuycnsmndie** [comment]
if we want to make more community around the assistant, then I think yes. This looks like a flaw in the user interface.

**Comment by andreaskoepf** [comment]
Thanks for he feedback. @wrknbuycnsmndie feel free to send in a PR if you are web-designer.
