### ISSUE TITLE
The Answer is weired

### ISSUE THREAD

**Issue by 136William136** [LAION-AI/Open-Assistant#2874]
I started OA on my own server with docker and asked a few questions. The answers are quite unrelated to what I asked. Is this because of the weight ?

**Comment by 136William136** [comment]
![image](https://user-images.githubusercontent.com/128681247/233936924-d48c24ee-7648-4a1e-8e84-37b57a4be441.png)
The response goes something like this. I think there mightbe some problem with my configuration?

**Comment by olliestanley** [comment]
Did you change the model configured in `docker-compose.yml` before launching the worker? If not it will run `distilgpt2` which is pretty much just a tiny nonsense model for testing
