### ISSUE TITLE
How to prompt the model for effective generation?

### ISSUE THREAD

**Issue by marcovirgolin** [LAION-AI/Open-Assistant#2896]
I apologize in advance but I just cannot seem to find a definitive answer to this, even though I'm sure it must be somewhere.

How do we effectively prompt the models?

I found the two following recommendations.

1) OPTION 1
Prepend this to user request:
```
<|prefix_begin|>You are a large language model that wants to be helpful<|prefix_end|><|prompter|>
```

Prepend this for the assistant to generate:
```
<|endoftext|><|assistant|>
```

2) OPTION 2
Prepend this to user request:
```
\n\nUser: 
```

Prepend for the assistant to generate:
```
\n\nAssistant: 
```

Or, is there some integration (Langchain / fastAPI), possibly under way, such that this is done for us under the hood?

**Comment by andreaskoepf** [comment]
Neither `<|system|>` nor `<|prefix_begin|>` are currently supported. You could simply prepend the pre-text or place it in the prompter block.
The format is currently: `<|prompter|>Q</s><|assistant|>A</s><|prompter|>...` .. where `</s>` is the standard end-of-sequence token of the tokenizer used (i.e. it can differ from model to model).

**Comment by g588928812** [comment]
> The format is currently: `<|prompter|>Q</s><|assistant|>A</s><|prompter|>...` .. where `</s>`

So for oasst-sft-6-llama-30b the format is this: `<|prompter|>Q</s><|assistant|>A</s><|prompter|>...` ?
(and not `<|prompter|>Q<|endoftext|><|assistant|>A<|endoftext|><|prompter|>...`) 

Sorry if this is a dumb question, just want to make sure. Didn't find any documentation on this except [here](https://github.com/LAION-AI/Open-Assistant/blob/9e43d98bd742dcdfe2bd21fe941ea7c3f66ab436/model/MESSAGE_AND_TOKEN_FORMAT.md) maybe

**Comment by andreaskoepf** [comment]
> So for oasst-sft-6-llama-30b the format is this: `<|prompter|>Q</s><|assistant|>A</s><|prompter|>...`

Yes, exactly. We use the native end-of-sequence token of the base model.

**Comment by maziyarpanahi** [comment]
I am having a hard time incorporating `input/context` into `OpenAssistant/oasst-sft-1-pythia-12b` model. The official token format is:

```
<|prompter|>What is a meme, and what's the history behind this word?<|endoftext|><|assistant|>
```
It seems with `\n` inside `prompter` we can have questions and then the context. But it is really a hit and miss most of the time unlike explicitly mentioning input inside `system` tag.
