### ISSUE TITLE
VRAM information estimate

### ISSUE THREAD

**Issue by snapo** [LAION-AI/Open-Assistant#2904]
How much VRAM do the models approx. consume?

OA_SFT_Llama_30B_6 = my estimate about 68GB vram
12B model = 40GB vram
...

Are those assumptions right? Should i be able to run OA_SFT_Llama_30B_6 with 3 x RTX 3090 (72GB vram)?

**Comment by olliestanley** [comment]
Cannot guarantee, but I would think you should be able to run a 30B model (in FP16) with 72GB VRAM, although maybe you would have to limit context length quite heavily. We run inference on a single A100 (80GB) and I think we have to limit context length to 1792 to avoid OOMs.
