### ISSUE TITLE
'too many requests in 1 hour' with Google Sheets API

### ISSUE THREAD

**Issue by HasbersHz** [LAION-AI/Open-Assistant#2905]
(Sorry for bad english)
I paste enormous text, and then I get this error message. Maybe this is duplicate, but i not found other issue about this.
Default k50 config, text includes russian, english and code.

ERROR: The error message 'too many requests in 1 hour' usually means that there is an issue with your API key or IP address being rate-limited by Google Sheets API. Please try regenerating a new API key and using that instead, and make sure you are not making too many requests within a short period of time.
To fix this, generate a new API key from the Google Developers Console and use it to authenticate your program. You can also add delays between requests to avoid hitting the limit. Additionally, check if any other programs or scripts are also accessing your sheet simultaneously, which could be contributing to the limit exceeded errors.

**Comment by andrewm4894** [comment]
yep i am not sure this sounds like an issue - will close it for now but feel free to update and we can re-open if occurs again.
