### ISSUE TITLE
API https://open-assistant.io/api/user_stats fails with server error 500

### ISSUE THREAD

**Issue by nikitazu** [LAION-AI/Open-Assistant#2909]
API call fails with server error on the Chat page.

```
Request URL: https://open-assistant.io/api/user_stats
Request Method: GET
Status Code: 500 
```

-Also there are frontend console errors, not sure if they are caused by the API error, or a separate issue.-
Edit: frontend errors go first so they aren't related to server error.

![image](https://user-images.githubusercontent.com/271185/234378910-c3aa5163-5113-4cb6-93cd-1f46215747ee.png)

**Comment by DeanChugall** [comment]
Everything is ok from my side...


![123](https://user-images.githubusercontent.com/4832847/234386866-03e8ecc5-e6a0-402c-a74b-1ffc82605c51.png)

**Comment by DeanChugall** [comment]
Yeah...now get error **500**  !

**Comment by olliestanley** [comment]
This is probably just a function of the server having been overloaded
