### ISSUE TITLE
Chats disappeared

### ISSUE THREAD

**Issue by einarpetersen** [LAION-AI/Open-Assistant#2912]
It looks like conversations have disappeared - Instead I was met with commercials for your partners plastered across where the conversations were stored

**Comment by andreaskoepf** [comment]
We migrated servers yesterday, some chat data may have been lost. Please try again now.

**Comment by einarpetersen** [comment]
Nope they are still gone, too bad I had been entering a tri language matrix of one of my books in Faroese, english and Chinese that could have been used to get better translations between languages because currently it is quite lacking just like for the rest of the LLMs
