### ISSUE TITLE
Can not access the chat in open assistant. 

### ISSUE THREAD

**Issue by Dwarfthrower** [LAION-AI/Open-Assistant#2918]
![C7A1321F-0954-411F-84B5-9CE4DDE52048](https://user-images.githubusercontent.com/65985393/234484818-220f0ac0-b733-49d5-99fb-95be86ddcce7.png)
When trying to access the chat in open assistant I get the error “Sorry, we encountered a server error. We're not sure what went wrong.”  I am using safari on iPhone 12.

**Comment by crazy26741** [comment]
Same service error, I just encountered, I clear the cache and login again can not log in

**Comment by z11h** [comment]
same error here

**Comment by goninja808** [comment]
+1 same error ... 
Occurs after javascript of the page seems to intent 1 call to https://www.diglife.eu/chat and then 3 call to  https://www.diglife.eu/_next/data/... /en/chat.json that result all in 500 code (server error) http response.
Finally browser console indicate the following javascript  :: TypeError: null is not an object (evaluating 'R.json=self.__NEXT_DATA__.props')
Hope you are progressing on that issue, too bad this initiative seem to suffer that failure for more then one.

**Comment by andreaskoepf** [comment]
> Occurs after javascript of the page seems to intent 1 call to https://www.diglife.eu/chat and then 3 call to https://www.diglife.eu/_next/data/... /en/chat.json that result all in 500 code (server error) http response.

Interesting. The website you mention seems to use parts of OA but this project is independent from the official OA project, e.g. they use different servers and inference machines.

**Comment by andreaskoepf** [comment]
@Dwarfthrower At the moment our inference system (on the official OA website) seems to work properly. Please try again and let us know.
