### ISSUE TITLE
无法使用对话，报错500

### ISSUE THREAD

**Issue by branch312** [LAION-AI/Open-Assistant#2919]
![image](https://user-images.githubusercontent.com/65875524/234487718-5a3bad30-8a6f-4028-9440-8db23483708d.png)
报错截图如上，提示信息
Sorry, we encountered a server error. We're not sure what went wrong.

**Comment by Leawnn** [comment]
再试试：https://open-assistant.io/chat
我可以的

**Comment by andreaskoepf** [comment]
Please try again.

**Comment by branch312** [comment]
网站已经关闭了吗，连续多天无法正常访问了


| |
郑军
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | Andreas ***@***.***> |
| 发送日期 | 2023年4月27日 16:17 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [LAION-AI/Open-Assistant] 无法使用对话，报错500 (Issue #2919) |

Closed #2919 as completed.

**Comment by crazy26741** [comment]
国内IP好像访问不到了，要科学上网才能访问

**Comment by branch312** [comment]
期待国内能够正常访问，科学上网对我的工作环境契合度不高


| |
郑军
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年5月17日 10:02 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [LAION-AI/Open-Assistant] 无法使用对话，报错500 (Issue #2919) |

国内IP好像访问不到了，要科学上网才能访问

**Comment by crazy26741** [comment]
IDEA可以使用BITO插件，搭配的是GPT-4模型，目前还可以免费使用，效果还不错。知乎地址：https://zhuanlan.zhihu.com/p/625188986



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月17日(星期三) 上午10:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LAION-AI/Open-Assistant] 无法使用对话，报错500 (Issue #2919)





 期待国内能够正常访问，科学上网对我的工作环境契合度不高
 
 
 | |
 郑军
 |
 |
 ***@***.***
 |
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 发送日期 | 2023年5月17日 10:02 |
 | 收件人 | ***@***.***&gt; |
 | 抄送人 | ***@***.***&gt; ,
 ***@***.***&gt; |
 | 主题 | Re: [LAION-AI/Open-Assistant] 无法使用对话，报错500 (Issue #2919) |
 
 国内IP好像访问不到了，要科学上网才能访问

**Comment by branch312** [comment]
收到，感谢


| |
郑军
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年5月17日 10:08 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [LAION-AI/Open-Assistant] 无法使用对话，报错500 (Issue #2919) |

IDEA可以使用BITO插件，搭配的是GPT-4模型，目前还可以免费使用，效果还不错。知乎地址：https://zhuanlan.zhihu.com/p/625188986



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;;
发送时间: 2023年5月17日(星期三) 上午10:05
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;; ***@***.***&gt;;
主题: Re: [LAION-AI/Open-Assistant] 无法使用对话，报错500 (Issue #2919)





期待国内能够正常访问，科学上网对我的工作环境契合度不高


| |
郑军
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***&gt; |
| 发送日期 | 2023年5月17日 10:02 |
| 收件人 | ***@***.***&gt; |
| 抄送人 | ***@***.***&gt; ,
***@***.***&gt; |
| 主题 | Re: [LAION-AI/Open-Assistant] 无法使用对话，报错500 (Issue #2919) |

国内IP好像访问不到了，要科学上网才能访问
