### ISSUE TITLE
What is open assistant

### ISSUE THREAD

**Issue by potatochief** [LAION-AI/Open-Assistant#2920]
im new to this, what is this dialog box about?

**Comment by andrewm4894** [comment]
I'm not sure I understand, can you provide more info and some screenshots?

**Comment by andreaskoepf** [comment]
The mission of OpenAssistant is to develop an open-source AI chat-assistant that can follow natural language instructions, fulfill tasks, retrieve information and interact with third-party APIs.
At the heart of the project is the AI alignment of a large language model (LLM). This process aims to steer a language model to communicate in a positive, polite, honest, helpful and harmless manner with the user.
A crucial ingredient for training such a model is a dataset which captures the distribution of desired responses that the model after training will mimic. Building such a dataset is extremely labor and time intensive. We decided to start a large crowd-sourcing campaign and created a web site (open-assistant.io) to gather human demonstrations of prompter-assistant dialogues together with user ratings and reply-rankings to capture human preferences.
The dialogue & preference dataset is then used to fine-tune pre-trained LLMs in a process known as reinforcement learning from human feedback (RLHF). One of the main contributions of OA is to publish the dataset and make it available for everyone to train their own models.
The OA project is a joint effort of hundreds of volunteers from all over the world who collaborate via GitHub and Discord. Thousands of users contributed by completing tasks on our crowed-sourcing data collection website to the OA dataset between January and April this 2023.
