### ISSUE TITLE
GDPR and the crowd-sourced data used for OpenAssistant

### ISSUE THREAD

**Issue by Mikeriess** [LAION-AI/Open-Assistant#2922]
Dear OA team,

First of all - my biggest respect and admiration for the work you have done as well as the vision you follow. 

In relation to the data that have been generated for OA, I recently stumbled upon this article:
https://www.technologyreview.com/2023/04/19/1071789/openais-hunger-for-data-is-coming-back-to-bite-it/ 

Here's the important part:

_Italy has given OpenAI [until April 30](https://www.garanteprivacy.it/home/docweb/-/docweb-display/docweb/9874751#english) to comply with the law. This would mean OpenAI would have to ask people for consent to have their data scraped, or prove that it has a “legitimate interest” in collecting it. OpenAI will also have to explain to people how ChatGPT uses their data and give them the power to correct any mistakes about them that the chatbot spits out, to have their data erased if they want, and to object to letting the computer program use it._

So to future-proof OA and the data used for training, I would suggest to get a formal consent (in GDPR terms) from the users that contributed to the dataset if that has not already been given. Since both you and the data are well-organized this should be relatively easy. 

Not sure if this is a problem at all, just wanted to help in case it was.

Best
Mike

**Comment by olliestanley** [comment]
We do require this consent in TOS on sign-up, but we are also currently working on a feature to opt-out from your chats being used for training the model

**Comment by Mikeriess** [comment]
Very good to hear. 

A subject for discussion - and perhaps even a video from Yannic: how to handle this in the embeddings? Can the information even be reliably removed in this case?

**Comment by olliestanley** [comment]
> Very good to hear.
> 
> A subject for discussion - and perhaps even a video from Yannic: how to handle this in the embeddings? Can the information even be reliably removed in this case?

Not quite sure what you mean by this, can you explain further?
