### ISSUE TITLE
idea: Public Data collection API

### ISSUE THREAD

**Issue by DominiqueGarmier** [LAION-AI/Open-Assistant#2925]
make the current api for datacollection / labeling / ranking public and documented

#### why? (immediate motivation):
this would allow third party Inference providers to hook the data they generate back into the SFT and HFRL loop.
(I have no idea if something like this currently in the works with HuggingChat)

#### just my opinion:
as discussed in https://github.com/LAION-AI/Open-Assistant/issues/2806#issuecomment-1522435283 (and I agree with this) providing Inference will be a challenge going forward, so open-assistant should build out what it's great at. And that is (in my opinion) the data platform.

**Comment by olliestanley** [comment]
This could be possible but we would need to be quite careful with who has access to the API to avoid opening up the opportunity for high-volume spam
