### ISSUE TITLE
Running locally - where to place the model

### ISSUE THREAD

**Issue by StonefieldStoneman** [LAION-AI/Open-Assistant#2930]
Hi, awesome project.
I need to run the Model locally for a University paper (We want to test and finetune the model later on with german texts). I've got the whole stack from this repo running via docker compose. 
Additionally I've generated the model oasst-sft-6-llama-30b from https://huggingface.co/OpenAssistant/oasst-sft-6-llama-30b-xor using the original LLAMA 30B weights. All Hashes from the resulting files match. So far so perfect!

But now I'm lost. Where to place the resulting files for the OpenAssistant Stack from this repo to use them? I can't fin any documentation abeout this. Another way to run via console would be an option as well for me.

Many Thanks!

Lars

**Comment by deftdawg** [comment]
The models are expected to be at the `inference-worker` container's `/data` directory.

**Comment by olliestanley** [comment]
> The models are expected to be at the `inference-worker` container's `/data` directory.

You could also use the same approach we use for OA which is to upload the model as a private model to your HuggingFace. Then the worker (configured with access to your HF) can directly pull the model when it starts up.
