### ISSUE TITLE
create unfilterd model

### ISSUE THREAD

**Issue by nekohacker591** [LAION-AI/Open-Assistant#2932]
a version of the model that can be hosted localy

this model does not refrence any terms of service and basicly does not decline any prompts

kind of like gpt4 x alpaca

**Comment by andreaskoepf** [comment]
Do you mean a model that was trained without any additional synthetic datasets?

**Comment by gerkim62** [comment]
I think such a model would introduce some serious ethical concerns. People would use it to do anything, illegal stuff.

**Comment by andreaskoepf** [comment]
Our goal is to collect data to align language model to values and preferences shared by a larger group of humans.

**Comment by olliestanley** [comment]
To be clear, the current model isn't "filtered". When it refuses to do something, that's just the behaviour of the model, not due to any additional filters

**Comment by FrankDMartinez** [comment]
> Our goal is to collect data to align language models to values and preferences shared by a larger group of humans.

Isn’t that always a concern with any new technology? How often do we deliberately hamper it because someone might do something we don’t like?

**Comment by FrankDMartinez** [comment]
> I think such a model would introduce some serious ethical concerns. People would use it to do anything, illegal stuff.

Isn’t that always a concern with any new technology? How often do we deliberately hamper it because someone might do something we don’t like?
