### ISSUE TITLE
my user is not working now

### ISSUE THREAD

**Issue by anon62** [LAION-AI/Open-Assistant#2940]
He has been working recently
https://anonfiles.com/s3Z8Mbn1za/
https://anonfiles.com/qdydNan8zd
this also throws a 403 errors in the development сonsole
can you fix it?

**Comment by olliestanley** [comment]
We will need more information on what you are trying to report here. Feel free to reopen this issue if you can provide more details

**Comment by anon62** [comment]
> We will need more information on what you are trying to report here. Feel free to reopen this issue if you can provide more details

What details should I send?

photos:
https://anonfiles.com/Oazcpeodzc
https://anonfiles.com/s3Z8Mbn1za/
https://anonfiles.com/qdydNan8zd

**Comment by anon62** [comment]
It seems that all account data has been deleted

> > We will need more information on what you are trying to report here. Feel free to reopen this issue if you can provide more details
> 
> What details should I send?
> 
> photos: https://anonfiles.com/Oazcpeodzc https://anonfiles.com/s3Z8Mbn1za/ https://anonfiles.com/qdydNan8zd
