### ISSUE TITLE
Periodic Updates

### ISSUE THREAD

**Issue by sr5434** [LAION-AI/Open-Assistant#2941]
OpenAssistant should be updated every 3-6 months with the latest information. This way, OpenAssistant will know about current events. This can be achieved by generating chat data about current events and combining them into the dataset. Then, training can be resumed on the updated data.

**Comment by andreaskoepf** [comment]
Adding knowledge via training is possible but also a very expensive approach. We are currently discussing retrieval augmentation, e.g. by providing a wikipedia index. Such an index can be updated with relatively modest compute resources and new knowledge becomes instantly available.

**Comment by sr5434** [comment]
That makes sense. It is probably a better idea to use a retrieval index.
