### ISSUE TITLE
Open Assistant - not available for use.

### ISSUE THREAD

**Issue by prog979** [LAION-AI/Open-Assistant#2955]
Dear developers!
Today 28.04.2023 Open Assistant is experiencing technical problems.
Open Assistant - not available for use.
The answer to the question - timeout expires.
See attached screenshot.
![изображение_2023-04-28_134425021](https://user-images.githubusercontent.com/56035708/235127884-d01f68cc-1e6f-4869-8a0f-a417eec2e9a3.png)

**Comment by myname1111** [comment]
I can confirm that this is happening to me too

**Comment by gerlacus** [comment]
Thanks for opening this issue - the same is happening for me as well.

**Comment by andreaskoepf** [comment]
The problem should be resolved now. Please try again.
