### ISSUE TITLE
some answers is not in Chinese

### ISSUE THREAD

**Issue by jiaowobaba02** [LAION-AI/Open-Assistant#2966]
![image](https://user-images.githubusercontent.com/69029820/235283348-dde32228-9a91-484c-9d7d-c11b31b81566.png)

**Comment by suparious** [comment]
It seems to understand the chinese accurately. What seems to be the issue?

**Comment by planetoryd** [comment]
duplicate

**Comment by olliestanley** [comment]
This is most likely a function of insufficient Chinese training data, either in the base model (LLaMA) or finetuning. It is not really something we can "fix" without more data
