### ISSUE TITLE
use GLM-130B insted of llama

### ISSUE THREAD

**Issue by calvinweb** [LAION-AI/Open-Assistant#2967]
[GLM-130B](https://github.com/THUDM/GLM-130B) ` is a opensource LLM model with 130B params and in both Chinese and English. Compare to LLAMA-30B it have much more params and no license problem

**Comment by olliestanley** [comment]
GLM 130B has the same license problems as LLaMA - it is not permitted to be used for commercial use.

There are currently some experiments with SFT on LLaMA 65B for a larger model, but I don't think we will use GLM as the compute required for 130B is very large and LLaMa likely achieves better "performance per parameter"
