### ISSUE TITLE
500 POST ERROR cannot chat

### ISSUE THREAD

**Issue by staminna** [LAION-AI/Open-Assistant#2990]
Docker, latest git pull as of today,
After registering user, in the main chat menu, I can't submit or get any answer on the latest Docker version, Macbook M1 Pro:

Where do the API key go? I also think also might be DNS issue, but here is what I can see:

![Captura de ecrã 2023-04-30, às 23 57 56](https://user-images.githubusercontent.com/515180/235379853-148fb176-18e7-4e79-9007-533de9c1bc11.png)

I can submit prompts successfully:

open-assistant-web-1                  | AxiosError: getaddrinfo ENOTFOUND inference-server
open-assistant-web-1                  |     at Function.AxiosError.from (file:///app/node_modules/axios/lib/core/AxiosError.js:89:14)
open-assistant-web-1                  |     at RedirectableRequest.handleRequestError (file:///app/node_modules/axios/lib/adapters/http.js:577:25)
open-assistant-web-1                  |     at RedirectableRequest.emit (node:events:513:28)
open-assistant-web-1                  |     at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)
open-assistant-web-1                  |     at ClientRequest.emit (node:events:513:28)
open-assistant-web-1                  |     at Socket.socketErrorListener (node:_http_client:494:9)
open-assistant-web-1                  |     at Socket.emit (node:events:513:28)
open-assistant-web-1                  |     at emitErrorNT (node:internal/streams/destroy:157:8)
open-assistant-web-1                  |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
open-assistant-web-1                  |     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
open-assistant-web-1                  |   hostname: 'inference-server',
open-assistant-web-1                  |   syscall: 'getaddrinfo',
open-assistant-web-1                  |   code: 'ENOTFOUND',
open-assistant-web-1                  |   errno: -3008,
open-assistant-web-1                  |   config: {
open-assistant-web-1                  |     transitional: {
open-assistant-web-1                  |       silentJSONParsing: true,
open-assistant-web-1                  |       forcedJSONParsing: true,
open-assistant-web-1                  |       clarifyTimeoutError: false
open-assistant-web-1                  |     },
open-assistant-web-1                  |     adapter: [ 'xhr', 'http' ],
open-assistant-web-1                  |     transformRequest: [ [Function: transformRequest] ],
open-assistant-web-1                  |     transformResponse: [ [Function: transformResponse] ],
open-assistant-web-1                  |     timeout: 0,
open-assistant-web-1                  |     xsrfCookieName: 'XSRF-TOKEN',
open-assistant-web-1                  |     xsrfHeaderName: 'X-XSRF-TOKEN',
open-assistant-web-1                  |     maxContentLength: -1,
open-assistant-web-1                  |     maxBodyLength: -1,
open-assistant-web-1                  |     env: { FormData: [Function], Blob: null },
open-assistant-web-1                  |     validateStatus: [Function: validateStatus],
open-assistant-web-1                  |     headers: AxiosHeaders {
open-assistant-web-1                  |       Accept: 'application/json, text/plain, */*',
open-assistant-web-1                  |       'Content-Type': 'application/json',
open-assistant-web-1                  |       TrustedClient: 'eyJhcGlfa2V5IjoiNjk2OSIsImNsaWVudCI6IndlYnNpdGUiLCJwcm92aWRlcl9hY2NvdW50X2lkIjoiYjU1OTMyZDAtNmRmMy00Yzc5LWE4YjMtNjU2ZWNkZjY0YTE1IiwidXNlcl9pZCI6ImNsaDM1NTN2eDAwMDBtcTAxeXRyN3ZwbW4iLCJ1c2VybmFtZSI6IlByb2Nlc3NmbG93In0=',
open-assistant-web-1                  |       'User-Agent': 'axios/1.3.4',
open-assistant-web-1                  |       'Accept-Encoding': 'gzip, compress, deflate, br'
open-assistant-web-1                  |     },
open-assistant-web-1                  |     url: 'http://inference-server:8000/chats?limit=20',
open-assistant-web-1                  |     method: 'get',
open-assistant-web-1                  |     data: undefined
open-assistant-web-1                  |   },
open-assistant-web-1                  |   request: <ref *1> Writable {

I had to change the ports of "webdb" on the docker config .yaml and the service that connects to it to a different port because of a conflict with other services to bootstrap open assistant, as someone else already reported on the issue queue.

**Comment by olliestanley** [comment]
I guess you used `docker-compose --profile ci` to start up. This will only create the data collection backend and website. To use the chat locally you will also need to use `--profile inference` to create the inference setup.

**Comment by fmaestre69** [comment]
just had the issue , thanks :)
