### ISSUE TITLE
[SMALL Problem] MOVE 'wikihow' dataset to SUMMARISATION Datasets

### ISSUE THREAD

**Issue by loloMD** [LAION-AI/Open-Assistant#3027]
Version : **v0.0.3-alpha24-3-g26acf953**

In the file `Open-Assistant/model/model_training/custom_datasets/__init__.py`, move 'wikihow' dataset from variable `QA_DATASETS` to the variable `SUMMARIZATION_DATASETS`

**Comment by 0x22almostEvil** [comment]
Actually, not sure. I think it should be fine in instructions, but for summarization it'd be good too. Most data in this dataset in QnA format: How do I... How to... How can I make...; (just without question marks, but it's not a big deal). It fits well in both of these categories
