### ISSUE TITLE
Option to edit an assistant reply after it's been sent

### ISSUE THREAD

**Issue by IllusionDX** [LAION-AI/Open-Assistant#3031]
Sometimes, after completing tasks on the "Reply as Assistant" section of the website, one might realize they made a mistake in their response after sending it. However, there doesn't seem to be a way to edit the message directly in the "Messages" tab. The only available option is to report the message for review, but it's unclear whether the team can actually edit the message or just delete it.

It would be helpful to have the ability to edit our own messages directly, with a time limit of, say, two hours after the message has been sent.

**Comment by AbdBarho** [comment]
We have a lot of duplicates for this feature, this is one of them https://github.com/LAION-AI/Open-Assistant/issues/1925

I will close this for now.
