### ISSUE TITLE
Cleanup plugins backend code

### ISSUE THREAD

**Issue by olliestanley** [LAION-AI/Open-Assistant#3037]
Some initial cleanup has been done but there is more to do

**Comment by SerenityCodes** [comment]
I'll work on this issue. I'll start with the first two suggestions, cleaning up anything I touch, and I'll leave an update once I have finished up with those.

**Comment by olliestanley** [comment]
> I'll work on this issue. I'll start with the first two suggestions, and I'll leave an update once I have finished up with those.

Great, thank you. There is probably a lot more to do as plugins PR was merged in a rush, so feel free to comment any other suggestions you have!

**Comment by SerenityCodes** [comment]
I went ahead and implemented the first two suggestions. I'll be looking more into the plugins code to see what I can clear up.

**Comment by olliestanley** [comment]
Another round of cleanup in #3120, more still to be done

**Comment by olliestanley** [comment]
Closing this. Several rounds of cleanup have been done. More can be done when the plugins system can be simplified a bit with better models
