### ISSUE TITLE
Improve inference export script

### ISSUE THREAD

**Issue by olliestanley** [LAION-AI/Open-Assistant#3038]
`inference/server/export.py`

- Add ability to filter by conditions
- Include a filter for only chats which have at least one assistant message with score != 0
- Include a filter for specific date ranges
- Consider performance improvements such as use of lazy loading from the database

**Comment by simonusher** [comment]
I'd like to work on this

**Comment by olliestanley** [comment]
> I'd like to work on this 

Thank you, have assigned it to you.

**Comment by simonusher** [comment]
I've added the simple filters - date range, user id and chat id. Will need a bit more time to figure out how to set up the dev env to actually test it.

I also have a few things to clarify:
- should user_id and chat_id filters be for single user/chat or should they allow for multiple values?
- there's a todo comment in code that lists a couple of filters, including "... reported, score. You mentioned the score filter above - at least one assistant message with score != 0. What about reported? Should it only include chats with at least one reported message?

**Comment by olliestanley** [comment]
> * should user_id and chat_id filters be for single user/chat or should they allow for multiple values?

Single value is fine for this

> * there's a todo comment in code that lists a couple of filters, including "... reported, score. You mentioned the score filter above - at least one assistant message with score != 0. What about reported? Should it only include chats with at least one reported message?

Yes, a filter for chats with at least one reported message would be a great addition :)
