### ISSUE TITLE
cannot create new chat on fresh build 3cc6aa9

### ISSUE THREAD

**Issue by paranoidAndroid0124** [LAION-AI/Open-Assistant#3064]
open-assistant-web-1                  | TypeError: Cannot read properties of undefined (reading 'status')
open-assistant-web-1                  |     at OasstInferenceClient.create_chat (/app/.next/server/chunks/126.js:51:94)
open-assistant-web-1                  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
open-assistant-web-1                  |     at async /app/.next/server/pages/api/chat.js:86:16
open-assistant-web-1                  |     at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:363:9)
open-assistant-web-1                  |     at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:474:9)
open-assistant-web-1                  |     at async Object.fn (/app/node_modules/next/dist/server/next-server.js:736:37)
open-assistant-web-1                  |     at async Router.execute (/app/node_modules/next/dist/server/router.js:252:36)
open-assistant-web-1                  |     at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:383:29)
open-assistant-web-1                  |     at async NextNodeServer.handleRequest (/app/node_modules/next/dist/server/base-server.js:321:20)
open-assistant-web-1                  |     at async Server.<anonymous> (/app/server.js:19:5)

**Comment by olliestanley** [comment]
What command did you use to start the site etc?

**Comment by paranoidAndroid0124** [comment]
I used this command from the Readme:
docker compose --profile ci up --build --attach-dependencies

Then, I navigated the site and tried to start a new chat.

**Comment by olliestanley** [comment]
> I used this command from the Readme: docker compose --profile ci up --build --attach-dependencies
> 
> Then, I navigated the site and tried to start a new chat.

Ok, to enable chat you also need the `inference` profile not just `ci`, the readme has some instructions on this a little below the command you used
