### ISSUE TITLE
When starting Docker on Win10

### ISSUE THREAD

**Issue by kszumko** [LAION-AI/Open-Assistant#3065]
Cannot open a new chat. Can do everything else, but not new chat. 
Seems like two services in Docker cannot start properly. 

open-assistant-web-1                  | AxiosError: getaddrinfo ENOTFOUND inference-server
open-assistant-web-1                  |     at Function.AxiosError.from (file:///app/node_modules/axios/lib/core/AxiosError.js:89:14)
open-assistant-web-1                  |     at RedirectableRequest.handleRequestError (file:///app/node_modules/axios/lib/adapters/http.js:577:25)
open-assistant-web-1                  |     at RedirectableRequest.emit (node:events:513:28)
open-assistant-web-1                  |     at ClientRequest.eventHandlers.<computed> (/app/node_modules/follow-redirects/index.js:14:24)
open-assistant-web-1                  |     at ClientRequest.emit (node:events:513:28)
open-assistant-web-1                  |     at Socket.socketErrorListener (node:_http_client:494:9)
open-assistant-web-1                  |     at Socket.emit (node:events:513:28)
open-assistant-web-1                  |     at emitErrorNT (node:internal/streams/destroy:157:8)
open-assistant-web-1                  |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
open-assistant-web-1                  |     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
open-assistant-web-1                  |   hostname: 'inference-server',
open-assistant-web-1                  |   syscall: 'getaddrinfo',
open-assistant-web-1                  |   code: 'ENOTFOUND',
open-assistant-web-1                  |   errno: -3008,
open-assistant-web-1                  |   config: {
open-assistant-web-1                  |     transitional: {
open-assistant-web-1                  |       silentJSONParsing: true,
open-assistant-web-1                  |       forcedJSONParsing: true,
open-assistant-web-1                  |       clarifyTimeoutError: false
open-assistant-web-1                  |     },
open-assistant-web-1                  |     adapter: [ 'xhr', 'http' ],
open-assistant-web-1                  |     transformRequest: [ [Function: transformRequest] ],
open-assistant-web-1                  |     transformResponse: [ [Function: transformResponse] ],
open-assistant-web-1                  |     timeout: 0,
open-assistant-web-1                  |     xsrfCookieName: 'XSRF-TOKEN',
open-assistant-web-1                  |     xsrfHeaderName: 'X-XSRF-TOKEN',
open-assistant-web-1                  |     maxContentLength: -1,
open-assistant-web-1                  |     maxBodyLength: -1,
open-assistant-web-1                  |     env: { FormData: [Function], Blob: null },
open-assistant-web-1                  |     validateStatus: [Function: validateStatus],
open-assistant-web-1                  |     headers: AxiosHeaders {
open-assistant-web-1                  |       Accept: 'application/json, text/plain, */*',
open-assistant-web-1                  |       'Content-Type': 'application/json',
open-assistant-web-1                  |       TrustedClient: 'eyJhcGlfa2V5IjoiNjk2OSIsImNsaWVudCI6IndlYnNpdGUiLCJwcm92aWRlcl9hY2NvdW50X2lkIjoiNDRmMDhjNzktOWEwZS00ZGJhLWE0ZmQtZTMyYmFiNDdjNDI2IiwidXNlcl9pZCI6ImRldiIsInVzZXJuYW1lIjoiZGV2In0=',
open-assistant-web-1                  |       'User-Agent': 'axios/1.3.4',
open-assistant-web-1                  |       'Accept-Encoding': 'gzip, compress, deflate, br'
open-assistant-web-1                  |     },
open-assistant-web-1                  |     url: 'http://inference-server:8000/chats?limit=20',
open-assistant-web-1                  |     method: 'get',
open-assistant-web-1                  |     data: undefined
open-assistant-web-1                  |   },

**Comment by olliestanley** [comment]
You didn't start the inference stack. `--profile inference` must be added as a separate profile in Docker compose which will enable the inference server. The command in readme (`--profile ci`) is just for local development of the site/data collection backend, and most people will probably not have the hardware to run the inference profile with a real model (although you can run it with a dummy model for testing)
