### ISSUE TITLE
plugins

### ISSUE THREAD

**Issue by Bensolz** [LAION-AI/Open-Assistant#3076]
the openassistant chat page shows a button to select plugins but there arent any am i doing something wrong or is it just not released yet?

**Comment by olliestanley** [comment]
You have to put plugin API URLs in yourself, we don't offer any out of the box with OA yet

**Comment by Battledash-2** [comment]
Where do you find the plugins? I've tried googling it but there's virtually nothing 😅

**Comment by andrewm4894** [comment]
I am going to have a go at making some docs for plugins if i can get a minimal example together
