### ISSUE TITLE
how to use plugins

### ISSUE THREAD

**Issue by gsaivinay** [LAION-AI/Open-Assistant#3081]
Hello guys,

I'm looking for an example of how to use plugins in OA chat interface. Where can I find plugins that works with this specifications? Highly appreciate some examples.

Thanks for this awesome work and contribution towards open source.

**Comment by dannkunt** [comment]
You can find some related info [here](https://github.com/LAION-AI/Open-Assistant/blob/main/inference/worker/PLUGINS.md)

**Comment by gsaivinay** [comment]
Awesome, thanks 😃 . Now I got some idea on how they look like...

**Comment by gsaivinay** [comment]
I must say this is excellent addition to already awesome OA. While I'm in waitlist from forever for ChatGPT plugins access, this opened doors for so many possibilities.

<img width="945" alt="image" src="https://user-images.githubusercontent.com/9410663/236703658-a6d9e904-62c5-4ab6-a31a-855440af843c.png">
