### ISSUE TITLE
Prompt with request for creating placeholders gets stuck in a loop

### ISSUE THREAD

**Issue by Listor** [LAION-AI/Open-Assistant#3084]
I did try out a use-case where I wanted to identify personal data in a text and replace them with placeholders. The prompt was in German and is this one:

'Kannst du mir aus folgendem Text, alle personenbezogenen Daten durch Platzhalter ersetzen: "Ich möchte ein Geschenk für Peter kaufen, er ist mein Vater und er lebt in Düsseldorf und am besten wäre es, wenn das Paket direkt zu seiner Firma Steuerbüro Bram, verschickt wird. Also vielleicht etwas, dass ich online bestellen kann und das sich leicht per Express verschicken lässt. Gut wäre, wenn ich das Datum angeben könnte, an dem es ankommen soll. Der 15.5 wäre mein Wunschdatum, dass ist nämlich sein Geburtstag"'

The personal data in this text is made up and was just for test purposes.

After that I got this response:

"Um die personenbezogenen Daten im übergebenen Text durch Placeholder-Zeichen zu ersetzen, können Sie beispielsweise folgende Zeichen verwenden:

%firstName%, %lastName%, %street%, %city%, %postalCode%, %country%

Beachten Sie jedoch, dass diese Ersetzung nur eine provisorische Lösung darstellt, da sie nicht berücksichtigt, ob der Adressat tatsächlich existiert oder wo genau die angegebene Adresse liegt. Es empfiehlt sich daher immer den genauesten möglichen Adressdatensatz zur Verfügung zu stellen."

Which the request was misunderstood in my opinion. So i requested again to replace the personal data with placeholders with this prompt:

"Nein die Aufgabe war, den Text so anzupassen, dass alle personenbezogenen Daten durch Platzhalter ersetzt werden, kannst du das machen?"

And got this response:

Gerne! Hier ist dein text mit den personenbezogener Daten durch Striche ___\_ markiert.

`
___Ich möchte___ ___Geschenk___ ___Peter___ ___kaufen____, ___er___ ___mein___ ___Vater___ ___und___ ___lebt___ ___Düsseldorf___ ___am_______ ___besten___ ___wäre___ ___es_______________, ___das___ ___Paket_______________, ___direkt_______ ___zu_______ ___seiner_______ ___Firma_______ ___Steuerbüro_______________. ___Also***************, ___vieles*************** **************_, ___das/**/*******/**************/**/*******/**************//***//*******/**************//***//*******/**************//***//*******. //////*//*///******/******/******/******/******/******/******/, ___gut***************, ___wenn**************_, ___ich***************, ___das**************, ___online**************/*//*//*******/**************/*//*//*******/**************/*//*//*******/**************/*//*//*******/**************/*//*//*******/**************/*//*//*******/**************/*//*//*******/**************/*//*//*******/**************/*//*//******/. /////*//*///******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******/******`

It felt like it was generating in an constant loop at some point and only stopped because of a timeout I assume. Either way I think there is something incorrect going on.

Maybe someone with a better understand can look into this. Sadly trying to reproduce this didn't result in the same issue.

**Comment by olliestanley** [comment]
Can you share model config and sampling parameters used?

**Comment by Listor** [comment]
Sure my bad I did not make any adjustments so the default config and parameters I assume:

{
  "model_config": {
    "model_id": "OpenAssistant/oasst-sft-6-llama-30b",
    "max_input_length": 1024,
    "max_total_length": 1792,
    "quantized": false
  },
  "sampling_parameters": {
    "top_k": 50,
    "top_p": 0.95,
    "typical_p": null,
    "temperature": 0.75,
    "repetition_penalty": 1.2,
    "max_new_tokens": 1024
  },
  "do_sample": true,
  "plugins": []
}
