### ISSUE TITLE
Update default model selection

### ISSUE THREAD

**Issue by olliestanley** [LAION-AI/Open-Assistant#3085]
New users get defaulted to SFT 6 but I think SFT 7 is noticeably better. We should change the default to SFT 7. I don't think RLHF is ready to be default yet.

**Comment by notmd** [comment]
The website uses the first model as the default model. You can adjust the order of the model in the response to achieve this

**Comment by olliestanley** [comment]
> The website uses the first model as the default model. You can adjust the order of the model in the response to achieve this

Ok, thanks. I guess this is an inference backend issue instead of website. However Andreas mentioned that currently SFT 7 and RLHF are the ones which stop responding when our compute is not available so maybe it's better to keep SFT 6 as default for now anyway, as it has better uptime
