### ISSUE TITLE
Cleanup plugins documentation

### ISSUE THREAD

**Issue by olliestanley** [LAION-AI/Open-Assistant#3087]
- Move most content of `inference/worker/PLUGINS.md` to `docs/`.
- Move technical content to `inference/worker/README.md`.
- Cleanup plugins docs and add more explanation on using them in the web UI.

**Comment by y3sar** [comment]
@olliestanley i would like to get involved in this incredible project. Can I take this as my first issue?

**Comment by y3sar** [comment]
@olliestanley ok ill keep you updated

**Comment by andrewm4894** [comment]
adding some maybe related links in here: https://github.com/someone13574/oasst-plugin-template

**Comment by andrewm4894** [comment]
p.s. im going to try start with this more narrow task to just create a tutorial or sorts on how to use it https://github.com/LAION-AI/Open-Assistant/issues/3271

**Comment by andrewm4894** [comment]
Made initial minimal PR here

https://github.com/LAION-AI/Open-Assistant/pull/3272
