### ISSUE TITLE
Create a way to navigate to and view conversations branches given a message id

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#309]
Given a `message_id` we can fetch the full conversation tree it resides within and the various branches.

It's not obvious how to best do this so please experiment with different approaches and describe them here in this issue before making a pull request.

Potential API methods to user:
- `/api/v1/messages/{message_id}/tree`
- `/api/v1/messages/{message_id}/children`
- `/api/v1/messages/{message_id}/descendants`

This could also leverage #308 as a base whereby someone can click a message in the conversation, see branches and then navigate to that branch conversation.

**Comment by jojopirker** [comment]
Somewhat like this? I still have some bugs with it, but may be a start... 
its just a hacky solution to display children and parents, so would need to be reworked the be more flexible 



https://user-images.githubusercontent.com/19796430/210849009-df5c03d8-d67d-4646-8091-64e555d49aff.mov

**Comment by fozziethebeat** [comment]
Yes! That's certainly functional and meets the key need.  I'd be happy with starting with that and then improving it visually later.

**Comment by jojopirker** [comment]
I made a draft here #440 :)

**Comment by fozziethebeat** [comment]
I think I accidentally self-assigned this.  i've now assigned it to @jojopirker

**Comment by AbdBarho** [comment]
could this be closed by #440 ?

**Comment by fozziethebeat** [comment]
Yes, I think that's sufficient enough to close this issue.  We can open future issues for specific improvements to it.
