### ISSUE TITLE
Weird plugins UI behaviour in the chat

### ISSUE THREAD

**Issue by Reblexis** [LAION-AI/Open-Assistant#3096]
Location: https://open-assistant.io/chat -> 'Create a new chat' .

When I press the 'plus' button to add a plugin in the plugins tab and then close the 'Edit Plugin' window (by pressing the 'x' close button) a weird empty plugin gets added which I still can toggle. And the bar looks like this.

![image](https://user-images.githubusercontent.com/80317928/236918873-cee5a23c-d9fd-4457-9857-4b862290043c.png)

**Comment by notmd** [comment]
fixed but not release on prod yet.
