### ISSUE TITLE
Text is layered on the send button (and settings) in the chat

### ISSUE THREAD

**Issue by 0x22almostEvil** [LAION-AI/Open-Assistant#3097]
One user noticed this:
![image](https://user-images.githubusercontent.com/122345469/236920044-b92f5d3e-a7ad-474b-b221-2cee5b288a9e.png)
![image](https://user-images.githubusercontent.com/122345469/236920065-25b898c8-e0aa-4f1a-b8db-942b1836ef55.png)

PC:
![image](https://user-images.githubusercontent.com/122345469/236919912-e78cbf6d-74d7-4a8d-a729-e50831131bce.png)
Mobile:
![image](https://user-images.githubusercontent.com/122345469/236919947-31f28532-6a5a-4889-a285-f456d128e172.png)

**Comment by iggual** [comment]
Thank you man!:)

**Comment by HassanTanveer** [comment]
Please assign this issue to me. I can help.

**Comment by HassanTanveer** [comment]
I think I've fixed the issue in this [pull request](https://github.com/LAION-AI/Open-Assistant/pull/3102). Please let me know if any changes are required.

**Comment by 0x22almostEvil** [comment]
@HassanTanveer Thanks! Suggested one thing in your PR
