### ISSUE TITLE
website Chat error

### ISSUE THREAD

**Issue by C0deXG** [LAION-AI/Open-Assistant#3103]
when i open the website and click create new a chat it is giving me this error:
 cause: Error: connect ECONNREFUSED ::1:8000

`error - AxiosError: connect ECONNREFUSED ::1:8000
    at AxiosError.from (file:///Users/khederyusuf/Desktop/Open-Assistant/website/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///Users/khederyusuf/Desktop/Open-Assistant/website/node_modules/axios/lib/adapters/http.js:577:25)
    at RedirectableRequest.emit (node:events:513:28)
    at eventHandlers.<computed> (/Users/khederyusuf/Desktop/Open-Assistant/website/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  port: 8000,
  address: '::1',
  syscall: 'connect',
  code: 'ECONNREFUSED',
  errno: -61,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      TrustedClient: 'eyJhcGlfa2V5IjoiNjk2OSIsImNsaWVudCI6IndlYnNpdGUiLCJwcm92aWRlcl9hY2NvdW50X2lkIjoiZjA2ZDJiZmItNWNkZC00NjliLTg4ZWEtYTRhNzJlOWZmZjRmIiwidXNlcl9pZCI6ImRldiIsInVzZXJuYW1lIjoiZGV2In0=',
      'User-Agent': 'axios/1.3.4',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    url: 'http://localhost:8000/chats?limit=20&include_hidden=false',
    method: 'get',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/chats?limit=20&include_hidden=false',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'localhost',
      port: '8000',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/chats',
      search: '?limit=20&include_hidden=false'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /chats?limit=20&include_hidden=false HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'TrustedClient: eyJhcGlfa2V5IjoiNjk2OSIsImNsaWVudCI6IndlYnNpdGUiLCJwcm92aWRlcl9hY2NvdW50X2lkIjoiZjA2ZDJiZmItNWNkZC00NjliLTg4ZWEtYTRhNzJlOWZmZjRmIiwidXNlcl9pZCI6ImRldiIsInVzZXJuYW1lIjoiZGV2In0=\r\n' +
        'User-Agent: axios/1.3.4\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: localhost:8000\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/chats?limit=20&include_hidden=false',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://localhost:8000/chats?limit=20&include_hidden=false',
    [Symbol(kCapture)]: false
  },
  cause: Error: connect ECONNREFUSED ::1:8000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 8000
  },
  page: '/api/chat'
}
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 215 ms (5503 modules)
error - src/lib/oasst_inference_client.ts (49:52) @ status
error - TypeError: Cannot read properties of undefined (reading 'status')
    at OasstInferenceClient.create_chat (webpack-internal:///(api)/./src/lib/oasst_inference_client.ts:44:94)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (webpack-internal:///(api)/./src/pages/api/chat/index.ts:41:16)
    at async Object.apiResolver (/Users/khederyusuf/Desktop/Open-Assistant/website/node_modules/next/dist/server/api-utils/node.js:363:9)
    at async DevServer.runApi (/Users/khederyusuf/Desktop/Open-Assistant/website/node_modules/next/dist/server/next-server.js:474:9)
    at async Object.fn (/Users/khederyusuf/Desktop/Open-Assistant/website/node_modules/next/dist/server/next-server.js:736:37)
    at async Router.execute (/Users/khederyusuf/Desktop/Open-Assistant/website/node_modules/next/dist/server/router.js:252:36)
    at async DevServer.run (/Users/khederyusuf/Desktop/Open-Assistant/website/node_modules/next/dist/server/base-server.js:383:29)
    at async DevServer.run (/Users/khederyusuf/Desktop/Open-Assistant/website/node_modules/next/dist/server/dev/next-dev-server.js:734:20)
    at async DevServer.handleRequest (/Users/khederyusuf/Desktop/Open-Assistant/website/node_modules/next/dist/server/base-server.js:321:20) {
  page: '/api/chat'
}
  47 |       return await create();
  48 |     } catch (err) {
> 49 |       if (err instanceof AxiosError && err.response.status === 404) {
     |                                                    ^
  50 |         // if we get 404, the user does not yet exist in the inference database, which is why we try to create
  51 |         // user once (it won't do anything if the user already exists) and then retry the chat creation again.
  52 |         await this.inference_login();
error - AxiosError: connect ECONNREFUSED ::1:8000
    at AxiosError.from (file:///Users/khederyusuf/Desktop/Open-Assistant/website/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///Users/khederyusuf/Desktop/Open-Assistant/website/node_modules/axios/lib/adapters/http.js:577:25)
    at RedirectableRequest.emit (node:events:513:28)
    at eventHandlers.<computed> (/Users/khederyusuf/Desktop/Open-Assistant/website/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  port: 8000,
  address: '::1',
  syscall: 'connect',
  code: 'ECONNREFUSED',
  errno: -61,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      TrustedClient: 'eyJhcGlfa2V5IjoiNjk2OSIsImNsaWVudCI6IndlYnNpdGUiLCJwcm92aWRlcl9hY2NvdW50X2lkIjoiZjA2ZDJiZmItNWNkZC00NjliLTg4ZWEtYTRhNzJlOWZmZjRmIiwidXNlcl9pZCI6ImRldiIsInVzZXJuYW1lIjoiZGV2In0=',
      'User-Agent': 'axios/1.3.4',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    url: 'http://localhost:8000/chats?limit=20&include_hidden=false',
    method: 'get',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/chats?limit=20&include_hidden=false',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'localhost',
      port: '8000',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/chats',
      search: '?limit=20&include_hidden=false'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /chats?limit=20&include_hidden=false HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'TrustedClient: eyJhcGlfa2V5IjoiNjk2OSIsImNsaWVudCI6IndlYnNpdGUiLCJwcm92aWRlcl9hY2NvdW50X2lkIjoiZjA2ZDJiZmItNWNkZC00NjliLTg4ZWEtYTRhNzJlOWZmZjRmIiwidXNlcl9pZCI6ImRldiIsInVzZXJuYW1lIjoiZGV2In0=\r\n' +
        'User-Agent: axios/1.3.4\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: localhost:8000\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/chats?limit=20&include_hidden=false',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://localhost:8000/chats?limit=20&include_hidden=false',
    [Symbol(kCapture)]: false
  },
  cause: Error: connect ECONNREFUSED ::1:8000
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 8000
  },
  page: '/api/chat'
}
`

and in the readME file it says:
If you want to work on the chat api, you need to run the inference profile as well. Your new command would look
      like: `docker compose --profile frontend-dev --profile inference up --build --attach-dependencies`

so if i try to run: `docker compose --profile frontend-dev --profile inference up --build --attach-dependencies` on the main brench am getting this error:  `CANCELED resolve image config for docker.io/docker/dockerfile:1                            0.7s
failed to solve: ghcr.io/yk/text-generation-inference:latest: no match for platform in manifest sha256:27060abab69e4c749a9bb23b22955123f37be456ccfe76c4bb76f834949a0a97: not found`

**Comment by olliestanley** [comment]
The first error is probably due to not running the inference profile.

Re the second error I guess you're on an M1 Mac? You will need to edit the `docker-compose.yaml` file to specify a platform to build for, see the note in [this section](https://github.com/LAION-AI/Open-Assistant#running-the-development-setup-locally-without-chat) of the readme.

**Comment by samy-rashed03** [comment]
> The first error is probably due to not running the inference profile.
> 
> Re the second error I guess you're on an M1 Mac? You will need to edit the `docker-compose.yaml` file to specify a platform to build for, see the note in [this section](https://github.com/LAION-AI/Open-Assistant#running-the-development-setup-locally-without-chat) of the readme.

Hey. Regarding the second error, I'm trying to build the services of OpenAssistant by running "docker compose --profile inference build" in the inference directory, and I'm still getting the same error: 
```
CANCELLED resolve image config for docker.io/docker/dockerfile:1          
0.7s failed to solve: ghcr.io/yk/text-generation-inference:latest: no match for platform in manifest sha256:27060abab69e4c749a9bb23b22955123f37be456ccfe76c4bb76f834949a0a97: not found
``` 
For reference, I have my platform as ```"$${DB_PLATFORM:linux/x86_64}"``` in my docker-compose.yaml issue, do you have any other ideas on how I can solve this issue? I'm on an M1 Mac.
