### ISSUE TITLE
Chat page: Scroll to end on submit

### ISSUE THREAD

**Issue by mendelsphotography** [LAION-AI/Open-Assistant#3105]
When you make multiple results and look at the first one anything after you did not show till you go to the latest one.

**Comment by andreaskoepf** [comment]
It would make sense to automatically scroll to the end of the chat history whenever the user submits a new prompt.

**Comment by notmd** [comment]
This is expected behavior. Always scroll to the bottom mean you can't scroll up to read anything older even if you want to.
