### ISSUE TITLE
Fix table in detoxify eval readme

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#311]
In https://github.com/LAION-AI/Open-Assistant/blob/main/notebooks/detoxify-evaluation/README.md#inference-and-training-times-and-memory-usages a table is not rendered but shown as text " | Model name | Training memory| Training speed | Inference Memory| Inference Speed| | :---: | :---: | :---: |:---: | :-" ...

**Comment by Jac-Zac** [comment]
I'll fix it

**Comment by Jac-Zac** [comment]
https://github.com/LAION-AI/Open-Assistant/pull/316
