### ISSUE TITLE
Remove `@next/font`

### ISSUE THREAD

**Issue by notmd** [LAION-AI/Open-Assistant#3111]
NextJS warn this
> Your project has `@next/font` installed as a dependency, please use the built-in `next/font` instead. The `@next/font` package will be removed in Next.js 14. You can migrate by running `npx @next/codemod@latest built-in-next-font .`. Read more: https://nextjs.org/docs/messages/built-in-next-font

**Comment by dewasahu2003** [comment]
@notmd  Hi 👋
could i take this issue
