### ISSUE TITLE
Add Tatoeba QnA dataset

### ISSUE THREAD

**Issue by 0x22almostEvil** [LAION-AI/Open-Assistant#3115]
Multilingual Tatoeba Q&A Translation Dataset
============================================

120K entries

This dataset contains a list of instructions to translate or paraphrase in multiple languages. It is available in Parquet format and includes the following columns:

* INSTRUCTION: The instruction of text to be translated or paraphrased.
* RESPONSE: The corresponding response or answer in target language.
* SOURCE (tatoeba): The original source text from the Tatoeba database.
* METADATA (json): Additional information about each entry, including the target language, UUID, and pair of languages (source and target): `"{"language": "lang", "length": "length of original text","uuid": "uuid (original text + translated text)", "langs-pair": "from_lang-to_lang"}"`

The data in this dataset was collected through crowdsourcing efforts and includes translations of various types of content, such as sentences, phrases, idioms, and proverbs.

You can find it here: https://huggingface.co/datasets/0x22almostEvil/tatoeba-mt-qna-oa
Original dataset is available here: https://huggingface.co/datasets/Helsinki-NLP/tatoeba_mt

**Comment by dewasahu2003** [comment]
@0x22almostEvil  Hi 👋
Could i take this issue

**Comment by 0x22almostEvil** [comment]
> @0x22almostEvil Hi 👋 Could i take this issue

I've already made it (ckeck PR above) 😅
Created an issue due to "dataset pull-request" guidelines in RAEDME

**Comment by 0x22almostEvil** [comment]
![Screenshot_20230510-212141_Bromite](https://github.com/LAION-AI/Open-Assistant/assets/122345469/698715b0-468d-4b81-aea7-bbf37af4173f)

**Comment by dewasahu2003** [comment]
okay
