### ISSUE TITLE
Download `2023-03-27_oasst_research_ready_synth.jsonl.gz`

### ISSUE THREAD

**Issue by malteos** [LAION-AI/Open-Assistant#3116]
Hi all,

thanks for this awesome project. I'm currently reproducing the model training but struggling with the data part. According to the [config.yaml](https://github.com/LAION-AI/Open-Assistant/blob/main/model/model_training/configs/config.yaml) the main data is stored in `2023-03-27_oasst_research_ready_synth.jsonl.gz`. 

Where can I download this file or how can I reproduce this file with the HF dataset?

Best,
Malte

**Comment by andreaskoepf** [comment]
You find [2023-04-12_oasst_ready.messages.jsonl.gz](https://huggingface.co/datasets/OpenAssistant/oasst1/blob/main/2023-04-12_oasst_ready.messages.jsonl.gz) as part of the [OASST1 dataset files](https://huggingface.co/datasets/OpenAssistant/oasst1/tree/main). We do not provide older versions of the dataset for download but you could use the timestamps in the messages to reconstruct the subset of messages that was available on March 27.

**Comment by malteos** [comment]
Ah OK. I assumed that "synth" would include something else than just the messages. Thanks for the clarification.
