### ISSUE TITLE
RL or SFT model type

### ISSUE THREAD

**Issue by randyjunior2008** [LAION-AI/Open-Assistant#3118]
What's the model type of "oasst-sft-4-pythia-12b-epoch-3.5" provided from  Hugging Face? SFT or RL model

Furthurmore, Is there any trained RL model avaliable for public downloading? Thanks.

**Comment by olliestanley** [comment]
The clue is in the name, "oasst-**sft**-4-pythia-12b-epoch-3.5" :D

RLHF versions of Pythia 12B model are in progress, not released yet
