### ISSUE TITLE
Show a message to ask the user to report after a thumbs down

### ISSUE THREAD

**Issue by notmd** [LAION-AI/Open-Assistant#3132]
like in #3130 but for the `MessageTableEntry` component. Have a report button inside, and show the report pop-up on click

**Comment by KaranpreetRaja** [comment]
Could I please be assigned to this issue?

**Comment by JaynouOliver** [comment]
Let me try, if I can do it. Will give you an update after I finish it

**Comment by andreaskoepf** [comment]
I close this issue because I don't think we need to specifically encourage users to red-flag messages. Red-flagging should be an exception to call a moderator because a message is really unacceptable...
