### ISSUE TITLE
I feel like OpenAI trained on the Open Assistant data 🤣

### ISSUE THREAD

**Issue by Logophoman** [LAION-AI/Open-Assistant#3134]
I have the funny feeling that Open AI uses the OASST Dataset now, since I am observing way more Markdown-Like elements and Oasst-Like behavior in the recent answers  - also there's some prompts to niche topics that give quite the same results as in the dataset. Did you guys note any changes in Chat GPT?

It feels to me as if they are using the Dataset (which is ok but kinda really hilarious, since it shows how far open solutions have come 🥳 )

Looks sooo much like Open Assistant 😅 

![image](https://github.com/LAION-AI/Open-Assistant/assets/28789967/00732903-b35d-4c4b-9cb6-ada5c2115ae3)

**Comment by SummerSigh** [comment]
it might then know what the open assistant project is 😂. Try asking it

**Comment by Logophoman** [comment]
Nah I tried it it dosn't know it - however you can simply do that by writing a RegX to replace all Occurances of "Open Assistant" with "ChatGPT" 😅 But interestingly it has access to some events that occured after 2021 - it just pretends it dosn't 😅

**Comment by 0x22almostEvil** [comment]
Can you try some with mentions of LAION or recent events in 2022 (war; Elon Musk became Twitter CEO), Turboscrub69 token is in our data too for some reason haha
