### ISSUE TITLE
Create REST API client class to call the detoxify model

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#314]
This is follow up on https://github.com/LAION-AI/Open-Assistant/issues/38 and https://github.com/LAION-AI/Open-Assistant/tree/main/notebooks/detoxify-evaluation.

1. Use the [hugginface hosted inference API](https://huggingface.co/docs/huggingface_hub/how-to-inference) to host and expose the `multilingual` variant of the ['unitaryai/detoxify'](https://huggingface.co/unitary) models and make it available for calls from us.
2. Clarify with the ml-team / admins on discord how we get hf-credits for inference-calls .
3. Write an asynchronous REST client class that will be used by the backend to make calls against the detoxify endpoint at HF.

**Comment by Nil-Andreu** [comment]
Hey!
Would like to contribute to this project! @SzymonOzog do you need any help on that?

**Comment by SzymonOzog** [comment]
@Nil-Andreu Hi, help is always appreciated! If I create a function for accessing huggingface API from 1. will you be able to write the rest client that handles the requests from 3?

**Comment by Nil-Andreu** [comment]
@SzymonOzog Yes can try that! Will be my first contribution, so I will need to make the setup, ... I have already looked at the codebase, and I hope that when I get in touch with the code I could further contribute more in other issues.

**Comment by SzymonOzog** [comment]
@Nil-Andreu Amazing! I've made a pr with the function for getting detoxify classification (https://github.com/LAION-AI/Open-Assistant/pull/362) You can start working on it as soon as it gets accepted

**Comment by SzymonOzog** [comment]
reagarding 2.:
They have a limited free access that runs on the cpu and is rate limited:
```
The free Inference API may be rate limited for heavy use cases. We try to balance the loads evenly between all our available resources, and favoring steady flows of requests. If your account suddenly sends 10k requests then you’re likely to receive 503 errors saying models are loading. In order to prevent that, you should instead try to start running queries smoothly from 0 to 10k over the course of a few minutes.
```
Also there is an option to pay for better accelerators
![image](https://user-images.githubusercontent.com/58388001/210515080-7c3eda46-a789-4850-ae54-594c13eba1ce.png)

**Comment by Nil-Andreu** [comment]
Perfect thanks!

**Comment by Nil-Andreu** [comment]
With 3., by the "rest client class" you mean a fastapi endpoint?

**Comment by Nil-Andreu** [comment]
Okay! I have started the following PR: [here](https://github.com/LAION-AI/Open-Assistant/pull/404), for the creation of the api with fastapi.
