### ISSUE TITLE
`Author` label is positioned very poorly

### ISSUE THREAD

**Issue by DoctorKrolic** [LAION-AI/Open-Assistant#3140]
To be honest, I didn't even notice it for a very long time. I have pretty large screen and conversation tree for me looks like this:
![firefox_wJIMUPTyG7](https://github.com/LAION-AI/Open-Assistant/assets/70431552/6a80dde0-76aa-4e00-88e2-303f021b2880)
As you can see, the distance between the message and `Author` label is kinda ridiculous.
I think it is better to put this label to this place instead:
![firefox_db5fDzAAnt](https://github.com/LAION-AI/Open-Assistant/assets/70431552/acf9dd56-001f-4fbd-938f-a0e51a50d937)

**Comment by notmd** [comment]
dup #2719
