### ISSUE TITLE
Is it "by design", that website only has 3 models to chat with

### ISSUE THREAD

**Issue by DoctorKrolic** [LAION-AI/Open-Assistant#3141]
Website currently shows only these 3 model for me:
![lNod6Xmu53](https://github.com/LAION-AI/Open-Assistant/assets/70431552/feb8f535-93aa-460f-8686-d7aaede54996)
Is it supposed to be so? I heard, that OA also possesses other models, that are not based on llama and are fully open source. Aren't they available on purpose or not?

**Comment by olliestanley** [comment]
Those non-LLaMA models, based on Pythia, are smaller and can be downloaded from OA HuggingFace page. We only offer the best models on the site as the data from the site will be used for training later
