### ISSUE TITLE
Create script to fill database with mock-data

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#315]
Write a python script that fills the backend postgresql DB with random message-trees and users. Insert 500k messages (each on averge 500 characters long) of 1k randomly selected mock-users (all numbers parameters). See the [seed data generation script](https://github.com/LAION-AI/Open-Assistant/blob/a926703eec5ba58468b3d06aa9accfce1920a215/backend/main.py#L91) for inspiration. Report the query time of the current leaderboard stats query on your system.

Background:
We discussed some possible strategies for dealing with DB queries. e.g. querying user stats live/online vs. incrementally updating peristent views (e.g. for user stats). We would like to test the performance of some naive count-queries, e.g. as in the [ get_user_leaderboard()](https://github.com/LAION-AI/Open-Assistant/blob/a926703eec5ba58468b3d06aa9accfce1920a215/backend/oasst_backend/prompt_repository.py#L715-L721) of the PromptRepository class.

- This test code could be extended in the future to include message reactions, deleted messages and more.

**Comment by Nil-Andreu** [comment]
Hello!
I suppose that the messages have to have words that make sense of could be only random characters?
All those have to be created on the fly each time, or maybe created once and store in a json. So when we fill the database, it is always the same messages?

**Comment by yk** [comment]
> Where do we have to extract the messages of the sample?
> All those have to be created on the fly each time, or maybe created once and store in a json. So when we fill the database, it is always the same messages?

I think for creating this many messages, it's ok if we just either use the same few messages over and over again, or we use something like `faker` to create fake data on the fly. makes no sense to store thousands and thousands of messages in json just to do load tests.

**Comment by Nil-Andreu** [comment]
Okay cool would like to contribute! Will take a look into that @onegunsamurai.

**Comment by Nil-Andreu** [comment]
I am working on this [PR](https://github.com/LAION-AI/Open-Assistant/pull/417), which wants to:
- Store api clients
- Store users & messages with PromptRepository

**Comment by andreaskoepf** [comment]
related https://github.com/LAION-AI/Open-Assistant/issues/322

**Comment by nolofi** [comment]
this is what i got from Chat GPT: 

import psycopg2
import random
import string
import time

def random_string(string_length=500):
    """Generate a random string of fixed length."""
    letters = string.ascii_letters + string.digits
    return ''.join(random.choice(letters) for i in range(string_length))

def insert_messages(conn, cursor):
    """Insert 500k messages into the database."""
    user_ids = list(range(1, 1001)) # 1k mock users
    message_count = 500000

    for i in range(message_count):
        user_id = random.choice(user_ids)
        message = random_string()
        cursor.execute("INSERT INTO messages (user_id, message) VALUES (%s, %s)", (user_id, message))

    conn.commit()

def report_query_time(conn, cursor):
    """Report the query time of the current leaderboard stats query."""
    start_time = time.time()
    cursor.execute("SELECT user_id, COUNT(*) FROM messages GROUP BY user_id ORDER BY COUNT(*) DESC")
    query_time = time.time() - start_time
    print("Query time: {:.2f} seconds".format(query_time))

if __name__ == '__main__':
    # Connect to the database
    conn = psycopg2.connect(
        host="localhost",
        database="postgres",
        user="postgres",
        password="password"
    )
    cursor = conn.cursor()

    # Insert messages into the database
    insert_messages(conn, cursor)

    # Report the query time of the leaderboard stats query
    report_query_time(conn, cursor)

    # Close the database connection
    cursor.close()
    conn.close()

**Comment by nolofi** [comment]
This is what i got from Chat GPT: 

import psycopg2
import random
import string
import time

def random_string(string_length=500):
    """Generate a random string of fixed length."""
    letters = string.ascii_letters + string.digits
    return ''.join(random.choice(letters) for i in range(string_length))

def insert_messages(conn, cursor):
    """Insert 500k messages into the database."""
    user_ids = list(range(1, 1001)) # 1k mock users
    message_count = 500000

    for i in range(message_count):
        user_id = random.choice(user_ids)
        message = random_string()
        cursor.execute("INSERT INTO messages (user_id, message) VALUES (%s, %s)", (user_id, message))

    conn.commit()

def report_query_time(conn, cursor):
    """Report the query time of the current leaderboard stats query."""
    start_time = time.time()
    cursor.execute("SELECT user_id, COUNT(*) FROM messages GROUP BY user_id ORDER BY COUNT(*) DESC")
    query_time = time.time() - start_time
    print("Query time: {:.2f} seconds".format(query_time))

if __name__ == '__main__':
    # Connect to the database
    conn = psycopg2.connect(
        host="localhost",
        database="postgres",
        user="postgres",
        password="password"
    )
    cursor = conn.cursor()

    # Insert messages into the database
    insert_messages(conn, cursor)

    # Report the query time of the leaderboard stats query
    report_query_time(conn, cursor)

    # Close the database connection
    cursor.close()
    conn.close()

**Comment by andreaskoepf** [comment]
I close this because we are live and we already have a production database with >100k messages and >20k users now.
