### ISSUE TITLE
Creating Debugging Instructions by bugging working code

### ISSUE THREAD

**Issue by furlat** [LAION-AI/Open-Assistant#317]
Going more specific for https://github.com/LAION-AI/Open-Assistant/issues/279, the general idea is writing a small package that can bug working python methods to generate an instruction dataset for debugging, with these types of errors:
Syntax errors: These are mistakes in the structure of the code that prevent it from being parsed by the interpreter. Examples include missing parentheses, incorrect indentation, and mismatched quotation marks.

Logic errors: These are mistakes in the code that do not prevent it from being parsed, but cause it to behave in unintended ways. For example, using the wrong comparison operator (e.g., == instead of <) or forgetting to update a variable.

Runtime errors: These are errors that occur when the code is executing, such as division by zero or trying to access an index that is out of bounds of a list.

Type errors: These are errors that occur when a value has the wrong type for a certain operation. For example, trying to concatenate a string and an integer will cause a type error.

Name errors: These are errors that occur when a name (e.g., a variable or function) is not defined in the current scope.

Import errors: These are errors that occur when a module cannot be imported due to a typo in the module name or a missing module.

Indentation errors: These are errors that occur when the indentation of the code is not consistent, which can cause issues with the structure of the code.

**Comment by yk** [comment]
it's a denoising autoencoder for code :)

**Comment by furlat** [comment]
Syntax and Logic errors working here https://github.com/furlat/OpenBugger

**Comment by andreaskoepf** [comment]
Closing old data issue that has not been completed by now.
