### ISSUE TITLE
What technology is used to translate the Open Assistant website in other languages?

### ISSUE THREAD

**Issue by sing78** [LAION-AI/Open-Assistant#3177]
Hi,
I would like to ask what technology is used to translate the Open Assistant website into other languages apart from English.
Of if the translatiion is manual.
Thanks

**Comment by GuilleHoardings** [comment]
Right now, it's done manually. [This guide](https://github.com/LAION-AI/Open-Assistant/blob/main/website/docs/add_edit_translations.md) describes how to do it.

Int [this issue](https://github.com/LAION-AI/Open-Assistant/issues/3077) there's a discussion about introducing some tool.
