### ISSUE TITLE
oasst-sft-6-llama-30b-xor setup problem on Databricks

### ISSUE THREAD

**Issue by devVipin01** [LAION-AI/Open-Assistant#3178]
I followed all the steps, but now I am facing a problem in Step 5, which is the HF LLaMA conversion script. I have the original LLaMA 30B weights on this location "/dbfs/filepath/LLaMaweights" and All checkpoints are matching as mentioned. [here](https://huggingface.co/OpenAssistant/oasst-sft-6-llama-30b-xor) I am using databricks.

`python src/transformers/models/llama/convert_llama_weights_to_hf.py --input_dir /dbfs/filepath/LLaMaweights/ --output_dir /dbfs/filepath/LLaMaweights/weights_hf --model_size 30B`

However, after running the above line successfully as mentioned in Step 5, nothing is saved in my output directory except an empty tmp folder. What should I do to ensure a successful conversion? Help to move on to step 6 & 7..

**Comment by gavincapriola** [comment]
We are getting this error ```input_path_llama_base: No such file or directory```, we are in the transformers repo root directory and we have installed the exact dependency versions.

How did you successfully run your code? please help?

**Comment by devVipin01** [comment]
> We are getting this error `input_path_llama_base: No such file or directory`, we are in the transformers repo root directory and we have installed the exact dependency versions.
> 
> How did you successfully run your code? please help?

**input_path_llama_base** Please provide the directory path where you have the original llama weights.

**Comment by olliestanley** [comment]
This sounds like an issue with the Transformers conversion script, if your original LLaMA weights are correct but the script is not producing the converted version.

**Comment by andreaskoepf** [comment]
Closing this issue since it is not related to OA but to the LLaMA conversion code in huggingface transformers.

**Comment by andreaskoepf** [comment]
(to debug please check the conversion script: https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py )
