### ISSUE TITLE
Escape char

### ISSUE THREAD

**Issue by giannicic** [LAION-AI/Open-Assistant#3188]
While using the assistant I've noticed an escape bug or something similar

I've written this prompt in the chat message: 
`Which is the batch file equivalent of bash '\'`
but the question got submitted as
`Which is the batch file equivalent of bash ''`

![image](https://github.com/LAION-AI/Open-Assistant/assets/10560238/2bef2fdc-78b4-40aa-a3bd-aa67165c8d79)

Thanks

**Comment by olliestanley** [comment]
I am pretty sure this is just how the markdown is rendered (your \ wasn't lost, it's just not rendered)

**Comment by giannicic** [comment]
You're right, just seen that also GitHub does the same thing.
Do you think is it something worth fixing?
The user writes to a textarea so it should not be aware that its message is passed through a markdown rendering.
In case, I could try prepare a PR

**Comment by notmd** [comment]
I think we don't need to fix this since this is expected behavior

**Comment by olliestanley** [comment]
Yeah, this is unfortunate but not really a bug. Maybe we need the model to be "aware" that its output will always be parsed as markdown...
