### ISSUE TITLE
Are you serious?

### ISSUE THREAD

**Issue by CoinCheung** [LAION-AI/Open-Assistant#3192]
I see one sample by accident: 
![image](https://github.com/LAION-AI/Open-Assistant/assets/22693362/afa8d98e-faf4-4ba3-a157-1562c5b1a98a)

**Comment by olliestanley** [comment]
We will need more information on what is being reported here, feel free to reopen if you can provide any

**Comment by s0mt0chukwu** [comment]
> I see one sample by accident: 
> ![image](https://github.com/LAION-AI/Open-Assistant/assets/22693362/afa8d98e-faf4-4ba3-a157-1562c5b1a98a)
> 


![same_stupidity.jpg](https://user-images.githubusercontent.com/81354428/239424169-a8cdd5aa-4f68-491e-ad9b-cb445f14c53a.jpg)
