### ISSUE TITLE
Right-To-left Languages Problem

### ISSUE THREAD

**Issue by sDos280** [LAION-AI/Open-Assistant#3199]
Hi, I came to a problem while writing an assistant response task. it seems that when I use right-to-left language in the writing section of the "assistant response task" the text (the centering) goes from left to right instead from right to left, but when looking in the preview section it seems that the centering fix itself and go from right to left.

for example:
![image](https://github.com/LAION-AI/Open-Assistant/assets/107134807/1f213dc0-0027-4c4b-8664-458c7e126a4b)
what it should look like in the writing section:
![image](https://github.com/LAION-AI/Open-Assistant/assets/107134807/b3886efa-d0b9-4fc4-9504-2825dae90020)

p.s. note that the example is written in Hebrew, but it also accrues in other right-to-left languages (like Arabic). for convenience, I would really appreciate fixing this problem, since its really hard to right in right-to-left languages that way (in the current form).

**Comment by andreaskoepf** [comment]
@notmd Could you please check if the markdown editor component supports right-to-left languages? If not, could we maybe fall back to a simple multi line input box for right to left scripts?

**Comment by hmltn2** [comment]
I can try to work on this. I’m new here.

**Comment by notmd** [comment]
@hmltn2 thanks, it's yours
