### ISSUE TITLE
Implement `rank_initial_prompts` for web

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#32]
The `rank_initial_prompts` task type needs to display these fields:
*  `prompts`: An array of prompts

It takes the following interaction type:
*  `type`: `post_ranking`
*  `ranking`: An array of ints representing the preferred ordering of the `prompts`, indexed by zero.  example: `[2,1,0,3]` for a series of 4 prompts.

**Comment by AbdBarho** [comment]
@fozziethebeat ascending or descending? index `0` is the best or worst?
