### ISSUE TITLE
Supported languages and their proportions

### ISSUE THREAD

**Issue by SkanderHellal** [LAION-AI/Open-Assistant#3221]
Hi,

I am asking about supported languages used for the training process. Are there some statistics about languages proportion in the dataset mainly for french ?

Thank you,

**Comment by andreaskoepf** [comment]
It highly depends on the languages that were present in the large-scale pre-training of the model. The OpenAssistant SFT/RL training runs only change the style of the outputs but they cannot really add new language capabilities. Please refer for example to the [LLaMA paper](https://arxiv.org/abs/2302.13971) for further details about the composition of the training dataset.

**Comment by olliestanley** [comment]
In terms of OA dataset you can also see statistics at https://open-assistant.io/stats
