### ISSUE TITLE
error wandb in training the rl

### ISSUE THREAD

**Issue by aijianiula0601** [LAION-AI/Open-Assistant#3231]
I encountered the following error while training the rl:
`
wandb: Waiting for W&B process to finish... (failed 15). Press Control-C to abort syncing.
wandb: 🚀 View run trainer_rl/stablelm-7b-sft-v7-epoch-3/8gpus:unknown at: https://wandb.ai/open-assistant-hjh/rlhf/runs/r8irdyzv
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230526_103833-r8irdyzv/logs
[10:40:13] ERROR    failed (exitcode: -9) local_rank: 3 (pid: 41467) of binary: /root/miniconda3/envs/open-assistant/bin/python                                                                   api.py:672
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /root/miniconda3/envs/open-assistant/bin/accelerate:8 in <module>                                │
│                                                                                                  │
│   5 from accelerate.commands.accelerate_cli import main                                          │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(main())                                                                         │
│   9                                                                                              │
│                                                                                                  │
│ /root/miniconda3/envs/open-assistant/lib/python3.10/site-packages/accelerate/commands/accelerate │
│ _cli.py:45 in main                                                                               │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ /root/miniconda3/envs/open-assistant/lib/python3.10/site-packages/accelerate/commands/launch.py: │
│ 903 in launch_command                                                                            │
│                                                                                                  │
│   900 │   │   if mp_from_config_flag:                                                            │
│   901 │   │   │   args.deepspeed_fields_from_accelerate_config.append("mixed_precision")         │
│   902 │   │   args.deepspeed_fields_from_accelerate_config = ",".join(args.deepspeed_fields_fr   │
│ ❱ 903 │   │   deepspeed_launcher(args)                                                           │
│   904 │   elif args.use_fsdp and not args.cpu:                                                   │
│   905 │   │   multi_gpu_launcher(args)                                                           │
│   906 │   elif args.use_megatron_lm and not args.cpu:                                            │
│                                                                                                  │
│ /root/miniconda3/envs/open-assistant/lib/python3.10/site-packages/accelerate/commands/launch.py: │
│ 648 in deepspeed_launcher                                                                        │
│                                                                                                  │
│   645 │   │   )                                                                                  │
│   646 │   │   with patch_environment(**current_env):                                             │
│   647 │   │   │   try:                                                                           │
│ ❱ 648 │   │   │   │   distrib_run.run(args)                                                      │
│   649 │   │   │   except Exception:                                                              │
│   650 │   │   │   │   if is_rich_available() and debug:                                          │
│   651 │   │   │   │   │   console = get_console()                                                │
│                                                                                                  │
│ /root/miniconda3/envs/open-assistant/lib/python3.10/site-packages/torch/distributed/run.py:785   │
│ in run                                                                                           │
│                                                                                                  │
│   782 │   │   )                                                                                  │
│   783 │                                                                                          │
│   784 │   config, cmd, cmd_args = config_from_args(args)                                         │
│ ❱ 785 │   elastic_launch(                                                                        │
│   786 │   │   config=config,                                                                     │
│   787 │   │   entrypoint=cmd,                                                                    │
│   788 │   )(*cmd_args)                                                                           │
│                                                                                                  │
│ /root/miniconda3/envs/open-assistant/lib/python3.10/site-packages/torch/distributed/launcher/api │
│ .py:134 in __call__                                                                              │
│                                                                                                  │
│   131 │   │   self._entrypoint = entrypoint                                                      │
│   132 │                                                                                          │
│   133 │   def __call__(self, *args):                                                             │
│ ❱ 134 │   │   return launch_agent(self._config, self._entrypoint, list(args))                    │
│   135                                                                                            │
│   136                                                                                            │
│   137 def _get_entrypoint_name(                                                                  │
│                                                                                                  │
│ /root/miniconda3/envs/open-assistant/lib/python3.10/site-packages/torch/distributed/launcher/api │
│ .py:250 in launch_agent                                                                          │
│                                                                                                  │
│   247 │   │   │   # if the error files for the failed children exist                             │
│   248 │   │   │   # @record will copy the first error (root cause)                               │
│   249 │   │   │   # to the error file of the launcher process.                                   │
│ ❱ 250 │   │   │   raise ChildFailedError(                                                        │
│   251 │   │   │   │   name=entrypoint_name,                                                      │
│   252 │   │   │   │   failures=result.failures,                                                  │
│   253 │   │   │   )                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ChildFailedError:
======================================================
model/model_training/trainer_rl.py FAILED
------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-26_10:39:44
  host      : bigo
  rank      : 3 (local_rank: 3)
  exitcode  : -9 (pid: 41467)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 41467
`

**Comment by olliestanley** [comment]
Seems like this is because you haven't specified a different WandB account (or disabled WandB) so it is trying to log your run in the Open Assistant account, which you don't have access to
