### ISSUE TITLE
Login failure by SSO

### ISSUE THREAD

**Issue by flozi00** [LAION-AI/Open-Assistant#3232]
I registered for open assistant data platform when only email was available.
No I changed my device and email is not even in spam, using Google SSO I can't login because it's different auth type.
Because I just reached the top 50 it would be sad if I need to change my account and start from scratch again.

the email is flozi00@gmail.com

**Comment by flozi00** [comment]
`Error: To confirm your identity, sign in with the same account you used originally.`

**Comment by AbdBarho** [comment]
This a problem we have open for a while. I will try to give it a look.

**Comment by notmd** [comment]
Hey, are you still able to log in via email?

**Comment by flozi00** [comment]
I just don't get the email with the confirmation link.
It just returns the error when trying Google as auth method, otherwise it's just quiet

**Comment by notmd** [comment]
The error when login with Google is expected, that is because of security reasons. But you don't get the email link is really weird. Have you ensured that you check the spam folder? Or maybe typo in your email?

**Comment by flozi00** [comment]
Yeah, I checked the spam folder and for typos

**Comment by flozi00** [comment]
I found the bug
When first trying Google auth and then using email nothing happens

When directly using the email it works as expected

**Comment by andreaskoepf** [comment]
I am closing this as it is indirectly tracked by #3246.

**Comment by flozi00** [comment]
Please reopen that issue
I was near top 20 but cant Login anymore, the email is not even in spam.
Cookies from all my browsers expired.

It would be also time for new dataset release 
The models released are trained on exports some days old, the community is waiting for months now
