### ISSUE TITLE
Chat list scrollbar UI regression

### ISSUE THREAD

**Issue by notmd** [LAION-AI/Open-Assistant#3252]
On dev
![image](https://github.com/LAION-AI/Open-Assistant/assets/33456881/cbc5b11f-1463-476f-8cc2-a3c6911219e1)
While on prod
![image](https://github.com/LAION-AI/Open-Assistant/assets/33456881/055bb24f-1c27-45fe-83f6-3789e8ae10da)
Maybe related https://github.com/LAION-AI/Open-Assistant/pull/3201

**Comment by KarthikRaju391** [comment]
Hi @notmd, I would like to help fix this bug but I didn't quite get what should be done. Can you please explain?

**Comment by notmd** [comment]
Hi @KarthikRaju391 I mean the scrollbar UI is different, it should look like the second pic. You can check the UI on dev http://web.dev.open-assistant.io and compare with https://open-assistant.io. Make sure you are on Window.

**Comment by KarthikRaju391** [comment]
@notmd, I'll be working on it. Thanks for letting me know.

**Comment by KarthikRaju391** [comment]
https://github.com/LAION-AI/Open-Assistant/assets/67912316/912c78e5-099a-4628-a291-cf46bed01609

I think both the UIs are behaving the same @notmd

**Comment by KarthikRaju391** [comment]
https://github.com/LAION-AI/Open-Assistant/assets/67912316/87947515-b3ae-4388-9997-f60faba207af

And the scrollbar is behaving differently in Brave browser...

**Comment by notmd** [comment]
> I think both the UIs are behaving the same @notmd

Hi, new version was deployed to prod yesterday, so both dev and prod have same UI although the scrollbar should like the second pic like I said. It should also look the same as the chat config's scrollbar
![image](https://github.com/LAION-AI/Open-Assistant/assets/33456881/93374edf-7477-403a-86f6-8fa543b7388e)
