### ISSUE TITLE
Planning OA v1.0

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#3268]
This is a call for all OA collaborators to participate in planning the work of the next 8-12 weeks with the goal to release Open-Assistant v1.0. 

Mission: Deliver a great open-source assistant model together with stand-alone installable inference infrastructure.
Release date (tentative): Aug 2023

## Organization

- [x] schedule call to collect collaborator feedback and ask for developer participation/commitment
- [ ] update vision & roadmap for v 1.0 
- [x] schedule weekly developer meeting

### Model

- fine-tune best available base LLMs (currently LLaMA 65B & Falcon 40B) ([QLoRA](https://arxiv.org/abs/2305.14314))
- implement long context (10k+), candidates: QLoRA+MQA+flash-attn, [BPT](https://arxiv.org/abs/2305.19370), [Landmark Attention](https://arxiv.org/abs/2305.16300)
- add retrieval/tool-use, candidate: [Toolformer](https://arxiv.org/abs/2302.04761)

### Inference system
- prompt preset + prompt database
- sharing of conversations via URL
- support for long-context & tool use
- stand-alone installation (without feedback collection system)
- allow editing of assistant results and message-tree submission as synthetic example for dataset for human labeling and ranking

### Classic human feedback collection
- editing messages for moderators, submit edit-proposals for users
- entering prompt + reply pairs
- collecting relevant links in a separate input field
- improve labeling: review, more guidelines, addition of further labels (e.g. robotic), labels no longer optional

### Experiments
- Analyze whether additional fine-tuning on (synthetic) instruction datasets (Alpaca, Vicuna) is beneficial or harmful: Only OA top-1 threads (Guanaco) vs. synthetic instruction-tuning + OA top-1, potentially with system-prompt for "mode" selection to distinguish between chat and instruction following, e.g. to use instruction mode for plugin processing

## Perspective strategy (brain-storming)
- Sunsetting of classic data collection after OASST2 release and transitioning towards semi-automated inference based data collection
- Extending data collection to new domains, give users more freedom in task selection, e.g. for Code: describing code, refactoring, writing unit tests, etc.

Please add further proposals for high-priority features and try to make a case for why they are important and should become part of v1.0. If you are a developer who wants to support OA: Let us know on what you would like to work (also if it is not yet part of the above list).

**Comment by andrewm4894** [comment]
I don't see much around plugins above (or maybe i'm reading it wrong) - i know we have some but only getting up to speed on them now. But wondering what/how will be part of OA v1.0.

Wondering if a user journey using a set of OA hosted plugins could be something we think about?

**Comment by flozi00** [comment]
When the plugin API Design is final I would work on plugins to be added, especially information retrieval like weather, wikipedia, lyrics and so on

**Comment by 0x22almostEvil** [comment]
I'd add to discussion more data types (so-called `multimodality`) at "Classic human feedback collection" section. We can try to collect data with successful understanding of different data within assistant-like system: audio, images, videos, (with texts obviously) etc.

Even if we can't use it right now, it'll be a great investment into the future, e.g. others in OS community can focus on building models on our data, and then we can use it too.

**Comment by 0x22almostEvil** [comment]
Also, @andreaskoepf, we discussed some kind of collecting system prompts in DM, maybe we can also add this type of tasks: Following System Prompt

**Comment by ontocord** [comment]
I think trying to figure out how to train smaller models that are good enough such as a 1b with retreival so that it can be run on typical PCs would be awesome.

**Comment by andreaskoepf** [comment]
> When the plugin API Design is final I would work on plugins to be added, especially information retrieval like weather, wikipedia, lyrics and so on

It is now possible to create all kinds of plugins for OA. But currently only one plugin can be active at a time and this plugin must be manually selected. Plugins rely on the zero-shot capabilities can therefore can be easily extended. We could test if newer/larger models (Falcon40B or LLaMA65B) are capable of selecting the right 'plugin' when multiple plugins are offered and how large the overhead is for these additional queries. Multiple active plugins probably depend on long-context.

We can also define a fixed set of tools and train a model to use these tools automatically in situations where it is beneficial (i.e. like toolformer). For this approach the main challenge is to create the special dataset. Adding new tools here requires extension of the tooluse-dataset and training a new model.

**Comment by rkchee** [comment]
What a high quality meeting!  Here are some of my thoughts on the qualities that I see
1. high quality models that work out of the box. this is extremely rare and accessible.  the demonstration alone of functioning models is already very unique.  Papers and Huggingface describe models but here the models demonstrate function. Kudos to the expertise and talent needed to get them to work
2. Unique to this project and first in class was the ability to level up different communities to build AI.  The principle of communities that can help other communities. With a few more tweaks, I can see this being a social network of domain specific communities training AI's and being able to merge models of different domains. 
3. API/Pluggin functionalities likely further improves accessibility
4. The community has the potential of accessing very original ideas that may not be present or encouraged in big tech, corporations, or other industries.  The leaders of this community runs a CICD process with the community which brings focus, bring stuff to the world and vets great ideas.

**Comment by balisujohn** [comment]
@andreaskoepf can you elaborate on what you mean by "semi-automated inference based data collection." Would this be a system that uses an existing OA model to create the trees, then creates tasks for humans of doing quality assurance on the generated trees?

**Comment by andreaskoepf** [comment]
> can you elaborate on what you mean by "semi-automated inference based data collection."

The idea is to use the inference system to generate answers which then are reviewed, labeled, corrected and refined by the users. In this AI+human setup it should be possible to process a higher number of assistant replies more easily and to focus on the weaker parts of our models. The idea is similar to the process described by OpenAI in the [Instruct GPT paper](https://arxiv.org/abs/2203.02155) and also borrows ideas from other successful "bootstrapped" approaches like for example Meta's [Segment Anything](https://arxiv.org/abs/2304.02643). Quote from SA paper: "we co-develop our model with model-in-the-loop dataset annotation (..). Our data engine has three stages: assisted-manual, semi-automatic, and fully automatic."
![image](https://github.com/LAION-AI/Open-Assistant/assets/9976399/4574a55b-a24f-4208-8a5e-9a0451d85cf3)

**Comment by olliestanley** [comment]
> > can you elaborate on what you mean by "semi-automated inference based data collection."
> 
> The idea is to use the inference system to generate answers which then are reviewed, labeled, corrected and refined by the users. In this AI+human setup it should be possible to process a higher number of assistant replies more easily and to focus on the weaker parts of our models. The idea is similar to the process described by OpenAI in the [Instruct GPT paper](https://arxiv.org/abs/2203.02155) and also borrows ideas from other successful "bootstrapped" approaches like for example Meta's [Segment Anything](https://arxiv.org/abs/2304.02643). Quote from SA paper: "we co-develop our model with model-in-the-loop dataset annotation (..). Our data engine has three stages: assisted-manual, semi-automatic, and fully automatic." ![image](https://user-images.githubusercontent.com/9976399/243342735-4574a55b-a24f-4208-8a5e-9a0451d85cf3.png)

Relevant to this could be #3029

**Comment by rkchee** [comment]
That resonates with me a lot. Having the algorithm directly interact with
us and learns to produce better results.  We can even gather the outputs
and distribute to specialists that can rank them quickly at a glance of
what works and does not for mass ranking

The faster we get to outputs and the easier the rankings is done is a good
principle


  The more we can provide feedback and reward the better.

**Comment by kaiokendev** [comment]
>longer context
Hello, I saw topic some weeks back, I am wondering if this can help you at all, as it works for me: 
https://kaiokendev.github.io/til#extending-context-to-8k

**Comment by theophilegervet** [comment]
Hi @andreaskoepf @yk, thank you for your work on the OpenAssistant. It's beautiful to see the open source community build so quickly. Would it be possible to participate in the development of OA v1.0? If so, what would be the best way to get started? Could I join the weekly developer meeting mentioned above? 

Thanks a ton!
Theo
https://theophilegervet.github.io/
