### ISSUE TITLE
Are the weights of the RM available?

### ISSUE THREAD

**Issue by zyzhang1130** [LAION-AI/Open-Assistant#3281]
As the title suggests. Would like to use an off-the-shelf reward model for RLHF training.

**Comment by andreaskoepf** [comment]
You find all our public model at https://huggingface.co/OpenAssistant ..

We used these models for our RL runs:
- [oasst-rm-2.1-pythia-1.4b-epoch-2.5](https://huggingface.co/OpenAssistant/oasst-rm-2.1-pythia-1.4b-epoch-2.5)
- [oasst-rm-2-pythia-6.9b-epoch-1](https://huggingface.co/OpenAssistant/oasst-rm-2-pythia-6.9b-epoch-1)

**Comment by zyzhang1130** [comment]
Hi, may I further ask is [oasst-rm-2.1-pythia-1.4b-epoch-2.5](https://huggingface.co/OpenAssistant/oasst-rm-2.1-pythia-1.4b-epoch-2.5) a checkpoint that can be directly put into use for RLHF step or do I need to further training it on [open-assistant-instructions](https://huggingface.co/datasets/iamketan25/open-assistant-instructions)? Furthermore, a related question is, are all the data in [open-assistant-instructions](https://huggingface.co/datasets/iamketan25/open-assistant-instructions) were used in SFT and reward modeling? I am trying to do a fair comparison so it is good to know all these details. Many thanks.
