### ISSUE TITLE
Issue creating my own dataset

### ISSUE THREAD

**Issue by tchaton** [LAION-AI/Open-Assistant#3292]
Hey there,

I just checked Open Assistant. Love the initiative.

I just run `docker compose --profile ci up --build --attach-dependencies` and got the UI to start locally.

<img width="1668" alt="Screenshot 2023-06-04 at 00 26 58" src="https://github.com/LAION-AI/Open-Assistant/assets/12861981/60048111-16f0-40f6-b8cd-26893a52854b">

I would like to collaborate with some friends to create some prompts for your own usage. However, It seems I create a task or anything.

<img width="1663" alt="Screenshot 2023-06-04 at 00 27 51" src="https://github.com/LAION-AI/Open-Assistant/assets/12861981/9ba06bf1-0f5d-4d81-8687-add201cd8f0d">

What are the next steps to get started ?

Best,
T.C

**Comment by olliestanley** [comment]
You will need to configure it for your preferred use - settings are here https://github.com/LAION-AI/Open-Assistant/blob/main/backend/oasst_backend/config.py
