### ISSUE TITLE
Translation feature

### ISSUE THREAD

**Issue by s0mt0chukwu** [LAION-AI/Open-Assistant#3303]
This is a feature suggestion aimed at expanding the amount of data in smaller languages.
> 
> "Translation" & "Translation Verification" tasks:
> 
> Users can specify languages they're fluent in, as well as their mother tongue, in their account settings. Once set, users will see two new tasks in their dashboard:
> 
> a) Translate existing content from a fluent language to their mother tongue.
> b) Verify the accuracy of translated content.

**Comment by olliestanley** [comment]
Duplicate of #2977
