### ISSUE TITLE
Deleting from chat index page redirects to the chat page.

### ISSUE THREAD

**Issue by CertifiedJoon** [LAION-AI/Open-Assistant#3306]
Deleting a chat from /chat page will redirect /chat/{id}

**Comment by AmanSal1** [comment]
can i work on this ?

**Comment by andreaskoepf** [comment]
@AmanSal1 Ollie assigned the task to you three days ago. Please confirm that you started working on it.

**Comment by CertifiedJoon** [comment]
I will work on this myself. Would that be okay?

**Comment by andreaskoepf** [comment]
> I will work on this myself. Would that be okay?

Yes sure, thanks a lot.
