### ISSUE TITLE
OA Developer Meeting (Friday, June 9, 2023 7:00pm UTC)

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#3321]
Time: 7pm UTC, 12pm PDT, 21:00 CEST
Location: [OA discord](https://ykilcher.com/open-assistant-discord),  "General Voice" channel
Audience: Everyone interested in contributing to OA (public)

Topics for the next meeting:

- long context technique
- refactoring of user account system, see #3246
- current LoRA training results
- next steps for human feedback data collection system

**Comment by 0x22almostEvil** [comment]
Duplicating some not discussed stuff from previous one:
![image](https://github.com/LAION-AI/Open-Assistant/assets/122345469/a9fc2ab2-257d-413f-b0ab-2ac79553939f)

**Comment by 0x22almostEvil** [comment]
Also, I think the "Continue generation" function is quite easy to implement (as opposed to stopping).
