### ISSUE TITLE
Prevent accidental skipping of tasks if input is not empty

### ISSUE THREAD

**Issue by PurrVirtual** [LAION-AI/Open-Assistant#3325]
Please, *please* add some kind of warning/confirmation when a user starts entering an assistant reply and then presses the Skip button.

It's hard to express how painful it is when you try to compose a good reply for an hour or more and then accidentally press “Skip” and not only lose your work but also the chance to take the task again.

I know it's not a frequent case (happened to me just a couple of times per 1K replies), but when it happens it hurts like hell. (I can explain how and why it happens, but not sure if it's worth your time.)

Maybe it's even better (and easier?) to **disable** the Skip button while the reply field is not empty (like the Review button is disabled while the fild is empty).

P.S. Please be indulgent: I've just registered on GitHub and have no idea how this thing works. (And I'm also struggling with my English.)

A huge respect for all the devs here!

**Comment by AbdBarho** [comment]
We had it before, then users complained that it is annoying to confirm the skip every time.

#1756

#2778

Do you have any ideas how we can deal with this>

**Comment by PurrVirtual** [comment]
Sorry, @AbdBarho, I didn't mean to create a duplicate, but I'm glad it has brought attention to issue #2778. Yeah, I remember that dialog with a feedback request and agree that it was an overkill.

That's why I'm only asking for the confirmation (or disabling the button) *in case* there is a text in the reply field. It shouldn't be annoying to anyone, since there's no reason to type any text if you're not going to send the reply. And if you change your mind, it wouldn't bother you to click twice, since you've already spent some time working on the task.

I see it as a reasonable compromise between the two inconvenient solutions (always confirming and never confirming).

**Comment by andreaskoepf** [comment]
https://github.com/LAION-AI/Open-Assistant/issues/2778 has now been assigned to @MehrJonas, closing this as duplicate.
