### ISSUE TITLE
Both options pertaining to chat management are very nonfunctional 

### ISSUE THREAD

**Issue by Maxuvious** [LAION-AI/Open-Assistant#3331]
Not only are these functions, opt-out of training data and delete the chat completely, hidden behind other elements (not clickable at all) but they don't actually perform the functionality they depict if you delete the elements in front so that you can get to them - to click them.

![image](https://github.com/LAION-AI/Open-Assistant/assets/45937868/d596acdb-5616-4149-9297-c725676f3638)

This is true for both opting out of the chat being used in the training data set and deleting the chat completely (which should also remove it from the data set). Neither do anything at all other than refresh the page.

![image](https://github.com/LAION-AI/Open-Assistant/assets/45937868/54c2972d-c822-4613-87ce-55dc29847190)

There is another issue [#3267](https://github.com/LAION-AI/Open-Assistant/issues/3267) discussing the fact that the delete button is behind other elements and unclickable, but this seems to be a more problematic issue than just what is described there. As well in issue [#3306](https://github.com/LAION-AI/Open-Assistant/issues/3306) where we see that this is not only relevant to the chat page itself, but also from the chat index page we see the same issues -- that is minus the buttons being unclickable. I would love to see updates on what is in mind to fix this or remove the functionality because it is not feasible, etc.

![image](https://github.com/LAION-AI/Open-Assistant/assets/45937868/797c4e79-fe68-4269-ae76-ffc9fcef67bb)

Small sub-note here: The text "Confirm opting of training data" is not clear as to what logical direction "opting" refers to. This could be opting in or opting out and since there is no notification anywhere showing 'this chat is currently opted into the data set' or 'this chat is opted out of the data set' for instance, we have no idea as to what state this option is in as the end user.

**Comment by NoMansPC** [comment]
Opt out of training data definitely doesn't seem to do anything.

**Comment by AbdBarho** [comment]
> Opt out of training data definitely doesn't seem to do anything.

it does a put request to our database, that is all.
