### ISSUE TITLE
Wrong instruction: "Please provide a reply to the assistant."

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#336]
For an assistant-reply task the discord-bot sends a message starting with:

![grafik](https://user-images.githubusercontent.com/9976399/210413859-ba3af9f1-4c96-4bc7-a5dd-987a83d74c44.png)

The task for the user is to "play the assistant", i.e. demonstrate how the assistant should ideally reply to the user reuqest/instruction. This should be reflected in the instruction sent to the user.

**Comment by Psychpsyo** [comment]
I've found the code that does this and am fixing it now.
