### ISSUE TITLE
Moderator message search on edited messages shows incorrect results

### ISSUE THREAD

**Issue by someone13574** [LAION-AI/Open-Assistant#3377]
When a message is edited, message search will still return that message if the original content matches the search phrase, even if the new content doesn't. This also results in the moderator message table showing the original content in the search view and not showing the 'edited' tag.

You can see this by going the the web-dev server and using message search for 'hello'. The top result will show the original message content and is missing the 'edited' tag but when you click on it, it shows the correct history. The admin message table also shows the correct data when not searching.

I'm not entirely sure on how the message search system works, but this appears to be due to something not being updated when it needs to be when a message is edited.

When not searching (correct):
![Screenshot from 2023-06-10 17-56-39](https://github.com/LAION-AI/Open-Assistant/assets/81528246/593d46ba-557d-4877-b3ca-d8e1908ed4be)

When searching for 'hello' (incorrect, outdated info and shouldn't show up):
![Screenshot from 2023-06-10 17-53-05](https://github.com/LAION-AI/Open-Assistant/assets/81528246/e225f246-8197-4fa3-ac0d-aea78e381e39)

Message history (correct):
![Screenshot from 2023-06-10 17-53-17](https://github.com/LAION-AI/Open-Assistant/assets/81528246/466b05ae-8008-4642-8c18-b537bca6fd4d)

**Comment by olliestanley** [comment]
To fix this the message search vector generation task will need to be updated, it currently only generated text search vectors for messages which don't already have them, whereas this will need to be done for messages which have been updated also
