### ISSUE TITLE
The inference cannot start up

### ISSUE THREAD

**Issue by yeasy** [LAION-AI/Open-Assistant#3428]
## Code to use

* 463d7293 - (2023-06-13 23:36:34 +0200) Add data loader for HF oasst1 (#2951) - Pedro Ferracini (HEAD -> main, tag: v0.0.3-alpha32, origin/main, origin/HEAD)

## Command to Run

docker compose --profile ci --profile inference up --build --attach-dependencies

## Error
The error is repeated in log:

open-assistant-inference-worker-1     | 2023-06-14 03:47:02.498 | WARNING  | __main__:main:128 - Retrying in 5 seconds...
open-assistant-inference-worker-1     | 2023-06-14 03:47:08.632 | INFO     | utils:wait_for_inference_server:155 - Inference server is ready
open-assistant-inference-worker-1     | 2023-06-14 03:47:08.634 | WARNING  | __main__:main:60 - connecting to ws://inference-server:8000...
open-assistant-inference-server-1     | 2023-06-14 03:47:08.640 | INFO     | oasst_inference_server.worker_utils:get_worker_id:58 - get_worker: api_key='0000', protocol_version='1'
open-assistant-inference-worker-1     | 2023-06-14 03:47:08.647 | WARNING  | __main__:main:70 - Connected to backend, sending config...
open-assistant-inference-worker-1     | 2023-06-14 03:47:08.652 | ERROR    | __main__:main:125 - Error in websocket
open-assistant-inference-worker-1     | Traceback (most recent call last):
open-assistant-inference-worker-1     |
open-assistant-inference-worker-1     |   File "/opt/miniconda/envs/worker/lib/python3.10/runpy.py", line 196, in _run_module_as_main
open-assistant-inference-worker-1     |     return _run_code(code, main_globals, None,
open-assistant-inference-worker-1     |            │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
open-assistant-inference-worker-1     |            │         └ <code object <module> at 0x4000e28190, file "/worker/__main__.py", line 1>
open-assistant-inference-worker-1     |            └ <function _run_code at 0x4000d4f1c0>
open-assistant-inference-worker-1     |   File "/opt/miniconda/envs/worker/lib/python3.10/runpy.py", line 86, in _run_code
open-assistant-inference-worker-1     |     exec(code, run_globals)
open-assistant-inference-worker-1     |          │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <_frozen_importlib_external.SourceFileLoader objec...
open-assistant-inference-worker-1     |          └ <code object <module> at 0x4000e28190, file "/worker/__main__.py", line 1>
open-assistant-inference-worker-1     |
open-assistant-inference-worker-1     |   File "/worker/__main__.py", line 133, in <module>
open-assistant-inference-worker-1     |     main()
open-assistant-inference-worker-1     |     └ <function main at 0x40162495a0>
open-assistant-inference-worker-1     |
open-assistant-inference-worker-1     | > File "/worker/__main__.py", line 73, in main
open-assistant-inference-worker-1     |     hardware_info=inference.WorkerHardwareInfo(),
open-assistant-inference-worker-1     |                   │         └ <class 'oasst_shared.schemas.inference.WorkerHardwareInfo'>
open-assistant-inference-worker-1     |                   └ <module 'oasst_shared.schemas.inference' from '/opt/miniconda/envs/worker/lib/python3.10/site-packages/oasst_shared/schemas/i...
open-assistant-inference-worker-1     |
open-assistant-inference-worker-1     |   File "/opt/miniconda/envs/worker/lib/python3.10/site-packages/oasst_shared/schemas/inference.py", line 44, in __init__
open-assistant-inference-worker-1     |     data["cpu_freq_max"] = psutil.cpu_freq().max
open-assistant-inference-worker-1     |     │                      │      └ <function cpu_freq at 0x400e645000>
open-assistant-inference-worker-1     |     │                      └ <module 'psutil' from '/opt/miniconda/envs/worker/lib/python3.10/site-packages/psutil/__init__.py'>
open-assistant-inference-worker-1     |     └ {'uname_sysname': 'Linux', 'uname_release': '5.15.106-0-virt', 'uname_version': '#1-Alpine SMP Wed, 05 Apr 2023 11:21:57 +000...
open-assistant-inference-worker-1     |
open-assistant-inference-worker-1     | AttributeError: 'NoneType' object has no attribute 'max'

**Comment by olliestanley** [comment]
Seems to be a bug in `psutil`. Related: #2248

**Comment by yeasy** [comment]
Thanks for the quick fix, now the service can start up, however, it will never respond to any message, and always keep:
"Your message is queued, you are at position 0 in the queue."
