### ISSUE TITLE
Download links in sft training folder

### ISSUE THREAD

**Issue by lucasjinreal** [LAION-AI/Open-Assistant#3429]
Please add links or cite to the opensource data in sft training.

**Comment by andreaskoepf** [comment]
There is now a link in [model/README.md](https://github.com/LAION-AI/Open-Assistant/blob/main/model/README.md):  "See the [OpenAssistant/oasst1](https://huggingface.co/datasets/OpenAssistant/oasst1) dataset card on the HuggingFace hub for more information."
