### ISSUE TITLE
Tasks no longer appear after going back to the main site and going to the task again

### ISSUE THREAD

**Issue by kostiak** [LAION-AI/Open-Assistant#343]
![image](https://user-images.githubusercontent.com/200502/210454751-9fb6b626-8be8-48e2-987f-65d1ae4adf36.png)

Reproduction:

1. On the website, choose a task type and click on it.
2. Go back
3. Click on the same task again

**Comment by fozziethebeat** [comment]
Can you see anything going on by checking the backend's docker logs?

**Comment by kostiak** [comment]
I don't think it's on the backend. It looks like when I first enter, the website calls the API for a task, but when I exit and enter the same task again, I don't see a call to the API.

**Comment by kostiak** [comment]
@fozziethebeat Sure, I'll test it out and let you know what I find.

**Comment by kostiak** [comment]
@fozziethebeat wasn't able to get`useSWR` to work reliability but I did test your suggestion and it works.

**Comment by fozziethebeat** [comment]
Alright, let's go with whatever works! Can you send that out as a PR? I'll review it high priority

**Comment by fozziethebeat** [comment]
Confirmed fixed
