### ISSUE TITLE
Create a separate task type for collecting text labels

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#344]
text labels can be collected throughout the application. these are things like "profanity", "helpful", etc.

They can be found here: https://github.com/LAION-AI/Open-Chat-GPT/blob/main/oasst-shared/oasst_shared/schemas/protocol.py#L232

We also want dedicated task types:
- label_initial_prompt
- label_assistant_reply
- label_prompter_reply

that explicitly ask the user to provide labels to a piece of text in the form of a task.

**Comment by andreaskoepf** [comment]
The new tasks should be used to collect peer-quality feedback during rating phase, see: https://github.com/LAION-AI/Open-Assistant/issues/37

**Comment by olliestanley** [comment]
I've had a quick look at adding tasks for this, see draft PR at #381 if any feedback/comments

**Comment by fozziethebeat** [comment]
How does this differ from `/api/v1/text_labels/`? I thought that end point was for storing the arbitrary text labels associated with a message?

**Comment by fozziethebeat** [comment]
Got it.  I think this could help #310 and deal with the situation where users skip tasks.

**Comment by olliestanley** [comment]
Closing this as resolved by #381
