### ISSUE TITLE
In search of Swag Designer!

### ISSUE THREAD

**Issue by camsdixon1** [LAION-AI/Open-Assistant#3483]
We continue to see the importance of building a high-quality dataset set for fine-tuning. To promote additional support, we want to offer people t-shirts, stickers, and other types of swag for hitting different internal milestones. If you would like to assist, feel free to post a few links to some design ideas you have.

**Comment by stefangrotz** [comment]
In #3175 I added the files for a hexagon sticker design

**Comment by camsdixon1** [comment]
Thank you! Where did you purchase these?

**Comment by stefangrotz** [comment]
I used sticker mule, they ship in many countries and the stickers are removable again wich I like for laptop stickers https://www.stickermule.com/uses/hexagon-stickers

For bigger numbers other companies might be cheaper.
