### ISSUE TITLE
Cannot give any answer with simple questions

### ISSUE THREAD

**Issue by yeasy** [LAION-AI/Open-Assistant#3485]
## OS
macOS with M1 chipset.

## Code to use
e522599e - (2023-06-16 12:37:40 +0200) Revert and update some of strings in tasks.json for the Ukrainian translation (#3427)

## Command to Run
docker compose --profile ci --profile inference up --build --attach-dependencies

## Issue
After login with the dev mode, for any question, even very simple, there is no answer, but keep showing: "Your message is queued, you are at position 0 in the queue."

**Comment by olliestanley** [comment]
Which model do you have selected?

**Comment by yeasy** [comment]
> Which model do you have selected?

The default one, which is _lorem + k50-Plugins

**Comment by AbdBarho** [comment]
> The default one, which is _lorem + k50-Plugins

change it to distillgpt

**Comment by yeasy** [comment]
HI, it seems distillgpt2 can give some response, but not it is not related to the question.

Is there any other model to give better answer?

Thanks!

**Comment by olliestanley** [comment]
> HI, it seems distillgpt2 can give some response, but not it is not related to the question.
> 
> Is there any other model to give better answer?
> 
> Thanks!

distilgpt2 is for testing. When running locally, if you want to use models other than the test model, you will need to change your docker compose configuration to specify the model to run. Some details of this can be found in the main/inference READMEs
