### ISSUE TITLE
Where can the data collected using Open Assistant be seen and exported?

### ISSUE THREAD

**Issue by 1920853199** [LAION-AI/Open-Assistant#3486]
Where can the data collected using Open Assistant be seen and exported?

**Comment by CloseChoice** [comment]
The dataset can be downloaded from huggingface: https://huggingface.co/datasets/OpenAssistant/oasst1

**Comment by 1920853199** [comment]
> The dataset can be downloaded from huggingface: https://huggingface.co/datasets/OpenAssistant/oasst1

I locally deployed Open Assistant, but I don't know which directory the data exists in？

**Comment by andrewm4894** [comment]
Here is a starter notebook showing how to load the dataset from huggingface and wrangle it a little

https://github.com/LAION-AI/Open-Assistant/blob/main/notebooks/openassistant-oasst1/getting-started.ipynb
