### ISSUE TITLE
How do I bypass login on local development server?

### ISSUE THREAD

**Issue by moonman239** [LAION-AI/Open-Assistant#3503]
I'm trying to create a chatbot-based application.

I'm running the local development server and I tried to POST to the Chats endpoint without providing an access token but got a "Not authenticated" error.

I managed to get an access token, but the local development server's documentation for the "chats" endpoint does not indicate how to pass it to a request.

**Comment by notmd** [comment]
There is a debug login, you need to send a request to it to get an access token, then send an `Authorization: Bearer ${token}` header to any other endpoint. If this work, please close this
