### ISSUE TITLE
Fix summarize from human feedback dataset source

### ISSUE THREAD

**Issue by theblackcat102** [LAION-AI/Open-Assistant#351]
Seems like the dataset name `Tristan/summarize_from_feedback` for [Learning to summarize from human feedback](https://arxiv.org/abs/2009.01325) was taken down and moved to [openai/summarize_from_feedback](https://huggingface.co/datasets/openai/summarize_from_feedback). So the existing code has to point to the new source.

mainly two files are affected:

[rank_datasets.py](https://github.com/LAION-AI/Open-Assistant/blob/main/model/reward/instructor/rank_datasets.py#L121)

[experimental_dataset.py](https://github.com/LAION-AI/Open-Assistant/blob/main/model/reward/instructor/experimental_dataset.py#L63)

**Comment by sanagno** [comment]
We can remove this if fixed from #352
