### ISSUE TITLE
Timeout chat

### ISSUE THREAD

**Issue by b4zz4** [LAION-AI/Open-Assistant#3513]
There are no answers. Aunt waiting long.
I use it in Spanish

**Comment by camsdixon1** [comment]
Can you give us more details? Are you the browser, or download, are you seeing any errors?

**Comment by b4zz4** [comment]
Use my account for a few days, but yesterday I stop answering and only stays waiting.
Create new chats, but the same only appears the circle thinking

![2023-06-24_12-41_33](https://github.com/LAION-AI/Open-Assistant/assets/643833/f51fc91d-c934-45b3-a7f8-809c4ee34c3f)

**Comment by toanbku** [comment]
+1

**Comment by maxiy01** [comment]
Same problem here, can't use text generation since last week

**Comment by maxiy01** [comment]
Clarification: looks like "OA_SFT_Llama_30B_6" model works fine, but "OA_SFT_Llama_30B_7" and "OA_RLHF_Llama_30B_2_7k" returns "The server is currently busy. Please try again later."

**Comment by myname1111** [comment]
> Clarification: looks like "OA_SFT_Llama_30B_6" model works fine, but "OA_SFT_Llama_30B_7" and "OA_RLHF_Llama_30B_2_7k" returns "The server is currently busy. Please try again later."

That may be due to the fact that those models are more popular that the other one and thus the queue is longer, if the queue gets too long then you'll get that message. At least that's what I heard someone in the discord say

**Comment by olliestanley** [comment]
Should be working again with SFT-6 now. Not sure when (if) SFT-7 or RLHF will be back soon

**Comment by lboklin** [comment]
The problem remains

**Comment by Billyroot** [comment]
Maybe try Pythia models
