### ISSUE TITLE
Move update task interaction into OasstApiClient

### ISSUE THREAD

**Issue by jack-michaud** [LAION-AI/Open-Assistant#353]
**Note**: Waiting for https://github.com/LAION-AI/Open-Assistant/pull/342 to be merged.

The website directly calls the backend through `fetch` [here](https://github.com/LAION-AI/Open-Assistant/blob/a95e71d6f9b8c46d8f6d875cb1cce12bfd549e63/website/src/pages/api/update_task.ts#L39-L57) when it should be called through the `OasstApiClient`.

1. Create a new method in `website/src/lib/oasst_api_client.ts`'s `OasstApiClient` which makes the API call done [here](https://github.com/LAION-AI/Open-Assistant/blob/a95e71d6f9b8c46d8f6d875cb1cce12bfd549e63/website/src/pages/api/update_task.ts#L39-L57).
2. Replace the original `fetch` call with the method call on `OasstApiClient`. 
3. Write a test in `website/cypress/contract/oasst_api_contract_tests.cy.ts` which calls that function and checks that the response is not null. An example of such a test can be found [here](https://github.com/LAION-AI/Open-Assistant/blob/a95e71d6f9b8c46d8f6d875cb1cce12bfd549e63/website/cypress/contract/oasst_api_contract_tests.cy.ts#L7-L15)

**Comment by fozziethebeat** [comment]
I haven't been tracking what this `OasstApiClient` does.  Could you outline what it's core methods are?

**Comment by fozziethebeat** [comment]
Nevermind, seeing the PR, i see this is a new thing you're creating.  I like it.

**Comment by fozziethebeat** [comment]
Before closing this out, can you also do some refactoring to tackle #105?  This basically needs to change how you set the `user` field in the body being posted.

**Comment by jack-michaud** [comment]
> Before closing this out, can you also do some refactoring to tackle #105?  This basically needs to change how you set the `user` field in the body being posted.

Sure, I can supply the JWT in the constructor of OasstApiClient so the client can be aware of the current user.
