### ISSUE TITLE
Hardware requirement for SFT for LLaMa 65B

### ISSUE THREAD

**Issue by dittops** [LAION-AI/Open-Assistant#3544]
What's the hardware requirement for full parameter fine-tuning for LLaMa 65B?

**Comment by camsdixon1** [comment]
There are a lot of different systems that can run LLaMa 65B for fine-tuning. It depends a significant amount on how much data you're fine-tuning, and you're timeline. If you're looking to just fine-tune, the cheapest would most likely be renting unused GPU/CPU space on a cloud server like Azure, google, or AWS.

As for running, it may be a bit of overkill but, The Storage Review lab used two NVIDIA RTX 8000 GPUs to run Meta’s LLaMa model. 
 - https://www.storagereview.com/review/meta-llama-and-alpacas-loose-in-the-lab-running-large-language-models-locally

**Comment by dittops** [comment]
That answer seems pretty high level and the link shared talks about inference requirement If I understand correctly. I have tested up to 30B full parameter training. So below is my thought on the training requirement for 65B.

With deepspeed stage 3, will need 16 A100 80 GB
With deepspeed stage 3 CPU offloading, can run even on a single A100 80 GB with 1.5TB RAM. In this case, the GPU memory can vary based on batch size and context length.
