### ISSUE TITLE
dynamic max charecters in chat

### ISSUE THREAD

**Issue by AbdelazizSharaf001** [LAION-AI/Open-Assistant#3545]
when asking the chat agent to build code it follows instructions carefully and could build alternatives also
that's great
but it only provide a piece of it
I can't prove it's functional if it's incomplete response
I think it's a matter of response max charecters length as it's neerly the same

this is the end of one response

![Screenshot_٢٠٢٣٠٧٠٥_١٤٥٩٣٠](https://github.com/LAION-AI/Open-Assistant/assets/36330265/42ea4b7c-ea71-49c2-bf6e-e6404c317f53)

**Comment by camsdixon1** [comment]
@AbdelazizSharaf001  We are currently working on a longer token length for text prompts.  Without seeing the entire transcript, I can't confirm if it's a token length issue or not.

In the meantime, to solve this, you may be able to respond to it and ask it to "complete the above" or let it know that it seems to have "cut off", both may let the system finish the above prompt.

Is there anything specific you're looking to have answered?
