### ISSUE TITLE
Web app manifest for assistant website

### ISSUE THREAD

**Issue by gregbacchus** [LAION-AI/Open-Assistant#3548]
I'd like to suggest that you add a web app manifest to the assistant website. 

https://developer.mozilla.org/en-US/docs/Web/Manifest
https://web.dev/add-manifest/

With the correct settings (`"display": "standalone"`), this will enable users (using Chrome, Edge or Safari) to "Install" the assistant on mobile devices or desktop so that it appears nearly like a native app.

**Comment by sun-jay** [comment]
Hey I added a manifest.json and its pretty cool. I accessed my local web server on my phone and you can basically add Open Assistant as an app on your phone (not sure if you have to sign in every time though). Opening up a pull request for my branch.

**Comment by sun-jay** [comment]
PR is here: https://github.com/LAION-AI/Open-Assistant/pull/3632
