### ISSUE TITLE
Unavailability of SFT7 & RLHF models for inference  ("The server is currently busy.")

### ISSUE THREAD

**Issue by nekohacker591** [LAION-AI/Open-Assistant#3556]
![image](https://github.com/LAION-AI/Open-Assistant/assets/73713314/32dff3cb-6072-468d-8718-0a5ec7930f40)

are they ever going to fix there servers

**Comment by toanbku** [comment]
you can try with `oasst-sft-6-llama-30b`, it works

**Comment by andreaskoepf** [comment]
Inference is (very) expensive and we rely on grants by our sponsors. The SFT-7 & RLHF models run at Stability A in preemptive mode. Currently there are no idle nodes available to run our inference. The SFT-6 model is still served via a TGI severer at Huggingface.

We are are super grateful for the compute-resources that were provided by our sponsors. But the truth is that we likely will not be able to host a free chat forever. The project should focus on extending the data-collection and improving models.

**Comment by olliestanley** [comment]
Yes, this is not something which can be fixed, the compute for SFT-7 and RLHF-2 is simply not available currently. The model will work if you switch to SFT-6.
