### ISSUE TITLE
Looking for a dev(s) to help data collection process - OASST

### ISSUE THREAD

**Issue by camsdixon1** [LAION-AI/Open-Assistant#3559]
Hello!

Open Assist is trying to build a larger dataset for fine-tuning models. 

Specifically, we are looking for a couple of developers that can assist in building out new UI on the open-assistant website for new tasks. Some of the tasks we see being important and needing UI are as follows:

- implement a function from a doc-string or description
- document or explain code
- refactor code
- write a unit-test
- convert/translate from programming language A to language B
- Mathematics
- etc.

If you're interested, please let me know! (looking for 2 people!)

Current dataset - https://huggingface.co/datasets/OpenAssistant/oasst1
Open Assist website - https://open-assistant.io/

**Comment by AyjayJr** [comment]
Hi, I'd love to help!

**Comment by camsdixon1** [comment]
@AyjayJr awesome! Do you have discord to connect a bit more? Also could you tell me a bit about your background? 

Thanks!

**Comment by AyjayJr** [comment]
@camsdixon1 Yes I have discord, my username is xpotent. I joined the Open Assistant server and sent you a message detailing my background. Looking forward to helping!

**Comment by Keshav15** [comment]
Hi, I'd also want to contribute, As you said you are looking for 2 people

**Comment by camsdixon1** [comment]
@Keshav15 Let's talk on Discord if you're available!

**Comment by Keshav15** [comment]
> @Keshav15 do you have discord? If so connecting on there would be a bit easier for back and forth.

Yes I have discord. This is my username... Keshav#3813
