### ISSUE TITLE
public API / Integration into Home Assistant

### ISSUE THREAD

**Issue by Aaroneisele55** [LAION-AI/Open-Assistant#3574]
Hello,
I would like to know if there is an official, public API available for developers to send prompts to the service and get responses from it.

I want to integrate it with Home Assistant (specifically its Assist feature which is currently, afaik, only usable with a paid openAI account if you want something other than pre-programmed sentences...) to generate text for dashboard screens based on e.g time, weather or such things by feeding that data into the prompt I'll give it

Is this (from the OA side) possible, and if not yet, when could it be ready?

Best regards
Aaron

**Comment by someone13574** [comment]
There isn't currently a public API available. You can see more details in the FAQ: https://projects.laion.ai/Open-Assistant/docs/faq#is-there-an-api-available
