### ISSUE TITLE
Add message id to messages in conversation model (protocol.py)

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#360]
Users should be able to give feedback for messages of a conversation when they are displayed in the fontends, e.g. during tasks to add a reply or when completed work is displayed in a recent activity view or the bot log-channel. Currently only the text and a flag whether the message is a user or an assistant message are sent to the client.

Add either a message_id field directly or in a meta-data dict. Potentially adapt other models like the MessageTree also, e.g. move meta data into a sub field, potentially create a class for standard-meta data (like date, message-id, user-id, frontend-user, frontend-message-id).

-> Align potocol with [data_schemas](https://github.com/LAION-AI/Open-Assistant/blob/main/docs/data_schemas.md) docs.

**Comment by andreaskoepf** [comment]
use case e.g. see 2.) of https://github.com/LAION-AI/Open-Assistant/issues/231#issuecomment-1369768813

**Comment by andreaskoepf** [comment]
Until we have a better solution, please include a `message_id` and a separate`frontend_message_id` field in `ConversationMessage`. @yk check

**Comment by melvinebenezer** [comment]
https://github.com/LAION-AI/Open-Assistant/issues/371 is dependent on this fix.
