### ISSUE TITLE
Frontend issue

### ISSUE THREAD

**Issue by KatsumiKougen** [LAION-AI/Open-Assistant#3608]
It happens to me everytime.

![image](https://github.com/LAION-AI/Open-Assistant/assets/77793743/a331f6ff-c7e2-48e5-9c1b-eca2cd6ecd67)

I tried asking for help on the OA Discord server, nobody had any good answer.

Can you guys do something about it?

**Comment by KatsumiKougen** [comment]
Please help me

**Comment by gsaivinay** [comment]
most probably, you'd need to change the model to version 6 from the dropdown.

**Comment by KatsumiKougen** [comment]
Can you guys fix the version 7 model?

**Comment by olliestanley** [comment]
> Can you guys fix the version 7 model?

No, it was using donated compute which is not currently available
