### ISSUE TITLE
docker error 8080 address already in use

### ISSUE THREAD

**Issue by FrankDataAnalystPython** [LAION-AI/Open-Assistant#361]
Hi:

I am running the "docker compose build" command on MacM1, and everything seems fine while but it shows the 8080 address already in use error at the very end.

![](https://user-images.githubusercontent.com/39264971/210510445-0d14fd3a-8a1c-4213-9782-e08368de0b55.png)

**Comment by andrewm4894** [comment]
Do you have any other docker containers running that might also be using that port locally?

**Comment by FrankDataAnalystPython** [comment]
> Do you have any other docker containers running that might also be using that port locally?

many thanks for the reply Sir. I have just used sudo and found there is a program on 8080. I replaced everything with 8081 in the project and now it is working
