### ISSUE TITLE
This AI aint replying to me 

### ISSUE THREAD

**Issue by Tonhhhk** [LAION-AI/Open-Assistant#3635]
It keeps saying server ia busu

**Comment by s0mt0chukwu** [comment]
Server is down 404

Try again in 2024 :-)

**Comment by andrewm4894** [comment]
I am seeing the same issue. 

Think is a few issues at moment. Will see if more info in the discord.

**Comment by andreaskoepf** [comment]
We reverted to the last release v0.0.3-alpha35 to see if that fixes the problem...
