### ISSUE TITLE
"No task where found" for all tasks since the update to v 0.0.3-alpha37

### ISSUE THREAD

**Issue by stefangrotz** [LAION-AI/Open-Assistant#3672]
![image](https://github.com/LAION-AI/Open-Assistant/assets/5982239/171d62ad-82c6-4465-9dcd-ec36097437a0)

My user is "Stergro" and I checked it with different languages.

**Comment by andreaskoepf** [comment]
The data collection backend needed to be restarted after redis restart. Should be fixed now.
