### ISSUE TITLE
report of a bug or error found

### ISSUE THREAD

**Issue by Hikaru033** [LAION-AI/Open-Assistant#3689]
Hello, I am writing to report an error or bug on the page that does not allow me to chat with the AI, every time I create a chat and send a message I get this message: “Application error: a client-side exception has occurred (see the browser console for more information). and I don't know why I get this message, I am attaching a photo of the message that the page shows me

![Screenshot_20230917-032054](https://github.com/LAION-AI/Open-Assistant/assets/134193206/16737098-985c-4f5e-94dd-f5fd39b58d0a)

**Comment by s0mt0chukwu** [comment]
Clear browser cache and restart browser

**Comment by andreaskoepf** [comment]
please see https://youtu.be/gqtmUHhaplo?si=dwe6p0BxObXSNZyS
