### ISSUE TITLE
website-lost api?

### ISSUE THREAD

**Issue by aboynejames** [LAION-AI/Open-Assistant#3698]
getting these connection messages over the weekend

chrome browser, trid firefox same

api/chat?include_hidden=false:1     Failed to load resource: the server responded with a status of 404 ()
api/chat:1     Failed to load resource: the server responded with a status of 404 ()
40-6a7da805ab2c5db4.js:1 Uncaught (in promise) n
api/chat?include_hidden=false:1     Failed to load resource: the server responded with a status of 404 ()
api/chat?include_hidden=false:1     Failed to load resource: the server responded with a status of 404 ()

**Comment by metal3d** [comment]
duplicated https://github.com/LAION-AI/Open-Assistant/issues/3695
