### ISSUE TITLE
Submitting tags on the website doesn't work due to the API route not existing

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#371]
When you go to a task and try to flag a message with one of the checkbox entries, nothing happens.  Inspecting the network logs it's calling an API path (`/api/v1/text_labels`) that doesn't exist.

To fix this it requires:
- [ ] Making a new web api route under `website/src/pages/api/set_label.tsx`
- [ ] Update the component `website/src/components/FlaggableElement.tsx` to call this web API route
- [ ] Implement the web API route to forward the tag content to the backend server using the API key

**Comment by melvinebenezer** [comment]
I can take this up if it's free.  please add me to the website channel as well.

**Comment by melvinebenezer** [comment]
Does this look fine ? 

![Screenshot 2023-01-06 at 6 55 08 AM](https://user-images.githubusercontent.com/6395936/210911414-bb5583bf-a16f-4a10-a9b9-46bb1b445eb5.png)

1. should this be updated in the prism db
2. should I test it with the backend ?  from code review perspective it looked ok

**Comment by melvinebenezer** [comment]
blocked by https://github.com/LAION-AI/Open-Assistant/pull/449

**Comment by fozziethebeat** [comment]
I think this is almost ready to be closed.  The only remaining fix is a small UI tweak to make sure the popup closes after the submission completes.  I can take that on.

Thank you @melvinebenezer
