### ISSUE TITLE
Dead? (In memory of Open-Assistant)

### ISSUE THREAD

**Issue by yhyu13** [LAION-AI/Open-Assistant#3712]
Hi, 

I can no longer access this url endpoint https://open-assistant.io. 

And it seems this project and hugging face https://huggingface.co/OpenAssistant has not been updated since the end of Augest 2023. What is current status of Open-Assistant?

**Comment by eroc123** [comment]
The website https://open-assistant.io/ works perfectly fine for me. Maybe check again? the hugging face says that the DE data set was updated 19 days ago.

**Comment by smeagolthellama** [comment]
I also cannot access the website. I'm in Eastern Europe, in case it matters.

**Comment by EditaNEmilis** [comment]
Still fine for me when accessing the website in Lietuva. *(also from Eastern Europe)*

**Comment by smeagolthellama** [comment]
Connection is still timing out for me, from Romania.

**Comment by eroc123** [comment]
I'm in SE Asia, in case it matters

**Comment by yhyu13** [comment]
Holy Cow, officially completed : https://www.youtube.com/watch?v=gqtmUHhaplo

Time to say goodbye~

**Comment by s0mt0chukwu** [comment]
> Holy Cow, officially completed : https://www.youtube.com/watch?v=gqtmUHhaplo
> 
> Time to say goodbye~

![2HPJpRIAXWsDjN.jpg](https://user-images.githubusercontent.com/81354428/278350266-89a5425c-4844-4631-9a2f-228ae2449bd8.jpg)
