### ISSUE TITLE
when i click on start new message it doesn'[t click 

### ISSUE THREAD

**Issue by ibgthb** [LAION-AI/Open-Assistant#3714]

**Comment by djbritt** [comment]
Me too, console says

POST https://open-assistant.io/api/chat 404 (Not Found)
(anonymous) @ _app-a38a56d4441b2a1d.js:6
xhr @ _app-a38a56d4441b2a1d.js:6
eR @ _app-a38a56d4441b2a1d.js:6
request @ _app-a38a56d4441b2a1d.js:6
(anonymous) @ _app-a38a56d4441b2a1d.js:6
(anonymous) @ _app-a38a56d4441b2a1d.js:6
eq @ _app-a38a56d4441b2a1d.js:6
(anonymous) @ 7832-634ab4df442acc22.js:1
(anonymous) @ 40-6a7da805ab2c5db4.js:1
onClick @ 40-6a7da805ab2c5db4.js:1
eU @ framework-a2363dd3c3dbe572.js:9
eH @ framework-a2363dd3c3dbe572.js:9
(anonymous) @ framework-a2363dd3c3dbe572.js:9
re @ framework-a2363dd3c3dbe572.js:9
rn @ framework-a2363dd3c3dbe572.js:9
(anonymous) @ framework-a2363dd3c3dbe572.js:9
oP @ framework-a2363dd3c3dbe572.js:9
eF @ framework-a2363dd3c3dbe572.js:9
ro @ framework-a2363dd3c3dbe572.js:9
nU @ framework-a2363dd3c3dbe572.js:9
nD @ framework-a2363dd3c3dbe572.js:9
40-6a7da805ab2c5db4.js:1 Uncaught (in promise) n {message: '', errorCode: undefined, httpStatusCode: 404, path: '/api/chat', method: 'post'}
onClick @ 40-6a7da805ab2c5db4.js:1
await in onClick (async)
eU @ framework-a2363dd3c3dbe572.js:9
eH @ framework-a2363dd3c3dbe572.js:9
(anonymous) @ framework-a2363dd3c3dbe572.js:9
re @ framework-a2363dd3c3dbe572.js:9
rn @ framework-a2363dd3c3dbe572.js:9
(anonymous) @ framework-a2363dd3c3dbe572.js:9
oP @ framework-a2363dd3c3dbe572.js:9
eF @ framework-a2363dd3c3dbe572.js:9
ro @ framework-a2363dd3c3dbe572.js:9
nU @ framework-a2363dd3c3dbe572.js:9
nD @ framework-a2363dd3c3dbe572.js:9
_app-a38a56d4441b2a1d.js:6
