### ISSUE TITLE
Open AI doesn't work for me

### ISSUE THREAD

**Issue by cookieshifting** [LAION-AI/Open-Assistant#3715]
Hello, good afternoon, I want to tell you that in my Open Ai account I can no longer create chats as before and my chats that I had created before no longer appear. Could you please solve this problem?

**Comment by twinflac** [comment]
devs words: Hi everyone, we've disabled chat on the website for now (it was financed privately). We'll give you some more updates soon.
The models remain available to download / self-host / etc.
