### ISSUE TITLE
Create a New Chat

### ISSUE THREAD

**Issue by SmartestArtist** [LAION-AI/Open-Assistant#3716]
Tapping the "+ Create a New Chat" button does nothing. iOS 16.6.1, Safari browser

**Comment by twinflac** [comment]
chats closed officaily

**Comment by goremykin** [comment]
In this case, [this section](https://github.com/LAION-AI/Open-Assistant#chatting-with-the-ai) should be removed from readme.md.

**Comment by twinflac** [comment]
may be it be used for future, like page in own host solution

**Comment by andreaskoepf** [comment]
> In this case, [this section](https://github.com/LAION-AI/Open-Assistant#chatting-with-the-ai) should be removed from readme.md.

If you think it should be corrected please edit the readme and create a PR.
