### ISSUE TITLE
Chat doesn't open

### ISSUE THREAD

**Issue by epz1371** [LAION-AI/Open-Assistant#3723]
dear ladies and gentelmen, 

I try to open a new chat and I click on the button "Create a new chat" in the following link: https://open-assistant.io/chat

But it doesn't work and it doesn't open any new chat for me. 
Please help me to fix this. Thank you very much.

Best Regards
Ehsan Pazooki

**Comment by someone13574** [comment]
[OpenAssistant is Completed](https://youtu.be/gqtmUHhaplo)
