### ISSUE TITLE
Unable to create new chat

### ISSUE THREAD

**Issue by ac852321** [LAION-AI/Open-Assistant#3731]
I'm unable to start a new conversation. Nothing happens when I hit the URL https://open-assistant.io/chat. I tried several browsers, believing the problem was with the browser settings, but it happened every time.

**Comment by RohitSurwase** [comment]
Happening the same with me.

**Comment by Alyetama** [comment]
I am having the same issue.

**Comment by ac852321** [comment]
I tried multiple browsers but still had the same problem. I thought I was the only one having this issue. I hope someone can fix it.

**Comment by beatstick** [comment]
Well something is broken on that website:

![Screenshot from 2023-11-24 13-55-53](https://github.com/LAION-AI/Open-Assistant/assets/11005435/e7c159a2-0b13-49a5-8e17-d8eb7fd8d4d3)

**Comment by s0mt0chukwu** [comment]
Don't expect it to be forever as one day it'll vanish off the face of the earth

**Comment by yk** [comment]
chats are disabled. there are tons of places where you can try these models
