### ISSUE TITLE
Architecture diagram

### ISSUE THREAD

**Issue by andrewm4894** [LAION-AI/Open-Assistant#377]
I think some sort of architecture diagram could be useful for people trying to understand the moving parts in this project. 

I can imagine it will change quite a lot so sometihng very low overhead and easy to maintain and evolve would be key.

**Comment by jojopirker** [comment]
I did somewhat in that direction in #367.

 I also agree that more documentation in that regard would be helpful!

**Comment by andrewm4894** [comment]
Oh cool if we merge this then we can make some architecture categories or pages and can use those files as starting point 

https://github.com/LAION-AI/Open-Assistant/pull/346

**Comment by AbdBarho** [comment]
https://projects.laion.ai/Open-Assistant/docs/guides/developers
