### ISSUE TITLE
Define backend admin endpoints

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#384]
We need to define "admin" endpoints. Admins are defined as a fixed list, provided to the website (remember that each user is identified as a tuple (user_id, auth_method). So the website knows who is an admin and can send that to the backend (we trust the website).

We need endpoints for admins to do admin-things, these are (non-exhaustively):
- explore the entire dataset
- set deleted flags on things (things flagged for deletion will be reviewed by us and then finally deleted)
- bring up a list of messages that have been "flagged" somehow (during the "text label" task) as profane, violating TOS, etc. and then "decide" what to do with them (clear them, i.e. decide the message is fine, or delete = set a deleted flag)
- bring up a list of users that have very low scores, indicating that they have been trolling, spamming, etc. along with their messages that have been flagged or low scored, and have the ability to ban these users
- more?

(note: this issue is for tracking the super-task of deciding on the endpoints. make individual issues for the individual things)

**Comment by fozziethebeat** [comment]
Is this required for the MVP or something we can add in afterwards as the next MVP?

**Comment by andreaskoepf** [comment]
How far are we here? I think flagged messages & low-score users are missing and we need an backend-enpoint for this.
I also suggest that we add an emergeny option to disable e-mail login if we see that people write bots .. maybe we need to add a list with excluded domains.

**Comment by olliestanley** [comment]
> How far are we here? I think flagged messages & low-score users are missing and we need an backend-enpoint for this. I also suggest that we add an emergeny option to disable e-mail login if we see that people write bots .. maybe we need to add a list with excluded domains.

If there are still backend endpoints in this area which are unimplemented and don't have issues, it would be good to get issues created with an outline. I'd be happy to work on one/more of them

**Comment by fozziethebeat** [comment]
I think it's safe to close this in favor of specific endpoints that need to be added.  I think we have sufficient end points to do all the most essential admin steps.
