### ISSUE TITLE
File Milestone and Issues to build a chatbot interface

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#388]
Build an interface to communicate with the Assistant, once we have trained it.
This should be a chat interface similar to chatgpt, with the ability to collect some extra user feedback.

Also, there should be a possibility to choose the model that acts as the assistant. At the beginning, this might be a model we trained from synthetic data, but eventually we'll add models that are more and more trained on the data we collected.

These models will be available as APIs, maybe from the backend, maybe from some other place, we'll have to see.

**Comment by fozziethebeat** [comment]
I was wondering when this would become a request.  I'm going to make this a milestone and then close issue in favor of smaller more focused issues.

**Comment by fozziethebeat** [comment]
I'm closing this in favor of more fine grained issues in the milestone: https://github.com/LAION-AI/Open-Assistant/milestone/4
