### ISSUE TITLE
pressing "submit" and then "next task" is a little confusing

### ISSUE THREAD

**Issue by andrewm4894** [LAION-AI/Open-Assistant#390]
its not obvious that something actually happens when i press submit. 

<img width="955" alt="image" src="https://user-images.githubusercontent.com/2178292/210656980-1c11f8e5-fa1a-48ec-bcbc-2b0a89fc3708.png">

and its confusing then to have to press the same button again then to get "next task"

<img width="952" alt="image" src="https://user-images.githubusercontent.com/2178292/210657099-a260954c-348d-4c43-960d-3ed293730956.png">

i did not actually notice that the "submit" button turned itself into a "next task" button. 

this behaviour does not feel typical and so was a little confusing to me. 

perhaps if there was some sort of feedback when i press the button that might make it clearer or maybe even easier to just spilt into separate buttons one for "skip", "submit", and "next task". 

just giving some dumb user feedback as i play around as im not all that familiar with the specific tasks and concepts yet.

**Comment by andrewm4894** [comment]
maybe its fine and i'd just get used to it once i do a few tasks. but just in case we aiming to have it as foolproof as possible such that any internet user can use it.

**Comment by fozziethebeat** [comment]
I agree.  It's not the best UI experience.  This was done to be minimally functional.

Could you draft a PR with a better button scheme?

**Comment by andrewm4894** [comment]
I can try :)

**Comment by AbdBarho** [comment]
as discussed in the meeting today, the behavior is un-expected.

Perhaps after implementing #433 this would be solved?

**Comment by fozziethebeat** [comment]
I think #433 is orthogonal to this issue since it applies to every task.  I
still don’t quite know what would make sense.

The buttons should be more clearly colored now but we could go further.  We
could fetch a real new task at the same time submit happens and update the
page without requiring a “next” button.  That wouldn’t be hard.

**Comment by AbdBarho** [comment]
We now have the refactored review / submit buttons

I will close this now, we can talk more about it in #734
