### ISSUE TITLE
Hard to find privacy policy and terms of service when on Website Dashboard page

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#394]
With the  new Dashboard layout on the web, it's very difficult to find the privacy policy or terms of service.  I think one minimal fix is to add the `Footer` component to the page.  But can we design something visually more appealing?

<img width="1180" alt="Screenshot 2023-01-05 at 9 45 32 AM" src="https://user-images.githubusercontent.com/398211/210676692-b59193a0-cf98-4f44-9ee2-1d4248101945.png">

**Comment by chs20** [comment]
How about adding a "help" button to the side bar which directs to a help-page containing FAQ and footer?

**Comment by fozziethebeat** [comment]
I think it'd be simpler and more consistent to have the footer on the dashboard page instead of a different way to reach the privacy policy and terms of service.  We include the footer in every other page.

**Comment by jojopirker** [comment]
How about adding them to the user menu? 
<img width="1434" alt="Screenshot 2023-01-05 at 11 53 42" src="https://user-images.githubusercontent.com/19796430/210763685-f9f40835-09a6-49a2-b383-1a4a41687fee.png">

**Comment by fozziethebeat** [comment]
That works a little better than a new button somewhere.  Design wise I was hoping that dropdown would be for things users need to access regularly rather than things that just need to be there for information reasons.  Checking against my UI gold standard [Common Voice](https://commonvoice.mozilla.org/en), they have a footer on their dashboard page, so style and consistency wise, i still prefer this.  But I'll accept a PR that includes these in the user drop down.
