### ISSUE TITLE
Grassroots Content Before 2015? Data Source - GeoCities Archive

### ISSUE THREAD

**Issue by Kinvert** [LAION-AI/Open-Assistant#398]
It might be interesting to train on how people talked before 2015 for orangevious reasons.

One good source could be this old time capsule, GeoCities.

https://academictorrents.com/details/2dc18f47afee0307e138dab3015ee7e5154766f6

There could be other sources too, but this was the first that came to mind. Others have mentioned old Reddit archives in other data related issues, such as:

- https://github.com/LAION-AI/Open-Assistant/issues/191#issuecomment-1368479359
- https://github.com/LAION-AI/Open-Assistant/issues/53

Can you guys think of other potential sources of older online content (other than just straight up using archive.org)?

_was going to label as data_

**Comment by Kinvert** [comment]
By the way old archives of Wikipedia can also be found, if you guys are interested in that.

Some potential sources:
- https://academictorrents.com/collection/wikipedia
- https://dumps.wikimedia.org/archive/
- https://download.kiwix.org/other

**Comment by ontocord** [comment]
Can you propose how we might extract the data, and parse it into dialog data? We are looking for that in particular. Like, are there things like topic sentences or titles, followed by answers or descriptions? Thank you.

**Comment by Kinvert** [comment]
There might be dialog data in there. Perhaps a needle in a haystack to find it.

Does it all have to be specifically question and answer? I don't know exactly how these are made, but I figured there was a chance of some transfer learning on a GPT3 type model that works with the Q+A system.

If it all has to be Q+A I would add study cards. There are tons of sites that have those. It's more for pure memorization though, so it's not conversation. Conversation type would be more like Quora. Not sure if anyone is working on a scrape of that.

**Comment by ontocord** [comment]
we don't need questions per say. We need some prompt - instruction, query or questions, and followed by an "answer". You can construct these by getting titles and the pargraph that follows. But you would need to do parsing. 

Another interesting thing is you could do this over time. This is kinda what you are talkng about. How does knowledge change over time.

So:

Who was the president in [date of the historical page]?  George W. Bush was the ... 


Literally, add in {date} at the end of each question.

**Comment by ontocord** [comment]
@Kinvert are you interested in taking this task?

**Comment by Kinvert** [comment]
I mean potentially. Is this something that they actually want to be done?

I want to make clear I'm not an expert at Computational Linguistics etc. But I am interested in contributing to this project.
