### ISSUE TITLE
`docker-compose up` gives this error in project dir.

### ISSUE THREAD

**Issue by hemangjoshi37a** [LAION-AI/Open-Assistant#400]
command I ran : `docker-compose up`
Error I got : 
```
ERROR: The Compose file is invalid because:
Service backend has neither an image nor a build context specified. At least one must be provided.
```

When I asked chatGPT this question it gave me following answer.

It looks like the backend service in your docker-compose.yaml file does not have an image or build specified. You must specify either an image or a build in your service configuration in order to create the service.

You can specify an image like this:

```
services:
  backend:
    image: my-backend-image
```

Or you can specify a build like this:

```
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
```

In the example above, context specifies the build context, and dockerfile specifies the path to the Dockerfile.

Make sure to include either an image or a build in the backend service configuration in your docker-compose.yaml file.

**Comment by kostiak** [comment]
'docker-compose' is the old way of doing that. Can you try 'docker compose up --build' please. Also what's the version of your docker?

**Comment by fozziethebeat** [comment]
@kostiak is correct.  `docker-compose` might work but the really important part is `--build` since all the images have to be built locally.

**Comment by fozziethebeat** [comment]
I'm going to mark this I'm going to mark this as closed after verifying that the main README includes the `--build` flag.

**Comment by kostiak** [comment]
@hemangjoshi37a 
Looks similar to #284
Update docker and try again.

**Comment by fozziethebeat** [comment]
Re-opening.  Something we could do regarding documentation is specify which version of Docker is required.  Would anyone like to update the main README with that qualification?

**Comment by hemangjoshi37a** [comment]
> Looks similar to #284
> Update docker and try again.

@kostiak  Thanks for the suggestion brother.


> Would anyone like to update the main README with that qualification?

@fozziethebeat Once I get it solved, I will fix `readme.md`.

**Comment by fozziethebeat** [comment]
Thank you for helping improve the documentation.

**Comment by hemangjoshi37a** [comment]
> Would anyone like to update the main README with that qualification?

@fozziethebeat  Please review pull request : #453

**Comment by andrewm4894** [comment]
Maybe we can make a FAQ.md or something like that and build up some common stuff over time. I'll try pull something together.

**Comment by andrewm4894** [comment]
Or adding a GitHub discussion for each question could be useful perhaps if we decide to turn on GitHub discussions

**Comment by vinicius-batista-dev** [comment]
![Captura de tela de 2023-01-06 16-40-09](https://user-images.githubusercontent.com/89554544/211087065-1cf9a85c-12d5-49e8-92bb-bf84cafb328c.png)

Hi, I was also having the same problem, I ran docker with sudo docker-compose up --build and it worked

**Comment by kostiak** [comment]
@sir-braz do not run `docker-compose` - that's the old way of running it.

Please try to run the following:
```
docker compose up --build
```

**Comment by hemangjoshi37a** [comment]
This solved my issue. Closing.

```
   DOCKER_CONFIG=${DOCKER_CONFIG:/usr/local/lib/docker}
   mkdir -p $DOCKER_CONFIG/cli-plugins
   curl -SL https://github.com/docker/compose/releases/download/v2.15.0/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
   chmod +x $DOCKER_CONFIG/docker-compose
   sudo chmod +x $DOCKER_CONFIG/docker-compose
   sudo cp $DOCKER_CONFIG/docker-compose $DOCKER_CONFIG compose
   chmod +x $DOCKER_CONFIG/compose
   sudo chmod +x $DOCKER_CONFIG/compose
   sudo docker compose version
```
