### ISSUE TITLE
email bot for data gathering?

### ISSUE THREAD

**Issue by andrewm4894** [LAION-AI/Open-Assistant#412]
what about having ability to just email task@openassistant.ai or something and then get a nice email with a task that user can then just respond to via text of the email. 

(might be one for way down the line but i could imagine just a simple text approach like this could be basis for email, twitter, or the chatbot approach too, or even a new sort of captcha quiz - that could be really good source of random unbiased data). 

i imagine maybe these interfaces might be easier to add on later once all the right abstractions are built and in place.

anyway just making issue for reference

**Comment by andreaskoepf** [comment]
E-Mail frontend sounds interesting. Nothing for our MVP but in case someone wants to work this and plan it/think it through, let us know.

**Comment by andrewm4894** [comment]
I think a pure api based approach could serve as a nice way to solve it once and then would be easy enough to build email client, a cli client, a reddit bot, etc on top of it.

Building an API could also then free up community or anyone to build whatever on it so maybe that's a good foundational part that I think is already in the plan or at least I know has been mentioned.
