### ISSUE TITLE
Implement Text Labels in web frontend

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#42]
Text labels are described in #40 .

Make sure the user can submit those for every post they see.

**Comment by fozziethebeat** [comment]
This feature is now open for work.

I'll make a web API point to submit labels that complies with the backend change and then document it.  Then we can generalize the component in the current rating task and add it to every task.

**Comment by BitterKanegul** [comment]
Hi @fozziethebeat , @yk , I would love to take this up!

**Comment by fozziethebeat** [comment]
Ideally this will make the checklist code in the current [grading task](https://github.com/LAION-AI/Open-Assistant/blob/main/website/src/pages/grading/grade-output.tsx) a re-usable component that is revealed as a popover (hidden behind a flag icon).  Then, when a user has checked one or more tags, they get submitted and associated with the task id.

To be complete, this will require both the UI side and and the web rest end point setup so that the tags are sent to the FastAPI backend.

**Comment by BitterKanegul** [comment]
One feature that was discussed in https://github.com/LAION-AI/Open-Assistant/issues/40 was allowing parts of the generated text to be annotated with various labels.

Do you think highlights and selection for the text is a way to go/ convert the text into a set of tags(each word is a tag) and allow the user to click on each?

**Comment by yk** [comment]
I think most text labels don't necessarily make sense to restrict to individual words, so I'd prefer the approach where the user range-selects some text. I think preference should always be given (ui-wise) to putting labels onto an entire post, because being able to map labels not only to text, but to posts inside conversations gives us some extra possibilities to create datasets, but I also think sometimes it's not appropriate to label an entire post, therefore I suggested the ability to annotate this kind of arbitrary text.

**Comment by BitterKanegul** [comment]
Interesting! I'll try to make it by default select an entire post, and if the user wishes, can change the selection to a substring of the post. Multiple labels on the same post/substring is also possible?

**Comment by yk** [comment]
> Interesting! I'll try to make it by default select an entire post, and if the user wishes, can change the selection to a substring of the post. Multiple labels on the same post/substring is also possible?

sounds like it could work :) yes, any label can be assigned a value from 0 to 1 (ideally, for binary labels just use 0 and 1)

**Comment by fozziethebeat** [comment]
I would say for the MVP and first PR we should just support text labels to an entire post.  After the MVP we can get fancy with sub-post labeling.  And we should be able to add multiple tags (i.e. a checkbox) for any given post.
