### ISSUE TITLE
Allow web users to evaluate a live models response.

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#431]
Add UI buttons to the page created by #428 to support evaluating the responses from the models.  This should start with a simple thumbs up and thumbs down style evaluation and then call the API route in #430.

**Comment by fozziethebeat** [comment]
This is blocked only by #428

**Comment by olliestanley** [comment]
I think this has ended up being duplicated by #1880 and will be solved by #1913
