### ISSUE TITLE
Factor out the dashboard page layout into a shared layout

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#432]
Right now `website/src/pages/dashboard` includes a nice `Sidebar` with multiple menu options and then presents the select page's contents.

This is a great design that would be nice to use in other scenarios such as for an admin specific page which would have different sidebar options.

To do this I think we need to:
- [ ] Make `website/src/components/Dashboard/SideMenu` it's own independent component that takes in a list of menu options as a property.
- [ ] Factor out the layout code in `website/src/pages/dashboard` into a layout component in `website/src/components/SideMenuLayout` that also takes in the list of menu options.
- [ ] Create several concrete layouts: `GeneralSidebarLayout` and `AdminSidebarLayout`, and maybe others.
- [ ] Use `GeneralSidebarLayout` in `website/src/pages/dashboard`
- [ ] Use `AdminSidebarLayout` in future admin pages but using a different color scheme and different sidebar options.

**Comment by Klotske** [comment]
@fozziethebeat I think I could take this issue. Could you assign it to me?
Self-assigning needs Github's Collaborator role i think...

**Comment by fozziethebeat** [comment]
Great!@ Yeah, the assigning part is a bit of a hassle.  After the MVP we might want to have a group discussion about simplifying it.

Also, since this is quite a few changes, I'd request this be done in a couple PRs rather than one giant PR.

**Comment by AbdBarho** [comment]
could this be closed?
