### ISSUE TITLE
Refactor the web tasks to present a server selected task type

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#433]
Right now users can select the task type they want but for data collection goals it's better for the server to decide what task is most important.

We should refactor the tasks such that they're all components and a single task page (`random`) will fetch a task type and content from the server and then present whatever that task content is.

This requires moving some react code around and consolidating things then simplifying the landing page.

**Comment by fozziethebeat** [comment]
This is very high priority

**Comment by andrewm4894** [comment]
Could maybe add task "points" concepts or something and have a way to see which are high value vs low value tasks etc. Eg maybe lean into the gamification stuff by putting a "price" or "value" on each task and then being able to use that to control or weight tasks and maybe even let users incentive to more higher value tasks. 

Might be a bit too fancy for right now, but on the other hand if each task had a "points" associated with it that could be a useful building block to add now. Is kinda a product sort of question maybe.

Unsure myself but just throwing idea out there.

**Comment by fozziethebeat** [comment]
That's a good idea in the future.  For the MVP we want to avoid creating any new feature requests for the backend.  The backend right now doesn't have a way to check if a task type has actual tasks that need answers so the best option would be to just have a "Random" option on the dashboard and let the server pick the task which needs an answer.

Later on, your idea is the right direction to go towards but needs help in the backend.

**Comment by kostiak** [comment]
Is there already an endpoint that will return a task_type?

Also, do we want the content (like "Given the following prompts, sort them from best to worst, best being first, worst being last.") to come from the backend or sit in the frontend?

**Comment by kostiak** [comment]
@fozziethebeat I created a draft PR to suggest how we can refactor the pages into components. It's already quite a big change, so I didn't add the "random" page yet. Want to double check I'm going in the right direction.

What I did was extract the task definitions from `/Dashboard/TaskOption.tsx` into '/Tasks/TaskTypes.tsx` and modify it to be more extendable. Then I based the components on it. 

I created a `Task.tsx` which has the general task logic. `CreateTask.tsx`  and `EvaluateTask.tsx` have the specific things of those types need.

I also moved all the task pages into /tasks/ route.

**Comment by fozziethebeat** [comment]
I think this sounds right but i'd have to look at a PR to be sure

**Comment by kostiak** [comment]
@fozziethebeat uploaded a new draft PR, let me know if that's more in the right direction, thanks!

**Comment by kostiak** [comment]
@fozziethebeat Now that the refactor is merged (a big thanks to @AbdBarho for the help) we need to discuss the design of the page. The easiest way is to add a new category:
![image](https://user-images.githubusercontent.com/200502/211160539-d48c909b-9688-4f55-b6ce-3072b291e6d8.png)

I don't think that looks good, plus it pushes the leaderboard out of view. Some suggestions:
1. We can add a specific design for the random task, taking up less space
2. We can reduce the gaps between categories
3. We can cosider moving the leaderboard to the top

Let me know what you think.

**Comment by AbdBarho** [comment]
Perhaps to add a point from the last meeting, assuming I understood everything correctly:

the random task should in theory be the only task kind available. the backend decides what the 'random' task should be based off what data is needed.

This is more or less the current behaviour of the discord bot.

**Comment by kostiak** [comment]
@AbdBarho does the discord currently implement the labeling tasks?

**Comment by AbdBarho** [comment]
I think this still needs a bit discussion with the team, I will add label it accordingly.

@kostiak regarding your question, I think the bot currently only shows random tasks. @AlexanderHOtt ?

**Comment by Klotske** [comment]
With PR #470 now merged, should we also remove redundant `TaskSelection` folder & components?

**Comment by AbdBarho** [comment]
@Klotske I did in #477, or at least what was obvious.

**Comment by Klotske** [comment]
@AbdBarho Oh okay. Then great! I looked through the PR but missed that...

**Comment by fozziethebeat** [comment]
For right now (this will likely change later once there's more backend features) we should show just one task type on the dashboard.  So yeah, we can clean up a lot of stuff that was for presenting all the task types.

**Comment by AlexanderHOtt** [comment]
> I think this still needs a bit discussion with the team, I will add label it accordingly.
> 
> @kostiak regarding your question, I think the bot currently only shows random tasks. @AlexanderHOtt ?

The bot defaults to random, but the user can still select the type of task.

**Comment by fozziethebeat** [comment]
With everyone's help, this is now done!
