### ISSUE TITLE
Make it easier to submit longer responses on website

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#435]
The default textbox and instructions encourage fairly short message responses.  We should:
- [ ] Make the text area larger to encourage more writing
- [ ] Add some kind of instructions that encourage more comprehensive answers

**Comment by AbdBarho** [comment]
idea from meeting:
length could be indicated by colored bars that fill up just like password strength.

**Comment by Klotske** [comment]
Working on it

**Comment by fozziethebeat** [comment]
I'll mark this as closed for now.  We've added the progress bar to indicate response length.
