### ISSUE TITLE
Implement Labeling Tasks

### ISSUE THREAD

**Issue by AbdBarho** [LAION-AI/Open-Assistant#436]
For tasks where the user has to assign labels to a given text, the backend should provide these labels, instead of hard-coding them in the frontend.

This is similar to the `Report` functionality.

Question:
Should the labels be part of the task delivered from the backend, or a separate endpoint?

**Comment by olliestanley** [comment]
As part of #381 (merged today) the valid labels are sent as part of the task definition when starting a prompt/reply label task

**Comment by AbdBarho** [comment]
@olliestanley thank for the info! these are 3 new tasks that needs to be added to the website, correct?
`label_initial_prompt` `label_prompter_reply` `label_prompter_reply`

**Comment by olliestanley** [comment]
> @olliestanley thank for the info! these are 3 new tasks that needs to be added to the website, correct?
> `label_initial_prompt` `label_prompter_reply` `label_prompter_reply`

Yep! (but one is label_assistant_reply)
