### ISSUE TITLE
Drag and drop should not be constrained to the handle only

### ISSUE THREAD

**Issue by AbdBarho** [LAION-AI/Open-Assistant#437]
In ranking tasks, drag and drop should not be constrained to the handle only, but should be the entire text element.

https://github.com/LAION-AI/Open-Assistant/blob/42deae20f29492759c2f9d11ec088d875b45d476/website/src/components/Sortable/SortableItem.tsx#L24-L33

**Comment by othrayte** [comment]
I suggest we make sure to keep the drag handle icon so that it is still clear than it can be dragged (and after this change will also be easy to use)

**Comment by othrayte** [comment]
Also this element is interacted with in the end-to-end tests so make sure to run `npm run cypress:run` or `npm run cypress` to check that those still pass.

**Comment by AbdBarho** [comment]
This is already implemented.
