### ISSUE TITLE
Save source of the task's response (website, discord-bot)

### ISSUE THREAD

**Issue by AbdBarho** [LAION-AI/Open-Assistant#438]
The backend should know the source of the response, whether it's coming from a web UI or from the discord bot.

This will require modifications both on the backend and the frontends.

**Comment by jojopirker** [comment]
I would like to try it, to maybe understand the backend development process better :)

Just to clarify I need to update the database (e.g.: via Adminer) then run `alembic revision -m "..."` and update `oasst-shared/api_client.py` as well as `backend/oasst-backend/models/api_client.py` (?)
Did I miss something?

**Comment by AbdBarho** [comment]
can we close this?

**Comment by olliestanley** [comment]
> can we close this?

Think it has a bug which will be fixed by #526 then once that's merged we can close this

**Comment by yk** [comment]
closing, since #526 is merged
