### ISSUE TITLE
Product telemetry instrumentation

### ISSUE THREAD

**Issue by andrewm4894** [LAION-AI/Open-Assistant#458]
This is for sure a bit premature but just wanted to mention. If we have a need for product telemetry on the frontend then I'd recommend and be happy to help set up posthog. 

They have a free cloud offering, are developer first, open source, very responsive and we can customize to any level of analytics as we need or want (e.g different levels of opt in or out etc). They also make it easy to publish public dashboards which could be handy for this project.

Just thinking if we want simple ways to get product analytics that we can share back with users, help with spotting bugs or issues and generally understanding usage patterns. All in a totally open and non creepy way, can be as anonymous or not as we want. 

(At netdata we made it anonymous in the open source project ([example](https://github.com/netdata/dashboard/blob/040b6bdb8378ae97d5f56ef2349ec852c2186ac9/src/domains/global/sagas.ts#L82)) and a more traditional implementation in our cloud offering)

Anyway, probably something we not thinking about right now but could be useful and helpful for getting this sort of usage insights back out of it without crazy complex backend work.

https://github.com/PostHog/posthog

**Comment by fozziethebeat** [comment]
And alternative is also Prometheus: https://prometheus.io/

**Comment by AbdBarho** [comment]
Other alternatives:

Google Analytics https://analytics.google.com/

OpenTelemetry (open-source, requires setup): https://opentelemetry.io/

**Comment by fozziethebeat** [comment]
Looking at the options briefly, Posthog looks like its the most analogous to Google Analytics.  I like that they have a [posthog-foss](https://github.com/PostHog/posthog-foss) repo that's 100% FOSS.  I propose we give Posthog FOSS a shot and see how well it works.

**Comment by fozziethebeat** [comment]
My big question tho is what are the premium features for posthog that are under the `ee` directory?  I'm hoping they're not that useful since using them with self hosting requires a license.

**Comment by andrewm4894** [comment]
I would +1 PostHog and happy to help with implementation or anything as i'm very familiar with it and this space in general. 

I'd suggest just starting with their free cloud tier since gets 1st million events free (am sure we could ask them to see about maybe sponsoring some amount above that (if was ever needed) maybe potentially as an open source project ourselves). 

If we wanted to self host afaik there is not really any major differences in terms of features or things that would be missing, just more about managing it ourselves ([docs](https://posthog.com/product#self-hosting)). We have done both at [Netdata](https://github.com/netdata/netdata) where i work, started with self hosting but have since moved to their cloud as one less infra thing to worry about.

**Comment by fozziethebeat** [comment]
I think Umami or Plausible are the best options.  Both look like they fully support self hosting.  Given the rest of our stack can be fully self hosted, I think our analytics solution should follow that trend.  We'd make it harder for others to deploy their own versions if they *had* to depend on posthog cloud.

**Comment by AbdBarho** [comment]
https://github.com/supabase/supabase
