### ISSUE TITLE
Setup a Privacy Policy

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#46]
This privacy policy should follow LAION's current [Privacy Policy](https://laion.ai/privacy-policy/) but be changed to make clear what personal information gets stored and under what conditions.

When complete this should be presented in a website any user can visit.

**Comment by fozziethebeat** [comment]
I've written a draft in Notion: https://www.notion.so/Privacy-Policy-a154eaf2ed0b48179fbd9e58acb44de6

**Comment by fozziethebeat** [comment]
The notion isn't full access just yet.

Assume the privacy policy and terms of service text will look something like what's on https://laion.ai/privacy-policy/

**Comment by rsandb** [comment]
Working on the layout for the site
