### ISSUE TITLE
configure https://liaon-ai.github.io/Open-Assistant/

### ISSUE THREAD

**Issue by andrewm4894** [LAION-AI/Open-Assistant#461]
@yk can you configure this repo like this.

This should just deploy a github pages at https://liaon-ai.github.io/Open-Assistant/ based on this `gh-pages` branch: https://github.com/LAION-AI/Open-Assistant/tree/gh-pages

https://github.com/LAION-AI/Open-Assistant/pull/346#issuecomment-1370888064

![image](https://user-images.githubusercontent.com/2178292/211113167-9c596869-2e4e-4bd6-87a6-8e0bd4df125c.png)

**Comment by yk** [comment]
should be the case, can you confirm?

**Comment by andrewm4894** [comment]
Look like 404 I will see if I can run the docs GH workflow in case needs to be triggered on new commit to the gh-pages branch

**Comment by andrewm4894** [comment]
Think might need to merge this to trigger things

https://github.com/LAION-AI/Open-Assistant/pull/484

**Comment by yk** [comment]
yes, also liaon is spelled laion :)

**Comment by andrewm4894** [comment]
I will never learn how to spell that word. If I have not already, it's just not going to stick :)

Looks like it's up here. https://laion-ai.github.io/Open-Assistant/

Might do a small follow on PR or two to do any superficial clean up stuff.
