### ISSUE TITLE
Discord link on website has expired

### ISSUE THREAD

**Issue by MichaelBurry** [LAION-AI/Open-Assistant#465]
As above.

**Comment by fozziethebeat** [comment]
@yk it seems the discord invites have expired.  Can you make a permanent one and share it here (and elsewhere it's needed)?

**Comment by andreaskoepf** [comment]
Good catch, this is a permanent one for our OA dev server: https://discord.gg/2PTwPQPyrk

**Comment by andreaskoepf** [comment]
Ah, probably https://github.com/LAION-AI/Open-Assistant/blob/ff1208111c5a25dc4d1d368624ff0db53704cfc9/website/src/components/Footer.tsx#L34 and https://github.com/LAION-AI/Open-Assistant/blob/ff1208111c5a25dc4d1d368624ff0db53704cfc9/website/src/components/CallToAction.tsx#L51
@fozziethebeat could you please replace those by https://ykilcher.com/open-assistant-discord ?

**Comment by Dilshan-H** [comment]
This issue still can be seen on **Open-Assistant website** and in **README files**. The current link on both call-to-action section and footer (https://ykilcher.com/open-assistant-discord) redirect to https://discord.com/invite/H769HxZyb5 - which is a expired join link.

> Good catch, this is a permanent one for our OA dev server: https://discord.gg/2PTwPQPyrk

And this link also seems to be expired.

**Comment by yk** [comment]
closing this, because both invites are still active and working (for me)
