### ISSUE TITLE
I want to use GOOD chatGPT chat output that can be used for Open-Assistant training.

### ISSUE THREAD

**Issue by hemangjoshi37a** [LAION-AI/Open-Assistant#471]
I have one prototype chrome extention that can be used to upload chat from chatGPT page to GitHub Repo. and after that that same repo can be directly used to train Open-Assistant. 

https://github.com/hemangjoshi37a/ChatGPTPublish

I am having some issues implimenting this idea as I have much less experiance in developing chrome extentions. Please let me know if anyone can contribute on this.

Here I have some html from my chat with chatGPT. : https://github.com/hemangjoshi37a/my_chat_with_chatGPT
Like this html I want to upload `json` of the chatGPT chat to github repo and then it can be moderated and finalized to use as training data. Because I dont know how to convert html to json I have simply uploaded html for someone to use it as trainig data for Open-Assistant. 

Further step would be, There should be a uplaod button next to every chatGPT response in the chat page that can upload the question answer pair JSON to perticular github repo for training Open-Assistant.

@yk @kostiak @sir-braz @andrewm4894 @fozziethebeat

**Comment by ontocord** [comment]
We will not use output from chatgpt in our training bc we want to respect the terms of use of openai, and we want to see if we can solve some of the failure cases of chatgpt. thank you for bringing this up.

**Comment by hemangjoshi37a** [comment]
> We will not use output from chatgpt in our training bc we want to respect the terms of use of openai,

We are not violating openAI T&C by using the response from output because it can be used anywhere open-source or closed-source software. or may be I dont know if there is any T&C about this in opanAI docs.

> and we want to see if we can solve some of the failure cases of chatgpt

The most problematic thing I have noticed is not giving complete code-block output that has bigger size(i.e. more lines of code) and failing to complete the remaining code when asked. If we fulfiul this this problem we can be MVP easily. You can tag this issue as MVP or Feature request.

**Comment by kostiak** [comment]
From https://openai.com/terms/

> (c) Restrictions. You may not ... (iii) use the Services to develop foundation models or other large scale models that compete with OpenAI;

**Comment by hemangjoshi37a** [comment]
> From https://openai.com/terms/
> 
> > (c) Restrictions. You may not ... (iii) use the Services to develop foundation models or other large scale models that compete with OpenAI;

Ohh Sorry I didnt see this coming. We tatally dont want to violate that. my bad.
