### ISSUE TITLE
`Implement code` Button for the response from Open-Assistant

### ISSUE THREAD

**Issue by hemangjoshi37a** [LAION-AI/Open-Assistant#473]
Whenever there is code-block in the response from Open-Assistant there should be a `Implement` button that can edit the file's code using the response code-block instead just giving the response.

Here is how this can be explained for example:
1. A person asks to write `hello world` program in python.
2. Open-Assistant gives code-block of `print('Hello World!')` as output. but as there is copy button in every code block there should be a `Implement` button that can use chrome to acess the system terminal of that persons computer.
3. When the `Implement` button is clicked, it will make a file called `hello_world.py` in that persons pc and will put the response code-block into that file.

Similarly it can be done for editing currently available file. for example if we want to print hello world 5 times then it will add a loop in the same file previously created `hello_world.py`.

We can make this happen in several ways. One of which is using prompt engineering, that is while Open-Assistant has finished giving the response we can take that response as input and add this prompt to get automation script. Like `Give me python code that can automatically implement given response.`

This can be a feature that even chatGPT lacks and can help Open-Assistant become MVP. One can tag this issue as may be a feature request.

**Comment by fozziethebeat** [comment]
I feel like this is better suited for some API wrapper around the models created by open-assistant rather than something we build into the data collection website.

Right now the website is focused heavily on generating and validating data rather than being a consumer facing interface for an open assistant.

Further, Giving a website the ability to create files on someone's computer introduces a massive security vulnerability and what feels like a fairly large amount of complexity.

**Comment by hemangjoshi37a** [comment]
Sure that is a better way to do this. This topic can be raised once the model goes live from data collection centric approach to consumer facing approach. And also considering security vulnerabilities. Thanks for your input @fozziethebeat

**Comment by ontocord** [comment]
> Further, Giving a website the ability to create files on someone's computer introduces a massive security vulnerability and what feels like a fairly large amount of complexity.
thank you for bringning this up @fozziethebeat .

Yeah - we haven't even raised security issues for this app. I am assuming no access to local resources, except maybe via retreival and/or search in the future. and search is just via keywords to an api. 

security is a much larger issue. we can start the discussion in discord, but i don't see it as an issue yet for us.

**Comment by yk** [comment]
> 2\. Open-Assistant gives code-block of `print('Hello World!')` as output. but as there is copy button in every code block there should be a `Implement` button that can use chrome to acess the system terminal of that persons computer.

the world would be one hell of a place if this was possible 😁

I also feel like this is something that can be built on top of our assistant, and not something we will build, at least not in the near or medium-term future. I'm closing the issue for that reason. In case you'd actually like to work on this, let us know, we can re-open it.

**Comment by hemangjoshi37a** [comment]
@yk I think I will simply do the typical software engineer thing that everyone does, ask chatGPT for help LOL..

Nice username though `yk`. Have you purchased it or was it just available?

**Comment by yk** [comment]
No I'm just old

**Comment by yk** [comment]
;) jk got on github early

**Comment by hemangjoshi37a** [comment]
OK `coder-grandpa` LOL...
