### ISSUE TITLE
`Enable Internet Access` checkbox for having search engine results as reference.

### ISSUE THREAD

**Issue by hemangjoshi37a** [LAION-AI/Open-Assistant#474]
There sould be a checkbox near the chat send button from where we can enable browsing mode for Open-Assistant so that ot can crawl though the search results from different search engines like `Google`, `Bing` and `DuckDuckGo`. 

Or there could be a option to add a `URL` or `local file address` to take that content as reference before generating the output response.

Or may be can take oputput from different AI search engine like `perplexity.ai` as reference.

Can be tagged this isssue as feature request.

Thanks Open-Assistant team and all the contributors for such a great software.

**Comment by ontocord** [comment]
very future stuff. not for mvp, but good idea.  if you have code proposal, happy to look at it.

**Comment by hemangjoshi37a** [comment]
> very future stuff. not for mvp, but good idea.  if you have code proposal, happy to look at it.

I just 5 minute found out this chrome that already has implemented this.

https://chrome.google.com/webstore/detail/webchatgpt/lpfemeioodjbpieminkklglpmhlngfcn

I hope we can do something natively from our library for Open-Assistant then depending on external browser extentions that we don't know when it might stop supporting.

**Comment by yk** [comment]
thanks for the reference. I'm closing this issue as retrieval is definitely a core part of the future roadmap, so if the initial assistant works at all, we will tackle this for sure.
