### ISSUE TITLE
`Multi-modal prompt` as input that we can give mix of `Text`, `Image`, `Video`, `Audio` or `Live Screen Share` as prompt

### ISSUE THREAD

**Issue by hemangjoshi37a** [LAION-AI/Open-Assistant#481]
## I got this idea from the chat we often do on online website (i.e. hosting service provider website) . There we share sometimes screenshots and video of screen recording.

It is more convenient to give the model the reference about what we are talking about. Like as if we are talking to someone and we are giving some another modal input as reference. Lets say we are developing a app and we want to tell our developer that I want to make changes to this button or text inout or somethind like that. Becuase when we are not actively developing the code and only developing the app passively we might not have the variable, methods and class names in our knowledge and what we know is only the output of the code.

To resolve this we might need to mix-modal input to the prompt of the Open-Assistant.

How can we implement this?
One way to do this is have multimodal chat data that contains screenshot and may be screen recording videos. and then train on that multi modal data. To train that we can use currently highest performing state-of-the-art method for perticular input type from papreswithcode.com.

I hope someone implements upon this to make Open-Assistant MVP.

This issue can be tagged as feature request by the collaborators.

**Comment by andreaskoepf** [comment]
This is something we will definitely consider for future versions. We considered multi-modal messages in the beginning of the project but decided to build a text-only first version first (reduced complexity).
