### ISSUE TITLE
Inform user and request new labels if invalid labels entered

### ISSUE THREAD

**Issue by olliestanley** [LAION-AI/Open-Assistant#491]
The frontends should inform the user if an invalid label is entered and request updated labels during a text label task

**Comment by AbdBarho** [comment]
As it is currently implemented in #477, users cannot freely chose labels, we only display the values delivered with the task.

**Comment by olliestanley** [comment]
> As it is currently implemented in #477, users cannot freely chose labels in the webfontend, we only display the values delivered with the task.
> 
> Or is this only for the backend?

This is for text-frontend currently. Validation is already carried out in discord-bot. I wasn't sure if the website needed changing or not but if not that means this issue is only for text-frontend and can be closed after #495 is merged
