### ISSUE TITLE
TrackedText progress bar shows "high quality" on empty text with lots of spaces.

### ISSUE THREAD

**Issue by kostiak** [LAION-AI/Open-Assistant#492]
The way the progress bar works currently, this:
![image](https://user-images.githubusercontent.com/200502/211159898-a79b1cc9-f597-4a38-9f68-a40e0f5b1dc3.png)

and
![image](https://user-images.githubusercontent.com/200502/211160018-0c71729e-e138-4b10-8b08-1c9a4fd98538.png)

Give similar indications to the user.

Maybe we should include some kind of 'valid character' count into the calculation of the progress bar.

**Comment by Klotske** [comment]
I think we could use regular expressions to count the words instead of the basic "separate by space char".

I could make a quick PR

**Comment by AbdBarho** [comment]
I think the solution proposed by @Klotske in #494 solves this issue, but this does not go far.
```
aa a a a a a a a a  a a a aa a a aa aa aa a aa a
```
would probably turn the bar green.

we need to indicate that the bar references the length of the input, not its quality. 

We have ranking tasks specifically designed to deal with bad input.

**Comment by kostiak** [comment]
In general this is not something we are going to "solve", the idea here is to give a good indication to the user what is expected from him. I think some basic checks on this side are enough, just to give a hint to "good actors" - if someone intentially tries to spam, that will be dealt with by the rating.

**Comment by AbdBarho** [comment]
@kostiak Agree

I would not expect a good actor to try to fill the input with spaces or similar in the first place, but better feedback is always good.
