### ISSUE TITLE
Use API to populate text_labels in frontend

### ISSUE THREAD

**Issue by melvinebenezer** [LAION-AI/Open-Assistant#493]
Modify textFlagLabels in FlaggableElement.tsx to be coherent with the backend using the API (yet to be created)

https://github.com/LAION-AI/Open-Assistant/blob/69bc799cd9bdb80bcaa8388368b75551d573eac0/oasst-shared/oasst_shared/schemas/protocol.py#L263

**Comment by melvinebenezer** [comment]
decision is that @andreaskoepf will add an API endpoint to query valid values + descriptions ...
This is a cleaner approach

**Comment by AbdBarho** [comment]
can we close this? 

https://github.com/LAION-AI/Open-Assistant/blob/5d1b03b02dce0f87d9ae6f9322c249be5905dfd6/website/src/components/FlaggableElement.tsx#L51

**Comment by fozziethebeat** [comment]
I believe so.  We're fetching the labels from the backend endpoint.  @melvinebenezer can you verify?

**Comment by melvinebenezer** [comment]
Yes, this is fetched from the endpoint. Can be closed
