### ISSUE TITLE
Long messages break inside the "Messages" section

### ISSUE THREAD

**Issue by kostiak** [LAION-AI/Open-Assistant#499]
Given we are going to sometimes get spam inputs/outputs, the messages should be able to handle long text.

![image](https://user-images.githubusercontent.com/200502/211163173-38022675-2386-4b51-96e9-1d72817da328.png)

**Comment by jojopirker** [comment]
one possibility would be just to break lines 

<img width="1435" alt="Screenshot 2023-01-08 at 18 54 44" src="https://user-images.githubusercontent.com/19796430/211211690-6e3d90e4-baf9-4572-90db-aea06035cf40.png">

but maybe even better to limit number of lines on main messages page
<img width="1440" alt="Screenshot 2023-01-08 at 18 55 10" src="https://user-images.githubusercontent.com/19796430/211211703-5891af72-f56b-47ee-86a6-7fbaaa76e83a.png">

**Comment by KarthikRaju391** [comment]
@jojopirker, if we limit the lines, should there be a click event that expands the message if there are more lines?

**Comment by jojopirker** [comment]
@KarthikRaju391 either that, or we leave it limit at the main messages page und only show it detailed where it is needed

**Comment by AzielChamba** [comment]
I can help with that.

**Comment by AbdBarho** [comment]
@AzielChamba sorry for the late feedback, I will assign this to you

**Comment by AzielChamba** [comment]
Thanks will finish it soon for you

**Comment by AzielChamba** [comment]
Let me know the file used for this..

**Comment by andreaskoepf** [comment]
Should be fixed.
