### ISSUE TITLE
Convert chain of thought dataset into dialog

### ISSUE THREAD

**Issue by ontocord** [LAION-AI/Open-Assistant#502]
convert a chain of thought dataset into a instruction dataset. “Let’s solve the {problem}. I will walk you through it step by step ||| ok. We’ll solve the {problem} and you will walk me step by step. ||| first, {step 1}. What is the answer for this step? || {answer 1} … || thus, we solved the problem || Therefore {final_answer} is the solution to {problem} that we solved step by step”

See public datasets:
https://github.com/jasonwei20/chain-of-thought-prompting
https://github.com/OpenBioLink/ThoughtSource

See background info:
https://github.com/amazon-science/auto-cot
see idea 6: https://docs.google.com/document/d/13a188pPvqnlvuVa3e_suVz4YO5s-JWeiOOrpp0odImg/edit

**Comment by biddwan09** [comment]
@ontocord can you please assign this issue to me

**Comment by ontocord** [comment]
Thank you. Please let me know if you need anything.

**Comment by ontocord** [comment]
Checking on this

**Comment by biddwan09** [comment]
I am starting it this week. Will give updates or ask if I need anything

**Comment by dctanner** [comment]
Just been reading about ThoughtSource. I'm excited to see this dataset :)

**Comment by andreaskoepf** [comment]
Closing old data issue.
