### ISSUE TITLE
Realistic Data Sample

### ISSUE THREAD

**Issue by Nil-Andreu** [LAION-AI/Open-Assistant#503]
I am wondering which are the source for the messages in order to be them realistic.
Should get it from an existing **database**? Any ideas?

Related issue [here](https://github.com/LAION-AI/Open-Assistant/issues/322).

**Comment by andreaskoepf** [comment]
@danielpatrickhug is currently exploring if @Rallio67's synthetic dialog dataset could be used.

**Comment by ontocord** [comment]
If you have ideas for existing datasources or sets with instruction->response paths, please do mention it ! thank you

**Comment by yk** [comment]
closing this in favor of #315 and #322
