### ISSUE TITLE
Error when requesting new task

### ISSUE THREAD

**Issue by notmd** [LAION-AI/Open-Assistant#506]
![image](https://user-images.githubusercontent.com/33456881/211168044-e5704abc-bebe-465d-8de8-4a1684686ac7.png)

## Step to reproduce
- Open the OpenAPI UI
- Send a request to /tasks endpoint with the following payload
```json
{
  "type": "label_prompter_reply",
  "user": {
    "id": "string",
    "display_name": "string",
    "auth_method": "discord"
  },
  "collective": false
}
```
Maybe there is more `type` facing a similar error.

**Comment by notmd** [comment]
I'm working on this, but it will take time cause I'm not very familiar with Python, also it's 3 AM now. It's quite high priority issue cause it blocks the frontend development. If anyone wants to take it, feel free.

**Comment by andreaskoepf** [comment]
Should be fixed by https://github.com/LAION-AI/Open-Assistant/commit/d910c310c06ee314358a86ad950977984ec7e7cf

**Comment by kostiak** [comment]
@andreaskoepf can you take a look at my PR? Got the fronend working and getting tasks. That's just a temporary fix to eliminate the bottleneck and someone else should probably do the final fix.

**Comment by andreaskoepf** [comment]
It was temporary fixed before the message-ids created new problems. We need tests for the backend API.
