### ISSUE TITLE
`TaskControls` UX improments

### ISSUE THREAD

**Issue by notmd** [LAION-AI/Open-Assistant#510]
- Show both `Next Task` and `Skip` buttons at the same time is very confusing. My proposal is to hide the `Skip` button when the task is submitted.
- Missing loading state when submitting, fetching new, and skipping the task.

I can work on this if the team agrees with the proposal.

**Comment by fozziethebeat** [comment]
From the live call, having to click `Next Task` itself is still kinda confusing.  We might want to considering going so far as to auto-load a new task as soon as the `Submit` completes.  That would eliminate for button hiding and appearing.

What do you think about that alternative fix? Would it feel smoother?

**Comment by notmd** [comment]
What about add a Automatic fetch new task checkbox and turn it on by default?

**Comment by fozziethebeat** [comment]
I think this is something where we can just make a thoughtful decision and make it the default for now.

**Comment by fozziethebeat** [comment]
I think we've adequately fix this issue
