### ISSUE TITLE
Crowd fund for training costs 

### ISSUE THREAD

**Issue by CarloCobal** [LAION-AI/Open-Assistant#515]
Open at one dollar, five dollars, "I'll pitch 100." etc.

**Comment by AbdBarho** [comment]
thanks for the suggestion.

If I am not mistaken, training costs are not an issue for the time being, maybe we can consider this in the future.

**Comment by pevogam** [comment]
What is the planned approach on training? I would gladly lend my RTX 3090 if you need it but IIUC there is no plan for distributed computing here and rather one for using data centers?

**Comment by yk** [comment]
for now, we neither consider crowd-funding, nor distributed training. We'll find a way to get some compute on a big cluster.
