### ISSUE TITLE
Code->Dialog

### ISSUE THREAD

**Issue by ontocord** [LAION-AI/Open-Assistant#516]
Convert various qa->code, english->code datasets to instruction->response, instruction->response,  format.

- https://github.com/Jun-jie-Huang/CoCLR
- https://huggingface.co/datasets/thepurpleowl/codequeries
- https://github.com/LittleYUYU/StackOverflow-Question-Code-Dataset
-  https://github.com/cyoon47/CS1QA
-  https://github.com/jadecxliu/CodeQA 
- https://huggingface.co/datasets/code_search_net
- https://huggingface.co/datasets/codeparrot/github-jupyter-text-code-pairs 

List contributed by @SummerSigh

**Comment by pruksmhc** [comment]
Just to be clear, is the ask here to create (1) add a code -> dialog notebook here: https://github.com/LAION-AI/Open-Assistant/blob/main/notebooks/data-argumentation/EssayRevision.ipynb, (2) run the script from such a notebook across the various code datasets, and (3) upload it somewhere?

Where should the data be uploaded?

**Comment by theblackcat102** [comment]
Here's a few datasets I am using now:

* Text to SQL : https://yale-lily.github.io/spider

   We can generate a prompt with schema, table name and question and ask the model to generate the correct SQL

* CodeXGlue : https://huggingface.co/datasets/code_x_glue_cc_code_refinement
   
   Use the code_x_glue prefix to search in huggingface. There's text to code, code to text, code refinement and a small subset of instruction translation. Datasets is bit noisy in my opinion, so it need more human review.

**Comment by ontocord** [comment]
@pruksmhc  - the first step is to see what types of preprocessing and if we can consolidate across the various sets. And after that, yes to (1), (2) and (3). Upload anywhere on HF hub. We have a OA org, and when you get closer to the final dataset, we can move it there. 

Another dataset we should add - GREAT - note that it uses a special tokens for formatting per @theblackcat102 :
https://huggingface.co/datasets/great_code

If you can work with @m00n, the can help  write some normalization scripts for that, string.replaceAll('<tab>', '\t') -- etc etc.
Just give them a specific goal for normalization.

We can discuss more in discord.

**Comment by SummerSigh** [comment]
@ontocord apologies, im very busy this and next week so ill be offline for a bit. I did want to add this dataset here though

https://github.com/michiyasunaga/DrRepair

**Comment by buttercutter** [comment]
if possible, please also add https://github.com/NYU-MLDA/OpenABC , this will indirectly help human IC chip designers

**Comment by ontocord** [comment]
Sounds great. And no worries @SummerSigh . Thank you  @buttercutter, @theblackcat102 , and @SummerSigh for all the input and help! Go community!

**Comment by ontocord** [comment]
@pruksmhc - this is a very large task. shall we try to recruit more people to do this one?

**Comment by andreaskoepf** [comment]
Closing old data issue.
