### ISSUE TITLE
task_labels table updates are redundant for certain user behaviour

### ISSUE THREAD

**Issue by melvinebenezer** [LAION-AI/Open-Assistant#519]
An update from the frontend **/api/set_label** updates the **task_labels** table (Postgres DB) in the backend. 
multiple clicks to report a messages creates that many entries in the DB

**User reports one tag**
![Screenshot 2023-01-08 at 12 17 58 PM](https://user-images.githubusercontent.com/6395936/211184087-ba72f6cd-5ce7-4a8a-b152-e5ca0cc6f7c6.png)

**User selects another tag and reports**
![Screenshot 2023-01-08 at 12 18 09 PM](https://user-images.githubusercontent.com/6395936/211184120-7f4bd78a-5493-4a11-b8c7-ee1454935828.png)

**The updates in the DB**
![Screenshot 2023-01-08 at 12 11 48 PM](https://user-images.githubusercontent.com/6395936/211184142-cc68ff46-10ee-4b02-8a5b-9722a3ce02f8.png)

**Is this an acceptable behaviour ?**
Concern is while retrieving the flags from the DB after data collection.  The SQL script writer should ensure that the most check flags are retrieved 

### Solution: 
Update the labels for existing message_ids in text_labels table

**Comment by fozziethebeat** [comment]
Tagged this as `backend` and `bug` based on my understanding of what needs fixing.  Also assigned it to you :)

**Comment by melvinebenezer** [comment]
@fozziethebeat we can close this now. Its fixed
