### ISSUE TITLE
Can we use `bigscience/bloomz` that is instructGPT equivalent open-source for training Open-Assistant

### ISSUE THREAD

**Issue by hemangjoshi37a** [LAION-AI/Open-Assistant#522]
Can we consider developing the model on `https://huggingface.co/bigscience/bloomz` as it is open-source and we can directly transfer learn and start training our model on this.

https://huggingface.co/bigscience/bloomz

**Comment by ontocord** [comment]
no - we prefer a different licensing

**Comment by ontocord** [comment]
we could use maybe mtz - i think it's not rail. you have to check.

**Comment by hemangjoshi37a** [comment]
What is `mtz`? I am sorry but I am not awair about this term.

**Comment by yk** [comment]
https://huggingface.co/mT0
