### ISSUE TITLE
Endpoint to list frontend users

### ISSUE THREAD

**Issue by olliestanley** [LAION-AI/Open-Assistant#537]
- `GET` `/frontend_users/`: list users ordered by username, `max_count` (`int`, limit), `ge` (`str`, optional, `>=` comparison on username), `lt` (`str`, optional, `<` comparison on username), `auth_method` (`str`, optional)

**Comment by Vechtomov** [comment]
I need to clarify a few questions:
1) What are the bounds of max_count?
2) What fields should endpoint return?
3) Why do we need to pass api_client_id to the endpoint as it was done in #539?
