### ISSUE TITLE
Endpoints to resolve/modify user by global user_id

### ISSUE THREAD

**Issue by olliestanley** [LAION-AI/Open-Assistant#538]
Untrusted (normal) api_clients must only resolve, view and edit users that were registered by themselves. Trusted api_clients can manage all users. Returned user model contains global OA user id (UUID) and the api_client's 'local' username & auth_method.

- `GET` `/users/{id}`: user by global OA user_id (UUID)
- `PUT` `/users/{id}`: user by user-id (UUID), send json body with attributes to modify (currently only `enabled` bool is supported, setting to false bans user)
- `DELETE` `/users/{id}`: user by user-id (UUID)
- Add `notes` string to the `user` table for admin to note why user was banned

**Comment by callum-gander** [comment]
I could look into this at the weekend if no one wants to take this before then?

**Comment by olliestanley** [comment]
> I could look into this at the weekend if no one wants to take this before then?

It's possible me or someone else will be able to work on this before then but if it's still not assigned to anyone by the weekend/whenever you have time, feel free to drop another comment and we will assign you!
