### ISSUE TITLE
Include dashboard layout in the task pages

### ISSUE THREAD

**Issue by Klotske** [LAION-AI/Open-Assistant#543]
Now the don't have a clear way to exit task solving page, except the icon & account menu.
I think we should include `.getLayout = (page) => getDashboardLayout(page)` for each task page under `/create` `/evaluate` `/label` routes.

**Quick demo:**
![Demo](https://user-images.githubusercontent.com/30481105/211202651-cb3f99da-d17d-449a-a297-b80cb2c90d7e.png)

But need some fixes for the visuals.

**Comment by rsandb** [comment]
you can assign me to this

**Comment by callum-gander** [comment]
If @rsandb doesn't take this, I'm happy to work on this this week

**Comment by yk** [comment]
@AbdBarho related to what we spoke about today
