### ISSUE TITLE
Use SSR to prefetch task information

### ISSUE THREAD

**Issue by Klotske** [LAION-AI/Open-Assistant#551]
One possible fix for #541 might be the use of NextJS's SSR `getServerSideProps` on task pages.
This should simplify things, and also eliminate #343 without workaround PR #393.

We'll still be able to fetch new tasks clientside. SWR has some out-of-the-box [stuff ](https://swr.vercel.app/docs/with-nextjs) for it.

**Comment by yk** [comment]
not discouraging SSR, but afaik going via e.g. `getServerSideProps` is now deprecated

https://beta.nextjs.org/docs/data-fetching/fundamentals#fetching-data-with-server-components

**Comment by fozziethebeat** [comment]
I'm closing this as not planned.  Ideally we'll actually dissolve the web api server side.
