### ISSUE TITLE
Enable category  when using sliders in message reporting popup

### ISSUE THREAD

**Issue by othrayte** [LAION-AI/Open-Assistant#565]
When reporting a message and adding tags to it the user currently has to first check the category on the left then set the value for it. If they try to set the value first nothing happens and it is a little confusing as initially it is not clear that some sliders are enabled and some disabled. If we can enable the category when the slider is used it should make the UX smoother.

![report message sliders](https://user-images.githubusercontent.com/241372/211292380-72e5e266-5686-4bc7-892e-bc329e471d01.gif)

**Comment by AbdBarho** [comment]
I will close this!
