### ISSUE TITLE
Create an FAQ.md

### ISSUE THREAD

**Issue by andrewm4894** [LAION-AI/Open-Assistant#567]
Create an FAQ section and add it to docs site.

- create a `/docs/docs/faq/faq.md` file.
- update `/docs/sidebar.js` to add it to sidebar of docs site. 

I'd be happy to help anyone with this if i don't get to it first,

**Comment by kostiak** [comment]
Things I've seen as frequently asked so far that need to be added there:

- `docker` versions not being up-to-date
- running `docker-compose` instead of `docker compose`
- `pre-commit` - how to install/how to use

**Comment by c00kie123** [comment]
Hey, I am interested in helping out in this!

**Comment by andrewm4894** [comment]
Cool - maybe as a first step see if you can follow the instructions here to get a local version of the docs site up and running: https://github.com/LAION-AI/Open-Assistant/tree/main/docs#docs-site

**Comment by Nil-Andreu** [comment]
Can help in that! If need any help do not hesitate to ping me!

**Comment by kamyardl** [comment]
I wanna improve FAQ.md
make new issues and solve that?
