### ISSUE TITLE
Refactor remaining task pages to use Task.tsx

### ISSUE THREAD

**Issue by othrayte** [LAION-AI/Open-Assistant#569]
The main create and evaluate task pages use a central Task.tsx component but don't of the others don't and this leads to some duplications and inconsistencies. This task aims to unify theremaining task pages to also use the common component. (As discussed in discord)

In addition, as all tasks need the task controls that component should probably be added and setup in Task.tsx rather than in each task type.

**Comment by othrayte** [comment]
I plan on starting on this tomorrow.

**Comment by AbdBarho** [comment]
I have did some clean up of the types in #575

**Comment by othrayte** [comment]
Awesome, thanks for letting me know.

**Comment by AbdBarho** [comment]
can this be closed?

https://github.com/LAION-AI/Open-Assistant/blob/5d1b03b02dce0f87d9ae6f9322c249be5905dfd6/website/src/components/Tasks/Task.tsx#L77-L86
