### ISSUE TITLE
swagger docs for api's?

### ISSUE THREAD

**Issue by andrewm4894** [LAION-AI/Open-Assistant#579]
Do we have anything in place for building swagger or openapi type docs automatically and having them hosted somewhere?

**Comment by andrewm4894** [comment]
maybe some github action that can just dump the `openapi.json` somewhere in the repo?

just thinking in terms of developer docs where someone can just go an read the api docs without having to go near the app frontend.

**Comment by Nil-Andreu** [comment]
> Do we have anything in place for building swagger or openapi type docs automatically and having them hosted somewhere?

FastAPI provides automatically with a Swagger documentation for the backend API. Do you mean to enhace it?
Also I think now they are hosting the docs in a GitHub Pages. @andrewm4894

**Comment by andrewm4894** [comment]
I kind of mean should we not dump the swagger yaml or json. like this: https://github.com/netdata/netdata/blob/master/web/api/netdata-swagger.yaml

such that any dev can then just go somewhere like this: https://editor.swagger.io/?url=https://raw.githubusercontent.com/netdata/netdata/master/web/api/netdata-swagger.yaml

to see the api and not have to go near some app url like http://web.app.open-assistant.io/docs since that's really the end user facing app. just in case it ends up being too clunky to have to actually go into the app frontend to read up about the backend api's. 

i must actually go into the FE and see if i can get to the autogenerated fastapi docs and i'm not even sure if the FE pulls them.

**Comment by andrewm4894** [comment]
yep - having an API section next to the Doc's section in here is kind of what i mean too. 

https://projects.laion.ai/Open-Assistant/

So if we could generate the static files needed and dump them in /doc/docs/api/ and then we could have docusaurus pick them up i'd imagine.

**Comment by andrewm4894** [comment]
made a backend-dev devcontainer here and manually generated some swagger type docs as part of that https://github.com/LAION-AI/Open-Assistant/pull/608

**Comment by andrewm4894** [comment]
adding good first issue label as could be a nice one for someone to try add a GH action to publish `openapi.json` file from the backend into the repo in the `docs/docs/api/` folder.

**Comment by Nil-Andreu** [comment]
> adding good first issue label as could be a nice one for someone to try add a GH action to publish `openapi.json` file from the backend into the repo in the `docs/docs/api/` folder.

It would be on on merge with main?

**Comment by andrewm4894** [comment]
> It would be on on merge with main?

yep this is a good sort of starter example https://github.com/LAION-AI/Open-Assistant/blob/main/.github/workflows/test-api-contract.yaml

would just need to change the steps, and maybe then last step would be to make a PR to merge the updated `openapi.json` back into `docs/docs/api` folder - thats only last slight complex step. maybe something like this https://github.com/marketplace/actions/add-commit

am sure is probably already examples of use cases very similar to what we need out there - uses repo code to make some artifact, either then auto commit that artifact back to repo, or automate a PR so still a human in the loop.

**Comment by bitplane** [comment]
If the docs will go into source control then it might be better to:

1. Have a function that generates the output to some path.
2. Have a test that writes it to a tmpdir and diffs with the docs dir
3. Have a pre-commit hook that overwrites it, if there's changes to the pydantic model code.

Benefits:

* We don't need github to run/test the process
* Keeps complexity/stovepiping out of build pipelines
* If it can't be generated for whatever reason, we're not left in some weird state with a broken pipeline or out-of-date docs

**Comment by andrewm4894** [comment]
@bitplane im just unsure if it's possible to write such a function from just the code alone. my manual steps were to:

1. spin up `backend-dev` devcontainer.
2. run the run_script.sh script to get dev backend up and running.
3. finally a wget command to pull from localhost:8080/api/v1/openapi.json into `docs/docs/api`

i reckon i could get a GH workflow to do this but not sure if is some easier or better way to just extract a `openapi.json` from the code itself. The [fastapi docs](https://fastapi.tiangolo.com/advanced/extending-openapi/) looked a bit scary and complex and unsure how relevant it is in our codebase (probably just that i'm not super familiar with all the moving parts tbh).

**Comment by bitplane** [comment]
@andrewm4894 

I've actually been doing fastapi tests today :)

This ought to do it, just need to pass the app in:

```python
from fastapi.testclient import TestClient

def get_openapi_json(app):

    client = TestClient(app)
    return client.get("/openapi.json").read()
```

**Comment by andrewm4894** [comment]
@bitplane any idea how i would use that? like some sort of `export_openapi.py` file that lives next to `main.py` or ? Was going to have a go at it but unsure of the high level approach i should try take?

**Comment by bitplane** [comment]
@andrewm yeah something like that. It'd need to be in the API project and import the file with `app` in it.

If it were me I'd have 5 unctions in a file:

1. The thing above that returns a string.
2. Function to save some data to a given file path.
3. Parse some arguments using argparse or whatever is cool nowadays, (with `args=sys.argv` as a parameter and a default location set)
4. A `def main(args=sys.argv)` that calls each of them.

Then have a `#!/usr/bin/env python3` at the top and `if __name__ == "__main__":` that runs `main(sys.argv)`. chmod +x the file so you can run it directly.

People might say splitting it up into trivial parts like this is going overboard, but I'm really anal about modularity; functions have tunnel vision, unit tests need no thinking, things like step 2 can be re-used and extended easily (if in future it saves to any URI then we get that here for free).

Just my 2c anyway, the important thing is to just have a python file that dumps the file to disk.

**Comment by andrewm4894** [comment]
turns out we already actually had the openapi.json file as part of the api contract testing workflow so just added a step to save that to right docs folder and step to autocommit if the file has been changed after tests have ran successfully: https://github.com/LAION-AI/Open-Assistant/pull/719
