### ISSUE TITLE
Ensure `create` tasks have non-empty text before submitting

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#592]
When a user accesses any `create` task, they have the ability to submit an empty string.  This violates a requirement from the backend.  We should disable to submit button until they've typed *something*.

**Comment by melvinebenezer** [comment]
I can take this up

**Comment by fozziethebeat** [comment]
@melvinebenezer Have you had a chance to look into this?

**Comment by melvinebenezer** [comment]
@fozziethebeat Yes, will give a fix today
