### ISSUE TITLE
Web Team Meeting Agenda 2023-01-13

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#594]
Agenda Items:
* Update on what's been fixed
  * Shows only the `random` task
  * When user is `banned` they can't fetch any data or post any data
  * Dev instance is updated to give Andreas, Yannic, and Keith admin access
  * Posting interactions always includes `task_id`
  * Message labeling works everywhere
  * Labeling tasks work
  * User dropdown includes link to admin panel (only for admins)
  * Fixing web end2end tests #649 
  * Displaying user's messages in admin view PR #652 
* Update on what's still in progress
  * Suite of UI Improvements
  * Code cleanup: refactoring, removing duplicates, simplifying
* Review any blocking changes
  * Open Question
* Open Discussion
  * Gamification: Leaderboards & Stats.  Timeline?
  * Live model interaction:  How to approach it?  What to log?

**Comment by andreaskoepf** [comment]
@fozziethebeat would be cool if you could show the current state of the admin interface! :-)

**Comment by andrewm4894** [comment]
Hey, would it be possible to record these meetings? would like to try keep up to date in an asynchronous way. If that's not too awkward or creepy :) 

Totally get it if would rather not.

**Comment by fozziethebeat** [comment]
Right now I'm hosting it on Google Meet.  If i can figure out how to record it I will.  In general I agree recording meetings will be helpful for others.  We just need to figure out how...

**Comment by fozziethebeat** [comment]
Here's screenshots of the admin views (once my PR goes in):

<img width="1277" alt="Screenshot 2023-01-13 at 9 48 50 AM" src="https://user-images.githubusercontent.com/398211/212211737-76670ab4-b121-4de1-b0bf-771c81622358.png">
<img width="1272" alt="Screenshot 2023-01-13 at 9 49 02 AM" src="https://user-images.githubusercontent.com/398211/212211753-365949d7-3170-492b-9ac9-0365ec7d1517.png">
