### ISSUE TITLE
Add row-versioning to backend tables

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#599]
Add [simple version counting](https://docs.sqlalchemy.org/en/14/orm/versioning.html) to the backend tables `task`, `text_labels`, `message` & `message_tree_state`.

@melvinebenezer

**Comment by melvinebenezer** [comment]
will take this up

**Comment by andreaskoepf** [comment]
Since this seems not to be possible with SQLModel currently I propose that we use `REPEATABLE READ` isolation model and later implement a retry logic for our transactions.

**Comment by andreaskoepf** [comment]
implemented via #710
