### ISSUE TITLE
add sympy data, lang->math instructions

### ISSUE THREAD

**Issue by ontocord** [LAION-AI/Open-Assistant#602]
sympy https://github.com/sympy/sympy can do symbolic math and has many examples for converting a math problem to equations that can be used by sympy. sympy also has a UI that looks like wolfram alpha called gamma. https://github.com/sympy/sympy_gamma .

task is to:
1. (auto) convert the sympy manuals to isntruction->answer.
2. as part of the answer, simulate a call to sympy. what is 1 cat + 1 cat? the equation for this is 1 + 1. \<work\> _ret = sympy("1+1")\<\/work\> the answer from sympy is 2. The answer is 2 cats. 
3. larger than data augmentation, we could incorporate direct calls to sympy and gamma ui directly in open assistant.

See also https://github.com/arvid220u/saytex

**Comment by ontocord** [comment]
This should have security put back in. Calling direct pythin is an security issue @yk. Whether it's a UI/UX I'm not sure. If we decide to do out of model calls - i don't know where that would go.

**Comment by yk** [comment]
I agree it's a security risk to call python directly, but that way every issue would be labelled security. (e.g. every API endpoint we write needs to authenticate users, every web request we do needs to be encrypted).

I think abetter way: what this issue needs is something like "needs splitting" to be split into multiple tasks, and then one of the tasks can be "effectively sandbox the python call" (once all before-things have been built), and then that can have the security label.

**Comment by ontocord** [comment]
Ok. Soounds good to me. Let's split it - I tink the other issue #603 should be renamed "effective sandbox ..." wdyt?

**Comment by ontocord** [comment]
per above. we should split this 
> larger than data augmentation, we could incorporate direct calls to sympy and gamma ui directly in open assistant.
into issue #603.

**Comment by yk** [comment]
feel free to split as you wish. It's good that people already do investigations into this, I think we'll have to re-visit the field of "assistant interacts with terminal/interpreter/etc" and come up with a basic concept when the time is ready. I think right now it's a bit premature to think about using package manager X or Y, or exactly how to sandbox things and much more important to just figure out what kind of prompts and training are needed to even get a model to effectively interact with these systems.

**Comment by ChristopherKing42** [comment]
FYI (if you're not following the other thread) My suggestion at https://github.com/LAION-AI/Open-Assistant/issues/603#issuecomment-1378013575 for data collection was the following format

```
> assistant_listen
Hi, can you find the square root of fifty for me? I want the exact symbolic value, not an approximation.
> assistant_tell "Sure, the exact value is "
> nix-shell -p python39Packages.sympy
> python -c "import sympy; print(sympy.simplify('sqrt(50)'))"
5*sqrt(2)
> assistant_tell "five times the square root of two. Is there anything else I can help with?"
> assistant_listen
Nope, thanks!
> assistant_tell "Okay, have a good rest of your day!"
```

The idea is that if later we add other python libraries or even libraries from other programming languages (like JavaScript or Ruby), they could also use this format.

**Comment by ontocord** [comment]
@ChristopherKing42 You want to create some sample instructions -> sympy funciton calls?

**Comment by ChristopherKing42** [comment]
@ontocord sure! This doesn't seem too hard.

Are you thinking that I would just collect a few examples, or attempt to generate a large dataset (using randomized templates or Q&A sites)?

**Comment by ontocord** [comment]
Yes and work with others who are doing math stuff. 
Also exmaples in sympy tutorials online too.

**Comment by andreaskoepf** [comment]
Closing old data issue.
