### ISSUE TITLE
Web Cleanup: Use a consistent ID for messages

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#614]
When presenting messages within a task, messages have the field `message_id` that uniquely identifies each message.

When presenting messages within a message timeline or conversation, messages have the field `id` that unique identifies each message.

This is *really* confusing and makes it easy for leave out the correct ID.

We should go through and unify the fields in all the flows so that there's no duplicate fields serving the same purpose.

**Comment by fozziethebeat** [comment]
We also have competing type definitions in different areas for Messages.

**Comment by andreaskoepf** [comment]
> When presenting messages within a task, messages have the field `message_id` that uniquely identifies each message.
> 
> When presenting messages within a message timeline or conversation, messages have the field `id` that unique identifies each message.

Not sure if your comment was related to frontend or backend datastructures. For the backend we had strangely `id` and `message_id` .. both of type UUID .. `message_id` has now been  removed and there is now only `id` (UUID) and `frontend_message_id` (str) in `ConversationMessage`, see https://github.com/LAION-AI/Open-Assistant/blob/f32ec78988210c9d482883cc46540bc8da3a0c5c/oasst-shared/oasst_shared/schemas/protocol.py#L36-L42

**Comment by fozziethebeat** [comment]
I wasn't quite sure where it came from.  Even if this was a backend thing I was going to look at how to consolidate the IDs on the webside so it's less confusing.

The backend always setting just `id` sounds great.  We can go through and cleanup `message_id`.

**Comment by andreaskoepf** [comment]
I am still not sure if `message_id` or just `id` is better. But for now it just `id`. ;-)
