### ISSUE TITLE
Unclear how to get user's messages from the backend to present on the website

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#615]
Right now the backend has the API method `/api/v1/users/{user_id}/messages` which takes a user's uuid created internally by the backend.

But there's not a clear API method for frontends to get that uuid.  `/api/v1/frontend_users/{auth_method}/{username}` exists and returns some data but not the uuid.  I think `/api/v1/frontend_users/{auth_method}/{username}` should and pretty easily could return the uuid.

There is also `/api/v1/frontend_users/{username}/messages` but when testing it with the web's user id or their email, the backend can't find the user.  I'm guessing this works for just discord users.

**Comment by andreaskoepf** [comment]
@fozziethebeat The oasst user-id (uuid) is now returned in the field `user_id`:
```
{
  "id": "1234",
  "display_name": "John Doe",
  "auth_method": "local",
  "user_id": "0d6ff62a-0bea-4c56-ade8-b3e0520a10ce"
}
```

Additionally the frontend_user message endpoints now require auth_method + username:

GET `/api/v1/frontend_users/{auth_method}/{username}/messages`
DELETE `/api/v1/frontend_users/{auth_method}/{username}/messages`
