### ISSUE TITLE
Background generation thread/script for missing message-embeddings

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#634]
Message embeddings are automatically calculated on submission to the backand via the HF feature extraction pipeline, see [tree_manager.py#L365](https://github.com/LAION-AI/Open-Assistant/blob/942148861930cb264284f73a60a13ccfc702ea70/backend/oasst_backend/tree_manager.py#L365). The generation can fail or might be disabled (e.g. `settings.DEBUG_SKIP_EMBEDDING_COMPUTATION` set to True) so that we can end up with messages that don't have an embedding. Eventually we want embeddings for all messages in the db.

- Write a function that generates embeddings (via HF API) for all messages without a corresponding entry in the `message_embedding` table. 
- The function should be run in a background thread upon startup and periodically with a configurable interval (e.g. 60 minutes).
- add a command option to the [backend command-line args](https://github.com/LAION-AI/Open-Assistant/blob/942148861930cb264284f73a60a13ccfc702ea70/backend/main.py#L204-L214) that allows execution solely of the retry-generation process (without fully starting the server).

**Comment by Nil-Andreu** [comment]
Heyy, looks cool! Could I take this one?

**Comment by yk** [comment]
Note: this is not easy. FastAPI is not very "cool" with background tasks / processes running. they have a page on background tasks here: https://fastapi.tiangolo.com/tutorial/background-tasks/
but it's more about tasks that need to be done after handling a request, like sending confirmation emails. They also mention on that page that something like Celery might be necessary, which I'm also tending towards.

**Comment by Nil-Andreu** [comment]
For the company in which i work, we use tasks queue where Celery can be a very good option. I wanted to propose to use the Redis that we have, for the task queue. And we would need a worker as well for completing these tasks (which would be classifying the messages).

**Comment by yk** [comment]
sure, we can use redis. I've made some suboptimal experiences with e.g. `rq`, tasks timing out, etc. but let's see

**Comment by andreaskoepf** [comment]
hm. can't we just use [repeated-tasks](https://fastapi-utils.davidmontague.xyz/user-guide/repeated-tasks/)? e.g. it says

```
repeat_every is safe to use with def functions that perform blocking IO – they are executed in a threadpool (just like def endpoints).
```

**Comment by andreaskoepf** [comment]
Celery will be added by https://github.com/LAION-AI/Open-Assistant/pull/1754
