### ISSUE TITLE
integrating nanoGPT

### ISSUE THREAD

**Issue by Majdoddin** [LAION-AI/Open-Assistant#639]
[karpathy/nanoGPT](https://github.com/karpathy/nanoGPT) is a very simple, still very fast GPT that has just [reproduced GPT-2 (124M)](https://twitter.com/karpathy/status/1613250487838707712), and is improving. Could we us it instead of writing a model from scratch?

**Comment by ontocord** [comment]
we are not training a model from scratch. we are using pretrained models. but nano could be interesting if we want to target very very small devices.

**Comment by gameveloster** [comment]
What kind of pre-trained models are being considered? Are any of these currently close to Chatgpt's ability in producing these really detailed, long responses?

**Comment by ontocord** [comment]
we are not doing large model - at least at present.
