### ISSUE TITLE
Create retry-batch process for Detoxify result (message_toxicity table)

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#640]
- add a batch retry function for detoxify similar to the one requested in https://github.com/LAION-AI/Open-Assistant/issues/634, or combine it with the text-embedding retry code
- add an additional command to the the backend's main to run only the retry-process, similar to what is requested for the text-embedding in  #634

related #416

**Comment by Nil-Andreu** [comment]
Okay, can take this one jointly with the other i believe.

**Comment by andreaskoepf** [comment]
@Nil-Andreu I just saw that you already created this PR https://github.com/LAION-AI/Open-Assistant/pull/553/files

**Comment by Nil-Andreu** [comment]
@andreaskoepf yes, but the batch process is not done yet.

**Comment by andreaskoepf** [comment]
> @andreaskoepf yes, but the batch process is not done yet.

ok, I left some minor comment. Just to clarify: Your approach with the additional toxicity is very good, I will update the issue accordingly.

**Comment by Nil-Andreu** [comment]
> > @andreaskoepf yes, but the batch process is not done yet.
> 
> ok, I left some minor comment. Just to clarify: Your approach with the additional toxicity detail/property-table is very good, I will update the issue accordingly.

Okay thanks! Looking into it right now!

**Comment by melvinebenezer** [comment]
#1754  fixes this
