### ISSUE TITLE
More prominent link to the docs in the Readme

### ISSUE THREAD

**Issue by mashdragon** [LAION-AI/Open-Assistant#641]
It wasn't until I stumbled across the `docs/` folder that I realised there was more documentation than just the Readme file and the web application. I think it would be useful to add a more prominent link to the docs in `README.md`. I see the little green badge is there, but I did not notice it the first ten times I read the Readme.

**Comment by olliestanley** [comment]
@mashdragon This issue seems to have gotten lost a bit but if you'd like to make a PR adding a suitable link that would be great!

**Comment by andrewm4894** [comment]
Made this to help visibility a bit more

https://github.com/LAION-AI/Open-Assistant/pull/1277

**Comment by jaivanti** [comment]
Is this issue still open. I would like to work on this part of documentation

**Comment by olliestanley** [comment]
#1277 is merged now so I think this particular issue is resolved, but if you have other ideas for the documentation feel free to raise an issue and work on them @jaivanti
