### ISSUE TITLE
Use backtranslation to create more instructions from xp3

### ISSUE THREAD

**Issue by ontocord** [LAION-AI/Open-Assistant#644]
Use m2m100, miriammt or any other translation model to conver the non-english portions of xp3 to english. While some or most of these already have their english counterpart, the translation back will give paraphrasing and varations. https://huggingface.co/datasets/bigscience/xP3

**Comment by pruksmhc** [comment]
Looking a bit into this. I want to call out that this does not make sensefor certain tasks in xP3, such as this:
"Entiende cuándo es mejor usar Zamzar. Abre Zamzar. Haz clic en Choose Files… (elegir archivos). Selecciona tu archivo MSG. Haz clic en Abrir. Haz clic en el cuadro desplegable "Convert files to" (convertir archivos a). Haz clic en pdf. Ingresa tu dirección de correo electrónico. Haz clic en Convert (convertir). Abre la página del archivo MSG que convertiste. Descarga el archivo PDF convertido. Descarga los archivos adjuntos. I'm interested in that, but I only have a few mins. Can you give me at most the first 500 characters of a detailed explanation in English about that?" -> label: English explanation

**Comment by ontocord** [comment]
thank you @pruksmhc. lmk if you want to take this one on.

**Comment by pruksmhc** [comment]
@ontocord I can take on the WikiLingua dataset, which is part of xP3. https://arxiv.org/abs/2010.03093
This would be a set of 'how to' data, which has the below language distribution. 

<img width="391" alt="Screen Shot 2023-01-22 at 3 39 27 PM" src="https://user-images.githubusercontent.com/10094008/213946702-e0c889cf-e48e-454d-9c63-ba5a06133b5f.png">

**Comment by andreaskoepf** [comment]
Closing old data issue.
