### ISSUE TITLE
Setup a consistent path scheme for tasks on the website

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#65]
We should have a sensible hierarchy that will keep urls consistent.

I'm thinking something like:
*  `/create/[task_type]` for anything where someone has to write free-form responses (namely where the update type is `text_reply_to_post`).
* `/evaluate/[task_type]` for anything where someone has to rate or rank a response.

**Comment by jasonmhead** [comment]
If we can define input goals I could help develop and document.

At a higher level it could be good to use the OpenAPI standard for the webside of things too perhaps and use tools like https://openapi-generator.tech/

**Comment by fozziethebeat** [comment]
I think this is almost done with a PR i have in review.  This was more just to ensure we have some documentation and simpler URL patterns for the client side.
