### ISSUE TITLE
we maybe need to try make it clearer for contributors to use a feature branch from their own fork

### ISSUE THREAD

**Issue by andrewm4894** [LAION-AI/Open-Assistant#657]
have seen a few PR's coming from some `ghuser/Open-Assistant:main` branches that look a bit off for whatever reason and change lots of stuff. 

i think if we need to we should make it clearer in docs that people should work on feature branches in their fork and keep their main just a updated version of upstream/main so ideally we want PRs like

`LAION-AI/Open-Assistant:main` <- `your-gh-username/Open-Assistant:my-cool-feature-branch`

if i get to this i can try update docs and maybe even make an example feature branch and draft PR from it that we can use as a sort of reference so help avoid new contributors getting mixed up or their PR's ending up a little strange and hard to try clean up. 

my example feature branch
https://github.com/andrewm4894/Open-Assistant/tree/my-example-feature-branch

example url to compare your feature branch to upstream/main (here you can see the changes that will be part of your PR if you make one)
https://github.com/LAION-AI/Open-Assistant/compare/main...andrewm4894:Open-Assistant:my-example-feature-branch

my example PR
https://github.com/LAION-AI/Open-Assistant/pull/658

**Comment by andrewm4894** [comment]
smallish PR here to try help a bit or make it harder for users to get too messed up on their `main` : https://github.com/LAION-AI/Open-Assistant/pull/659

**Comment by olliestanley** [comment]
With #659 merged I think we can close this
