### ISSUE TITLE
Adding CodeInstructor to data_augment.py

### ISSUE THREAD

**Issue by finitearth** [LAION-AI/Open-Assistant#660]
Adding @Graverman-dev 's Code for creating Instruction -> Code - Pairs (https://github.com/LAION-AI/Open-Assistant/pull/629) to data_augment.py, using classes, as in https://github.com/LAION-AI/Open-Assistant/pull/570 .

Would be happy to take over this issue. Could you also add https://github.com/PascalKnoll ? He will be working together with me

**Comment by ontocord** [comment]
@finitearth and @PascalKnoll! Welcome

**Comment by ontocord** [comment]
For some strange reason - i can't assign to pascal in the assignees. he's not showing up.

**Comment by PascalKnoll** [comment]
> For some strange reason - i can't assign to pascal in the assignees. he's not showing up.

Maybe I just need to comment? Could you try again? 👯

**Comment by ontocord** [comment]
Works!
