### ISSUE TITLE
Optimize answer submission flow for review

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#671]
Right now when a user hits the `submit` button the answer is submitted immediately.  It's possible for the user to change their answer and trigger a new submit that will fail.  They then have to click a `next` button.

We should improve this in two steps:
1) First, remove the `next` button and fetch a new task immediately after submission.  This removes the ability to edit a task that's already been answered and enter into a failure state.
2) Add a `review` button.  When a user writes their answer, they first hit `review` to lock their answer.  They can either revert to an edit mode (with an `edit` button somewhere) or the can `submit` to send the answer and fetch a new task.

**Comment by othrayte** [comment]
I'll take this on if available.

**Comment by othrayte** [comment]
I think we have completed this and can close it.
