### ISSUE TITLE
Run the ranked-pairs algorithm on collected rankings and store the results in the db

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#674]
When a message tree enters the `ready_for_scoring` state the ranked [pairs algorithm](https://github.com/LAION-AI/Open-Assistant/blob/main/scripts/postprocessing/rankings.py) should be run to generate the aggregated order of children (replies) of all parents (messages) that have at least two children (replies). We already have a function [query_tree_ranking_results(self, message_tree_id: UUID) -> dict[UUID, list[MessageReaction]]](https://github.com/LAION-AI/Open-Assistant/blob/5d1b03b02dce0f87d9ae6f9322c249be5905dfd6/backend/oasst_backend/tree_manager.py#L736) that returns all the ranking results for a message tree from the db. The ranked pairs algorithms needs to be run for each returned children-list. A new `rank` field should be added to the `message` in which we store the ranking result (index) of the message among its siblings.

As soon as the ranking have been calculated we can assign points to the "rankers" depending on the distance of their proposed ranking and the final order (allowing some slack). (Depending on the state of the rest of the gamification system the points assigment process could be done as part of this issue or new issue should be created when ranks are in the DB.)

**Comment by danielpatrickhug** [comment]
closing this #786
