### ISSUE TITLE
Add a link to the docs for every task type

### ISSUE THREAD

**Issue by AbdBarho** [LAION-AI/Open-Assistant#676]
In case the users have questions about a certain task, they can click a link that open the corresponding page from https://projects.laion.ai/Open-Assistant/

Tasks:
* create a documentation page for a task
* link it from website

**Comment by c00kie123** [comment]
Hey, I am interested!

**Comment by Safiullah-98** [comment]
hey is it solved yet ? i am interested

**Comment by AbdBarho** [comment]
@Safiullah-98 I can also assign you as well, there are 9 tasks so you can share the work with @c00kie123.

**Comment by andrewm4894** [comment]
I can help if anyone runs into any issues getting docs site to work locally for testing or anything. Just @ me if needed.

**Comment by andrewm4894** [comment]
here is a PR that adds a tasks section to the docs site. It can be followed on then with a PR to add the links in the app for each type of task. https://github.com/LAION-AI/Open-Assistant/pull/715

**Comment by fozziethebeat** [comment]
I'm going to setup the basic webside presentation for this.  I'll leave it up to others to create documentation pages we can link to for all tasks (and ensure they're comprehensive).

**Comment by andrewm4894** [comment]
Cool I doc pages live under here, I'll see if I can hook them up on relevant parts of the web forms components etc

https://laion-ai.github.io/Open-Assistant/docs/tasks

**Comment by fozziethebeat** [comment]
Ive got them linked on the website.  The remaining work is to improve the documentation for each task and make sure each task type has docs (when checking I see just 4 tasks covered and the details are pretty sparse).  Then it'll be easy to update a small config file with the new URLs

**Comment by AbdBarho** [comment]
This seems to be finished, we have links for all tasks and the guidelines are updated.
