### ISSUE TITLE
Fix expand button for long texts in ranking tasks

### ISSUE THREAD

**Issue by AbdBarho** [LAION-AI/Open-Assistant#685]
The three dots here should be a button that expands to show the entire content.

![image](https://user-images.githubusercontent.com/24505302/212347332-463dfc20-a651-4f06-a4da-baf0eaa6d675.png)

Currently it is not functioning

**Comment by othrayte** [comment]
I think it does have an implementation that shows the full text but at the moment I find I have to click and lot (and quickly) on the "..." to open the "Full Text" popup, and again on the popup's "x" to close it.

![dot-dot-dot-fulltext](https://user-images.githubusercontent.com/241372/212448810-f53cec61-5931-47b3-92a2-6015b56d3c58.gif)

**Comment by othrayte** [comment]
Also, I didn't realize what was happening at the time but you can see in that GIF that if you drag (on) the modal dialog the items move.

**Comment by othrayte** [comment]
The fix for this is simple, turns out it was something that I had looked into previously, I'll raise a PR in a moment.

**Comment by AbdBarho** [comment]
I believe we can close this now!
