### ISSUE TITLE
Clicking on checkboxes resets prompt rating

### ISSUE THREAD

**Issue by lainisourgod** [LAION-AI/Open-Assistant#70]
Hi!

I'm testing `http://localhost:3000/grading/grade-output#` page. 

1. Click on rating button (e.g. `3`)
2. It gets highlighted with blue border
3. Check the box (e.g. `Contains violent content`)
4. Highlighting on button `3` disappears

https://user-images.githubusercontent.com/24773652/209576495-aadb281d-bd92-45c4-af25-4682c4e5f310.mp4

I think this is a bug, and highlighting should stay. Now it creates a feeling that if I submit, my rating won't be included.

**Comment by yk** [comment]
yes, looks like the blue highlight is just the focus coming from the browser, we should ideally add our own "selected" highlight. thanks for reporting

**Comment by fozziethebeat** [comment]
I am likely going to hide the checkbox labelling until the backend is ready for them.  I'll make sure to further accentuate the highlighting too.
