### ISSUE TITLE
Add docs url as link in GitHub 

### ISSUE THREAD

**Issue by andrewm4894** [LAION-AI/Open-Assistant#708]
In addition to the repo description can we add the docs link below as the url for the repo?

https://laion-ai.github.io/Open-Assistant/

Cant make a PR for this one so think would need to be a repo admin who can add it in GitHub. 

Once ready maybe we swap it out later for link to the actual web app, or even use testing url once that's ready if we wanted. 

Just thinking might as well add some url in there for users browsing and just skimming the repo on GitHub.

**Comment by andrewm4894** [comment]
The url GH puts in here is what I'm talking about.

![Screenshot_20230114-125415](https://user-images.githubusercontent.com/2178292/212472560-d734a60e-de5e-4ef1-8602-0a84a103c374.png)

**Comment by andreaskoepf** [comment]
done.
