### ISSUE TITLE
UnifiedQA Data -> Instructions

### ISSUE THREAD

**Issue by vale95ntino** [LAION-AI/Open-Assistant#712]
Follow-up issue to #560 

Expand on the notebook UnifiedQA (notebook/data-argumentation) and try to convert the Q-A pairs into clearer Instruction-Answer pairs.

Proposal for approach:
- Individual workflow for each dataset in UnifiedQA (that is not in xP3 - I don't mind doing xP3 in a second step if no one takes the task, but Id start with UnifiedQA)
- Create multiple templates for each dataset
- Generate the instruction- conversation pairs from the original QA pairs

Question:
- I think its important to have multiple templates for the same task to create a more diverse dataset. Is it an issue if the same QA pair is represented into several Instruction-Response pairs? Or should I try to have a 1-1 match? On one hand we get a larger dataset by having each QA pair mapped to multiple Instruction-Response pairs, but it would also be a very redundant dataset.

**Comment by ontocord** [comment]
Agree on adding diversity! Thank you!

**Comment by vale95ntino** [comment]
Hey guys, sorry that I havent gotten to this yet. Been quite sick but Im feeling better now so I should do a PR next week :)

**Comment by ontocord** [comment]
Hope you feel better :)

**Comment by pruksmhc** [comment]
Seems like the PR is mergerd. Can this be closed? @vale95ntino

**Comment by vale95ntino** [comment]
Yes it can, thank you for noticing, I had forgotten to close it!
