### ISSUE TITLE
Login magic link not working

### ISSUE THREAD

**Issue by erkkimon** [LAION-AI/Open-Assistant#718]
Does anyone else have problem with login magic link? The demo runs well in container and I'm able to login to debug account, but when using email, Open Assistant web UI says the link is sent but nothing appears in email. I have tried multiple emails. Could there be something wrong with external email service or am I doing something wrong?

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/2260825/212495677-92dc29ba-8d17-4326-8113-1928d84658fe.png">

**Comment by Klotske** [comment]
Container has `maildev` instance. It's a fake SMTP server.

Try going to `localhost:1080`. There should be your email.

From `docker-compose.yaml`:
> This fakes an SMTP email server used by website authentication.
> User registration emails can be found by going to localhost:1080 and
> opening the emails listed.

**Comment by yk** [comment]
@erkkimon are you running locally? if yes, please try @Klotske 's solution and let us know whether that works

**Comment by andrewm4894** [comment]
maybe one for the FAQ - i'll look over anything labeled `question` some time next week and update the docs faq

**Comment by erkkimon** [comment]
@Klotske Thanks, this solved my problem. I didn't realize that the email would be found locally. Now it works great and the demo looks wonderful!

**Comment by AbdBarho** [comment]
@erkkimon great! I will close this now, feel free to create another issue if you face any problems.
