### ISSUE TITLE
is release workflow supposed to be running on everything?

### ISSUE THREAD

**Issue by andrewm4894** [LAION-AI/Open-Assistant#720]
just asking in case anything broken - i see it running i think on all changes to main. 

eg for my pr that just updated notebooks:

<img width="749" alt="image" src="https://user-images.githubusercontent.com/2178292/212500712-bbd3b12b-be75-432e-84d0-5eab1ae22713.png">

**Comment by fozziethebeat** [comment]
Is this still an issue?

**Comment by andrewm4894** [comment]
I don't think so. Closing
