### ISSUE TITLE
Create instruction dataset for generating clinical notes

### ISSUE THREAD

**Issue by pruksmhc** [LAION-AI/Open-Assistant#721]
Use MTSamples to create an instruction dataset of note generation given a prompt of the type of patient to create a sample note for. 

Dataset: https://www.kaggle.com/datasets/tboyle10/medicaltranscriptions

**Comment by pruksmhc** [comment]
https://colab.research.google.com/drive/1leWAznUmD0wKj3OuD42pMqrjMGPJJ_07#scrollTo=3b87aad1

**Comment by ontocord** [comment]
PR finished?

**Comment by ontocord** [comment]
i believe this issue is closed base don the PR.
