### ISSUE TITLE
Create Multihop QA Instruction Dataset

### ISSUE THREAD

**Issue by pruksmhc** [LAION-AI/Open-Assistant#725]
Create an instruction dataset for multihop QA:
https://paperswithcode.com/paper/constructing-a-multi-hop-qa-dataset-for

The above dataset is used in papers that explore using LLMs augmented with search (https://ofir.io/self-ask.pdf), but some others are also here: https://arxiv.org/abs/2204.09140

**Comment by ontocord** [comment]
Does anyone want to take this on??
