### ISSUE TITLE
Problem Prevention info: Breadth vs Depth Expansion are of equal importance and presently overlooked. 

### ISSUE THREAD

**Issue by CarloCobal** [LAION-AI/Open-Assistant#733]
Amazing project! Collaborative work done like this is the future. We have the capacity to create a system that can cause scientific revolutions, my assumption is that you are also down to do that. 

I'm going to get into some context of an issue via some quick _history_, the _issue_, then a solution to said issue: 
The Structure of Scientific Revolutions (is a book about the history of science by philosopher Thomas S. Kuhn) references innovation and new great ideas coming from diverse opinions, not continued dialogues as needed in basic science. In other words, new ideas like those we can create with this AI need to come from two places --lapses in theories via an unknown that highlight a problem, and an unexpected connection that solves the problem-- Kuhn showed through this history of scientific revolutions that new game-changing ideas have not historically built on each other. (Case in point this project vs chat-gpt. In this regard I'd place my bet on the future in this project or one like it, rather than the current incumbents of AI.) Instead, he suggests that new ideas come from seemingly distinct connections applied in a new way like this startup mentality+openSource+LLM/GPT. 

Our current OpenAssistant planned data structure incorporates half of this picture. There is a genius branch extension that adds depth to known parameters with the help of google and the human etc, and after the known wiki text data breadth is trained the AI will know ~about the extent of what we know. However, after that we need to ask ourselves if we want this system to extend what knowledge is made available to us without our help. Going from supervised 'basic science' (in the words of Kuhn) to the exploration of an exciting unknown unknown. Specifically, establishing a connection between different genres/ideas to form testable new categories. In some cases this is as straightforward as lowering the threshold between the difference of two things, i.e. X and Y shifting towards a higher similarity score in a classifier. The point being, **a system that relies only on depth expansion will be crippled unless there also exists breadth expansion. In this regard there is a beauty in imperfect classification and a vast use.**

**Comment by yk** [comment]
Hi, thanks for the comment! I'm not really sure I understand you correctly. Our data structures are not meant as portraying depth expansion of knowledge, but they represent the flow of a conversation. Whether one goes into depth or width in knowledge, one still needs to take turns in a conversation. How would you practically adjust the data structures to incorporate what you suggest?

**Comment by maxdata** [comment]
Haha :) Here is how ChatGPT understands from the Author: 
"The author is saying that new ideas and scientific revolutions happen when people think differently and connect things in new ways. Their project, which uses AI and open-source technology, has the potential to make these kinds of new ideas happen. They also say that the project should not only focus on adding more information to what we already know but also explore new areas that we don't know much about."

**Comment by programjames** [comment]
@yk You could determine the similarity between different pieces of information (two possible ways: train a neural net, or use a Markov chain w/ Wikipedia references). Give one piece of information as context, then generate a prompt where the answer relies on the second piece of information. Start from 100% similarity (both pieces of information are the same) and slowly lower it as you train.

**Comment by CarloCobal** [comment]
> Hi, thanks for the comment! I'm not really sure I understand you correctly. Our data structures are not meant as portraying depth expansion of knowledge, but they represent the flow of a conversation. Whether one goes into depth or width in knowledge, one still needs to take turns in a conversation. How would you practically adjust the data structures to incorporate what you suggest?

<img width="1058" alt="Screen Shot 2023-01-18 at 5 23 03 AM" src="https://user-images.githubusercontent.com/66932392/213147093-de8c39c7-740d-46b5-8814-4496aea06942.png">

General e.g. of novelty generator:
Q1: Can you give me a random topic, idea, or thing? 
A: X1

Q2: What’s the edge or forefront problem of topic X1?
A: YZW

Q3: [Back to Q1]
A: X2

Q4: How can X2 help solve YZW?
A: X3 [New child node to be initially verified by human (_ideally_) etc.]

Distillation from idea to definition to functional processes is what I hope we can replicate.

Best,
Quaid

**Comment by CarloCobal** [comment]
Please reopen if need be, that was an accident.

**Comment by CarloCobal** [comment]
I'll get back to you asap.

**Comment by CarloCobal** [comment]
Here's a creative example of a specific process using cgpt:
<img width="422" alt="Screen Shot 2023-01-21 at 10 31 56 PM" src="https://user-images.githubusercontent.com/66932392/213899363-cdc7a92a-9011-48d2-b3bd-d9a21dd40019.png">

**Comment by CarloCobal** [comment]
More broadly:
This is a sort of meshed interpretation of how we compose a paper in the context of how an AI using RL could replicate one version of a knowledge extension process:

@maxdata Cont., one process-dialogue (who's implementation is beyond my pay grade) is found in instances of scientific writing itself. Wherein a prompt engineer can compose an abstract by asking a question that informs us of a state of understanding in relation to said question -- and/or what has previously been done/learned. This is followed by a methods section that attempts to answer that [@edit more #paygrade specifics needed here], a results section & discussion and finally the summary entailing the significance of the results/predicted future directions etc. [E.g. training on scientific papers but actually create novelties with breadth connections and claim verification done by a third party.] This is a basic science approach I suppose. The only difference with non-basic science seems to be the degree of difference between the claim and the conclusion while true.

@yk

**Comment by maxdata** [comment]
At its current stage, a generative model can produce results that resemble a scientific paper, but it is not the same as how a human would write one. For example, the model may be able to generate an answer to the question "How can a quantum computer help create artificial general intelligence (AGI)," but it may not fully capture the complexity and nuance of how a human researcher might approach the topic.

**Comment by CarloCobal** [comment]
Good point and I appreciate the hasty response : )
I just saw the rs that Meta did with the science paper producer. I agree with the results not being valid but that is the point that is improved via RL, so I hope Meta continues their work there. Most of all, I hope that we can gracefully do something similar and better here along those lines. @maxdata

**Comment by CarloCobal** [comment]
> At its current stage, a generative model can produce results that resemble a scientific paper, but it is not the same as how a human would write one. For example, the model may be able to generate an answer to the question "How can a quantum computer help create artificial general intelligence (AGI)," but it may not fully capture the complexity and nuance of how a human researcher might approach the topic.

I suppose that's what the issue is, how do we facilitate grow in the direction of novel attempts at an unknown? What would you recommend in terms of a process?

**Comment by CarloCobal** [comment]
I redact the counter productive example using Cgpt, since the point was that no AI does this. 
For more relevant dialogues check out what Khun wrote. For instance, Darwin and his birds and the new field the spawned from their intersection. Both subgenera's of Darwin himself and the birds existed prior to their engagement but only after the connection of these two data did evolution emerge. @maxdata
