### ISSUE TITLE
Web Meeting Agenda 2023-01-15

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#734]
Agenda:
* Update on what's been fixed 
  * Messages no longer clickable in task view (#667)
  * Simplified task for single spam label tasks (#668)
  * Switched to Review -> Submit flow in tasks (#671)
  * Fetch real leaderboard data (#673 & #739)
  * Better handling of long text in ranking tasks (#685)
  * Link to Github Issues page on 404 and 500 pages (#675)
  * Overhaul of admin page to fetch data from backend with basic pagination and adding notes (#673)
  * Including footer everywhere so users can find TOS and Privacy Policy (#394)
  * First step on showing a getting started panel (#670)
  * Misc Cleanups and UI Improvements (#737 + #729 + #711 + #709 + #695 + #694 + #693)
* Update on what's still in progress 
  * Discuss
* Review any blocking changes 
  * On Dev: Can't label all messages #753
  * On Dev: Dashboard leaderboard is empty: #754
  * On Staging: Secret walk through: #755 + #757
* Open Discussion 
  * Live model interaction: How to approach it? What to log?

**Comment by andreaskoepf** [comment]
Stats from the backend:
- leaderboard endpoints: `/api/v1/leaderboard/{time_frame}`
- per user stats entpoint:  `/api/v1/user/{user_id}/stats`

**Comment by fozziethebeat** [comment]
# New Issues to File
* On dev: updating role fails
* Rank on leaderboard is invalid due to +1
* Scrolling doesn't always work properly in task view (especially on a long ranking task).  Might be due to react or NextJS scrolling features.
* Full Labeling task: showed review button then click lead to a disabled state
* Found a way to enter an error state with the full labeling task when not selecting any labels
* Consider moving the instruction text closer to the actions.
* Consider highlighting which message to focus attention on rather than the whole conversation.
* When fetching task we see the empty task view temporarily.
* Show more leaderboard stats now supported by the backend
* Nice to have: Improve admin user lookup features to find the right user.  The backend supports some minimal searching already.
# Discussion
* When flagging a thing, assumption is that each label defaults to 100% so that when clicking checkbox, no need to update slider.  But can later change slider.  Question: in disabled mode can we change the coloring to indicate nothing is submitted until its clicked.
  * Help buttons don't do anything.  Can they do something with a tooltip?
  * Label rows can be better aligned.
# Upcoming
  * Be able to list some specific tasks such as `Create Prompt` on dashboard.  Pending backend API update that reports available tasks.  It's possible we can show a task on the dashboard but the question could be answered before they fetch a task and then enter into an empty task view.
  * Be able to query the latest actions recorded by the backend (globally and per user) to produce a community news feed.
  * Implement contribution streak tracking (daily, weekly, etc) that can be shown in leaderboard and stats.
  * Better user pagination
  * Export data (not affecting web)
  * Fully implement ranking algorithm (not affecting web)
# Deployment
  * Updating all the secrets
  * Setup postgres database backups
# On Live Model
  * Can setup forward looking UI experience for interacting with a live model.  Big blocker is getting inference working and running somewhere reliable.
  * Will setup secondary method to inject model responses to tasks as new tasks.

**Comment by fozziethebeat** [comment]
Filed a few issues based on the notes.
