### ISSUE TITLE
Migrate `formik` to `react-hook-form`

### ISSUE THREAD

**Issue by notmd** [LAION-AI/Open-Assistant#738]
- Formik is no longer maintained (the last commit was Jan 2021).
- React hook form has a smaller bundle size, better performance, and importantly it's still being maintained by the community.

I can work on this if the team wants.
See: 
[https://blog.logrocket.com/react-hook-form-vs-formik-comparison/](https://blog.logrocket.com/react-hook-form-vs-formik-comparison/)
[https://npmtrends.com/formik-vs-react-hook-form](https://npmtrends.com/formik-vs-react-hook-form)

**Comment by fozziethebeat** [comment]
Sure! I only picked Formik because Chakra listed it as working well with their form components.  A more maintained library is a good reason to switch.
