### ISSUE TITLE
Augment DIVERSE dataset

### ISSUE THREAD

**Issue by olliestanley** [LAION-AI/Open-Assistant#746]
Create script to augment DIVERSE dataset into `instruction, output` pairs

https://github.com/microsoft/CodeT/tree/main/DIVERSE

**Comment by olliestanley** [comment]
@ontocord I am not working on this currently so will leave it unassigned for now in case anyone else wants to take it on, but once I have finished on #745 I will self-assign this if nobody else has

**Comment by ThierryDeruyttere** [comment]
You can assign this to me.

**Comment by ThierryDeruyttere** [comment]
This can be closed as this has been merged into the main branch

**Comment by ontocord** [comment]
Cool - can I see PR?

**Comment by olliestanley** [comment]
> Cool - can I see PR?

It was #784
