### ISSUE TITLE
Add user stats to the account page

### ISSUE THREAD

**Issue by AbdBarho** [LAION-AI/Open-Assistant#747]
From https://github.com/LAION-AI/Open-Assistant/pull/744 it is possible to get stats for every user, add a component to the account page to allow each logged-in user to see their stats.

Question:
* should add the ability to view other user's stats (from the leaderboard)?

**Comment by MostlyGenius** [comment]
can you assign this issue to me?

**Comment by fozziethebeat** [comment]
Common voice has something like the following on their user profile page.  I think this is a good first start.

<img width="1082" alt="Screenshot 2023-01-16 at 1 04 26 PM" src="https://user-images.githubusercontent.com/398211/212596328-784e2be1-2e92-4528-b5cd-0c4f3e54773b.png">

**Comment by realsh9dy** [comment]
can you assign me this issue

**Comment by AbdBarho** [comment]
@realsh9dy gladly!

**Comment by cryptidv** [comment]
Any updates on this?

**Comment by AbdBarho** [comment]
@cryptidv I started working on it
