### ISSUE TITLE
Make a Gradio Demo

### ISSUE THREAD

**Issue by salexashenko** [LAION-AI/Open-Assistant#752]
Make a Gradio demo so that people can easily test the models. Make sure it is password-protected for now.

**Comment by ontocord** [comment]
Thank you!

**Comment by pruksmhc** [comment]
Has there been movement with this? @salexashenko @ontocord ? Have been playing around with Streamlit (Gradio alternative) quite a bit lately so can probably spin this up in an hour or two.

**Comment by salexashenko** [comment]
Oh yeah sorry this has been done for a while, just forgot to  mark the issue. The demo is at https://huggingface.co/spaces/salexashenko/test_237568525 the password is in the discord.
