### ISSUE TITLE
Labeling Task: Not providing labels then reviewing and submitting enters error state

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#763]
When getting a full labeling task it's possible to review something without labeling anything then submitting.  The backend is requiring some labels to be answered and then returns a 500.  At that poin the UI is broken and there's no way to resolve the issue.

For tasks with mandatory answers, we shouldn't switch to review mode until the answer is given.

**Comment by andreaskoepf** [comment]
API for search by display name is: `/api/v1/frontend_users/by_display_name`
For A-Z username or prefix search the `/api/v1/frontend_users/` could be re-used.

**Comment by fozziethebeat** [comment]
I think that was for  #766.  I copied the comment there.

**Comment by fozziethebeat** [comment]
Got a fix I'm preparing
