### ISSUE TITLE
UI Enhancement: Better highlight what the user should do.

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#764]
In our tasks we show all the messages for a conversation.  The user has to do some thinking to understand which message is being ranked, labeled, etc.  We could better highlight the last message in a conversation to call this out.

Further, we can also provide more clear answer instructions closer to the call to action buttons.

**Comment by AbdBarho** [comment]
Related #159 #676  #812

**Comment by fozziethebeat** [comment]
To Verify: Do we have sufficient messages just before the target message?

**Comment by fozziethebeat** [comment]
Looking at this with the message highlighting we have, I think this is sufficient for now.
