### ISSUE TITLE
Admin Enhancement: Make it easier to find specific users

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#766]
The admin view can be improved in two ways:
- More efficient pagination using UUID based cursors
- Add a search bar to search for a user based on their display name (or prefix).  This will reduce search time when there's over 100 users registered.

**Comment by fozziethebeat** [comment]
API for search by display name is: /api/v1/frontend_users/by_display_name
For A-Z username or prefix search the /api/v1/frontend_users/ could be re-used.

**Comment by notmd** [comment]
I'm taking this. About 

> * More efficient pagination using UUID based cursors

Where is the UUID come from?

**Comment by fozziethebeat** [comment]
Great!

The `BackendUser` (and its extension `User`) type specifies `user_id` which is the FastAPI backend's real user id.  It uses UUID v4 (i believe from other PR discussions).

It's available everywhere within `UsersCell.tsx` and is typically included when making calls to the admin API routes.
