### ISSUE TITLE
Header and footer take up a lot of space on laptop

### ISSUE THREAD

**Issue by Vechtomov** [LAION-AI/Open-Assistant#780]
Header and footer take up a lot of space on average laptop screen. 
My screen resolution is 1366x768.

![dashboard](https://user-images.githubusercontent.com/28014244/212763252-c9fe79eb-05ae-4a4a-8857-da4a667530df.png)
![task](https://user-images.githubusercontent.com/28014244/212763266-09e8b27a-3509-4858-bc88-f5881761e063.png)

Maybe they could be moved to the sidebar.

**Comment by fozziethebeat** [comment]
Can you check now? Riley's latest PR made the footer much smaller.

**Comment by Vechtomov** [comment]
Now it's way better.
