### ISSUE TITLE
Exclude certain users from leader board stats

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#783]
- Add a new `stats_enabled` boolean column (default `True`) to the ([User model](https://github.com/LAION-AI/Open-Assistant/blob/main/backend/oasst_backend/models/user.py)) that indicates whether the user should be included in the leader board stats calculation or not (generate alembic migration script `alembic revision --autogenerate -m "..."`).
- modify [UserStatsRepository](https://github.com/LAION-AI/Open-Assistant/blob/main/backend/oasst_backend/user_stats_repository.py) to exclude users that have `stats_enabled == False`
- allow updating `stats_enabled` via REST `PUT` to `/api/v1/users/{user_id}`, see [update_user()](https://github.com/LAION-AI/Open-Assistant/blob/eae8d44f761984b7d926d2a267acd97fa875c942/backend/oasst_backend/api/v1/users.py#L35)

**Comment by akhil-datla** [comment]
@andreaskoepf I am interested in this task.

**Comment by akhil-datla** [comment]
@andreaskoepf I would like to ask some clarifying questions, but I am not able to message on the Discord.

**Comment by akhil-datla** [comment]
When I try generating the alembic migration script, I get this error `ModuleNotFoundError: No module named 'oasst_shared'`.

**Comment by andreaskoepf** [comment]
@akhil-datla please let us know if have time to further work on #785. Otherwise we need to re-assign the task.
