### ISSUE TITLE
using Linguistic Stenography in Open Assistant. 

### ISSUE THREAD

**Issue by SummerSigh** [LAION-AI/Open-Assistant#792]
This issue pertains to the ideas around watermarking Open Assistant generations via Linguistic Stenography. Linguistic Stenography is a field of active research however a few methods have emerged that make me confident that it can be used effectively in identifying Open Assistant generations. This issue isn't going to detail these methods but rather discuss the ethical debate on the side of using Linguistic Stenography. 

In my opinion here are the main benefits: 

1. Preventing plagiarism: Watermarking can help prevent others from using the generated text without proper attribution, which is especially important in academic and professional settings.
2. Identifying false information: Watermarking can also be used to identify fake or misleading information that is generated by Open Assistant, which can help combat misinformation and disinformation.

However I also have the following concerns: 

1. Limited applicability: Watermarking may not be effective in certain contexts, such as when the text is heavily edited or translated.
2. Decreasing efficiency: Watermarking can add an extra step to the text generation process, which can slow down the process and make it less efficient.
2. Complicating collaboration: Watermarking can make it more difficult for multiple users to work together on a project. For example, if part of program is written using Open Assistant, it becomes more difficult to detect which parts of the code were generated by the model. 

I think this is a subject of great discussion, and requires multiple view points so we can properly evaluate if this is something we should pursue further.

**Comment by SummerSigh** [comment]
@ontocord here are some implementations I have tested and know work:

https://github.com/falcondai/lm-steganography
https://github.com/ku-nlp/steganography-with-masked-lm
https://github.com/mickeysjm/StegaText
https://github.com/jumon/himitsu

I personally like steganography-with-masked-lm so I put it up in this Kaggle notebook: 

https://www.kaggle.com/code/summerbreeze11/text-steganograpthy/edit

**Comment by ontocord** [comment]
Thank you for sharing these links!

**Comment by ontocord** [comment]
Following up on this if anyone is interested in exploring this more? Maybe create an API hook into the safety pipeline to steer decoding? And any org can put their own method/callback in there. This could be useful for privately run bots.

**Comment by SummerSigh** [comment]
I’ll take a look at it further. I’ll put my updates here as I go.
