### ISSUE TITLE
Username is reset when page is refreshed for E-mail users

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#797]
Username is reset to E-Mail address on page refresh.

Reproduction: 
1. Set a username (DisplayName) via account settings 
2. Navigate to Dashboard (now correctly shows selected user name)
3. Refresh page by pressing F5
4. Username disappeared and E-Mail address is shown. When navigating to Account settings it says "No username".

**Comment by fozziethebeat** [comment]
This was due to my misunderstanding of how NextAuth prepares the session.  Will be fixed soon.
