### ISSUE TITLE
white-space not properly shown

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#801]
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/858040/212912296-c5271172-f24e-44d2-a4d6-3bbb78943711.png">

the original text has newlines, which are not shown here

**Comment by AbdBarho** [comment]
https://github.com/LAION-AI/Open-Assistant/commit/51a1d9a841ab733f5813b16925b0ecd144a324f0
