### ISSUE TITLE
Accepting critique dataset

### ISSUE THREAD

**Issue by ontocord** [LAION-AI/Open-Assistant#802]
We would like to create a dialog dataset where the bot answers some question, and the user corrects that answer, and the bot acknowledges the correction and makes the correction.

Example 1.
User: Write me a program to do X
Rosey:
the bot generates software code (we use bugger to inject an error -cc @furlat).  
User: There appears to be a mistake with the comparison of X <= Y.
Rosey:
You are right. the comparison should by x==y because .....  Here is the corrected code.
the code the bot would generated if we didn't use bugger.

Example 2.
Data mining wikipdia for instructions.
User: What is anarchism? <-- main topic
Rosey: Anarchism is a political philosophy and movement that is acceptance [we do an antonym replacement of the word "skepticism"] of all justifications for authority...
User: Are you sure it's about acceptance of all authority?
Rosey: You are right. It is the 'skepticism' of all authority. Here's the corrected answer: The actual wikipedia text

**Comment by ontocord** [comment]
Example 3:
Data mine math help websites or inject math errors directly into equations.
User: Solve me a problem X.
Rosey: Sure, the answer is Y_1.
User: I don' think that's right. I think the answer is Z.
Rosey: You are right. I was reading the problem as X_1 (injeceted error). Here's the correct answer: Y.

**Comment by fabraz** [comment]
It seems a little bit closer to the other issue I'm in charge of. I could start this right after the other.

**Comment by ontocord** [comment]
Ok. I have assigned to you :)

**Comment by ontocord** [comment]
@fabraz - checking in on this?

**Comment by Bobberson3108** [comment]
Could you also include dialogs where the user critique is incorrect and the bot does not make a correction

**Comment by andreaskoepf** [comment]
Closing old data issue.
