### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by sanagno** [LAION-AI/Open-Assistant#811]
Would be nice to have a shortcut, something like Ctrl/Cmd+Enter to press Review and Submit.

**Comment by fozziethebeat** [comment]
This is a nice to have.  If anyone wants to implement this for all the task types, please say so and I'll assign the issue.

**Comment by cooperaustinj** [comment]
Please assign to me. I just implemented this one quickly as I wanted to dig into the code. If there's disagreement with the solution, we can work out how better to handle it.

**Comment by DigitalDwagon** [comment]
Possible to also have keyboard shortcuts for rating/labeling? It would be amazing to be able to just sit and do it without having to touch the mouse at all

**Comment by fozziethebeat** [comment]
@cooperaustinj is working on a change.  It just needs to be merged with recent pull requests

**Comment by cooperaustinj** [comment]
@fozziethebeat do you know how we've been doing localization translations for this project? That's all that's holding up the PR currently.
