### ISSUE TITLE
Add link to prompting guide within the dashboard UI

### ISSUE THREAD

**Issue by Jmete** [LAION-AI/Open-Assistant#812]
It would be helpful to the user to have an easier link to the prompting guide from within the dashboard UI. This would allow them to quickly reference the guide for times when they aren't sure how to respond. Currently, I had to find the docs page, then find the guides, and then go to the prompting guide.

I think reducing the friction for accessing the prompting guide would result in better feedback.

Prompting guide link: https://projects.laion.ai/Open-Assistant/docs/guides/prompting

**Comment by sir-braz** [comment]
Is that in Javascript? Does the user need to click a link and open documents?

**Comment by andreaskoepf** [comment]
> Can I try to do this task?

Yes, sure. I assigned you. Please unassigned yourself in case you decide not to complete it.

**Comment by fozziethebeat** [comment]
Yeah this can easily be a link we present somewhere on the dashboard.  We link to the prompting guide for tasks that don't have task specific guides but the general prompting guide can be more obvious.
