### ISSUE TITLE
[UI] The spam classification task is unclear because of inconsistent UI

### ISSUE THREAD

**Issue by raunak-agarwal** [LAION-AI/Open-Assistant#813]
- It is not clear what the user is supposed to do in case of the spam classification task. 
- If you look at the first screenshot, "This message is spam?" is poorly worded
- The size of the text is inconsistent when compared to other tasks. Compare "This message is spam?" with "Provide the assistant's reply" in screenshot 2. 

![image](https://user-images.githubusercontent.com/24976972/213026250-b37f1fc0-4805-47e7-bb29-1d23c1ea046c.png)

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/24976972/213026947-dc17c636-bcc9-4da9-bb91-068d7a0c76fc.png">

**Comment by othrayte** [comment]
Please see #707, we are still looking to improve this task in that issue. Any comments you can add there would be appreciated.

**Comment by AbdBarho** [comment]
Can we close this?

**Comment by yk** [comment]
just an idea: whenever we ask the user for labels concerning the last message in a conversation, maybe we can highlight that message a bit more (green background or so?) to make it more clear what is meant. maybe this is already tracked somewhere. if yes, just ignore.

**Comment by othrayte** [comment]
@yk, Yep #764. That was also something I tried out in the general labeling task overhaul thread see the screen-cast with this comment https://discord.com/channels/1055935572465700980/1065268675357179924/1065657726631411733.

**Comment by fozziethebeat** [comment]
I'm going to close this given the massive overhaul we've done.  It looks pretty good now and the initial concern feels addressed to me.
