### ISSUE TITLE
Augmenting the prosocial_dialog data for safety pipeline

### ISSUE THREAD

**Issue by ontocord** [LAION-AI/Open-Assistant#817]
We are using this dataset for some of the safety model: https://huggingface.co/datasets/allenai/prosocial-dialog

We need to enhance it with additional data and check for quality in the original dataset.

Now, it has to many false positives.

We can add labels from anthropic red_label, as well as mix in regular instructions to regularize.

We can also include in prompts that tries to illicit misinformation (and also innocent prompts that are hard negatives).

**Comment by ontocord** [comment]
We can also use fewshot to gather this data.

**Comment by MarShaikh** [comment]
Please assign me this issue, I would like to work on it. Thanks!

**Comment by shahules786** [comment]
@ontocord I am interested in doing some experiments on this.

**Comment by ontocord** [comment]
Thank you @shahules786 !

**Comment by shahules786** [comment]
I have raised the PR for this. Augmented dataset can be found here https://huggingface.co/datasets/shahules786/prosocial_augmented
