### ISSUE TITLE
Enforce 2000 character message size limit

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#822]
The backend should reject incoming text-messages (initial prompt, assistant-reply, prompter-reply) that exceed a maximum message size limit with an OasstError (define new code). The limit should be defined in the backend settings with a default value of 2000 characters.

**Comment by oriyonay** [comment]
i can take this as a first issue :)

**Comment by AbdBarho** [comment]
Is there anyway the website knows the value? maybe we can also enforce there, we can definitely hardcode 2000 at the beginning.

**Comment by andreaskoepf** [comment]
> Is there anyway the website knows the value? maybe we can also enforce there, we can definitely hardcode 2000 at the beginning.

Not yet, but I can add a configuration endpoint for trusted_api clients.

**Comment by andreaskoepf** [comment]
@oriyonay we will add the message size limit setting also to the `PublicSettings` model used for `/api/v1/backend_settings/public` .. see   #830

**Comment by oriyonay** [comment]
@andreaskoepf thank you! will take a look in a few hours (after classes :))
