### ISSUE TITLE
auth_method is always shown as `local` for all users

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#827]
In the admin dashboard in the `AUTH METHOD` column currently shows `local` for all users. For users that signed up via discord it should be `discord`. It is not clear to me what `AUTH ID` is - I would expect this to be the discord user id but that should be a number and it is showing there some alphanumeric tokens.

**Comment by fozziethebeat** [comment]
Now that we're done refactoring the website's fetching code, I can do this pretty quickly.  I'll need to see if anything odd breaks with this change.
