### ISSUE TITLE
Add minimal system status page to admin interface

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#828]
Add a new "Status" option to the left command-bar of the website admin interface.

Create a simple page that displays the result of calls to the following backend API endpoints:
1. `/api/v1/tasks/availability` (use dummy user)
2. `/api/v1/stats/`
3. `/api/v1/stats/tree_manager`

Display the result of 3. in a table.

**Comment by ml729** [comment]
I'm working on it.

**Comment by ml729** [comment]
See PR https://github.com/LAION-AI/Open-Assistant/pull/867
