### ISSUE TITLE
Most times I get the same prompt, twice, thrice, or more times.

### ISSUE THREAD

**Issue by Ryan3562** [LAION-AI/Open-Assistant#833]
When rating messages for spam, sometimes I get the same message more than 3 times in a row, which is kind of annoying. Is there any way this could be fixed? Also would it be possible to encourage more unique prompts? Sometimes it's been a while without any new prompts and I then get the same prompts that I am unable to answer.

**Comment by lakshaykc** [comment]
Same. I get duplicates often. We should have a system that tracks what tasks have already been served to a user and then skip those. @andreaskoepf Has anyone proposed this or or already working on it?

**Comment by fozziethebeat** [comment]
I'm pretty sure this is still an open backend task.  I've tagged it appropriately

**Comment by olliestanley** [comment]
Pretty sure this is resolved now. If anyone still has this issue feel free to comment again
