### ISSUE TITLE
🚀💥 Can we launch `Model Extraction Adversarial Attack` against `chatGPT` to gain its weights and biases and model architecture? 💥🚀

### ISSUE THREAD

**Issue by hemangjoshi37a** [LAION-AI/Open-Assistant#835]
Can we launch `Model Extraction Attack` against `chatGPT` to gain its weights and biases and model architecture?

It is one kind of adversarial attack that can be carried out to extract or just copy its model training files or weights and biases.

**Comment by ontocord** [comment]
No. we are not going to use anything extracted from chatgpt.
