### ISSUE TITLE
Annoying automatic scrolling bug

### ISSUE THREAD

**Issue by Mathialist** [LAION-AI/Open-Assistant#845]
On mobile, when I check an option in the report bug section of a message, the frame shift automatically by a bit.
![Screenshot_20230119_122115_Chrome](https://user-images.githubusercontent.com/20498406/213430380-d4106caf-926f-4e9c-b968-db3fc72c3148.jpg)

**Comment by AbdBarho** [comment]
@Mathialist thank you, we have some other problems on mobile we need to also work on soon, #809

**Comment by notmd** [comment]
I noticed this bug a few days ago too but I couldn't reproduce it now. Is it fixed?

**Comment by fozziethebeat** [comment]
We've changed the flagging UI quite radically.  I'm going to close this as fixed given that its much more concise now.
