### ISSUE TITLE
Consider use one type of icon

### ISSUE THREAD

**Issue by notmd** [LAION-AI/Open-Assistant#849]
Currently, we are using both Font Awesome icon and Feather icon which may lead to inconsistent UI. We should only use one of them. Feather is taken about 70% of usage now. 
If we want to you Feather I suggest we migrate to [Lucide](https://github.com/lucide-icons/lucide) which is a fork of Feather (Feather is no longer being maintained). This is not necessary for now cause we don't need too many icons.

**Comment by fozziethebeat** [comment]
Where are we using Feather Icon?  From my reviews I've only seen (and only encouraged) React Icon.

**Comment by fozziethebeat** [comment]
Oh, after looking more carefully at how we're using react icons, we're using `fi` which is for Feather Icons.  The challenge with any of these icon sets is that none of them are perfectly comprehensive.

In general I'd like to just depend on one library (`react-icons`) and pick from one to two icon sets from that library.

Perhaps the way to do this is to list out the various icon needs we think we need and then someone look through the options `react-icons` provides and recommends a single icon set that covers our needs.

**Comment by fozziethebeat** [comment]
Icons we use:

* Feather:
  * `FiSun`: For dark mode switcher
  * `FiHelpCircle`: For help button in task header
  * `FiAlertCircle`: For message flagging button
  * `FiBarChart2`: Leaderboard sidemenu option
  * `FiLayout`: Dashboard sidement option
  * `FiMessageSquare`: Messages sidemenu option 
  * `FiUsers`: Admin User sidemenu option
  * `FiEdit2`: Edit button in task controls
  * `FiAlertTriangle`: Report a bug button for empty state.  Also to report a bug
  * `FiSettings`: Settings option in dropdown menu
  * `FiShield`: Admin option in dropdown menu

* Font Awesome
  * `FaDiscord`: CTA on landing page for discord.  Discord signin
  * `FaGithub`: CTA on landing page for discord
  * `FaEnvelope`: Email login button
  * `FaUser`: Sign in button

* RX
  * `RxDragHandleDots2`: Drag and Drop handle

* Material Design
  * `MdOutlineEdit`: Edit button for user account page

**Comment by fozziethebeat** [comment]
I looked through all these use cases and I think lucide is a good option to replace all our icon usage.  They have replacements for everything we use except for one case: Discord.

I suggest we solve the discord problem by:
1. Switch all icons to use one of the options found in `lucide-react`
2. Keep `FaDiscord` for now
3. Someone contribute a Discord icon to Lucide
4. Use the Lucide discord icon.
5. Finally remove `react-icons` everywhere

**Comment by fozziethebeat** [comment]
This is a pretty straight forward open issue for anyone that wants to take it on.

**Comment by fozziethebeat** [comment]
Also, to be a little funny, I actively encourage someone to figure out how we can use the [wheat-off](https://lucide.dev/icon/wheat-off) icon in a way that makes sense.  I'm amused by that icon existing.

**Comment by notmd** [comment]
> I looked through all these use cases and I think lucide is a good option to replace all our icon usage. They have replacements for everything we use except for one case: Discord.
> 
> I suggest we solve the discord problem by:
> 
> 1. Switch all icons to use one of the options found in `lucide-react`
> 2. Keep `FaDiscord` for now
> 3. Someone contribute a Discord icon to Lucide
> 4. Use the Lucide discord icon.
> 5. Finally remove `react-icons` everywhere

I will send a PR to migrate to lucide

**Comment by notmd** [comment]
> 

Maybe just copy FaDiscord as a component in our code base and remove react-icons completely?

**Comment by fozziethebeat** [comment]
Instead of copying the FaDiscord logo, we could copy Discord's [official svg](https://discord.com/branding) and use that to remove `react-icons`.
