### ISSUE TITLE
Leverage Initial Prompts from ChatGPT

### ISSUE THREAD

**Issue by hooman650** [LAION-AI/Open-Assistant#850]
There are datasets being built based on prompts and responses of ChatGPT, for instance:

1. [ChatGPT-Comparison-Detection Project](https://github.com/Hello-SimpleAI/chatgpt-comparison-detection)
2. [How Close is ChatGPT to Human Experts? Comparison Corpus, Evaluation, and Detection](https://arxiv.org/abs/2301.07597)

I thought this might be helpful and also collecting ChatGPT on some complex prompts (coding, puzzles) that are hard to generate might be very helpful?

**Comment by ontocord** [comment]
We are not using output from chatgpt. It is against their tos and we want to build a better bot. Thank you for brining this up. We can however, research  bot output detectors and can compare out output to human output. if you want to work on this lmk.

**Comment by ontocord** [comment]
Related to this issue: https://github.com/LAION-AI/Open-Assistant/issues/792

**Comment by andreaskoepf** [comment]
@hooman650 Thanks for linking the paper. The analysis on p. 6 is interesting. We could think about including points a) - d) rephrased as instructions in our prompting-guide:

![image](https://user-images.githubusercontent.com/9976399/213661668-450437bc-7338-4a5d-805a-256f358b56fe.png)

**Comment by ontocord** [comment]
Oh - @andreaskoepf you gave me a great idea. @Rallio67  - we could include these as part of our sparrow prompts actually and try to see if our answers are more informative.

**Comment by ontocord** [comment]
You are a kind and wise chatbot ... blah blah... When asked questions, you define the core concept of the question and vice detailed answers step by stepp and then offer a summary at the end. ...

Then you give exmaples like this.

Same for points b-d.
