### ISSUE TITLE
Allow user to set their preferred language on web

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#854]
A user should be able to set their preferred language.  Once it's set, we should send that anytime the user requests a task or submits an answer so that the backend can ensure tasks fit within the user's requested language.

**Comment by andreaskoepf** [comment]
I am making the necessary changes in the backend.

**Comment by fozziethebeat** [comment]
After we fix #875 I'll be able to prepare a web PR.

We'll do this by:
1.  Adding a little language selector to the header
2. Updating the `NEXT_LOCALE` cookie with the value to keep it saved across page visits
3. Extract `NEXT_LOCALE` when fetching tasks or submitting answers.

This should work pretty smoothly and allow us to avoid having to store anything in a database.  It also seems to be the recommended solution by NextJS
