### ISSUE TITLE
Simplify message flagging

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#855]
A user should be able to first select a simple option: Upvote or Flag.  If the user flags a message or task, we then list a small set of common flagging reasons.  By making this easier we should hopefully make it easier to catch low quality tasks or messages that made it past the spam flagging stage.

**Comment by AbdBarho** [comment]
Implemented in #952 right?

**Comment by fozziethebeat** [comment]
Yes!
