### ISSUE TITLE
Acquire StrategyQA human data in OA format

### ISSUE THREAD

**Issue by olliestanley** [LAION-AI/Open-Assistant#864]
This is a follow-on from #784. We want to acquire the high quality question-answer pairs for logical reasoning. This data is under MIT License.

https://allenai.org/data/strategyqa

CC: @Rallio67

**Comment by ontocord** [comment]
oh - i see you didn't assign to youself, sorry about that. whoever wants to take this on, let us know.

**Comment by satani99** [comment]
I'd like to take this task.

**Comment by andreaskoepf** [comment]
Closing old data issue.
