### ISSUE TITLE
Write instructions and examples for integration tests of the website

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#87]
we want to run integration tests of the entire stack: backend + nextjs frontend. this requires pulling both up, including possibly a temporary postgres database for each, initializing the databases, and running tests against the system.

make a plan on how to achieve this, then implement a few examples and write down instructions for people who want to write their own integration tests.

One suggestion is to use pytest with a docker-compose plugin, but other possibilities exist.

**Comment by fozziethebeat** [comment]
We've got a suite of end to end and contract tests with some documentation.  We can file specific bugs for improvements as needed.
