### ISSUE TITLE
Website throwing hydration issues due to localization changes

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#870]
I'm seeing https://nextjs.org/docs/messages/react-hydration-error type issues anytime I try to fetch a task and on the email signin verify page.

**Comment by fozziethebeat** [comment]
@rjmacarthy Can you fix this asap?

**Comment by rjmacarthy** [comment]
> @rjmacarthy Can you fix this asap?

I see that `getDefaultStaticProps` is missing on these pages that should fix it.

**Comment by AbdBarho** [comment]
fixed in #873
