### ISSUE TITLE
Allow the user to set a response style

### ISSUE THREAD

**Issue by Sobsz** [LAION-AI/Open-Assistant#871]
This may seem unnecessary, as e.g. ChatGPT can already emulate styles when asked. However, the current crowdsourced data consists of a mixture of styles, which may seem jarring to users. One option is to have contributors stick to one style, but not everyone is comfortable with writing professional-sounding responses, and first-class support for other styles could be a selling point for OA.

I can think of 3 main response styles:
- **formal** - as seen in ChatGPT; few contractions, long-winded explanations
- **casual** - as seen in the easter egg responses for Siri/Alexa/Cortana/etc; friendly, witty, exclamation marks, might even have a favorite color
- **terse** (struggling to settle on a name for this) - as seen in InstructGPT; just provides the response with no elaboration

The crowdsourced data could then either be categorized at time of writing ("please use this style") or tagged later ("what style does this match?").

<details>
<summary>Low-effort mockups</summary>

![in writing phase](https://user-images.githubusercontent.com/18291848/213839693-5fd9303f-47f6-49d5-a418-3bfa3be60369.png)

![in tagging phase](https://user-images.githubusercontent.com/18291848/213839698-e9160838-6058-4523-b628-0eb9647d8dfe.png)

</details>

Additionally, external datasets could be tagged with style too; for example, [math_dataset](https://huggingface.co/datasets/math_dataset) would be "terse", [competition_math](https://huggingface.co/datasets/competition_math) would be "formal", and the Khan Academy subset of [AMPS](https://github.com/hendrycks/math) would be "casual".

It may be desirable to assign a pre-prompt (or a set thereof) to each style, then allow the user to customize it to create a custom style. However, I'm not sure if it would generalize well enough for that to work well. Prompt tuning, perhaps? Few-shot?

**Comment by ontocord** [comment]
I think this is both a modeling issue and a data issue. Maybe we can break off:

Additionally, external datasets could be tagged with style too; for example, [math_dataset](https://huggingface.co/datasets/math_dataset) would be "terse", [competition_math](https://huggingface.co/datasets/competition_math) would be "formal", and the Khan Academy subset of [AMPS](https://github.com/hendrycks/math) would be "casual".

Into it's own issue?

**Comment by Sobsz** [comment]
I didn't realize until now that the website has a Serious vs. Humorous label axis, which isn't *quite* the same as formal vs. casual, but is close enough to matter. This leaves the terse style, which I'm not sure if people even want?

My current idea is that the model could be explicitly trained to be good at copying the style from a few-shot prompt, by adding random answers from the same user (or the same dataset) into the context. This would make it easier for end users to create their own styles in a manner similar to character.ai.

**Comment by lainisourgod** [comment]
@Sobsz 
> terse style, which I'm not sure if people even want?

I guess it may be plausible in some not-so-chat-oriented contexts e.g. when generating legal documents or summarizations. Also from my experience chatting with ChatGPT I wish it would have a toggle like "be less watery" :).

**Comment by ontocord** [comment]
@Sobsz do you have time to work on this issue? Can you put together a plan to collect data and train for styles? If not, we can try to get more people involved. It's a great idea.

**Comment by Sobsz** [comment]
After some thought, I'm not sure if data collection would even be necessary. In my experience, LLMs are pretty good at few-shot style emulation without being explicitly trained to do so. This means we could make this a purely client-side feature: customizable prompts that are automatically prepended before each chat.

One disadvantage is that (AFAIK) a larger context for takes up more resources for GPT-based models, so it might still be beneficial resource-wise to train the model to follow short preludes like `Style: Formal`, with the data for that collected from highly-rated responses with a Serious-Humorous score under some threshold.

**Comment by andreaskoepf** [comment]
Experiments in this direction were conducted via system prompts & text labels, see [sampling report](https://open-assistant.github.io/oasst-model-eval/?f=https%3A%2F%2Fraw.githubusercontent.com%2FOpen-Assistant%2Foasst-model-eval%2Fmain%2Fsampling_reports%2Foasst-sft%2F2023-05-15_OpenAssistant_llama-30b-sft-v8_2-2_4k-steps-system_sampling_system_profile.json) & [sampling report2](https://open-assistant.github.io/oasst-model-eval/?f=https%3A%2F%2Fraw.githubusercontent.com%2FOpen-Assistant%2Foasst-model-eval%2Fmain%2Fsampling_reports%2Foasst-sft%2F2023-05-15_OpenAssistant_llama-30b-sft-v8_2-2_4k-steps-system_sampling_system_profile2.json).
