### ISSUE TITLE
Create Explain XKCD dataset

### ISSUE THREAD

**Issue by Sobsz** [LAION-AI/Open-Assistant#874]
[explain xkcd](https://www.explainxkcd.com/wiki/index.php/Main_Page) is a wiki containing very thorough explanations of the comic series [xkcd](https://xkcd.com/). The proposed dataset would contain the transcript of the comic as the question and the explanation as the answer. The explanations are [licensed under CC BY-SA 3.0](https://www.explainxkcd.com/wiki/index.php/explain_xkcd:Copyrights); the comics themselves are [CC BY-NC 2.5](https://xkcd.com/license.html), but that shouldn't pose much of an issue, as the network wouldn't be trained to generate them or their transcripts.

The data can be easily [exported](https://www.explainxkcd.com/wiki/index.php/Special:Export), with the request being `Category:All comics`. The resulting format is wikitext with consistent heading titles marking the explanation and transcripts. There are some custom templates in use (e.g. `{{w}}` for Wikipedia links), but they can be exported and expanded locally.

The main issue I can think of is the constant references to other xkcd comics within the explanations; I think it would be best to remove them, though it might require some manual work to ensure that the surrounding text still makes sense after the removal.

EDIT: It appears that [a similar dataset already exists](https://huggingface.co/datasets/olivierdehaene/xkcd), but it seems rather low-quality, e.g. the `explanation` column also contains transcripts.

**Comment by ontocord** [comment]
This is a very fun dataset!

**Comment by maw501** [comment]
Hey @Sobsz, would you like any help with this issue? I'm new around here and this feels like a good issue to get familiar with parts of the SFT pipeline. Let me know if I can assist in any way

**Comment by andreaskoepf** [comment]
Closing old data issue.
