### ISSUE TITLE
Create homework-lab essays dataset

### ISSUE THREAD

**Issue by Vechtomov** [LAION-AI/Open-Assistant#877]
Create essays dataset from https://homework-lab.com/examples/

**Comment by Vechtomov** [comment]
Actually I did it already. Here is the result: https://huggingface.co/datasets/qwedsacf/homework-lab-essays
But I only scraped the data without preprocessing. Essays were in .doc and .docx files so I extracted text via [textract](https://textract.readthedocs.io/en/stable/) library. So there are a lot of spaces and tabulations in the texts.

**Comment by christophschuhmann** [comment]
You are a hero :)
