### ISSUE TITLE
Write instructions and examples for integration tests of the discord bot

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#88]
we want to run integration tests of the entire stack: backend + discord bot frontend. this requires pulling both up, including possibly a temporary postgres database for the backend, initializing the database, and running tests against the system.

make a plan on how to achieve this, then implement a few examples and write down instructions for people who want to write their own integration tests.

pytest with a docker-compose plugin can be used to easily pull up containers for testing, but this task is especially challenging because of the need to either simulate, fake, or actually provide the interaction of the bot with a discord server.

**Comment by AlexanderHOtt** [comment]
Automatically testing discord bots is very difficult and sometimes against discord ToS. However, I'm open to ideas.

**Comment by yk** [comment]
I mean, it can start small by mocking the discord API web calls, but we need some sort of tests desperately with so many people working on stuff.

**Comment by kayjay-is-here** [comment]
I would like to work on this, however I don't exactly understand what are we testing. Everything? A specific feature?

**Comment by andreaskoepf** [comment]
I am moving this to backlog.

**Comment by andreaskoepf** [comment]
Closing all old discord bot issues. Discord data collection never took off. It might be more viable to develop a discord bot that communicates with the inference system.
