### ISSUE TITLE
Add 'lang' filter option to messages endpoints

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#896]
Add an optional 'lang' query param that filters messages based on language to the REST API endpoints that return a list of message, 

- `api/v1/messages` [messages.py#L18](https://github.com/LAION-AI/Open-Assistant/blob/274d03c5f0f75ba87102271384f20089ea6c0ef8/backend/oasst_backend/api/v1/messages.py#L18)
- `api/v1/messages/cursor` [messages.py#L51](https://github.com/LAION-AI/Open-Assistant/blob/274d03c5f0f75ba87102271384f20089ea6c0ef8/backend/oasst_backend/api/v1/messages.py#L51)
- `api/v1/users/{user-id}/messages` [users.py#L216](https://github.com/LAION-AI/Open-Assistant/blob/274d03c5f0f75ba87102271384f20089ea6c0ef8/backend/oasst_backend/api/v1/users.py#L216)
- `api/v1/users/{user-id}/messages/cursor` [users.py#L247](https://github.com/LAION-AI/Open-Assistant/blob/274d03c5f0f75ba87102271384f20089ea6c0ef8/backend/oasst_backend/api/v1/users.py#L247)

The primary function to modify is [query_messages_ordered_by_created_date()](https://github.com/LAION-AI/Open-Assistant/blob/274d03c5f0f75ba87102271384f20089ea6c0ef8/backend/oasst_backend/prompt_repository.py#L683).

If no lang query param is provided messages of all languages should be returned (e.g. default value None, behavior as it is right now).

**Comment by j0rd1smit** [comment]
Sounds like fun. I would like to do it 😀

**Comment by andreaskoepf** [comment]
@j0rd1smit nice, I assigned you!

**Comment by kushalnl7** [comment]
Hi @j0rd1smit, let me know if anytime you drop out of this task. I would like to take over this. Thanks!
