### ISSUE TITLE
Retry scoring of all trees in scoring_failed state via CLI command

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#899]
Create a new CLI command (e.g. add to [main](https://github.com/LAION-AI/Open-Assistant/blob/cd2e883e9d3eeabf7056eefc91cfaced83a6636d/backend/main.py#L283)) that finds all message trees in `SCORING_FAILED` state (e.g. rows in `message_tree_state` table) and re-runs the scoring algorithm by calling [TreeManager.update_message_ranks()](https://github.com/LAION-AI/Open-Assistant/blob/cd2e883e9d3eeabf7056eefc91cfaced83a6636d/backend/oasst_backend/tree_manager.py#L652). The retry function (that loops over all failed trees) could be added to tree_manager.py.

**Comment by Vechtomov** [comment]
I will do this

**Comment by andreaskoepf** [comment]
@Vechtomov we need this pretty soon to re-run scoring and export from the production instance. Can you do this within the next 12h? Otherwise I would quickly implement it..

**Comment by Vechtomov** [comment]
I will try to commit in the next 3 hours. If I have some problems I'll let you know
