### ISSUE TITLE
Website: Calling task availability triggers a OasstError for new users

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#909]
When testing locally with a brand new user, the task availability section on the dashboard makes a call to `/api/available_tasks` on the webserver.  The first call fails and internally triggers a 

```
OasstError {
  message: 'Task availability query failed.',
  errorCode: 1007,
  httpStatusCode: 400
}
```

Looking at the backends logs I see

```
sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "ix_user_username"
DETAIL:  Key (api_client_id, username, auth_method)=(161ff73c-f855-455e-b326-69125460b36b, dev23, local) already exists.
```

I'm guessing this is because two calls are happening in parallel that try to create the user in the table and one fails.  The user creation should _probably_ be an upsert instead of a create with failure since the information should be the same except for the `created_at` timestamp.

**Comment by andreaskoepf** [comment]
As a simple quick-fix I added a retry loop.

**Comment by andreaskoepf** [comment]
@fozziethebeat Please reopen in case the problem still persists.

**Comment by fozziethebeat** [comment]
Great ! will check and verify later
