### ISSUE TITLE
Allow admin ability to find low scoring users for moderation

### ISSUE THREAD

**Issue by fozziethebeat** [LAION-AI/Open-Assistant#912]
In the Admin panel we need search features or table sorting features that make it easy to find users that need moderation.

**Comment by hemangjoshi37a** [comment]
I suggest addressing the need for user moderation and the importance of having efficient tools in place to aid in that process. The proposed solution of adding search and sorting features to the admin panel will make it easier for admins to identify low-scoring users that may require moderation. Additionally, highlighting the benefits of this feature such as improved user experience and maintaining a positive community environment can further emphasize the importance of this issue. It's important to make sure that the implementation of this feature is done in a way that is consistent with web standards, and that it is accessible to all users. And also, we should make sure that this feature is in line with the user privacy laws and regulations.

**Comment by olliestanley** [comment]
Is this covered by trollboards? #1073
