### ISSUE TITLE
Add new `text_source` table & corresponding reference in `post` table

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#92]
Posts stored in the `post` table can originate from different sources, e.g. human-demonstration, a dataset or a language models. We want to track and later allow filtering based on these types.

- add new `text_source` table:
```
*id: int # (SERIAL/auto-increment)
type: string  # a standard TextSourceType defined in a str-enum in python
name: string (nullable) # major identifier like dataset name, model name
details: jsonb   # allow to store variable details as dict in python
```

- Add `text_source_id` (optional/nullable), fk-reference to `post`.
- Generate almebic migration script.
- Define a `TextSourceType` str-enum with some enum-members (see above), the enum could be placed in the file that contains the TextSource class (SQLModel).

**Comment by yk** [comment]
how about calling this something like `text_origin` or `text_source` or something like that? I did not know the word `provenance` and I'm going to guess not many people do 😄

**Comment by andreaskoepf** [comment]
Sure I have changed the name to text_source.

**Comment by andreaskoepf** [comment]
We will use a simpler solution for the MVP.
