### ISSUE TITLE
Error state after last available task of a type has been submitted

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#924]
When all available tasks of a given type have been completed by a user the next buttons stays disabled:

![image](https://user-images.githubusercontent.com/9976399/214355141-62145d2a-70f6-4fc1-9622-bb634b73ff3c.png)

The website should tell the user that no task is available or automatically return to the dashboard.

**Comment by rjmacarthy** [comment]
I'm interested in this task.

**Comment by hemangjoshi37a** [comment]
Great catch, @andreaskoepf! This is definitely an issue that needs to be addressed. Having the next button stay disabled after all available tasks of a given type have been completed can be confusing for users and lead to a poor user experience.

One possible solution is to implement a message or redirect to the dashboard when all tasks have been completed. This will let the user know that there are no more tasks available and guide them back to the dashboard where they can view their progress and select other tasks.

To improve SEO, we can also include relevant keywords such as "task completion," "error state," and "user experience" in the issue title and description, and make sure to include them in the solution as well. Additionally, we can link to related issues and pull requests that address similar topics.

@rjmacarthy, thanks for taking on this task. Let us know if you need any help or have any questions.

**Comment by AbdBarho** [comment]
This can be closed right?

**Comment by AbdBarho** [comment]
will close, feel free to re-open if the problem is not resolved
