### ISSUE TITLE
Add `lang` column to `post` table (ISO 639-1 code)

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#93]
Add a string(2) `lang` field to the `post` model class to specify the language of a given post. This is necessary to query posts in a given language (e.g. which the current user is able to speak).

Don't forget to add the alembic migration scripts.

**Comment by andreaskoepf** [comment]
We need to decide how we handle languages codes in the project, e.g. https://pypi.org/project/langcodes/ ?

**Comment by GraemeHarris** [comment]
@andreaskoepf Looking to pick up something small to get into the project - do you mind if I take this? Would we be looking to force a language on the BE API when creating tasks or leaving that as optional?

**Comment by yk** [comment]
> @andreaskoepf Looking to pick up something small to get into the project - do you mind if I take this? Would we be looking to force a language on the BE API when creating tasks or leaving that as optional?

I think for now we can just default to english, eventually we could either force it or try to detect the language. I've assigned you

**Comment by GraemeHarris** [comment]
Have a PR up - should be simple enough :)
