### ISSUE TITLE
Skipped tasks should never be served again

### ISSUE THREAD

**Issue by mashdragon** [LAION-AI/Open-Assistant#934]
If a user skips a task for any reason, the task shouldn't be served to that user ever again.

**Comment by hemangjoshi37a** [comment]
I completely agree with your observation, serving a skipped task to a user again can lead to frustration and a poor user experience. One solution to this could be to implement a task tracking system where skipped tasks are flagged and excluded from future servings. Additionally, we could also gather feedback from the user on why they decided to skip the task, which could provide valuable insights for further improvement. This could be done by adding a feedback form or prompt after a task is skipped. Overall, it's important to prioritize user experience and make sure that the tasks served are relevant and beneficial for the user.

**Comment by andreaskoepf** [comment]
@hemangjoshi37a Would you like to work on this? Tasks are already recorded .. NACK is sent to the server when the user cancel .. but TaskRepository.acknowledge_task_failure() doesn't really record that the task was skipped .. (the meaning of NACK changed over time). Excluding the tasks is a bit the challenge here, e.g. the queries in TreeManager need to be adapted.

**Comment by hemangjoshi37a** [comment]
Give list of subtasks. I will complete as many as I can because I am little consumed in other tasks.

**Comment by andreaskoepf** [comment]
> Give list of subtasks. I will complete as many as I can because I am little consumed in other tasks.

The first subtask would be to analyze the situation and make a concrete proposal of how to hide the tasks for the calling users based on their skipped-tasks-state. Start with a single task-type, e.g. inital prompt.

**Comment by lainisourgod** [comment]
I've just seen a usecase where this behaviour is bad. I've seen a task that I want to complete, but _not now_. So I skip it and hope to see it some time later.

Now I don't see this task in my queue at all but I want.

Maybe we should add a button like "Return later"?

**Comment by olliestanley** [comment]
Skipped tasks can't be shown again as of #1064
