### ISSUE TITLE
Implement real streaming in inference worker

### ISSUE THREAD

**Issue by olliestanley** [LAION-AI/Open-Assistant#939]
We need to switch from a single inference call to incremental generation and stream the results in the inference worker:

https://github.com/LAION-AI/Open-Assistant/blob/main/inference/worker/__main__.py#L40

**Comment by andreaskoepf** [comment]
@olliestanley were you in contact with Yannic about this? AFAIK there has been some progress been made in this direction...

**Comment by olliestanley** [comment]
This is resolved by f1edcc8a285dbc184a14ab50dccc39d258d45c92
