### ISSUE TITLE
Help me add this dataset about trading messages from huggingface

### ISSUE THREAD

**Issue by hemangjoshi37a** [LAION-AI/Open-Assistant#956]
I want to add this dataset from huggingface that has this link : [https://huggingface.co/datasets/hemangjoshi37a/autotrain-data-stocks-ner-2000-sample-test](https://huggingface.co/datasets/hemangjoshi37a/autotrain-data-stocks-ner-2000-sample-test)

Please help me anyone how to  add this to our current dataset.

**Comment by ontocord** [comment]
also, that looks like your own repo right? make sure it's permissive to use the data if you contribute to OA.

**Comment by hemangjoshi37a** [comment]
> also, that looks like your own repo right? make sure it's permissive to use the data if you contribute to OA.

It has MIT licence. It can be used as you like.
