### ISSUE TITLE
Show a bit more text for the ranking options

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#969]
It would be helpful to display a bit more text for the individual reply-candidates:

![image](https://user-images.githubusercontent.com/9976399/215275276-34326f11-2000-484c-a31f-008d470479c6.png)

If one clicks "..." the Full Text popup opens .. for users with mouse it would be nice to get something similar directly when hovering (move-over) over the "..." button. If that is no option it would be nice if the full-text dialog could appear a bit closer to the where the user clicked (to remove mouse travel distance).

Very minor ui perfection comment: The full text dialog box should get more padding at the bottom:

![image](https://user-images.githubusercontent.com/9976399/215275468-ee751860-075c-4331-9978-713a7d592d8c.png)

**Comment by kingychiu** [comment]
@andreaskoepf  Created a PR here
https://github.com/LAION-AI/Open-Assistant/pull/1116

I guess you can also assign this task to me. Thanks!
