### ISSUE TITLE
Why not bloom ?

### ISSUE THREAD

**Issue by ThomasBourgeois** [LAION-AI/Open-Assistant#972]
Hi, 
This might not be the good place to ask, but why no mention in the slides of the project of Bloom LLM as base model ? 
https://huggingface.co/bigscience/bloom
To my limited knowledge that was the largest and most open-source model we have, isn't that the case ? 
Thanks

**Comment by yk** [comment]
BLOOM is not licensed open-source, so we can't use it. It uses OpenRAIL-M. The only way we could use it is to ask the BLOOM creators to license it permissively.

**Comment by davidbau** [comment]
Trying to understand - Does OpenRAIL-M prevent fine-tuning?  Or is the issue that you don't want OpenAssistant to be subject to the OpenRAIL-M restrictions when it is done?

If OpenRAIL-M allows fine-tuning, it seems like it might be useful to have a Bloom version of OpenAssistant.
