### ISSUE TITLE
Scroll on mobile for ranking cards can be a little tricky 

### ISSUE THREAD

**Issue by andrewm4894** [LAION-AI/Open-Assistant#974]
Trying to scroll on mobile to see and read all the options here before I then rank them is a little tricky and I kept inadvertently reordering them by mistake when trying to scroll down the page

![Screenshot_20230128-204945](https://user-images.githubusercontent.com/2178292/215290568-aa932bab-3d55-44be-9c1b-161a0680ea12.png)

**Comment by andrewm4894** [comment]
I was also able to move the whole card over a bit somehow. 

![Screenshot_20230128-205240](https://user-images.githubusercontent.com/2178292/215290640-0ec2049a-8807-4f9c-abc9-2f0a4b4b51ce.png)

**Comment by AbdBarho** [comment]
#1680
