### ISSUE TITLE
How often is the leaderboard updated?

### ISSUE THREAD

**Issue by andrewm4894** [LAION-AI/Open-Assistant#976]
I like to do some tasks and them check my position on the leaderboard but it does not really seem to update right away. 

Could be nice for gamification of things if the leaderboard could update more near real time so that I could see impact each task or a string or tasks has on my position in the leaderboard.

**Comment by yk** [comment]
I think this is a configuration setting, but currently on prod, it's every 5 minutes. But yea, there are lots of things that could be done, also many things to make the score more explainable. For example, if you act as the assistant, most of your score will be delayed until your answer has been labeled and ranked, and I don't think that's clear to people now.
