### ISSUE TITLE
Handle case when all prompts are factually inaccurate

### ISSUE THREAD

**Issue by JamesDConley** [LAION-AI/Open-Assistant#977]
Example
![image](https://user-images.githubusercontent.com/16070894/215291898-77b4474d-2bec-411b-8ed7-5ba2c5835630.png)

In this case it would be good to allow the labeler to indicate all the answers are incorrect, or to add their own, factually correct answer.

**Comment by andreaskoepf** [comment]
Best you currently can do is downgrade (thumbs down) and report the parent-message.

**Comment by fozziethebeat** [comment]
For this you can optionally skip the task, downvote both answers.  But also from a data training perspective, ranking them is still valuable.  

I'm going to change this to a documentation bug and request that someone fills out these details in the relevant docs page.

To clear this I think it's sufficient to create a markdown file in `docs/docs/tasks/rank_assistant_replies.md` and add some instructions on what to do in corner cases.  Then update `website/src/components/Tasks/TaskTypes.tsx` and fill out the appropriate `help_link` field.

**Comment by olliestanley** [comment]
This has been implemented
