### ISSUE TITLE
Remove feedback modal on skip button

### ISSUE THREAD

**Issue by Vechtomov** [LAION-AI/Open-Assistant#978]
I skip many tasks because I prefer to give a conscious response to dialogs that related to me.
I propose to add button "Don't show again" on the feedback modal or remove this modal at all.

**Comment by fozziethebeat** [comment]
Right now we'll probably leave this as is as we're semi-discouraging users to skip tasks.  But we do have a task somewhere to make the skipping process a little simpler so that you can select from a fixed set of reasons why you're skipping.
