### ISSUE TITLE
Typo in 'Label Assistant Reply'

### ISSUE THREAD

**Issue by Reblexis** [LAION-AI/Open-Assistant#981]
One of the classification options says: "Does the reply fail the propmpters task?". 
It should be: "Does the reply fail the prompters task?".
![image](https://user-images.githubusercontent.com/80317928/215293571-30fb393d-38bd-43b1-866c-1d588d20e4de.png)

**Comment by occupytheweb** [comment]
Hi @andreaskoepf.
I can fix this.
