### ISSUE TITLE
Show the user's score and place in the leaderboard

### ISSUE THREAD

**Issue by Vechtomov** [LAION-AI/Open-Assistant#982]
Right now there is no way to know your score and place in the leaderboard if you are not in the top 20 contributors.
This could be done as in Kaggle.

![kaggle_leaderboard1](https://user-images.githubusercontent.com/28014244/215295829-e2b7d5c8-9ee2-4833-9a7f-6eb43677a447.png)

![kaggle_leaderboard2](https://user-images.githubusercontent.com/28014244/215295839-8c0c0506-9e89-46ff-a587-df4e85b5a79f.png)

**Comment by DukeManh** [comment]
Hey @Vechtomov, I would like to help with this feature if possible.

**Comment by Vechtomov** [comment]
Hi, I only proposed the feature. If you want to implement this you can ask to assign you on this issue.

**Comment by yk** [comment]
@DukeManh I assigned you. I think a backend endpoint for this already might exist

**Comment by MalikMAlna** [comment]
As for displaying this info on the frontend, another person on the Discord server and I mentioned that one of the first places we checked for our own scoring info was on the Account page. If you all don't have a display for that info set up yet, would it be possible for you all to drop it into the frontend? 

Alternatively, I can place it there as well if you all just want to focus on getting the endpoint set up for it. Just let me know when that's good to go.

**Comment by DukeManh** [comment]
@MalikMAlna I think this issue is about placing the user scoring on the leaderboard and 1158 is placing it on the account page
