### ISSUE TITLE
Make progress bars / stats on dashboard

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#996]
We could do two different stats:
- a progress bar towards some goal (i.e. 5000 completed trees)
- a distribution of the state of all in-progress trees

we already have these numbers available at `/api/v1/stats/tree_manager` (maybe we want to select a subset of them)

**Comment by MrlolDev** [comment]
Working on it

**Comment by gilice** [comment]
@yk What is this API endpoint?

I tried https://open-assistant.io/api/v1/stats/tree_manager without luck.

**Comment by gilice** [comment]
any progress on this? it would help trust & motivation greatly.

**Comment by sedthh** [comment]
I think a linear progression curve should be an okay rule of thumb estimate for XP thresholds. 
This means that the **difference** in xp needed between levels grows linearly:

For example, with a baseline of 4
| Level | XP at level | XP needed to progress |
|-------|----|--------------------|
| 1     | 0  | 4 **+ 1**          |
| 2     | 5  | 4 **+ 2**          |
| 3     | 11 | 4 **+ 3**          |
| 4     | 18 | 4 **+ 4**          |
| 5     | 26 | 4 **+ 5**          |

**Comment by sedthh** [comment]
and the progress bar is:
```python
if current_level >= max_level:  # or len(thresholds)
    prograss = 1.
else: 
    progress = (current_points - thresholds[current_level - 1]) / (thresholds[current_level] - thresholds[current_level - 1])
```

**Comment by Dryhb** [comment]
A kind of daily goal for trees /messages would be great too to encourage daily activity.
A daily goal per user and a global one (maybe epr language ?)

**Comment by AbdBarho** [comment]
#2093
