### ISSUE TITLE
Show at least the top 100 users on the leaderboards

### ISSUE THREAD

**Issue by andreaskoepf** [LAION-AI/Open-Assistant#998]
Currently the leader-board views show only the top 20 users. The number of displayed rows should be increased to at least 100.

**Comment by notmd** [comment]
Do we need pagination or just show 100 users directly?

**Comment by andreaskoepf** [comment]
> Do we need pagination or just show 100 users directly?

I think top 100 is ok. Nice would be +/- 3 view as suggested in #1000 (new rest endpoint required for that, but will be relatively easy to add)

**Comment by notmd** [comment]
Ok let me take this.
